### PR TITLE
Fix Chrome's 'Data Saver' mode prevents tracking

### LINKED ISSUE #7733: Chrome's "Data Saver" mode prevents tracking
Visitors using chrome's [Data Saver mode] (https://support.google.com/chrome/answer/2392284?hl=en) are not tracked. I can see them in Google Analytics, but not in Piwik.

### PR DESCRIPTION
**Pull request by tsteur**
fixes #7733 

tested it via demo.piwik.org

### CODE REVIEW

File: core/Tracker/VisitExcluded.php [hunk 1]
```diff
@@ -180,13 +180,26 @@ private function isIpInRange()
...
 
         return $isInRanges;
     }
 
+    private function isChromeDataSaverUsed(IP $ip)
+    {
+        // see https://github.com/piwik/piwik/issues/7733
+        return !empty($_SERVER['HTTP_VIA'])
+            && false !== strpos(strtolower($_SERVER['HTTP_VIA']), 'chrome-compression-proxy')
+            && $ip->isInRange('66.249.80.0/20');
```
Comment (mattab) [inline core/Tracker/VisitExcluded.php]: here we look at a specific IP range, instead let's apply this logic for all Google bot IP addresses? (reason: Chrome proxy IPs will likely change in the future, and maybe they already use more than this one IP range)

Comment (tsteur) [inline core/Tracker/VisitExcluded.php]: I don't know all googles IP ranges. Are they specified somewhere?  

I didn't use `getBotIpRanges()` as it might also contains non google ip addresses? And as it could be misused? Also `isInRange()` is very very slow (this made bulk tracking very slow, that's why it caches some parts). So tried to avoid too many calls.

Comment (mattab) [inline core/Tracker/VisitExcluded.php]: > I don't know all googles IP ranges. Are they specified somewhere? 

they are here, need to be refactored out: https://github.com/piwik/piwik/blob/2.14.3/core/Tracker/VisitExcluded.php#L193-L203

Comment (tsteur) [inline core/Tracker/VisitExcluded.php]: done
