### PR TITLE
Fixes #8217 regression, make sure temporary metrics are available to UserCountryMap for cities layer

### LINKED ISSUE #8217: Cities are not being shown on the visitors map
When I switch to cities view, I can see the following error in the console:
```
Uncaught TypeError: Cannot read property 'toFixed' of undefined
```
I can reproduce it using demo: http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#/module=UserCountry&action=index&idSite=7&period=day&date=yesterday

### PR DESCRIPTION
**Pull request by diosmosis**
As title, also includes UI tests for cities/regions layer, plus change that allows UI tests to send mouse events to specific coordinates.

In order to get some visits to show up on the city map, I had to set the IPs in UITestFixture visits to IPs that have locations. And force the use of GeoIP there.

### CODE REVIEW

File: tests/PHPUnit/Fixtures/UITestFixture.php [hunk 1]
```diff
@@ -49,6 +53,10 @@ public function setUp()
             "idsite = 1"
         );
 
+        // for proper geolocation
+        LocationProvider::setCurrentProvider(LocationProvider\GeoIp\Php::ID);
+        IPAnonymizer::deactivate();
+
```
Comment (mnapoli) [inline tests/PHPUnit/Fixtures/UITestFixture.php]: Would it make sense to make a more specific fixture? This change + adding `self::downloadGeoIpDbs()` makes the base fixture more complex (and maybe slower, not sure about that), that's why I'm asking.

Comment (diosmosis) [inline tests/PHPUnit/Fixtures/UITestFixture.php]: Base fixture?

Comment (mnapoli) [inline tests/PHPUnit/Fixtures/UITestFixture.php]: default fixture? Isn't that the default fixture used for ui tests?

Comment (diosmosis) [inline tests/PHPUnit/Fixtures/UITestFixture.php]: Yeah, I don't see how it will slow the tests down, the GeoIP database will only be downloaded if it doesn't exist already. So it will happen once per test run (on travis). Is that what you're worried about?

Comment (mnapoli) [inline tests/PHPUnit/Fixtures/UITestFixture.php]: OK no worries :)
