### PR TITLE
Use mbstring proxy methods

### LINKED ISSUE #12101: Call to undefined function Piwik\Plugins\ScheduledReports\mb_strtoupper() in plugins/ScheduledReports/Controller.php 39
error message reported by email: 

> Call to undefined function Piwik\Plugins\ScheduledReports\mb_strtoupper() in /home/adad1041/public_html/adept_piwik/plugins/ScheduledReports/Controller.php 39 using PHP 7.0.23

we should call nb_strtotupper only when the function is available (when `mbstring` extension is enabled), otherwise we should just leave the text as-is (to avoid calling strtotupper on unicode which would not work).

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #12101

### CODE REVIEW

File: core/Common.php [hunk 1]
```diff
@@ -235,6 +235,24 @@ public static function mb_strtolower($string)
...
+     * @return string
+     * @api
+     */
+    public static function mb_strtoupper($string)
+    {
+        if (function_exists('mb_strtoupper')) {
+            return mb_strtoupper($string, 'UTF-8');
+        }
+
+        return strtoupper($string);
```
Comment (mattab) [inline core/Common.php]: here we should default to returning the original string, otherwise we risk destroying the unicode string when mbstring becomes un-available for some reason. Better keep original string than risking breaking it :+1:

**Review by mattab — CHANGES_REQUESTED** [review]

File: core/Common.php (hunk 1 above)
Comment (sgiehl) [reply core/Common.php]: We aren't doing that in the method above for strtolower as well

Comment (mattab) [reply core/Common.php]: let's do it in all mb_ proxy methods to avoid destroying unicode strings

Comment (sgiehl) [reply core/Common.php]: Imho we shouldn't take care of that. As we can't avoid problems with unicode. `substr` for example might cut off within a multibyte char, `strlen` might return an incorrect length.
Also Twig for example does the same in some of their filters: if `mb_strtolower` isn't available they use `strtolower`

Comment (mattab) [reply core/Common.php]: >  As we can't avoid problems with unicode. 

Actually we can avoid potential problems by not touching the string... ideally we would detect when it's a unicode string but this may get tricky (or slow)

Comment (sgiehl) [reply core/Common.php]: Well ok, if you think it makes sense to change that now after it was [already over 6 years in the code](https://github.com/piwik/piwik/commit/a4287c9a1fadab7052c4fb50f7c9481785728c9b) and we didn't get any bug report about it...

Comment (tsteur) [reply core/Common.php]: I think what @sgiehl was pointing out we might avoid it the problem there but get the problem somewhere else... not quite getting the problem as well @mattab ?

**Review by mattab — APPROVED** [review]

**Comment by mattab** [comment]
:+1: 
(It's a very unlikely bug indeed (especially since we now require mbstring) but i wouldn't be surprised some users would have experienced it and maybe not report it... )
