### PR TITLE
Show plugins update count asynchronously with 5 minute caching

### LINKED ISSUE #23570: Move Plugin Update Count Fetching to Frontend to Avoid Backend Timeouts
#### 🔍 Background

Matomo currently displays the number of available plugin updates in the **Admin menu** via backend logic:

https://github.com/matomo-org/matomo/blob/ecb4f2be6ce6e93430f47461981fffcc3cce6312/plugins/CorePluginsAdmin/Menu.php#L53-L61

However, this information is retrieved via a call to the **Marketplace API**, which:

* Is triggered **for every controller action** rendering a backend template (even for reporting)
* Introduces a **performance bottleneck** if the Marketplace API is unavailable or slow
* Is **not cached on failure**, so timeouts are retried repeatedly, compounding the slowdown

📍 Related rendering call:
https://github.com/matomo-org/matomo/blob/aa6585c860585a9ba9ebd134e5a1be29a043aad0/core/Plugin/Controller.php#L700

#### 🎯 Goal

Move the update count check away from backend page rendering and into the **frontend** (Vue) layer, to decouple the UI from potentially blocking requests.

---

#### 1. 💡 Move Update Check to Frontend

* Create a new Vue component that runs **only on admin pages**
* This component triggers an **async request** to fetch the number of available plugin updates
* Once the count is known, it dynamically **adds a badge** to the `Plugins` menu entry (if any updates exist)

💡 **Alternative**: Integrate this functionality into the existing `UpdateCheck` Vue component:
`CoreHome.VersionInfoHeaderMessage`

---

#### 2. 🛠 Backend Adjustments

* Expose a lightweight API endpoint that returns the **count of plugin updates**
* Ensure the endpoint uses caching (success and failure) to avoid excessive load or redundant retries

---

### 📈 Benefits

* 🚀 Speeds up all UI page loads, especially when Marketplace is unreachable
* 🔄 Isolates update-check logic from core rendering path
* 🧱 Sets a precedent for moving similar non-critical backend data into async frontend calls

---

### 📝 Tasks

* [ ] Create Vue component to fetch and inject update count into menu
* [ ] Expose backend endpoint returning plugin update count
* [ ] Replace backend logic in `Menu.php`
* [ ] Apply timeout and failure caching in backend check
* [ ] Test for regressions in admin menu rendering

---

refs #23538

### PR DESCRIPTION
**Pull request by michalkleiner**
### Description:

- Remove update count from menu item returned by PHP
- Add vue component that fetches the update count via a new small API endpoint
- Cache marketplace number of plugin updates for 5 minutes
- Add a few param types

Note: Not explicitly testing the Marketplace response here as that is [covered](https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/Marketplace/tests/Integration/PluginsTest.php#L491) in the Marketplace plugin itself, so relying on the updates override in the fixture for the API test.

Note 2: Added a new collapsible menu macro variable to make it clearer that we want collapsible menu for admins. Then we can pass the hasSomeAdminAccess variable to the menu macro call without confusing its meaning inside _menu.twig template.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/CorePluginsAdmin/vue/src/PluginsUpdateCount/PluginsUpdateCount.vue [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+          method: 'CorePluginsAdmin.getNumberOfPluginUpdates',
+        }).then((response) => {
+          const count = response.value || 0;
+
+          if (count) {
+            const originalText = el.textContent?.trim() ?? '';
+            el.textContent = `${originalText} (${count})`;
+          }
+        });
+      } catch (error) {
```
Comment (nathangavin) [inline plugins/CorePluginsAdmin/vue/src/PluginsUpdateCount/PluginsUpdateCount.vue]: Instead of using `try catch`, maybe use the built-in `.catch((e) => {}` with the AjaxHelper?

**Review by nathangavin — DISMISSED** [review]

File: plugins/CorePluginsAdmin/vue/src/PluginsUpdateCount/PluginsUpdateCount.vue (hunk 1 above)
Comment (michalkleiner) [reply plugins/CorePluginsAdmin/vue/src/PluginsUpdateCount/PluginsUpdateCount.vue]: Good suggestion, replaced

**Review by nathangavin — APPROVED** [review]

File: plugins/CoreHome/templates/_menu.twig [hunk 2]
```diff
@@ -1,4 +1,4 @@
-{% macro menu(menu, anchorlink, cssClass, currentModule, currentAction, collapsible) %}
+{% macro menu(menu, anchorlink, cssClass, currentModule, currentAction, collapsible, hasSomeAdminAccess) %}
```
Comment (sgiehl) [inline plugins/CoreHome/templates/_menu.twig:1]: That doesn't look right. Why should that be shown to users with admin access, if the API method to fetch the count, actually checks for superuser permission?

Comment (sgiehl) [inline plugins/CoreHome/templates/_menu.twig:1]: I guess a check for super user permission (isSuperUser) would have been better here. There is no value in adding the new component for admin users, as the plugin menu is only rendered for super users and the new API method is also only available for superusers.

Comment (michalkleiner) [reply plugins/CoreHome/templates/_menu.twig:1]: Good point @sgiehl, created a tiny [follow up PR](https://github.com/matomo-org/matomo/pull/23654) for that if you can have a look.

**Comment by psternuva** [comment]
@sgiehl 

The change in MenuAbstract addItem() Method signature
from `$order = 50`
to       `int $order = 50`

causes, at least in our instance, a warning about loss of precision (float implicitly cast to int).

See report here: https://forum.matomo.org/t/matomo-v5-5-1-warning-implicit-conversion-from-float-to-int-loses-precision/64118
