### PR TITLE
Fix check if table exists

### LINKED ISSUE #16580: Matomo 4 beta: MySQL syntax error
This has been reported twice independently on the forum:
https://forum.matomo.org/t/mysqli-prepare-error-you-have-an-error-in-your-sql-syntax-check-the-manual-that-corresponds-to-your-mysql-server-version-for-the-right-syntax-to-use-near-at-line-1/38986
https://forum.matomo.org/t/mysqli-error-when-upgrading-to-matomo-4-beta/38924

Log from the latter post including SQL queries:

``` 
DEBUG Piwik\Plugin\Manager[2020-10-13 06:11:11 UTC] [7a606] Loaded plugins: CorePluginsAdmin, CoreAdminHome, CoreHome, WebsiteMeasurable, IntranetMeasurable, Diagnostics, CoreVisualizations, Proxy, API, Widgetize, Transitions, LanguagesManager, Actions, Dashboard, MultiSites, Referrers, UserLanguage, DevicesDetection, Goals, Ecommerce, SEO, Events, UserCountry, GeoIp2, VisitsSummary, VisitFrequency, VisitTime, VisitorInterest, RssWidget, Feedback, Monolog, Login, TwoFactorAuth, UsersManager, SitesManager, Installation, CoreUpdater, CoreConsole, ScheduledReports, UserCountryMap, Live, PrivacyManager, ImageGraph, Annotations, MobileMessaging, Overlay, SegmentEditor, Insights, Morpheus, Contents, BulkTracking, Resolution, DevicePlugins, Heartbeat, Intl, Marketplace, ProfessionalServices, UserId, CustomJsTracker, Tour, PagePerformance, CustomDimensions
ERROR Piwik\ExceptionHandler[2020-10-13 06:11:11 UTC] [7a606] Uncaught exception: pathto/matomo/libs/Zend/Db/Statement/Mysqli.php(77): Mysqli prepare error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?' at line 1
ERROR Piwik\ExceptionHandler[2020-10-13 06:11:11 UTC] [7a606] Mysqli prepare error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?' at line 1
ERROR Piwik\ExceptionHandler[2020-10-13 06:11:11 UTC] [7a606] #0 pathto/matomo/libs/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('SHOW TABLES LIK...')
ERROR Piwik\ExceptionHandler[2020-10-13 06:11:11 UTC] [7a606] #1 pathto/matomo/libs/Zend/Db/Adapter/Mysqli.php(419): Zend_Db_Statement->__construct(Object(Piwik\Db\Adapter\Mysqli), 'SHOW TABLES LIK...')
ERROR Piwik\ExceptionHandler[2020-10-13 06:11:11 UTC] [7a606] #2 pathto/matomo/libs/Zend/Db/Adapter/Abstract.php(478): Zend_Db_Adapter_Mysqli->prepare('SHOW TABLES LIK...')
ERROR Piwik\ExceptionHandler[2020-10-13 06:11:11 UTC] [7a606] #3 pathto/matomo/core/DbHelper.php(40): Zend_Db_Adapter_Abstract->query('SHOW TABLES LIK...', Array)
ERROR Piwik\ExceptionHandler[2020-10-13 06:11:11 UTC] [7a606] #4 pathto/matomo/plugins/Login/Auth.php(68): Piwik\DbHelper::tableExists('user_token_auth')
ERROR Piwik\ExceptionHandler[2020-10-13 06:11:11 UTC] [7a606] #5 pathto/matomo/core/Access.php(187): Piwik\Plugins\Login\Auth->authenticate()
ERROR Piwik\ExceptionHandler[2020-10-13 06:11:11 UTC] [7a606] #6 pathto/matomo/core/FrontController.php(405): Piwik\Access->reloadAccess(Object(Piwik\Plugins\Login\Auth))
ERROR Piwik\ExceptionHandler[2020-10-13 06:11:11 UTC] [7a606] #7 pathto/matomo/core/dispatch.php(31): Piwik\FrontController->init()
ERROR Piwik\ExceptionHandler[2020-10-13 06:11:11 UTC] [7a606] #8 pathto/matomo/index.php(25): require_once('pathto...')
ERROR Piwik\ExceptionHandler[2020-10-13 06:11:11 UTC] [7a606] #9 {main}
DEBUG Piwik\Profiler[2020-10-13 06:11:11 UTC] [7a606] <hr /><strong>SQL Profiler</strong><hr /><strong>Summary</strong><br/>Executed 5 queries in 0.019 seconds(Average query length: 0.004 seconds)<br />Queries per second: 259.4<br />Longest query length: 0.019 seconds (<code>INSERT INTO matomo_session (id,modified,lifetime,data) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE modified = ?,lifetime = ?,data = ?</code>)
DEBUG Piwik\Profiler[2020-10-13 06:11:11 UTC] [7a606] <hr /><strong>Breakdown by query</strong><br/>Executed <b>1</b> time in <b>18.8ms</b>  <pre>	INSERT INTO matomo_session (id,modified,lifetime,data) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE modified = ?,lifetime = ?,data = ?</pre>Executed <b>1</b> time in <b>0.3ms</b>  <pre>	SELECT data FROM matomo_session WHERE id = ? AND modified + lifetime >= ?</pre>Executed <b>1</b> time in <b>0.1ms</b>  <pre>	SELECT DATABASE()</pre>Executed <b>1</b> time in <b>0.1ms</b>  <pre>	SELECT option_value, option_name FROM `matomo_option` WHERE autoload = 1</pre>Executed <b>1</b> time in <b>0.1ms</b>  <pre>	SELECT option_value FROM `matomo_option` WHERE option_name = ?</pre>
DEBUG Piwik\Profiler[2020-10-13 06:11:11 UTC] [7a606] Total queries = 5 (total sql time = 0.02s)

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #16580

### CODE REVIEW

File: core/DbHelper.php [hunk 1]
```diff
@@ -37,7 +37,7 @@ public static function getTablesInstalled($forceReload = true)
      */
     public static function tableExists($tableName)
     {
-        return Db::get()->query("SHOW TABLES LIKE ?", $tableName)->rowCount() > 0;
```
Comment (tsteur) [inline core/DbHelper.php:40]: Do bind parameters not work there basically @sgiehl ? If we prefix below, then we could also do an `equal =` comparison and not like?

File: core/DbHelper.php [hunk 2]
```diff
@@ -37,7 +37,7 @@ public static function getTablesInstalled($forceReload = true)
...
+        return Db::get()->query(sprintf("SHOW TABLES LIKE '%s'", $tableName))->rowCount() > 0;
```
Comment (tsteur) [inline core/DbHelper.php:40]: could maybe add a comment to the function to not use user input as table name to prevent SQL injections but that kind of applies everywhere for tables in Matomo anyway. At the same time might not hurt to mention it

Comment (diosmosis) [reply core/DbHelper.php:40]: Could also just remove `'` characters from $tableName?

Comment (tsteur) [reply core/DbHelper.php:40]: this alone would probably not prevent injections. wouldn't hurt though to do it additionally.

Comment (diosmosis) [reply core/DbHelper.php:40]: out of curiosity, what kind of value would get past that? I guess we could also remove `'";\`` characters?

Comment (tsteur) [reply core/DbHelper.php:40]: @diosmosis it depends on the use cases and how it's used. Eg you could trick Matomo into thinking the table is there or not there, or find out what tables exist by changing the input, etc. Make use of `_` and `%`...

Comment (diosmosis) [reply core/DbHelper.php:40]: 👍 that makes sense.

File: core/DbHelper.php (hunk 1 above)
Comment (sgiehl) [reply core/DbHelper.php:40]: Couldn't find any reliable information on that, but found various reports that variables don't work in `SHOW TABLES` query. Switching to an equal isn't possible in that case I guess as `SHOW TABLES LIKE` is a predefined construct, at least I wouldn't know how to convert that to a where condition that works...

File: core/DbHelper.php (hunk 2 above)
Comment (sgiehl) [reply core/DbHelper.php]: updated.

**Comment by Milo-W** [comment]
OK, I had further problems but I chose MariaDB instead of MySQL which I have on the server so now it's all good. 5.3.2 no error, just had to choose proper db settings!
