### PR TITLE
Prevent cached feedback icons being shown if the feedback plugin is disabled

### LINKED ISSUE #21365: [Bug]: Translation strings missing in 5.0 for user feedback text
### What happened?

When clicking the thumbs up/down feedback button at the top of table and charts, the feedback form shows missing translation strings. This appears to be a regression in Matomo 5.0 which was temporarily deployed to Cloud. This can be reproduced on demo2. This does not appear to affect `5.x-dev` so possibly it has been resolved. Per dev team: "there seems to be something wrong with the Feedback-Plugin and Permissions".

image

### What should happen?

Translations shown

### How can this be reproduced?

Using the **demo2** instance go to Behaviour -> Software (for example) and click the thumbs up icon at the top of any chart or table.

### Matomo Version

Matomo 5

### Matomo Patch or Minor Version

5.0

### PHP Version

NA

### Server Operating System

NA

### What browsers are you seeing the problem on?

Chrome

### Computer Operating System

NA

### Relevant log output

_No response_

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by bx80**
### Description:

Fixes #21365

This PR adds a check to make sure the Feedback plugin assembly is loaded before showing the rate feature icons, this prevents an issue where the feedback plugin is disabled but the cached javascript still shows the rate feature icons which will then be missing translation strings when clicked.

~~There is a related issue not fixed by this PR where the `EnrichedHeadline` component in `CoreHome` depends on the feedback plugin and will always try to load it dynamically when widgets are active, if the feedback plugin is disabled then a browser console error `Uncaught (in promise) PluginOnDemandLoadError: Loading plugin Feedback on demand failed.` however this does not affect the visible user experience and may require larger changes to fix.~~ Fixed by @sgiehl's suggestion below

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/CoreHome/vue/src/EnrichedHeadline/EnrichedHeadline.vue [hunk 1]
```diff
@@ -45,7 +45,7 @@
         :class="{ 'active': showInlineHelp }"
         :title="translate(reportGenerated ? 'General_HelpReport' : 'General_Help')"
       ><span class="icon-info" /></a>
-      <div class="ratingIcons">
+      <div class="ratingIcons" v-show="showRateFeature">
```
Comment (michalkleiner) [inline plugins/CoreHome/vue/src/EnrichedHeadline/EnrichedHeadline.vue]: Is there any particular reason to use `v-show`? Does the UI layout break if the element is removed completely using `v-if`?

```suggestion
      <div class="ratingIcons" v-if="showRateFeature">
```

Comment (bx80) [reply plugins/CoreHome/vue/src/EnrichedHeadline/EnrichedHeadline.vue]: I've no preference here, `v-if` seems to work as just as well as `v-show`  :+1:

Comment (michalkleiner) [reply plugins/CoreHome/vue/src/EnrichedHeadline/EnrichedHeadline.vue]: The difference is that `v-if` removes the markup completely whereas `v-show` just toggles visibility via CSS, so for this issue I think the correct-er way is `v-if`.

Comment (bx80) [reply plugins/CoreHome/vue/src/EnrichedHeadline/EnrichedHeadline.vue]: Yep, always good to avoid extra markup no matter how small :slightly_smiling_face:

**Comment by sgiehl** [comment]
@bx80 to decouple CoreHome from the Feedback plugin you could try using `useExternalPluginComponent`, and avoid directly using the component from Feedback plugin. You can see an example here:
https://github.com/matomo-org/matomo/blob/fe3a9f1f5020e10164dcc44f027677fb5c58efee/plugins/CoreAdminHome/vue/src/JsTrackingCodeGenerator/JsTrackingCodeGeneratorSitesWithoutData.vue#L87-L92

**Comment by bx80** [comment]
@sgiehl That worked well and fixes the javascript error when the feedback plugin is disabled. :+1: I've also adjusted the check to see if the feedback plugin is loaded to check directly for the feedback translations rather than the existence of `window.Feedback` which was still cached in some of my tests.

File: plugins/CoreHome/vue/src/EnrichedHeadline/EnrichedHeadline.vue [hunk 2]
```diff
@@ -202,5 +193,17 @@ export default defineComponent({
       return Matomo.helper.htmlEntities(v);
     },
   },
+  computed: {
+    showRateFeature() {
+      // eslint-disable-next-line  @typescript-eslint/no-explicit-any
+      return (window as any).translations.Feedback_SendFeedback;
```
Comment (mneudert) [inline plugins/CoreHome/vue/src/EnrichedHeadline/EnrichedHeadline.vue]: Works as intended :+1: 

But perhaps we can get rid of the lint disabling? There are two ways I know of that should work without changing other modules/files:

```
// piwik_translations is typed in CoreVue
return !!window.piwik_translations.Feedback_SendFeedback;

// the fallback translation should also work after importing the function
return translateOrDefault('Feedback_SendFeeback') !== 'Feedback_SendFeeback';
```

Comment (bx80) [reply plugins/CoreHome/vue/src/EnrichedHeadline/EnrichedHeadline.vue]: Good idea, using the translation method to check for the translation rather than directly checking the window object seems like the best approach :+1:

**Review by mneudert — APPROVED** [review]
