### PR TITLE
Truncate userId to prevent error data too long

### LINKED ISSUE #16249: SQL error: Data too long for column 'user_id'
We hit this SQL error last night:

```
Error query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'user_id' at row 1...
Parameters: array (
ERROR BulkTracking[2020-07-28 06:59:44 UTC] [6291e] 0 => '�?���',
ERROR BulkTracking[2020-07-28 06:59:44 UTC] [6291e] 1 => 'S�(<�',
ERROR BulkTracking[2020-07-28 06:59:44 UTC] [6291e] 2 => '�k�w',
ERROR BulkTracking[2020-07-28 06:59:44 UTC] [6291e] 3 => 237,
ERROR BulkTracking[2020-07-28 06:59:44 UTC] [6291e] 4 => '%252525252525252525252525252525252525252525252525252525252525252525252525252525252528...%252525252525252525252525252525252525252525252525252525252525252525252525252525252529a.langton@Sus.ta.i.n.j.ex.k@fen.Gku.an.gx.r.ku.ai8.xn%252525252525252525252525252525252525252525252525252525252525252525252525252525252520.xn%252525252525252525252525252525252525252525252525252525252525252525252525252525252520.u.k@Meli.S.a.Ri.c.h4223@e.xultan.tacoustic.sfat.lettuceerz@fault.ybeamdulltnderwearertwe.s.e@p.laus.i.bleljh@r.eces.si.v.e.x.g.z@leanna.langton@WWW.EMEKAOLISA@www.karunakumari46@sh.jdus.h.a.i.j.5.8.7.4.8574.85@c.o.nne.c.t.tn.tu@Go.O.gle.email.2.%25252525252525252525252525252525252525252525252525252525252525252525252525252525255C%25252525252525252525252525252525252525252525252525252525252525252525252525252525255Cn1@sarahjohnsonw.estbrookbertrew.e.r@hu.fe.ng.k.Ua.ngniu.bi..uk41@Www.Zanele@silvia.woodw.o.r.t.h@w.anting.parentcrazyre.stfir.stdro@www.mondaymorninginspiration@fidelia.commons@Hu.Fen.Gk.Uang.Ni.U.B.I.Xn--.U.K.6.2@p.a.r.a.ju.mp.e.r.sj.a.s.s.en20.14@Leanna.Langton@Your.Qwe.Aqmail@Sus.Ta.I.N.J.Ex.K',
ERROR BulkTracking[2020-07-28 06:59:44 UTC] [6291e] 5 => '2020-07-27 05:16:49',
```

Obviously that horrendous "user id" is to blame. The associated log file entry is,

```
www.example.org 172.107.167.119 - %252525252525252525252525252525252525252525252525252525252525252525252525252525252528...%252525252525252525252525252525252525252525252525252525252525252525252525252525252529a.langton@Sus.ta.i.n.j.ex.k@fen.Gku.an.gx.r.ku.ai8.xn%252525252525252525252525252525252525252525252525252525252525252525252525252525252520.xn%252525252525252525252525252525252525252525252525252525252525252525252525252525252520.u.k@Meli.S.a.Ri.c.h4223@e.xultan.tacoustic.sfat.lettuceerz@fault.ybeamdulltnderwearertwe.s.e@p.laus.i.bleljh@r.eces.si.v.e.x.g.z@leanna.langton@WWW.EMEKAOLISA@www.karunakumari46@sh.jdus.h.a.i.j.5.8.7.4.8574.85@c.o.nne.c.t.tn.tu@Go.O.gle.email.2.%25252525252525252525252525252525252525252525252525252525252525252525252525252525255C%25252525252525252525252525252525252525252525252525252525252525252525252525252525255Cn1@sarahjohnsonw.estbrookbertrew.e.r@hu.fe.ng.k.Ua.ngniu.bi..uk41@Www.Zanele@silvia.woodw.o.r.t.h@w.anting.parentcrazyre.stfir.stdro@www.mondaymorninginspiration@fidelia.commons@Hu.Fen.Gk.Uang.Ni.U.B.I.Xn--.U.K.6.2@p.a.r.a.ju.mp.e.r.sj.a.s.s.en20.14@Leanna.Langton@Your.Qwe.Aqmail@Sus.Ta.I.N.J.Ex.K [27/Jul/2020:01:16:49 -0400] "GET /en/node/2265/track HTTP/1.1" 301 - "https://%25252525252525252525252525252525252525252525252525252525252525252525252525252525252528...%25252525252525252525252525252525252525252525252525252525252525252525252525252525252529a.langton@Sus.ta.i.n.j.ex.k@fen.Gku.an.gx.r.ku.ai8.xn%25252525252525252525252525252525252525252525252525252525252525252525252525252525252520.xn%25252525252525252525252525252525252525252525252525252525252525252525252525252525252520.u.k@Meli.S.a.Ri.c.h4223@e.xultan.tacoustic.sfat.lettuceerz@fault.ybeamdulltnderwearertwe.s.e@p.laus.i.bleljh@r.eces.si.v.e.x.g.z@leanna.langton@WWW.EMEKAOLISA@www.karunakumari46@sh.jdus.h.a.i.j.5.8.7.4.8574.85@c.o.nne.c.t.tn.tu@Go.O.gle.email.2.%2525252525252525252525252525252525252525252525252525252525252525252525252525252525255C%2525252525252525252525252525252525252525252525252525252525252525252525252525252525255Cn1@sarahjohnsonw.estbrookbertrew.e.r@hu.fe.ng.k.Ua.ngniu.bi..uk41@Www.Zanele@silvia.woodw.o.r.t.h@w.anting.parentcrazyre.stfir.stdro@www.mondaymorninginspiration@fidelia.commons@Hu.Fen.Gk.Uang.Ni.U.B.I.Xn--.U.K.6.2@p.a.r.a.ju.mp.e.r.sj.a.s.s.en20.14@Leanna.Langton@Your.Qwe.Aqmail@Sus.Ta.I.N.J.Ex.K@www.example.org/" "Mozilla/5.0 (X11; OpenBSD i386) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.125 Safari/537.36"
```

This is during an off-line mass log file import. I guess that column should be sanitized, within reason?

### PR DESCRIPTION
**Pull request by tsteur**
fix https://github.com/matomo-org/matomo/issues/16249

### CODE REVIEW

File: plugins/CoreHome/Columns/UserId.php [hunk 1]
```diff
@@ -55,7 +55,11 @@ public function __construct()
      */
     public function onNewVisit(Request $request, Visitor $visitor, $action)
     {
-        return $request->getForcedUserId();
+        $value = $request->getForcedUserId();
```
Comment (tsteur) [inline plugins/CoreHome/Columns/UserId.php:58]: no need to truncate the data in `getForcedUserId()` directly. Should someone use > 200 characters then the visitorId will still be different for different visitors this way (as it does like `substr(sha1($userId), 0, 16)`)
