### PR TITLE
Fix possible notices

### LINKED ISSUE #17883: Possible warning notices during log archive
While running our nightly log import/archive, I noticed these two warnings:

```
INFO [2021-08-09 07:02:17] 16363  Scheduler: finished. Time elapsed: 13.758s
INFO [2021-08-09 07:02:17] 16363  Scheduler: executing task Piwik\Plugins\CoreAdminHome\Tasks.purgeOrphanedArchives...
WARNING [2021-08-09 07:02:17] 16363  /var/www/example.com/analytics/public/core/DataAccess/Model.php(635): Notice - Undefined index: hash - Matomo 4.4.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
WARNING [2021-08-09 07:02:17] 16363  /var/www/example.com/analytics/public/core/DataAccess/Model.php(638): Notice - Array to string conversion - Matomo 4.4.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
```

Aside from the non-zero exit code, nothing else bad happened.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #17883

### Review

* [ ] Functional review done
* [ ] Potential edge cases thought about (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/DataAccess/Model.php [hunk 1]
```diff
@@ -632,10 +632,10 @@ public function getArchiveIdsForSegments($archiveTableName, array $segments, $ol
     private function getDeletedSegmentWhereClause(array $segment)
     {
         $idSite = (int)$segment['enable_only_idsite'];
-        $segmentHash = $segment['hash'];
+        $segmentHash = $segment['hash'] ?? '';
```
Comment (sgiehl) [inline core/DataAccess/Model.php:635]: @diosmosis Do you have a quick idea why the hash might be unset here? Haven't had a deeper look at the code where that might come from.

Comment (diosmosis) [reply core/DataAccess/Model.php:635]: @sgiehl looks like a bug, `hash` isn't selected in SegmentEditor\Model::getSegmentsDeletedSince()

Comment (sgiehl) [reply core/DataAccess/Model.php:635]: good catch. Updated that method 👍
