### PR TITLE
Lock down accounts by IP after N failed attemps at logging in

### LINKED ISSUE #2888: Lock down accounts by IP after N failed attemps at logging
Our security policy aims to make security a principal design behind Piwik. One aspect that bugs me currently is that good old brute force attacks could be vector of penetration in Piwik (if eg. attacker knows the login).

We should provide a core mechanism that would lock out, for  30min for example, a user after N failed attemps. Settings could be changed by the Super User and feature would be enabled by default, lock 30 min out after 5 failed attempts.

Implementation proposal:
- Record, using Piwik_SetOption, count of lockdown for each IP that fails to enter valid login / pwd combination
- After N failures, lock IP down and refuse authentication (even if the combination is actually valid!).
- Document as FAQ, linked from UI, the sql to delete all locked out IPs in case the SU was actually locked out and can't wait.

### PR DESCRIPTION
**Pull request by tsteur**
As discussed in #2888 a quite simple implementation that should do the job. Heaps more could be done as mentioned in the comments but might not be needed.

It took me couple hours to understand all the authentication/login flows as there are lots of different components now such as Auth, SessionAuth, SessionInitializer, Access, etc. and it wasn't clear where to put things to make it work universally while still being clear about when it happens etc.

Also had to add couple of events eg for failed logins. The most important part is really to register a failed login attempt when there is one (we often authenticate eg API requests etc even though the user didn't, or we always authenticate first against session then regular auth adapter etc which makes things complicated). And it is important to check whether IP is blocked when trying to attempt to log in. All those parts should be covered.

When an IP is blocked, I did not want to block any already logged in users in the UI. This could be annoying when a company shares the same IP and it would otherwise even block the super user.

The superuser has a diagnostic page to unblock all users and a console command. Can also document in a FAQ how to do it through the SQL database directly.

For system settings and diagnostics page screens see screenshot tests.

Functionality wise you specify two values: X amount of login retries allowed in Y amount of minutes. If you have more than X amount of logins within Y amount of minutes, you are blocked and cannot log in. Even when successful token provided for example. You can only log in again, when some time has passed and you had less than X amount of login retries within the last Y amount of minutes. There is no specific lock out time that you can configure so if people lock themselves out they can use UI again after eg 30 min or 60min. By default we allow 20 logins within 60 minutes. When sharing an IP within an office those 20 logins could be reached within an hour but should be maybe fine. Hard to find the right balance here.

You can also whitelist and blacklist specific IPs.

fixes #2888 

I'll try to write some more tests for the different login failures once the PR is reviewed.

### CODE REVIEW

**Comment by sgiehl** [comment]
Haven't tested, but wondering if using "Webcron" (calling the archiver with token_auth in url) will still work if the according account got locked down.

**Comment by tsteur** [comment]
Just tested it, but it works as it is only an API test.

But realizing now that the UI is sending API requests so there is pretty much no way to keep the UI working for a logged in user when the IP got blocked by a different user. Will need to block the entire UI as it current behaviour it would only block partial UI and look broken.

**Comment by tsteur** [comment]
Todo: We need to update either this PR or https://github.com/matomo-org/matomo/pull/13670 depending on which one gets merged first to apply brute force / lock down changes to #13670

File: plugins/Login/Login.php [hunk 1]
```diff
@@ -33,13 +38,76 @@ public function registerEvents()
...
+        // time frame
+        $bruteForce = StaticContainer::get('Piwik\Plugins\Login\Security\BruteForceDetection');
+        if ($bruteForce->isEnabled()) {
+            if (!$this->hasAddedFailedAttempt) {
+                $bruteForce->addFailedLoginAttempt(IP::getIpFromHeader());
+                // we make sure to log max one failed login attempt per request... otherwise we might log 3 or many more
+                // if eg API is called etc.
+                $this->hasAddedFailedAttempt = true;
+            }
+        }
```
Comment (diosmosis) [inline plugins/Login/Login.php]: These two `if`s can be combined.

File: plugins/Login/Security/BruteForceDetection.php [hunk 2]
```diff
@@ -0,0 +1,134 @@
...
+    }
+
+    public function addFailedLoginAttempt($ipAddress)
+    {
+        $now = $this->getNow()->getDatetime();
+        $db = Db::get();
+        $db->query('INSERT INTO '.$this->tablePrefixed.' SET ip_address = ?, attempted_at = ?', array($ipAddress, $now));
+    }
+
+    public function canLogin($ipAddress)
```
Comment (diosmosis) [inline plugins/Login/Security/BruteForceDetection.php]: small issue, but I think this method would be clearer if named `isAllowedToLogin`

File: plugins/Login/Login.php [hunk 3]
```diff
@@ -33,13 +38,76 @@ public function registerEvents()
...
+    }
+
+    public function beforeLoginCheckBruteForce()
+    {
+        $bruteForce = StaticContainer::get('Piwik\Plugins\Login\Security\BruteForceDetection');
+        if (!$this->hasPerformedBruteForceCheck && $bruteForce->isEnabled() && !$bruteForce->canLogin(IP::getIpFromHeader())) {
+            throw new Exception(Piwik::translate('Login_LoginNotAllowedBecauseBlocked'));
+        }
+        // for performance reasons we make sure to execute it only once per request
+        $this->hasPerformedBruteForceCheck = true;
```
Comment (diosmosis) [inline plugins/Login/Login.php]: If `onFailedLoginRecordAttempt()` is called in a request, then this method can get called more than once, correct? Perhaps we should check if `$this->hasPerformedBruteForceCheck` is true at the top of this method and return if so?

File: plugins/Login/Security/BruteForceDetection.php [hunk 4]
```diff
@@ -0,0 +1,134 @@
...
+    public function isEnabled()
+    {
+        return $this->settings->enableBruteForceDetection->getValue();
+    }
+
+    public function addFailedLoginAttempt($ipAddress)
+    {
+        $now = $this->getNow()->getDatetime();
+        $db = Db::get();
+        $db->query('INSERT INTO '.$this->tablePrefixed.' SET ip_address = ?, attempted_at = ?', array($ipAddress, $now));
```
Comment (diosmosis) [inline plugins/Login/Security/BruteForceDetection.php]: mysqlism here. don't think it's a big deal since matomo and mysql are pretty intertwined at this point, just letting you know in case you missed it.

File: plugins/Login/Security/BruteForceDetection.php [hunk 5]
```diff
@@ -0,0 +1,134 @@
...
+        $this->minutesTimeRange = $systemSettings->loginAttemptsTimeRange->getValue();
+        $this->maxLogAttempts = $systemSettings->maxFailedLoginsPerMinutes->getValue();
+    }
+
+    public function isEnabled()
+    {
+        return $this->settings->enableBruteForceDetection->getValue();
+    }
+
+    public function addFailedLoginAttempt($ipAddress)
```
Comment (diosmosis) [inline plugins/Login/Security/BruteForceDetection.php]: I'm wondering, could this be a potential ddos attack vector? If someone purposefully sends tons of tracker requests w/o a token auth, would it fill up the table w/ meaningless data? I suppose they would have to vary their IP addresses, or use multiple ip addresses and time things right to add the junk data. Not sure exactly what kind of effect this would have.

File: plugins/Login/Security/BruteForceDetection.php [hunk 6]
```diff
@@ -0,0 +1,134 @@
...
+        return empty($numLogins) || $numLogins <= $this->maxLogAttempts;
+    }
+
+    public function getCurrentlyBlockedIps()
+    {
+        $sql = 'SELECT ip_address
+                FROM ' . $this->tablePrefixed . ' 
+                WHERE attempted_at > ?
+                GROUP BY ip_address 
+                HAVING count(*) > ' . (int) $this->maxLogAttempts;
```
Comment (diosmosis) [inline plugins/Login/Security/BruteForceDetection.php]: This query will do a full table scan, correct? Since there's no index on attempted_at. Would that be an issue for tracking (assuming there are enough roes in the table)?

File: plugins/Login/tests/UI/Login_spec.js [hunk 7]
```diff
@@ -119,4 +123,64 @@ describe("Login", function () {
...
+        testEnvironment.testUseMockAuth = 1;
+        testEnvironment.bruteForceBlockThisIp = 1;
+        delete testEnvironment.bruteForceBlockIps;
+        delete testEnvironment.queryParamOverride;
+        testEnvironment.save();
+
+        expect.screenshot("bruteforcelog_blockedapi").to.be.capture(function (page) {
+            page.load(apiAuthUrl);
+        }, done);
+    });
```
Comment (diosmosis) [inline plugins/Login/tests/UI/Login_spec.js]: I think this one could be tested in a system test w/ `Http::sendRequest()`, in case you don't want to keep the screenshot around.

**Comment by diosmosis** [comment]
Reviewed code, haven't tested locally though

**Comment by Findus23** [comment]
@tsteur In case this isn't already included (I didn't check), I think it would be worth it to extend this feature to the password reset feature.

Currently an attacker can try out unlimited password resets, which will send unlimited emails to the Matomo user and if they accidently click on the link in any email, the attacker has immediate full access to the instance (which is another security issue in itself, that maybe should be fixed in one of the next releases (https://github.com/matomo-org/matomo/issues/11071))

**Comment by tsteur** [comment]
> @tsteur In case this isn't already included (I didn't check), I think it would be worth it to extend this feature to the password reset feature.
> 
> Currently an attacker can try out unlimited password resets, which will send unlimited emails to the Matomo user and if they accidentaly click on the link in any email, the attacker has immediate full access to the instance (which is another security issue in itself, that maybe should be fixed in one of the next releases (#11071))

Not sure @Findus23 I can add a simple block to password reset page if user is already blocked because of too many failed logins. I reckon in case you locked yourself out it may be good to reach the password reset page though. Once the lock is expired, you can simply log in with the new password... Maybe create a new issue for this, but don't think it has too much of a priority if we should also count the number of resets etc. In theory, just one reset is enough though to possibly trick a user, or one reset every hour... or something. I don't think it adds much to security and rather #11071 can be looked at to be improved eventually.

File: plugins/Login/Login.php (hunk 1 above)
Comment (tsteur) [reply plugins/Login/Login.php]: will do 👍

File: plugins/Login/Login.php (hunk 3 above)
Comment (tsteur) [reply plugins/Login/Login.php]: not sure I understand what you mean... it already checks this flag in the `if` in `beforeLoginCheckBruteForce()`.  and we have a different flag in`onFailedLoginRecordAttempt`

File: plugins/Login/Security/BruteForceDetection.php (hunk 5 above)
Comment (tsteur) [reply plugins/Login/Security/BruteForceDetection.php]: Depends... if you have access to someones WIFI, you could possibly try lots of failed logins to log out the organisation...Or depending how Matomo is configured, you could maybe set a custom IP in the header if reads the IP from a different header.

Otherwise re meaningless data... you could also send heaps of meaningless data to the tracker API etc. I don't think that's an issue?

File: plugins/Login/Security/BruteForceDetection.php (hunk 4 above)
Comment (tsteur) [reply plugins/Login/Security/BruteForceDetection.php]: will update 👍

File: plugins/Login/Security/BruteForceDetection.php (hunk 2 above)
Comment (tsteur) [reply plugins/Login/Security/BruteForceDetection.php]: will change 👍

File: plugins/Login/Security/BruteForceDetection.php (hunk 6 above)
Comment (tsteur) [reply plugins/Login/Security/BruteForceDetection.php]: I figured because we delete entries after 7 days there shouldn't be too many in the DB and it should be fine and the query is only executed in a task or when viewing blocked IPs.

File: plugins/Login/lang/en.json [hunk 8]
```diff
@@ -10,6 +11,21 @@
         "InvalidUsernameEmail": "Invalid username or e-mail address.",
         "LogIn": "Sign in",
         "LoginOrEmail": "Username or Email",
+        "HelpIpRange": "Enter one IP address or one IP range per line. You can use CIDR notation eg. %1$s or you can use wildcards, eg. %2$s or %3$s",
+        "SettingBruteForceEnable": "Enable Brute Force Detection",
+        "SettingBruteForceEnableHelp": "Brute Force Detection is an important security part to protect your data. Instead of allowing any user to try thousands, or millions of password combinations within a very short time, it will only allow a specific amount of failed logins within a short period of time. If too many failed logins occur in that time range, the user won't be able to log in until some time has passed. Please note that if too many failed logins occur, all users that use the same IP may be blocked from logging in as well.",
```
[the remark this answers is not in the document]
Comment (tsteur) [reply plugins/Login/lang/en.json]: will update 👍

File: plugins/Login/lang/en.json [hunk 9]
```diff
@@ -10,6 +11,21 @@
...
+        "SettingBruteForceWhitelistIp": "Never block any of these IPs from logging in",
+        "SettingBruteForceBlacklistIp": "Never block any of these IPs from logging in",
```
[the remark this answers is not in the document]
Comment (tsteur) [reply plugins/Login/lang/en.json]: will do 👍

File: plugins/Login/Login.php (hunk 3 above)
Comment (diosmosis) [reply plugins/Login/Login.php]: Nvm, missed the `if`.

File: plugins/Login/Security/BruteForceDetection.php (hunk 5 above)
Comment (diosmosis) [reply plugins/Login/Security/BruteForceDetection.php]: Was wondering if it would affect the tracking latency, but sounds like it won't

File: plugins/Login/Security/BruteForceDetection.php (hunk 6 above)
Comment (diosmosis) [reply plugins/Login/Security/BruteForceDetection.php]: 👍

**Comment by Findus23** [comment]
@tsteur I think the main reason why we should limit the password resets is that attackers can create a lot of chaos by requesting hundreds of password resets per minute an spamming the users mailbox, overloading the mailserver or even damaging the spam ranking. 
You are right that this is less or a security issue, but more limiting the damage an attacker can create. 
I like the position of discourse on having rate limits on everything and it really helps keeping spam out of the Matomo forum as most spammers get caught in some limit before posting.
https://blog.codinghorror.com/rate-limiting-and-velocity-checking/

**Comment by tsteur** [comment]
Can you create a new issue for this?

**Comment by tsteur** [comment]
@diosmosis fyi fixed the tests
