### PR TITLE
Fix for row labels sometimes disappearing when double clicked in table report

### LINKED ISSUE #20894: Row labels disappear on double click in table report
## Context

I have a custom report with a subtable. When I double click in the white space on a row, then all top level row labels disappear in Matomo 5.0 beta:

Screenshot 2023-06-14 at 7 15 51 AM

In Matomo 4.0 the labels shorten:

image

I couldn't reproduce it yet on a standard report I think.

## Expected Behavior

Labels stay fully visible

### PR DESCRIPTION
**Pull request by bx80**
### Description:

Fixes #20894 

This can take a bit of time to recreate, I used the event report and clicked repeatedly on the first label to expand and collapse it:
image

Eventually the label disappears:
image

The label is disappearing because the column width is being set to zero by the `resizeDataTable()` event, a minimum label size is passed to `getLabelWidth()` but this method sometimes incorrectly calculates a zero width value from existing DOM elements. I suspect that this could be race condition between the row collapse and resize table events.

This PR adds a check to the `getLabelWidth()` method to prevent zero values being returned and instead falls back to the passed `minLabelWidth` value. After this change I was no longer able to recreate the issue, despite much clicking.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/CoreHome/javascripts/dataTable.js [hunk 1]
```diff
@@ -496,8 +496,11 @@ $.extend(DataTable.prototype, UIControl.prototype, {
             if (allColumns > 2 * firstTableColumn) {
                 amount = 2 * firstTableColumn;
             }
-
-            return parseInt(labelWidth / amount, 10);
+            var newWidth = parseInt(labelWidth / amount, 10)
+            if (newWidth == 0) {
+                newWidth = minLabelWidth; // fallback to the minimum width if zero
```
Comment (sgiehl) [inline plugins/CoreHome/javascripts/dataTable.js]: might be better to use the maximum available space so the label won't get smaller.
```suggestion
                newWidth = maxLabelWidth; // fallback to the maximum width if zero
```

**Review by sgiehl — CHANGES_REQUESTED** [review]
@bx80 For me this is reproducible on 5.x-dev if you click on a row to load it's subtable, but close the row before the subtable is loaded. As soon as the subtable is then loaded, the label disappears.

**Review by sgiehl — APPROVED** [review]
works as expected now 👍
