### PR TITLE
Fix for unhandled datatable maps in custom dimensions

### LINKED ISSUE #20043: Fatal error: Call to undefined method Piwik\\DataTable\\Map::getRows() in CustomDimensions/API.php
Using latest Matomo version.

> Error: {"message":"Call to undefined method Piwik\\DataTable\\Map::getRows()","file":"\plugins\/CustomDimensions\/API.php","line":65,"request_id":"f4e73","backtrace":" on \plugins\/CustomDimensions\/API.php(65)\n#0 [internal function]: Piwik\\Plugins\\CustomDimensions\\API->getCustomDimension('1', '51', 'year', '2022-01-01,2022...', false, false, false, '15')\n#1 \core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#2 \core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#3 \core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#4 \core\/API\/Request.php(267): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'getCustomDimens...', Array)\n#5 \plugins\/API\/Controller.php(45): Piwik\\API\\Request->process()\n#6 [internal function]: Piwik\\Plugins\\API\\Controller->index()\n#7 \core\/FrontController.php(631): call_user_func_array(Array, Array)\n#8 \core\/FrontController.php(169): Piwik\\FrontController->doDispatch('API', false, Array)\n#9 \core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#10 \index.php(25): require_once('\c...')\n#11 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(631): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(100): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(140): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(190): Piwik\\FrontController::(Object(Error))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}

> URL: /?module=API&method=CustomDimensions.getCustomDimension&idSite=51&date=2022-01-01,2022-11-23&period=year&format=json&token_auth=XYZANONYMIZED&idDimension=1&subcategory=Events_Events&idSubtable=15

> GET: {"module":"API","method":"CustomDimensions.getCustomDimension","idSite":"51","date":"2022-01-01,2022-11-23","period":"year","format":"json","token_auth":"XYZANONYMIZED","idDimension":"1","subcategory":"Events_Events","idSubtable":"15","filter_limit":100}

### PR DESCRIPTION
**Pull request by bx80**
### Description:

If the `Archive::createDataTableFromArchive()` method returns a `DataTable\Map` instead of a `DataTable` object then `getCustomDimension()` tries to use it as a single DataTable object resulting in errors. This fix checks if the returned object is a `DataTable\Map` and if so uses a different method to retrieve the required data.

Fixes #20043

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by justinvelluppillai** [comment]
You can probably base this off 4.x-dev and aim for 4.13.0

File: plugins/CustomDimensions/API.php [hunk 1]
```diff
@@ -62,13 +63,25 @@ public function getCustomDimension($idDimension, $idSite, $period, $date, $segme
 
         if (!empty($idSubtable) && $dataTable->getRowsCount()) {
             $parentTable = Archive::createDataTableFromArchive($record, $idSite, $period, $date, $segment);
-            foreach ($parentTable->getRows() as $row) {
-                if ($row->getIdSubDataTable() == $idSubtable) {
+
+            $parentValue = null;
+            if ($parentTable instanceof Map) {
+                $row = $parentTable->getRowFromIdSubDataTable($idSubtable);
```
Comment (sgiehl) [inline plugins/CustomDimensions/API.php]: Doesn't this method exist for all DataTable types? Guess we could always use it to get the correct row in all cases. So we wouldn't need the check if it's a map.

Comment (bx80) [reply plugins/CustomDimensions/API.php]: Good point :+1:  
I've updated the change to just use that method for all returned object and not check the type.

**Comment by sgiehl** [comment]
@bx80 When changing the base branch of the PR, you need to rebase the branch on the new base branch. Merging this branch in won't remove all the additional commits from the original base. If you need help with that, let me know.

**Comment by bx80** [comment]
@sgiehl Thanks, I've rebased the branch from 4.x-dev and force pushed the changes, it's still showing extra commits though. It's fairly painful to rebase 5.x-dev to 4.x-dev at the moment with the Angular removal changes. Might be cleaner if I just create a new branch  / PR?

**Comment by sgiehl** [comment]
@bx80 rebasing should only be painful when you have dozens of merge conflicts. But in this case there shouldn't be any conflicts. So it should be a simple rebase on the branch, while removing all commits that don't belong to this PR...

**Review by sgiehl — APPROVED** [review]
I've rebased the branch, and removed all the commits left over from `5.x-dev`.
If tests are passing, this one should be good to merge.

**Comment by bx80** [comment]
Thanks @sgiehl! :smiley: I was mistakenly attempting to merge in the other 5.x commits rather than just removing them :roll_eyes:
