### PR TITLE
Use email address validator from Zend

### LINKED ISSUE #7298: Email address hel*lo@mail.com should be accepted as valid
Hello.
I'm trying to register a user with email "hel*lo@mail.com" using the Piwik's API. The API responses with following error:
```javascript
 'result' => 'error'
 'message' => 'The email doesn't have a valid format.'
```

According to specs (http://tools.ietf.org/html/rfc5322#section-3.4 , http://tools.ietf.org/html/rfc2822#section-3.2.4) email address "hel*lo@mail.com" is valid.

Can you change email validator according specs?

### PR DESCRIPTION
**Pull request by barbushin**
Closes #7298

### CODE REVIEW

**Comment by mattab** [comment]
Feedback: 
* add a unit test for this method to show that it really closes #7298 and that it validate email addresses properly

**Comment by barbushin** [comment]
@mattab Done

File: core/Piwik.php [hunk 1]
```diff
@@ -563,7 +563,14 @@ public static function redirectToModule($newModule, $newAction = '', $parameters
...
     public static function isValidEmailString($emailAddress)
     {
-        return (preg_match('/^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9_.-]+\.[a-zA-Z]{2,}$/D', $emailAddress) > 0);
+        static $zendEmailValidator;
+        if(!$zendEmailValidator) {
+            $zendEmailValidator = new \Zend_Validate_EmailAddress(array(
+                'mx' => false,
+                'deep' => false
+            ));
+        }
```
Comment (diosmosis) [inline core/Piwik.php]: Instead of using a static variable here, DI should be used. You can get an object from DI via,

```
StaticContainer::get('Zend_Validate_EmailAddress'); // full class name goes here
```

If there's no definition in a PHP config file (ie, config/global.php or one of the plugin ones), the DI container will create a new instance itself, autowiring dependencies.

Since you're creating a instance w/ a specific constructor arg, you'll have to add a definition for the instance in `config/global.php`. Should be self-explanatory how to do it, let me know if it isn't.

Regarding `StaticContainer` use: since Piwik's internals are so deeply coupled, we have to use something like this (which stores the container as a global static variable), however we're getting close to removing it. In the future, if possible, try not to use it (by specifying dependencies in the constructor). In this case, since it's a static method, there's no choice but to use it (especially since it's `@api`). If this isn't clear, let me know, I'll try to clarify.

File: tests/PHPUnit/Integration/EmailValidatorTest.php [hunk 2]
```diff
@@ -0,0 +1,140 @@
...
+ * @group Core
+ */
+class EmailValidatorTest extends IntegrationTestCase
+{
+    protected function isValid($email)
+    {
+        return Piwik::isValidEmailString($email);
+    }
+
+    public function testValidStandard()
```
Comment (diosmosis) [inline tests/PHPUnit/Integration/EmailValidatorTest.php]: The current convention for test names is `test_{{methodName}}_{{descriptionOfTest}}`, for example:

`test_isValid_shouldValidateANormalEmail`

Can you change the test method names to this type of name?

More examples: https://github.com/piwik/piwik/blob/master/tests/PHPUnit/Integration/TrackerTest.php

File: tests/PHPUnit/Integration/EmailValidatorTest.php [hunk 3]
```diff
@@ -0,0 +1,140 @@
...
+
+namespace Piwik\Tests\Integration;
+
+use Piwik\Piwik;
+use Piwik\Tests\Framework\TestCase\IntegrationTestCase;
+
+/**
+ * @group Core
+ */
+class EmailValidatorTest extends IntegrationTestCase
```
Comment (diosmosis) [inline tests/PHPUnit/Integration/EmailValidatorTest.php]: Is there a reason this is an integration test? Note: currently the IntegrationTestCase base class will create a database before tests start and reset it before each test, which slows things down.

File: core/Piwik.php (hunk 1 above)
Comment (barbushin) [inline core/Piwik.php]: @diosmosis StaticContainer is martked as `@deprecated`.

**Comment by barbushin** [comment]
@diosmosis I've renamed test methods, and changed test parent class to `PHPUnit_Framework_TestCase`. Thanks for that review!

File: core/Piwik.php (hunk 1 above)
Comment (diosmosis) [inline core/Piwik.php]: It was introduced as `@deprecated` because Piwik's dependencies are too hard-coded. It's taken us ~5 months or so to try to remove it, and we are still one month away from doing it. You can use it for now, though you should try to avoid where possible.

Comment (barbushin) [inline core/Piwik.php]: @diosmosis I'm worried, that if I put `Zend_Validate_EmailAddress` in DI, then another core/plugins developers will call email validation using `Zend_Validate_EmailAddress` from DI, instead of using `Piwik::isValidEmailString()`, and in this way Piwik will depends on Zend/Validate library. I gues this case is not about DI pattern, it's about https://en.wikipedia.org/wiki/Flyweight_pattern

But if this is a common practice for Piwik to use DI container as Flyweighter, then I can do some refactoring. Benaka, are you 100% sure about it?

Comment (diosmosis) [inline core/Piwik.php]: Most of what's in DI is currently not API, and when things are made API they are explicitly mentioned in docs (or should be).

As for the flyweight pattern, that normally involves more than one object. This is caching a single instance for the current request. If you don't want to use DI, you could use the transient cache, via, `Piwik\Cache::getTransientCache()`.

Whatever you do, please make sure this value can be reset during tests, and if possible, overridden (though I think this is only do-able through DI). Static local variables have made me waste days debugging tests, and I would gladly anger the design pattern gods or whatever entity is responsible for programming zealotry if it meant I didn't have to waste my time on pointless work.

**Comment by barbushin** [comment]
Moved `Zend_Validate_EmailAddress` to `DI`. Now it's ready to merge?

**Comment by barbushin** [comment]
It was a wrong old test method `UsersManagerTest::testAddUserWrongEmail()` that  asserted that `ema'il@email.com` is invalid, but regarding RFC and new email validator(and http://isemail.info) `ema'il@email.com` is valid.

`array('mx' => false, 'deep' => false)` are default settings for `Zend_Validate_EmailAddress` so I think we can just forget about it.

File: config/global.php [hunk 4]
```diff
@@ -64,5 +64,7 @@
 
     'observers.global' => array(),
 
-    'Piwik\EventDispatcher' => DI\object()->constructorParameter('observers', DI\get('observers.global'))
+    'Piwik\EventDispatcher' => DI\object()->constructorParameter('observers', DI\get('observers.global')),
+
+    'Zend_Validate_EmailAddress' => DI\object('Zend_Validate_EmailAddress'),
```
Comment (mnapoli) [inline config/global.php]: FYI this line is not necessary: by default with [autowiring](http://php-di.org/doc/autowiring.html) PHP-DI can create the instance without configuration needed (because here there is no constructor parameter to configure). It's no big deal but it's just to let you know

Comment (mnapoli) [inline config/global.php]: Ah I just saw d4a024b02b0e5f18b7c88b965d836e8c609bdec9 ;)
