### PR TITLE
Convert comma separated param values to arrays if needed

### LINKED ISSUE #12627: Fatal error: Cannot unset string offsets in JqplotDataGenerator
Following error happened on `index.php?date=2018-03-18&viewDataTable=graphVerticalBar&module=VisitTime&action=getByDayOfWeek&widget=1&columns_to_display=nb_actions%2Cnb_uniq_visitors&idSite=1&period=week`

`"message":"Cannot unset string offsets","file":"plugins\/CoreVisualizations\/JqplotDataGenerator.php","line":106`

Haven't tried to reproduce myself so not sure if it is an easy fix or not.

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #12627

### CODE REVIEW

File: core/Plugin/ViewDataTable.php [hunk 1]
```diff
@@ -455,7 +455,12 @@ private function overrideViewPropertiesWithQueryParams()
     protected function getPropertyFromQueryParam($name, $defaultValue)
     {
         $type = is_numeric($defaultValue) ? 'int' : null;
-        return Common::getRequestVar($name, $defaultValue, $type);
+        $value = Common::getRequestVar($name, $defaultValue, $type);
+        // convert comma separated values to arrays if needed
+        if (is_array($defaultValue)) {
+            $value = Piwik::getArrayFromApiParameter($value);
+        }
+        return $value;
```
Comment (diosmosis) [inline core/Plugin/ViewDataTable.php]: Will this affect other parameters as well? Eg, the 'label' parameter or a parameter like it might have commas in it but might not be an array.

Comment (sgiehl) [reply core/Plugin/ViewDataTable.php]: it shouldn't, as those parameters should not have an array as default value.

Comment (diosmosis) [reply core/Plugin/ViewDataTable.php]: Ah, I see, nvm then.

**Comment by diosmosis** [comment]
LGTM. Do you think it would be worthwhile to mention this change in the changelog? That plugins that add overridable array ViewDataTable properties can now accept comma separated lists from query parameters? Although I originally remember this being supported by columns_to_display, so maybe it's more of a regression.

**Comment by sgiehl** [comment]
`columns` could be given as comma separated list. Not sure if that applied for `columns_to_display` as well. I'm not sure if we should mention it in the changelog... @mattab any opinion?

**Comment by diosmosis** [comment]
Right, maybe I'm thinking about `columns`

**Comment by mattab** [comment]
I reckon it's not needed to mention it in this case
