### PR TITLE
Fix translation usage in datatable footer

### LINKED ISSUE #9670: Translation strings show up with placeholders in UI
This regressed I think from #9546 - some of the strings are displayed with placeholders in the UI eg.

not translated

ping @sgiehl

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #9670

### CODE REVIEW

File: plugins/CoreHome/javascripts/dataTable.js [hunk 1]
```diff
@@ -1239,14 +1239,18 @@ $.extend(DataTable.prototype, UIControl.prototype, {
...
 
-        var getText = function (text, addDefault) {
-            text = _pk_translate(text);
-            if (text.indexOf('%s') > 0) {
-                text = text.replace('%s', '<br /><span class="action">&raquo; ');
+        var getText = function (text, addDefault, replacement) {
+            if (/(%(.\$)?s+)/g.test(_pk_translate(text))) {
+                var values = ['<br /><span class="action">&raquo; '];
+                if(replacement) {
+                    values.push(replacement);
```
Comment (tsteur) [inline plugins/CoreHome/javascripts/dataTable.js]: I haven't tested it yet but does it actually do the same? I think before it was maybe replacing the first `%s` with `self.props.pivot_dimension_name` and now it's maybe the second `%s` (`replacement`)

**Comment by mattab** [comment]
Works for me :+1:
