### PR TITLE
Return status code 401 for invalid tokens in API requests

### LINKED ISSUE #18055: Request with invalid token_auth responds 200 OK
When sending requests against  the API module with a non existing token, the HTTP response should be 403. Not 200.

## Expected Behavior

When sending a request with a non existing token, response code should be 403
## Current Behavior

Response code is 200

## Steps to Reproduce (for Bugs)

1. `curl -ik 'https://matomo.example.com/index.php?module=API&method=API.getMatomoVersion&token_auth=I_DONT_EXIST'`

## Your Environment

* Matomo Version: 4.4.1
* PHP Version: PHP 7.4.3
* Server Operating System: Ubuntu 20.04.03

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:

Fixes: #18055 

update the status code to 401 when an invalid token in API

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by peterhashair** [comment]
Maybe the CHANGELOG wording needs an update.

**Comment by peterhashair** [comment]
Maybe we don't need this change. 

```php
   if ($referrer && $matomoUrl && Url::isValidHost(Url::getHostFromUrl($referrer)) &&
                strpos($referrer, $matomoUrl) === 0
            ) {
                Common::sendResponseCode(440);
```

**Review by sgiehl — CHANGES_REQUESTED** [review]
Maybe better give this one a new try. It can't / doesn't work the way it's implemented.
* On the login page, the CSS fails to load, as it results in a 401 response
* The 440 response code is actually a special IIS code, not sure if we should use it, as no one might expect it
* Currently any method using one of the `Access::check*` methods might end up in a 401 response, which also affects the UI and not only API
* You should not adjust the response code in Access class, as you can't know if exceptions thrown there, are not caught and ignored.

**Comment by peterhashair** [comment]
@sgiehl yeah, removed from `access.php`.  I tried another place that only affects API. I don't believe this is a perfect way, any suggestions?

**Comment by sgiehl** [comment]
Checking the trace for a certain method doesn't seem to be something we should consider doing. Isn't the method throwing a certain exception that can be checked for?

In general I guess my approach would have been to convert `HttpCodeException` to an interface, and let the `NoAccessException` implement it, so we can simply use the http code check that already exists.

**Comment by peterhashair** [comment]
@sgiehl it seems like the `HttpCodeException` used a couple of places, convert to an interface maybe broken some other code. I saw we have used `HttpCodeException`in a way below, could we  `NoAccessException` extend  `HttpCodeException` but has 401 in the __construct, like the current PR, will that cause any regression?

https://github.com/matomo-org/matomo/blob/6b1fca27df7d96c316e60a2c4b45456cb0544809/core/Http/BadRequestException.php#L12-L18

**Comment by sgiehl** [comment]
I described my approach that way on purpose. You can't simply change the `NoAccessException` to extend from `HttpCodeException` instead of `InvalidRequestParameterException`. The problem is, that we are catching `InvalidRequestParameterException` in some places. Currently that indirectly also catches any `NoAccessException`, as it inherits from it. This won't work now anymore.

**Comment by peterhashair** [comment]
@sgiehl right, that makes sense. If we convert `HttpCodeException` into an interface then, what happened to the place that actually creates the class any suggestions? eg: 
```php    
$ex = new HttpCodeException(Piwik::translate('Login_LoginNotAllowedBecauseUserLoginBlocked'), 403); 
```

**Comment by peterhashair** [comment]
ping @sgiehl

**Comment by sgiehl** [comment]
Guess we need to convert this into another exception that implements the new interface. Guess the `NoAccessException` might work there.

File: core/Http/BadRequestException.php [hunk 1]
```diff
@@ -8,11 +8,12 @@
 
 namespace Piwik\Http;
 
+use Piwik\NoAccessException;
 
-class BadRequestException extends HttpCodeException
+class BadRequestException extends NoAccessException
```
Comment (sgiehl) [inline core/Http/BadRequestException.php]: That is logically wrong. A Bad request is not an access problem. This one should be a `implements HttpCodeException`

File: core/NoAccessException.php [hunk 2]
```diff
@@ -9,13 +9,34 @@
...
+use Piwik\Exception\Exception;
+use Piwik\Http\HttpCodeException;
 
 /**
  * Exception thrown when a user doesn't have sufficient access to a resource.
  *
  * @api
  */
-class NoAccessException extends InvalidRequestParameterException
+class NoAccessException extends Exception implements HttpCodeException
```
Comment (sgiehl) [inline core/NoAccessException.php]: this one should still extend `InvalidRequestParameterException`

**Review by sgiehl — CHANGES_REQUESTED** [review]

File: core/NoAccessException.php (hunk 2 above)
Comment (peterhashair) [reply core/NoAccessException.php]: @sgiehl ah, I thought the whole point is made `NoAccessException ` a type of `HttpCodeException` so it run into the `getResponseException`  return 403. Should I make InvalidRequestParameterException implements HttpCodeException?

**Comment by peterhashair** [comment]
@sgiehl just checking instead of interface etc. how about just checking if ` if ($e instanceof NoAccessException) {` then return 403 in API request.

**Comment by sgiehl** [comment]
That works for sure as well. But we are actually not using exceptions in a useful way. Moving the HttpCodeException to an interface, would have been a first step to improve that mess of exception handling. We should try to improve things when we are already working on it. And changing that exception stuff is a matter of half an hour or so. I'm actually not sure where the problem is, wasn't that almost finished?

File: CHANGELOG.md [hunk 3]
```diff
@@ -14,6 +14,7 @@ The Product Changelog at **[matomo.org/changelog](https://matomo.org/changelog)*
 * The javascript event `piwikPageChange`, which is triggered when a reporting page is loaded, has been renamed to `matomoPageChange`. Ensure to update your implementation if you rely on it.
 * Plugin names are now limited to 60 characters. If you used to have a plugin with a longer name, you might need to rename it.
 * The `instance_id` configuration does no longer support characters other than `a-z`, `0-9` and the special characters `.-_`. If the configured value contains other characters, they will be simply removed.
+* When invalid token provided in the API request, the response code changed from 200 to 401.
```
Comment (sgiehl) [inline CHANGELOG.md]: So this says it changed to `401`, but the code below looks like it returns a `403` 🤔

**Review by sgiehl — CHANGES_REQUESTED** [review]

**Comment by bx80** [comment]
@sgiehl Was the update to the changelog the only outstanding issue you had with this PR?

**Comment by sgiehl** [comment]
I think so. But we might still need to ensure that this change only affects those parts is was meant for.

**Comment by bx80** [comment]
@sgiehl I've fixed the integration test which now correctly checks for a 401 if an invalid token is used. All other access tests are passing. Can you give this a (hopefully) final review when you get a chance?

File: core/Exception/InvalidRequestParameterException.php [hunk 4]
```diff
@@ -8,9 +8,10 @@
  */
 namespace Piwik\Exception;
 
-class InvalidRequestParameterException extends Exception
+use Piwik\Http\HttpCodeException;
+
+class InvalidRequestParameterException extends Exception implements HttpCodeException
```
Comment (sgiehl) [inline core/Exception/InvalidRequestParameterException.php]: I don't think this on should implement `HttpCodeException`, as it actually doesn't define a correct response code.
Otherwise this will cause all exceptions that inherit from this one to also be handled as `HttpCodeException`

File: core/NoAccessException.php [hunk 5]
```diff
@@ -18,4 +19,8 @@
  */
 class NoAccessException extends InvalidRequestParameterException
```
Comment (sgiehl) [inline core/NoAccessException.php]: This one should directly implement `HttpCodeException`

File: core/NoAccessException.php [hunk 6]
```diff
@@ -18,4 +19,8 @@
...
 {
-}
\ No newline at end of file
+    public function __construct($message)
+    {
+        parent::__construct($message, $code = 401);
+    }
```
Comment (sgiehl) [inline core/NoAccessException.php]: As this Exception is now used like this 
```
$ex = new NoAccessException(Piwik::translate('Login_LoginNotAllowedBecauseUserLoginBlocked'), 403);
```

We need to handle the code correctly:
```suggestion
    public function __construct($message, $code = 401)
    {
        parent::__construct($message, $code);
    }
```

File: core/Http/BadRequestException.php [hunk 7]
```diff
@@ -9,10 +9,10 @@
 namespace Piwik\Http;
 
 
-class BadRequestException extends HttpCodeException
+class BadRequestException extends \Exception implements HttpCodeException
 {
     public function __construct($message)
     {
         parent::__construct($message, $code = 400);
     }
```
Comment (sgiehl) [inline core/Http/BadRequestException.php]: We could also improve that one, so it's possible to overwrite the code if needed.
```suggestion
    public function __construct($message, $code = 400)
    {
        parent::__construct($message, $code);
    }
```

**Review by sgiehl — CHANGES_REQUESTED** [review]
There are some more changes needed

**Review by sgiehl — APPROVED** [review]
