### PR TITLE
Ensure getmypid is only used when available otherwise disable SharedSiteIds

### LINKED ISSUE #20537: Archiving error when getmypid function is disabled
Some hosting servers have the getmypid function disabled for security reasons. We have some checks to see if this function is enabled or not but they aren't being used before it is called in this scenario resulting in an error:

```
[29-Mar-2023 10:30:58 UTC] PHP Fatal error: Uncaught Error: Call to undefined function Piwik\CliMulti\getmypid() in /home/wp/disk/wordpress/wp-content/plugins/matomo/app/core/CliMulti/Process.php:125
--
[29-Mar-2023 10:30:53 UTC] Matomo: Scheduled tasks archive data
```

Reported by a couple of customers here:
https://github.com/matomo-org/matomo-for-wordpress/issues/660

### PR DESCRIPTION
**Pull request by bx80**
### Description:

Fixes #20537 

Based on @sgiehl's changes in https://github.com/matomo-org/matomo/pull/20540 and also incorporating the feedback from @tsteur: 

> Another way would be something like below code to check if `SharedSiteIds` is supported and only then use it. Otherwise use the `FixedSiteIds`. This can make it worse though in cases where there are many sites and `getmypid()` is disabled. In this case Matomo would always start archiving with idsite 1 etc and never make it to the higher idsites. Meaning the created PR could work better overall even though it means the logic may not always run concurrently.

Disabling `SharedSiteIds` seems like the safer option if using random process ids. Since the current state is that archiving doesn't run at all and fails with an error on hosts without `getmypid()` I'd suggest a fix that may degrade performance on some edge cases (only if `getmyid()` is disabled) is preferable to no fix at all. We could perhaps document somewhere that hosting providers who disable `getmypid()` are not recommended for installations with many sites or high traffic.

I've tested this by disabling `getmypid()` locally, recreating the original issue and then successfully running archiving with the fix applied.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
I'm tempted to say we should also apply this change here:
https://github.com/matomo-org/matomo/pull/20540/files#diff-a1b3870254fbf6ecce77c9f76b05978f3c13b0ac87314247dc0e7782972932a8R362

I know it's not needed, as the climulti might not be used in this case anymore, but in terms of abstraction I think it could at some point be useful if we use `Common::getProcessId()` everywhere instead of `getmypid()` directly (Unless the direct usage is needed for feature detection for sure).

**Comment by bx80** [comment]
@sgiehl I've added the extra `Common::getProcessId()` call as suggested, this should be ready for review now,

File: core/CronArchive.php [hunk 1]
```diff
@@ -1457,7 +1457,7 @@ private function makeWebsiteIdArchiveList(array $websitesIds)
             return new FixedSiteIds($websitesIds);
         }
 
-        if (!empty($this->shouldArchiveSpecifiedSites)) {
+        if (!empty($this->shouldArchiveSpecifiedSites) && !SharedSiteIds::isSupported()) {
```
Comment (sgiehl) [inline core/CronArchive.php]: From a logical point of view, shouldn't that be an OR condition?

Comment (bx80) [reply core/CronArchive.php]: Yes it should, fixed! :+1:

**Review by sgiehl — APPROVED** [review]
Did some local testing with and without getmypid function disabled. Archiving now works in both cases, so guess this should fix the related issues.
