### PR TITLE
Fix row evolution for reports where visits metric is not available

### LINKED ISSUE #22236: [Bug] Charts for Conversions by Entry Pages & Page Titles Broken
### What happened?

The 'Visits' chart plot does not have a title and once another chart plot type is selected, the visits type cannot be reselcted.
image

Entry Page conversion charts are partly broken for both:
- Conversions -> Overview (or specific Goal) -> Goals by Pages
- Ecommerce -> Sales -> Sales by Pages
Ecommerce report - entry page ev chart

```
WARNING: /plugins/API/RowEvolution.php(67): Warning - Undefined array key &quot;nb_visits&quot; - Matomo 5.1.0-b3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CoreHome, Action: getRowEvolutionPopover, Method: API.getRowEvolution, In CLI mode: false)
```

### What should happen?

The chart plot category 'Visits' should function properly. 

### How can this be reproduced?

View a evolution chart for Ecommerce -> Sales -> Sales by Pages -> Entry Pages -> Click the chart button for any page URL

### Matomo version

5.1.0-b3 (Cloud)

### PHP version

8.1

### Server operating system

Linux

### What browsers are you seeing the problem on?

Chrome

### Computer operating system

Ubuntu

### Relevant log output

```
WARNING: /plugins/API/RowEvolution.php(67): Warning - Undefined array key &quot;nb_visits&quot; - Matomo 5.1.0-b3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CoreHome, Action: getRowEvolutionPopover, Method: API.getRowEvolution, In CLI mode: false)
```
Browser console error when clicking the 'Visits' chart plot type:
```
index.php?module=Proxy&action=getCoreJs&cb=b8dc07360884fb8559939d48d1bf5db7:774 Uncaught TypeError: Cannot read properties of undefined (reading 'tickOptions')
    at exports.JqplotEvolutionGraphDataTable.setYTicksForAxis (index.php?module=Proxy&action=getCoreJs&cb=b8dc07360884fb8559939d48d1bf5db7:774:9)
    at exports.JqplotEvolutionGraphDataTable.setYTicks (index.php?module=Proxy&action=getCoreJs&cb=b8dc07360884fb8559939d48d1bf5db7:768:655)
    at RowEvolutionSeriesToggle.replot (index.php?module=Proxy&action=getCoreJs&cb=b8dc07360884fb8559939d48d1bf5db7:787:99)
    at RowEvolutionSeriesToggle.showSeries (index.php?module=Proxy&action=getCoreJs&cb=b8dc07360884fb8559939d48d1bf5db7:782:588)
    at HTMLTableRowElement.<anonymous> (index.php?module=Proxy&action=getCoreJs&cb=b8dc07360884fb8559939d48d1bf5db7:790:243)
    at HTMLTableRowElement.dispatch (index.php?module=Proxy&action=getCoreJs&cb=b8dc07360884fb8559939d48d1bf5db7:4:43184)
    at y.handle (index.php?module=Proxy&action=getCoreJs&cb=b8dc07360884fb8559939d48d1bf5db7:4:41168)
```
### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

Row evolution for reports, that don't contain the nb_visits metric currently does not work correctly:

Ecommerce report - entry page ev chart

fixes #22236

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/API/RowEvolution.php [hunk 1]
```diff
@@ -63,9 +63,14 @@ public function getRowEvolution($idSite, $period, $date, $apiModule, $apiAction,
...
-            $metadata['metrics'] = [
-                'nb_visits' => $metadata['metrics']['nb_visits'],
-            ];
+            if (array_key_exists('nb_visits', $metadata['metrics'])) {
+                $metadata['metrics'] = [
+                    'nb_visits' => $metadata['metrics']['nb_visits'],
+                ];
+            } else {
+                // if no visits are available, simply use the first available metric
+                $metadata['metrics'] = array_slice($metadata['metrics'], 0, 1);
```
Comment (mneudert) [inline plugins/API/RowEvolution.php:72]: Should we add a simple screenshot (e.g. in `RowEvolution_spec.js`) that ensures this does not regress?

Comment (sgiehl) [reply plugins/API/RowEvolution.php:72]: I've added a test for that.

**Review by mneudert — APPROVED** [review]
