### PR TITLE
Filter special whitespace when rendering ImageGraphs without unifont

### LINKED ISSUE #21867: [Bug] Bad date formatting in email reports
### What happened?

When selecting the date range 'week' in the calendar and sending an HTML or PDF email report, symbols appear below the evolution graph in the date field that should not be there.
image

### What should happen?

We should see the normal date range, without any strange symbols, below evolution graph in email report.

### How can this be reproduced?

Go to Email Reports, Select 'week' from calendar and send report.
image

### Matomo version

5.0.1

### PHP version

_No response_

### Server operating system

_No response_

### What browsers are you seeing the problem on?

_No response_

### Computer operating system

_No response_

### Relevant log output

_No response_

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by mneudert**
### Description:

When generating an email report after selecting a week period, the dates can be displayed with broken unicode symbols when the default font is used:

This appears to have been introduced by #19932 (Intl update for CLDR 42):

- https://unicode-org.atlassian.net/browse/CLDR-14032
- https://icu.unicode.org/download/72 (Common changes -> CLDR 42 -> "In many formatting patterns...")

I have only found `&thinsp;` and `&nnbsp;` in our locale files, simply converting them to a regular space or `&nbsp;` should solve the rendering errors.

Refs #20953 (the initial fix for `&nnbsp;` characters)
Fixes #21867

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/ImageGraph/StaticGraph.php [hunk 1]
```diff
@@ -248,14 +265,17 @@ protected function initpData()
             }
         }
 
-        // Use a different formating method if not using unifont
+        // Fix whitespace if not using unifont
+        $abscissaSeries = $this->abscissaSeries;
         $formatMethodName = 'formatYAxis';
-        if (strpos($this->font, 'unifont') === false) {
+
+        if (!str_ends_with($this->font, API::UNICODE_FONT)) {
```
Comment (michalkleiner) [inline plugins/ImageGraph/StaticGraph.php]: We can't use `str_ends_with` introduces in PHP 8 as we need to stay PHP 7.2 compatible.

**Review by michalkleiner — CHANGES_REQUESTED** [review]

File: plugins/ImageGraph/StaticGraph.php (hunk 1 above)
Comment (sgiehl) [reply plugins/ImageGraph/StaticGraph.php]: I guess we actually should be able to, as we have the symfony php8 polyfill included.

Comment (mneudert) [reply plugins/ImageGraph/StaticGraph.php]: I can change it back to `false === strpos`, but as said the polyfill is already imported by symfony and twig.

I have no strong opinion on using the polyfill functions, but I would not expect them to silently go away and break things.

Comment (michalkleiner) [reply plugins/ImageGraph/StaticGraph.php]: > I guess we actually should be able to, as we have the symfony php8 polyfill included.

I probably missed that. It might be good if we had some docs on which PHP8 functions we could use so that we actually write better code.

Ref #21736.

Comment (michalkleiner) [reply plugins/ImageGraph/StaticGraph.php]: Based on my quick search we don't have a single use of `str_ends_with` or `str_starts_with` in the codebase (outside of Symfony and Twig dependencies themselves), so I would probably say we should not introduce it randomly here. Thoughts?

Comment (mneudert) [reply plugins/ImageGraph/StaticGraph.php]: I removed the usage. We could add the already existing polyfills explicitly to our `composer.json` to announce their usability. Perhaps both the functions you mentioned and also `str_contains` then get some usage, eventually replace the several hundred `strpos` occurences in the codebase :see_no_evil:

Comment (sgiehl) [reply plugins/ImageGraph/StaticGraph.php]: sounds like a good approach @mneudert. Not sure if it's worth to create a separate issue for that or wait until someone has some time in between to handle that

Comment (michalkleiner) [reply plugins/ImageGraph/StaticGraph.php]: Sounds good as a separate technical debt issue, thanks Marc!

**Review by sgiehl — APPROVED** [review]
@mneudert For this to be part of 5.0.3, you need to switch the base branch. Otherwise this looks good to merge. Even though we should work on a more solid solution at some point, but there was another issue for that afaik.
