### PR TITLE
Prevent possible error when action is provided as array

### LINKED ISSUE #18701: Fatal error "ucfirst(): Argument #1 ($string) must be of type string" in ReportsProvider
Error: {"message":"ucfirst(): Argument #1 ($string) must be of type string, array given","file":"core\/Plugin\/ReportsProvider.php","line":37,"request_id":"9ae88","backtrace":" on core\/Plugin\/ReportsProvider.php(37)\n#0 core\/Plugin\/ReportsProvider.php(37): ucfirst(Array)\n#1 core\/Http\/ControllerResolver.php(101): Piwik\\Plugin\\ReportsProvider::factory('CoreHome', Array)\n#2 core\/Http\/ControllerResolver.php(59): Piwik\\Http\\ControllerResolver->createReportController('CoreHome', Array, Array)\n#3 core\/FrontController.php(604): Piwik\\Http\\ControllerResolver->getController('CoreHome', Array, Array)\n#4 core\/FrontController.php(168): Piwik\\FrontController->doDispatch('CoreHome', Array, Array)\n#5 core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#6 index.php(25): require_once('c...')\n#7 {main}",

URL: https://example.yourdomain/index.php?action[%24foobar]=1

Seems in https://github.com/matomo-org/matomo/blob/4.7.0-rc2/core/FrontController.php#L462 we're not defining `string`. Not sure if we can change `false` to an empty string for `$action`. This might break some things. Maybe if `$action` is not `false` then we would throw an exception if `$action` is not a string? 

Happens with PHP 8

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #18701 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/FrontController.php [hunk 1]
```diff
@@ -460,6 +460,10 @@ protected function prepareDispatch($module, $action, $parameters)
 
         if (is_null($action)) {
             $action = Common::getRequestVar('action', false);
+            if ($action !== false) {
+                // If a value was provided, check it has the correct type.
+                $action = Common::getRequestVar('action', null, 'string');
```
Comment (sgiehl) [inline core/FrontController.php:465]: This will throw an exception with the message `The parameter 'action' doesn't have a correct type, and a default value wasn't provided.`

Directly using `Piwik::getAction()` would in theory also work, but it would change the behavior slightly. Instead of throwing an error when an incorrect type was provided, it would use an empty string as default instead.

**Review by tsteur — COMMENTED** [review]
LGTM. Some test is failing though: https://app.travis-ci.com/github/matomo-org/matomo/jobs/557678896
