### PR TITLE
Handle case only file name updates on case insensitive file systems

### LINKED ISSUE #18724: 4.7.0 After triggering the automatic update a fatal error occurres
After triggering the automatic update a fatal error occurres

## Expected Behavior
Upgrade to Matomo 4.7.0 with the well-known dialogue (Datebase update needed or similar)

## Current Behavior
After the upgrade this dialog is displayed:

```
A fatal error occurred

Please contact the system administrator, or login to Matomo to learn more.

If you are Super User, but cannot login because of this error, you can still troubleshoot further. Follow these steps:
1) open the config/config.ini.php file and look for the salt value under [General].
2) edit this current URL you are viewing and add the following text (replacing salt_value_from_config by the salt value from the config file):

index.php?i_am_super_user=SALT&....

```
The upgrade is performed with a superuser!
According to the steps of the dialogue this happens:

```
A fatal error occurred

The following error just broke Matomo (v4.7.0):

File `../../CoreHome/vue/src/MenuDropdown/MenuDropdown.less` not found. in anonymous-file-0.less
in /srv/www/DocRoot/piwik/core/AssetManager/UIAssetMerger/StylesheetUIAssetMerger.php line 53            

Troubleshooting
Follow these steps to solve the issue or report it to the team:

    If you have just updated Matomo to the latest version, please try to restart your web server. This will clear the PHP opcache which may solve the problem.
    If this is the first time you see this error, please try refresh the page.
    If this error continues to happen, we appreciate if you send the error report to the Matomo team.

Further troubleshooting

If this error continues to happen, you may be able to fix this issue by disabling one or more of the Third-Party plugins. If you don't know which plugin is causing this error, we recommend to first disable any plugin not created by "Matomo" and not created by "InnoCraft". You can enable plugin again afterwards in the Plugins or Themes page under settings at any time.

CustomVariables 	4.0.1 	deactivate
InvalidateReports 	4.0.1 	deactivate
LoginTokenAuth 	4.0.0 	deactivate
MarketingCampaignsReporting 	4.1.1 	deactivate
Provider 	4.0.3 	deactivate
```

## Possible Solution
No idea

## Steps to Reproduce (for Bugs)
1. Matomo 4.6.2
2. Click automatich update to 4.7

## Your Environment
* Matomo Version: 4.6.2
* Matomo Update History: 4.6.2,4.6.1,4.5.0,4.4.1,4.3.1,4.3.0-b3
* PHP Version: 8.0.15
* Memory limit:  2048M
* Server Operating System: 5.10.76-linuxkit
* PHP Disabled functions:
 pcntl_alarm, pcntl_fork, pcntl_waitpid, pcntl_wait, pcntl_wifexited, pcntl_wifstopped, pcntl_wifsignaled, pcntl_wifcontinued, pcntl_wexitstatus, pcntl_wtermsig, pcntl_wstopsig, pcntl_signal, pcntl_signal_dispatch, pcntl_get_last_error, pcntl_strerror, pcntl_sigprocmask, pcntl_sigwaitinfo, pcntl_sigtimedwait, pcntl_exec, pcntl_getpriority, pcntl_setpriority, 
* PHP INI max_execution_time: 30
* PHP INI post_max_size: 32M
* PHP INI max_input_vars: 10000
* DB Prefix: piwik_
* DB Charset: utf8mb4
* MySQL Version: 8.0.28
* Plugins Activated:
 API, Actions, Annotations, BulkTracking, Contents, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, CoreVue, CustomDimensions, CustomJsTracker, CustomVariables 4.0.1, DBStats, Dashboard, DevicePlugins, DevicesDetection, Diagnostics, Ecommerce, Events, GeoIp2, Goals, Heartbeat, ImageGraph, Insights, Installation, Intl, InvalidateReports 4.0.1, LanguagesManager, Live, Login, LoginTokenAuth 4.0.0, MarketingCampaignsReporting 4.1.1, Marketplace, Monolog, Morpheus, MultiSites, Overlay, PagePerformance, PrivacyManager, Provider 4.0.3, Proxy, Referrers, Resolution, SEO, ScheduledReports, SegmentEditor, SitesManager, Transitions, UserCountry, UserCountryMap, UserId, UserLanguage, UsersManager, VisitFrequency, VisitTime, VisitorInterest, VisitsSummary, WebsiteMeasurable
*Plugins Deactivated:
 Feedback, IntranetMeasurable, MobileAppMeasurable, MobileMessaging, ProfessionalServices, RssWidget, TagManager, Tour, TwoFactorAuth, Widgetize
* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0

Any advices?

### PR DESCRIPTION
**Pull request by bx80**
### Description:

Fixes #18724

## Background

During an update, any files that already exist in the installation destination but no longer exist in the update package will be identified and removed.

The process is:
1) Copy the new files.
2) Check for obsolete files that exist in the installation target but are no longer part of the package.
3) Delete the obsolete files.

This causes a problem when a file is renamed with only a change in case, eg. `Myfile` to `MyFile`. 

For case sensitive systems this works:
1) The new `MyFile` is copied without interfering with the old `Myfile`
2) `Myfile` is identified as not being in the source package and noted for deletion.
3) The obsolete `Myfile` is correctly unlinked without interfering with the new `MyFile`.

For case insensitive system this fails:
1) The new `MyFile` is copied and overwrites the old `Myfile` as the name is treated as the same.
2) `Myfile` is identified as not being in the source package and noted for deletion.
3) The new `MyFile` is incorrectly deleted as the name is treated as the same, this results in a missing file.

## Fix 
To fix this a new method has been added which checks if the file system is case insensitive by writing a file with one case and checking if it exists using another case. If the file is reported to exist under a differently cased filename then the file system is assumed to be case insensitive.

When checking for files which exist in the installation but not in the source package and a case insensitive file system is detected then the file name comparison will be performed in a case insensitive manner, this results in the following behaviour:

1) The new `MyFile` is copied and overwrites the old `Myfile` as the name is treated as the same.
2) `MyFile` in the source package is compared case insensitively with the existing `Myfile` and considered to exist in the source package, so it is not noted for deletion.
3)  No attempt is made to delete `Myfile` and as it has been overwritten with the new `MyFile`, resulting in the new file in the correct place.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: tests/PHPUnit/Unit/FilesystemTest.php [hunk 1]
```diff
@@ -265,6 +311,32 @@ private function createEmptyTarget()
...
+
+        return $target;
+    }
+
+    private function createCaseInsensitiveSourceFiles()
+    {
+        $source = $this->createEmptySource();
+        Filesystem::mkdir($source . '/CoreHome');
+        Filesystem::mkdir($source . '/CoreHome/vue');
+        Filesystem::mkdir($source . '/CoreHome/vue/src');
```
Comment (justinvelluppillai) [inline tests/PHPUnit/Unit/FilesystemTest.php]:
```suggestion
```

`Filesystem::mkdir()` is recursive, so can remove these safely

File: tests/PHPUnit/Unit/FilesystemTest.php [hunk 2]
```diff
@@ -265,6 +311,32 @@ private function createEmptyTarget()
         return $this->testPath . '/target';
     }
 
+    private function createCaseInsensitiveTargetFiles()
+    {
+        $target = $this->createEmptyTarget();
+        Filesystem::mkdir($target . '/CoreHome');
+        Filesystem::mkdir($target . '/CoreHome/vue');
+        Filesystem::mkdir($target . '/CoreHome/vue/src');
```
Comment (justinvelluppillai) [inline tests/PHPUnit/Unit/FilesystemTest.php]:
```suggestion
```

**Review by justinvelluppillai — APPROVED** [review]
Looks good to me and tests work (using the case insensitive filesystem path).

@tsteur do you maybe want to take a look at this solution?
