### PR TITLE
Fix possible error on PHP 8.1

### LINKED ISSUE #18910: Deprecated - trim() in PHP 8.1
```
WARNING: /core/CliMulti/Process.php(291): Deprecated - trim(): Passing null to parameter #1 ($string) of type string is deprecated - Matomo 4.8.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)
```

## Steps to Reproduce (for Bugs)
1. Install Matomo 4.8.0
2. Have PHP 8.1

## Context
Browse URL:
```
/index.php?date=yesterday&module=CorePluginsAdmin&format=html&action=plugins&idSite=8&period=day&segment=&widget=&showtitle=1&random=9226
```

## Your Environment
* Matomo Version: 4.8.0
* PHP Version: 8.1
* Server Operating System: Debian 10

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #18910

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by justinvelluppillai — APPROVED** [review]

**Comment by justinvelluppillai** [comment]
A few test failures here but seem unrelated.

File: core/CliMulti/Process.php [hunk 1]
```diff
@@ -288,6 +288,11 @@ private static function returnsSuccessCode($command)
     {
         $exec = $command . ' > /dev/null 2>&1; echo $?';
         $returnCode = @shell_exec($exec);
+
+        if (false === $returnCode || null === $returnCode) {
+            return false;
```
Comment (sgiehl) [inline core/CliMulti/Process.php:293]: It just came to my mind that this will actually change the current behavior. But maybe this might actually fix some possible issues.
`shell_exec` returns `false` or `null` if something didn't work with the command, otherwise the return code is returned.
If an error occurred and e.g. `null` or `false` was returned, the `trim` triggered a warning on PHP 7 and maybe even PHP 8. The error should only occur on PHP 8.1.
After the trim `$returnCode` is an empty string in case of an error and `0 == (int) $returnCode` actually evaluates to `true` and we assume the command succeeded, which it actually didn't.

Comment (tsteur) [reply core/CliMulti/Process.php:293]: @sgiehl not sure I understand it changes behaviour. Looks like this maybe worked before? https://3v4l.org/7C8Qf

Looks generally good though 👍

Comment (justinvelluppillai) [reply core/CliMulti/Process.php:293]: previously if `$returnCode` was `false` or `null`, this function would return `true`, now it returns `false`.

Comment (justinvelluppillai) [reply core/CliMulti/Process.php:293]: I think this is ok to merge. This change in behaviour would almost certainly be better if it affected anyone at all
