### PR TITLE
Fix for datatable row sum error

### LINKED ISSUE #18468: WARNING: /core/DataTable/Row.php(805) after update to 4.6.1
## Expected Behavior
No warning

## Current Behavior
After the migration to version 4.6.1, some warnings are displayed in each page of the Matomo UI:
>WARNING: /core/DataTable/Row.php(805): Trying to add two strings in DataTable\Row::sumRowArray: 2021-12-07 01:50:26 + 2021-12-07 02:05:12 for column _metadata in row # [‘label’ => ‘Martijn’, ‘nb_visits’ => 73, ‘nb_actions’ => 82, ‘Actions_nb_pageviews’ => 79, ‘Goal_revenue’ => 0, ‘Goal_nb_conversions’ => 0, ‘_metadata’ => array ( ‘ts_archived’ => ‘2021-12-07 01:50:26’, ), ‘visits_evolution’ => 2.076, ‘visits_evolution_trend’ => 1, ‘actions_evolution’ => 1.504, ‘actions_evolution_trend’ => 1, ‘pageviews_evolution’ (Module: MultiSites, Action: getAllWithGroups, In CLI mode: false)

## Steps to Reproduce (for Bugs)
Migration from version 4.5.0 to version 4.6.1...
Then open Matomo Analytics...

## Context
From Forum:
https://forum.matomo.org/t/error-after-update-to-4-6-1/43990

## Your Environment

* Matomo new Version: 4.6.1
* Matomo previous Version: 4.5.0
* PHP Version: _To be completed_
* Server Operating System: _To be completed_
* Additionally installed plugins: _To be completed_

### PR DESCRIPTION
**Pull request by bx80**
### Description:

Potentially fixes #18468 

I've been unable to recreate the exact conditions that cause this error:

>WARNING: /core/DataTable/Row.php(805): Trying to add two strings in DataTable\Row::sumRowArray: 2021-12-07 01:50:26 + 2021-12-07 02:05:12 for column _metadata in row # [‘label’ => ‘Martijn’, ‘nb_visits’ => 73, ‘nb_actions’ => 82, ‘Actions_nb_pageviews’ => 79, ‘Goal_revenue’ => 0, ‘Goal_nb_conversions’ => 0, ‘_metadata’ => array ( ‘ts_archived’ => ‘2021-12-07 01:50:26’, ), ‘visits_evolution’ => 2.076, ‘visits_evolution_trend’ => 1, ‘actions_evolution’ => 1.504, ‘actions_evolution_trend’ => 1, ‘pageviews_evolution’ (Module: MultiSites, Action: getAllWithGroups, In CLI mode: false)

But it seems likely that some archiving process is calling `DataTable\Row::sumRowMetadata()` to sum all row metadata values. Recent change #6784 adds the `ts_archived` date value to the row metadata and attempting to sum this is probably causing the error.

This PR adds a check to the `DataTable\Row::sumRowMetadata()` method to prevent any attempt to sum metadata values for the `ts_archived` column which is always going to fail.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/DataTable/Row.php [hunk 1]
```diff
@@ -579,6 +579,10 @@ public function sumRowMetadata($rowToSum, $aggregationOperations = array())
                         continue;
                     }
 
+                    if ($column === 'ts_archived') {
```
Comment (sgiehl) [inline core/DataTable/Row.php]: I don't think this will fix the referenced issue. Logically `$column` can only be `ts_archived` at that point if `$aggregationOperations` would contain `ts_archived`. As this metadata was newly added, and a aggregation method is not set anywhere for it, I don't think this is the reason. But the `_metadata` column seems to be summed up with the normal columns it seems. Removing that might breaks something so instead I guess adding the column here might fix the issue:
https://github.com/matomo-org/matomo/blob/c75aa0a67379465bede34013661df993630e4eef/core/DataTable/Row.php#L37-L40

Comment (bx80) [reply core/DataTable/Row.php]: Thanks @sgiehl, I figured there was some code attempting to sum up all row metadata values rather than ts_archived specifically, but wasn't sure where.

**Review by sgiehl — APPROVED** [review]
Guess that should be fine.
