### PR TITLE
Fix type error when idSites isn't an array

### LINKED ISSUE #22673: [Bug] \Piwik\Archive\ArchiveInvalidator::removeInvalidationsSafely says idSites can be int, but that's not completely accurate
### What happened?

I noticed that custom reports were archiving even after being deleted. Debugging, I ended up finding that if a single site ID is passed as the idSites argument, the `removeInvalidationsFromDistributedList` method doesn't handle it properly because of a TypeError on [line 690](https://github.com/matomo-org/matomo/blob/5.x-dev/core/Archive/ArchiveInvalidator.php#L690).

### What should happen?

Since the comment block says that int is an allowed type for idSites, the `removeInvalidationsFromDistributedList` should handle that as well, or the `removeInvalidationsSafely` method should wrap it with an array before passing isSites on to `removeInvalidationsFromDistributedList`.

### How can this be reproduced?

Using CustomReports 5.0.17 or earlier do the following:
- Create a new report
- Note that the option record named ReArchiveList was updated to add the newly created report
- Delete the newly created report
- Note that the option record named ReArchiveList was not updated
- Note that archiving is done for the deleted report the next time archiving runs

### Matomo version

5.x-dev

### PHP version

8.1.30

### Server operating system

Ubuntu 22.04

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Computer operating system

Ubuntu 22.04

### Relevant log output

_No response_

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by snake14**
### Description:

I noticed that custom reports were archiving even after being deleted. Debugging, I ended up finding that if a single site ID is passed as the idSites argument, the removeInvalidationsFromDistributedList method doesn't handle it properly because of a TypeError on [line 690](https://github.com/matomo-org/matomo/blob/5.x-dev/core/Archive/ArchiveInvalidator.php#L690).

This PR wraps idSites with an array if it's a string or int.

Fixes: #22673 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/Archive/ArchiveInvalidator.php [hunk 1]
```diff
@@ -654,6 +654,10 @@ public function removeInvalidationsFromDistributedList($idSites, $pluginName = n
         $list = new ReArchiveList();
         $entries = $list->getAll();
 
+        // Make sure that idSites is an array or all before using it
+        $idSites = $idSites === 0 || $idSites === '0' || $idSites == 'all'
```
Comment (michalkleiner) [inline core/Archive/ArchiveInvalidator.php]: After a quick check for how `'all'` sites are handled elsewhere this might be shorter
```suggestion
        $idSites = empty($idSites) || 'all' === $idSites
```

**Comment by michalkleiner** [comment]
Thanks for the PR, @snake14, that's a good find! Would you be able to update `ArchiveInvalidatorTest` as well to cover this case, make sure it fails before the fix and passes after the fix?

**Comment by snake14** [comment]
> Thanks for the PR, @snake14, that's a good find! Would you be able to update `ArchiveInvalidatorTest` as well to cover this case, make sure it fails before the fix and passes after the fix?

@michalkleiner Sure thing. I just ran out of time last week and forgot to create the PR as a draft.

**Comment by michalkleiner** [comment]
All good, please add the `Needs review` label back when ready. Cheers!

File: core/Archive/ArchiveInvalidator.php [hunk 2]
```diff
@@ -654,6 +654,10 @@ public function removeInvalidationsFromDistributedList($idSites, $pluginName = n
         $list = new ReArchiveList();
         $entries = $list->getAll();
 
+        // Make sure that idSites is an array or all before using it
+        $idSites = empty($idSites) || 'all' === $idSites
```
Comment (sgiehl) [inline core/Archive/ArchiveInvalidator.php]: Shouldn't this be done in the method that is calling this one? This methods seems only be used by `removeInvalidationsSafely`, which also calls `removeInvalidations`. The latter one might also have problems if an unexpected value is passed in...

Comment (snake14) [reply core/Archive/ArchiveInvalidator.php]: @sgiehl I thought about that, but `removeInvalidations` calls Model, which uses `getRemoveInvalidationsIdSitesClause` to handle whether idSites is an int or array.

Comment (sgiehl) [reply core/Archive/ArchiveInvalidator.php]: Ok. That kinda makes sense. 
Anyway. There's something else: assuming that an `empty` parameter is the same as `all` to me looks like a "breaking" change. At the moment, passing in an empty value would result in nothing to be done. Now it would cause every site to be handled.
Even if such a change could logically make sense, we should avoid doing it unless we can ensure that it can't break anything. I'm not able to say if there might be any edge case where that method could be incorrectly called and would with this change result in unexpected behavior.

Comment (snake14) [reply core/Archive/ArchiveInvalidator.php]: That's a good point. I just updated the fix to only automatically fix when an int is passed.

File: core/Archive/ArchiveInvalidator.php [hunk 3]
```diff
@@ -654,6 +654,9 @@ public function removeInvalidationsFromDistributedList($idSites, $pluginName = n
         $list = new ReArchiveList();
         $entries = $list->getAll();
 
+        // Make sure that idSites is an array to prevent typeError
+        $idSites = is_array($idSites) || $idSites === 'all' ? $idSites : (is_numeric($idSites) ? [$idSites] : []);
+
         if ($idSites === 'all') {
             $idSites = $this->getAllSitesId();
         }
```
Comment (sgiehl) [inline core/Archive/ArchiveInvalidator.php]: Switching the checks might make everything a bit simpler.

```suggestion
        if ($idSites === 'all') {
            $idSites = $this->getAllSitesId();
        }

        // Make sure that idSites is an array to prevent typeError
        $idSites = !is_array($idSites) ?  [$idSites] : $idSites;
```

Comment (snake14) [reply core/Archive/ArchiveInvalidator.php]: @sgiehl Thank you. Good call using the existing 'all' check. I found a test case which resulted in unexpected results with the ternary  completely simplified, so I had to have one additional check.

**Review by sgiehl — APPROVED** [review]
