### PR TITLE
Only try to track screen resolution if available

### LINKED ISSUE #23960: [Bug] Uncaught TypeError: Cannot read properties of null (reading 'width')
### What happened?

A script error is stopping the execution of the data collection.
It happens, when the Screen.width is read, on this JS-function: `var dQ = parseInt(ac.width, 10);`

### What should happen?

matomo.js should not stop and should give a unknown value.

### How can this be reproduced?

Open a in-private browser with Edge or open the page if this was never opened before (user data should not be in the database).
The script is executed and will crash on line 41:
`var dQ = parseInt(ac.width, 10);`

Dot some reasons, ac is NULL and so this will fail.

Replacing it with `var dQ = parseInt(ac?.width, 10);` and `var dO = parseInt(ac?.height, 10);`, it will show a resolution of "NaNxNaN".

At the beginning there is a line `ac = screen`. Should it be `ac = Screen` ?

### Matomo version

5.6.2

### PHP version

8.3.27

### Server operating system

Unix

### What browsers are you seeing the problem on?

Microsoft Edge

### Computer operating system

Windows 11

### Relevant log output

```shell
matomo.js:41 
 Uncaught TypeError: Cannot read properties of null (reading 'width')
c8	@	matomo.js:41
cN	@	matomo.js:46
ce	@	matomo.js:48
(anonymous)	@	matomo.js:65
cy	@	matomo.js:53
U.trackPageView	@	matomo.js:65
ak	@	matomo.js:12
ai	@	matomo.js:70
addTracker	@	matomo.js:72
(anonymous)	@	matomo.js:76
(anonymous)	@	matomo.js:76
```

### Validations

- [x] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [x] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [x] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description

In some rare cases it might happen that the screen element is not accessible. Matomo might currently fail to track in this case, as it tries to access it's properties directly.

This PR adds a check if the properties are actually available.

fixes #23960

### Checklist

- [NA] I have understood, reviewed, and tested all AI outputs before use
- [NA] All AI instructions respect security, IP, and privacy rules

### Review

- [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
- [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behaviour of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
- [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
- [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
- [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
- [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
- [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
- [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
- [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
- [ ] [New documentation added or existing documentation updated](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)

### CODE REVIEW

File: js/piwik.js [hunk 1]
```diff
@@ -3477,9 +3477,12 @@ if (typeof window.Matomo !== 'object') {
                     }
                 }
 
-                var width = parseInt(screenAlias.width, 10);
-                var height = parseInt(screenAlias.height, 10);
-                browserFeatures.res = parseInt(width, 10) + 'x' + parseInt(height, 10);
+                if (isDefined(screenAlias.width) && isDefined(screenAlias.height)) {
+                    var width = parseInt(screenAlias.width, 10);
+                    var height = parseInt(screenAlias.height, 10);
+                    browserFeatures.res = parseInt(width, 10) + 'x' + parseInt(height, 10);
```
Comment (tzi) [inline js/piwik.js]: Why do we do `parseInt()` two times on width and height?

**Review by tzi — DISMISSED** [review]

File: js/piwik.js (hunk 1 above)
Comment (sgiehl) [reply js/piwik.js]: Good questions. Haven't realized that when moving the code. Does indeed not make much sense. Will change it.

**Review by tzi — APPROVED** [review]
