### PR TITLE
Display useful message how to solve "Form security error" issue, when SSL may be mis-configured

### LINKED ISSUE #9407: Login may fail with un-helpful message "Form security error" when SSL is mis-configured
### How to reproduce

 * Set `assume_secure_protocol = 1` in config
 * Set `force_ssl=0`

Go to: 
 * http://piwik-server/
 * attempt to login 
 * Got `Form security failed` error message, that does not include the actual solution to the problem in this case
 * Expected: message should be helpful and help user solve the issue, which is to set `force_ssl=1`. 

### Explanation

When Piwik is used over HTTPS, we set the [Secure cookie flag `session.cookie_secure` ](http://php.net/manual/en/session.configuration.php#ini.session.cookie-secure)

```
        // advise browser that session cookie should only be sent over secure connection
        if (ProxyHttp::isHttps()) {
            @ini_set('session.cookie_secure', '1');
        }
```
source: https://github.com/piwik/piwik/blob/2.15.0/core/Session.php#L61-L64

So the PHP session ID cookie is only set when HTTPS is used.

In the case where Piwik thinks it's loaded over HTTPS (`assume_secure_protocol=1`) but it actually isn't, then the session ID cookie will be discarded and re-created on each page view, causing the NONCE to be re-generated, causing the login form submit to fail the nonce check.

### Solution

By setting `force_ssl=1` this will likely solve issue for this use case.

### PR DESCRIPTION
**Pull request by mattab**
fixes #9407 

Suggested solution

https

### CODE REVIEW

File: core/SettingsPiwik.php [hunk 1]
```diff
@@ -427,6 +427,10 @@ public static function overwritePiwikUrl($currentUrl)
      */
     public static function isHttpsForced()
     {
+        if (!SettingsPiwik::isPiwikInstalled()) {
```
Comment (tsteur) [inline core/SettingsPiwik.php]: Just curious why we check for this? Wouldn't it use pretty much the default value from global ini anyway? And would it be bad to redirect during installation?

File: core/Url.php [hunk 2]
```diff
@@ -176,20 +176,10 @@ public static function getCurrentScriptName($removePathInfo = true)
...
-        } catch (Exception $e) {
-            $assume_secure_protocol = false;
-        }
-        if ($assume_secure_protocol) {
-            return 'https';
-        }
-        if(    (isset($_SERVER['HTTPS']) && ($_SERVER['HTTPS'] == 'on' || $_SERVER['HTTPS'] === true))
-            || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')){
-
+        if (self::isPiwikServerAssumeSecureConnectionIsUsed()) {
```
Comment (tsteur) [inline core/Url.php]: should it be `doesPiwikServer...`? instead of `isPiwikServer...`?

File: core/Url.php [hunk 3]
```diff
@@ -686,4 +676,31 @@ public static function getLocalHostnames()
...
+        return 'http';
+    }
+
+    /**
+     * @return bool
+     */
+    public static function isPiwikServerAssumeSecureConnectionIsUsed()
+    {
+        try {
+            $assume_secure_protocol = @Config::getInstance()->General['assume_secure_protocol'];
```
Comment (tsteur) [inline core/Url.php]: Try/Catch might not be needed but can be ignored since it was already there before :)

File: core/Url.php [hunk 4]
```diff
@@ -176,20 +176,10 @@ public static function getCurrentScriptName($removePathInfo = true)
...
-        }
-        if(    (isset($_SERVER['HTTPS']) && ($_SERVER['HTTPS'] == 'on' || $_SERVER['HTTPS'] === true))
-            || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')){
-
+        if (self::isPiwikServerAssumeSecureConnectionIsUsed()) {
             return 'https';
         }
-        return 'http';
+        return self::getCurrentSchemeFromRequestHeader();
     }
```
Comment (tsteur) [inline core/Url.php]: much more readable now :+1:

File: core/Url.php (hunk 2 above)
Comment (tsteur) [inline core/Url.php]: forget it, I got it now... had to read it a couple of times :)

File: plugins/Login/Controller.php [hunk 5]
```diff
@@ -216,7 +218,41 @@ protected function authenticateAndRedirect($login, $password, $rememberMe, $urlT
...
+     * @param $message
+     * @return string
+     */
+    protected function getMessageExceptionNoAccessWhenInsecureConnectionMayBeUsed($message)
+    {
+        $message = '';
+
+        $isSecureConnectionLikelyNotUsed = Url::getCurrentSchemeFromRequestHeader() == 'http';
+        $hasSessionCookieSecureFlag = ProxyHttp::isHttps();
+        $isSecureConnectionAssumedByPiwikButNotForcedYet = Url::isPiwikServerAssumeSecureConnectionIsUsed() && !SettingsPiwik::isHttpsForced();
```
Comment (tsteur) [inline plugins/Login/Controller.php]: Maybe there could be two new methods in `Url` or so... `Url::isSecureConnectionLikelyNotUsed()` and `Url::isSecureConnectionAssumedByPiwikButNotForcedYet()` then it would be also testable or maybe better just one new method in `Url` for this  (would be more reusable maybe): `($isSecureConnectionLikelyNotUsed && $hasSessionCookieSecureFlag && $isSecureConnectionAssumedByPiwikButNotForcedYet)`

File: core/Url.php (hunk 2 above)
Comment (mattab) [inline core/Url.php]: renaming it to `isPiwikConfiguredToAssumeSecureConnection`

File: core/SettingsPiwik.php (hunk 1 above)
Comment (mattab) [inline core/SettingsPiwik.php]: it's to make sure that user is not redirected to HTTPS when it may not be working yet, ie. while installing Piwik, in case user uses  `common.config.ini.php` config file which may have `force_ssl` = 1

File: core/Url.php (hunk 4 above)
Comment (mattab) [inline core/Url.php]: Cool, even more now after applying your feedback!
