### PR TITLE
Fix #6927 race conditions when deleting files

### LINKED ISSUE #6927: concurrency problem w/ plugin activation
If multiple requests try to activate a plugin concurrently, OnDiskUIAsset::delete may throw. The situation that arises is as follows:

1. one request starts the activation process, it checks whether the asset file exists
2. another request checks whether it exists AND removes the file
3. the original request tries to remove the file, but it doesn't exist anymore and an exception is thrown

To fix, OnDiskUIAsset should silence the unlink error and only throw if the file is not writable. This may require a bit of refactoring to the existing code.

### PR DESCRIPTION
**Pull request by mnapoli**
See #6927

### CODE REVIEW

**Comment by mattab** [comment]
Hi @diosmosis pls review that one

File: core/AssetManager/UIAsset/OnDiskUIAsset.php [hunk 1]
```diff
@@ -58,12 +59,18 @@ public function delete()
...
+            }
 
             // try to remove compressed version of the merged file.
-            @unlink($this->getAbsoluteLocation() . ".deflate");
-            @unlink($this->getAbsoluteLocation() . ".gz");
+            try {
+                Filesystem::remove($this->getAbsoluteLocation() . ".deflate");
+                Filesystem::remove($this->getAbsoluteLocation() . ".gz");
+            } catch (Exception $e) {
+            }
```
Comment (diosmosis) [inline core/AssetManager/UIAsset/OnDiskUIAsset.php]: Surrounding the calls in a try-catch every time we want to ignore unlink failures seems excessive... Maybe instead there can be two methods 'tryRemove' and 'remove'? tryRemove would do the same logic as remove now but return true/false based on whether remove succeeds or not. remove would use tryRemove and if false, throws.

What do you think?

Comment (mnapoli) [inline core/AssetManager/UIAsset/OnDiskUIAsset.php]: Yep that makes sense. But is that very common to remove files but not actually care if they are really deleted?

Comment (diosmosis) [inline core/AssetManager/UIAsset/OnDiskUIAsset.php]: No, but I would assume in most cases we wouldn't want a failed remove to result in an exception that causes the request to fail. So there may be custom error handling, and using a try-catch every time for something as simple as file deletion seems verbose to me.

Comment (mnapoli) [inline core/AssetManager/UIAsset/OnDiskUIAsset.php]: Updated the code to optionally log a warning instead of throwing an exception. I've used a method parameter instead of defining a new method to avoid creating too many similar methods.
