### PR TITLE
Fix Scheduled Reports sent one hour late in daylight saving timezones

### LINKED ISSUE #7658: Daily Scheduled Reports sent one hour late, if daylight saving time is active
Please refer to this closed but unresolved issue: https://github.com/piwik/piwik/issues/5873

Short summary of old issue:
Daily reports scheduled for 12 are actually sent shortly after 13 o'clock. Global timezone setting is "Europe/Berlin"; Setting for all websites is also "Europe/Berlin".

We recently re-tested this issue (before and after the switch to central European daylight saving time). 
The issue had disappeared during winter time, but has reappeared with summer time. 

Therefore, it looks like Piwik is ignoring the switch to (Central European) summer time. 

Verified on Version 2.11.2

### PR DESCRIPTION
**Pull request by sgiehl**
[Replaces #10318]

This PR aims to fix the issue, that scheduled reports might be sent one hour to late / to early if the reports are saved for an site having a timezone using daylight savings.

The problem occurs because the "hour" the report should be sent at is currently saved in the timezone of the site. That means a new report with the timezone like e.g. `Europe/Berlin` with the setting to send the report at 8 o'clock would be one hour earlier/later when the daylight saving changes.

Internal Piwik uses UTC for running the tasks, so it tries to adjust the saved hour using the site's timezone difference. At the moment that would be two hours for `Europe/Berlin`, so the report would sent at 6 o'clock UTC. When the daylight saving changes again, the timezone difference will be only an hour. So Piwik will then reduce the saved hour value only by one to get the UTC time, which will be 7 o'clock (which is one hour later).

To avoid this in the future, I changed the current behavior to **not** save the hour value in the site's timezone anymore, but to use the UTC time instead. Doing this, the value can't be affected by daylight saving anymore. I also added an update script to update existing reports to have UTC values.

When creating/editing an report for an site using a timezone with a difference to UTC, Piwik will now should the UTC, aswell:

image

fixes #7658, refs #5873

### CODE REVIEW

File: plugins/ScheduledReports/Controller.php [hunk 1]
```diff
@@ -26,7 +26,11 @@ public function index()
         $view = new View('@ScheduledReports/index');
         $this->setGeneralVariablesView($view);
 
-        $view->countWebsites = count(APISitesManager::getInstance()->getSitesIdWithAtLeastViewAccess());
+        $siteTimezone = $this->site->getTimezone();
+        $dateTimeZone = new \DateTimeZone($siteTimezone);
+
+        $view->timeZoneDifference = -$dateTimeZone->getOffset(new \DateTime());
+        $view->countWebsites      = count(APISitesManager::getInstance()->getSitesIdWithAtLeastViewAccess());
```
Comment (mkrakiewicz) [inline plugins/ScheduledReports/Controller.php]: Wouldn't this cause a memory hog, if there are lots of sites added?

Comment (sgiehl) [inline plugins/ScheduledReports/Controller.php]: If so that would have been there before, as well. I've only added the detection for timezone offset.

File: plugins/ScheduledReports/templates/index.twig [hunk 2]
```diff
@@ -32,6 +32,7 @@
 </div>
 
 <script type="text/javascript">
+    var timeZoneDifference = {{ timeZoneDifference }} / 3600;
```
Comment (mkrakiewicz) [inline plugins/ScheduledReports/templates/index.twig]: Did you see Adam's comment in previous PR? Do you think it would be a good idea to move this to separate function?

File: plugins/ScheduledReports/Controller.php (hunk 1 above)
Comment (mkrakiewicz) [inline plugins/ScheduledReports/Controller.php]: Ok, I see.

File: core/Updates/2.16.3-b2.php [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+    {
+        $model      = new ScheduledReportsModel();
+        $allReports = ScheduledReportsAPI::getInstance()->getReports();
+
+        foreach ($allReports as $report) {
+            $timezone     = Site::getTimezoneFor($report['idsite']);
+            $dateTimeZone = new \DateTimeZone($timezone);
+
+            $timeZoneDifference = -ceil($dateTimeZone->getOffset(new \DateTime()) / 3600);
+            $report['hour'] = (24 + $report['hour'] + $timeZoneDifference) % 24;
```
Comment (mkrakiewicz) [inline core/Updates/2.16.3-b2.php]: Personally I would move math calculations to a separate function but it's just a minor thing.

**Comment by mkrakiewicz** [comment]
I think it looks OK in general 👍

**Comment by sgiehl** [comment]
@mkrakiewicz I've updated the code according to your feedback.
Guess it should be ready to merge then

**Comment by mattab** [comment]
@sgiehl 

We got a similar report: 

> [...] Piwik seems to have some weird ideas
about scheduling (I just scheduled a report for Daily at 17:00 for website in UTC+12 timezone, and it
has been scheduled for first run *tomorrow* at 16:00, and it knows
that's in 1day + some minutes). 

Do you think this PR will fix such issue as well, that a report scheduled for 5pm later today in UTC+12 will run today and not tomorrow (in UTC+12 timezone) ?

**Comment by sgiehl** [comment]
Yes, that should fix all time issues regarding scheduled reports. The report hour will always be saved in UTC. And as the scheduling is also done in UTC, the time should always be correct then.

**Comment by sgiehl** [comment]
I'll update the PR later, so it will get mergable again.

File: plugins/ScheduledReports/javascripts/pdf.js [hunk 4]
```diff
@@ -122,10 +131,12 @@ function initManagePdf() {
 
         apiParameters.parameters = getReportParametersFunctions[apiParameters.reportType]();
 
+        var hour = adjustHourToTimezone($('#report_hour').val());
```
Comment (adaqus) [inline plugins/ScheduledReports/javascripts/pdf.js]: Please provide `-timeZoneDifference` as a second argument for `adjustHourToTimezone()`.

Comment (mattab) [inline plugins/ScheduledReports/javascripts/pdf.js]: @sgiehl  as @adaqus pointed out, isn't the second argument missing?

Comment (sgiehl) [inline plugins/ScheduledReports/javascripts/pdf.js]: fixed
