### PR TITLE
Fix the password length checks on invite User

### LINKED ISSUE #19573: Invitation process doesn't trigger insecure password check
Whenever a new user in Matomo is created or a password is changed Matomo calls the `UsersManager.checkPassword` event and if it fails, warns the user that the password is insecure. 
https://github.com/matomo-org/matomo/blob/5df7397b4276a8f23e5537b7ba84394f4238dbed/plugins/UsersManager/UsersManager.php#L155

That's used by https://plugins.matomo.org/PasswordVerifier and other plugins to disallow some kind of passwords.

But with the new invitation process and `acceptInvitation()` this function is never called in the process and only the builtin basic check is done:
https://github.com/matomo-org/matomo/blob/5df7397b4276a8f23e5537b7ba84394f4238dbed/plugins/Login/Controller.php#L574-L577

This means users could sign up with passwords that don't match the password requirements.

Matomo Version: 04c1149d81bd5e48671f212f9a1cbd12fa10ef85

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:

Fixes: #19573  
update password checks

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by bx80 — CHANGES_REQUESTED** [review]
It would be great if we could have the `acceptInvitation` method call  `UsersManager::checkPassword` instead of duplicating the same checks, as suggested in the issue description. There might be additional password requirements in the future, so having just one place that decides if a password is valid would be more future proof. `checkPassword` throws an exception instead of providing a return value, but `acceptInvitation` could catch the exception string and set it as the value of `$error`.

File: plugins/UsersManager/UsersManager.php [hunk 1]
```diff
@@ -173,13 +174,23 @@ public static function checkPassword($password)
...
+            if ($showError) {
+                return Piwik::translate('UsersManager_ExceptionInvalidPasswordTooLong',
+                    array(self::PASSWORD_MAX_LENGTH));
+            }
             throw new Exception(Piwik::translate('UsersManager_ExceptionInvalidPasswordTooLong',
-              array(self::PASSWORD_MAX_LENGTH)));
+                array(self::PASSWORD_MAX_LENGTH)));
+
         }
+        return null;
```
Comment (bx80) [inline plugins/UsersManager/UsersManager.php]: To avoid duplicating the translation method calls, throw and return statements this can be simplified to:

```php
        $error = null;

        if (!self::isValidPasswordString($password)) {
            $error = Piwik::translate('UsersManager_ExceptionInvalidPassword', array(self::PASSWORD_MIN_LENGTH));
        }
        else if (mb_strlen($password) > self::PASSWORD_MAX_LENGTH) {
            $error = Piwik::translate('UsersManager_ExceptionInvalidPasswordTooLong', array(self::PASSWORD_MAX_LENGTH));
        }

        if ($error && !$showError) {
            throw new Exception($error);
        }

        return $error;
```

File: plugins/UsersManager/UsersManager.php [hunk 2]
```diff
@@ -152,7 +153,7 @@ public static function isValidPasswordString($input)
         return $l >= self::PASSWORD_MIN_LENGTH;
     }
 
-    public static function checkPassword($password)
+    public static function checkPassword($password, $showError = false)
```
Comment (bx80) [inline plugins/UsersManager/UsersManager.php]: A type hint on the new parameter would be nice along with a PHPDoc header for the method, also maybe `returnError` would be a better name since the method doesn't output anything itself?

**Review by bx80 — CHANGES_REQUESTED** [review]

File: plugins/UsersManager/UsersManager.php [hunk 3]
```diff
@@ -170,16 +171,21 @@ public static function checkPassword($password)
          *
          * @param string $password Checking password in plain text.
          */
+        $error = null;
+
         Piwik::postEvent('UsersManager.checkPassword', array($password));
```
Comment (sgiehl) [inline plugins/UsersManager/UsersManager.php:175]: you need to add a try catch around that. The event is supposed to throw an exception if the password isn't valid, which would currently pass through even if `$returnError = true`

Comment (peterhashair) [reply plugins/UsersManager/UsersManager.php:175]: @sgiehl that makes more sense, update it.

**Review by sgiehl — APPROVED** [review]
