### PR TITLE
Ensure LatestStable release channel uses the version provided from API

### LINKED ISSUE #21894: [Bug] LatestStable channel tries to update 4.14.0 to 5.0.2 instead of 4.16.1
### What happened?

When using an older 4.x version, e.g. `4.14.0`, the update check API in the `latest stable` release channel responds that `4.16.1` is available. This is also shown by the `CoreUpdater`:

> You can update to version 4.16.1 automatically or download the package and install it manually:

However, the download link points to `https://builds.matomo.org/matomo.zip` [source](https://github.com/matomo-org/matomo/blob/593437a3fd35381c13fe5cf7fabae5767dc3a519/plugins/CoreUpdater/ReleaseChannel/LatestStable.php#L33), at the moment being the latest 5.x release of `5.0.2`, not the intended `https://builds.matomo.org/matomo-4.16.1.zip`.

This wrong version is then also used by the automatic update and may result in unexpected major upgrades:

> ✓ Downloading update from https://builds.matomo.org/matomo.zip
> ✓ Unpacking the update
> ✓ Verifying the unpacked files
> ✓ Installing the latest version
> ✓ Checking for new plugin updates
> ✓ Updating plugin AnonymousPiwikUsageMeasurement to version 5.0.0

### What should happen?

The update process should respect the version shown, if it is not the real latest version, but a required intermediate version.

### How can this be reproduced?

Start the update process of any older Matomo 4 version (`4.14.0` and earlier).

### Matomo version

4.14.0

### PHP version

_No response_

### Server operating system

_No response_

### What browsers are you seeing the problem on?

_No response_

### Computer operating system

_No response_

### Relevant log output

_No response_

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #21894

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/CoreUpdater/ReleaseChannel.php [hunk 1]
```diff
@@ -41,6 +41,6 @@ public function getUrlToCheckForLatestAvailableVersion()
 
     public function getDownloadUrlWithoutScheme($version)
     {
-        return sprintf('://builds.matomo.org/piwik-%s.zip', $version);
```
Comment (mneudert) [inline plugins/CoreUpdater/ReleaseChannel.php:44]: This needs to reflected in the failing `ReleaseChannelTest::testGetDownloadUrlWithoutScheme...` expectation.

File: plugins/CoreUpdater/ReleaseChannel/LatestStable.php [hunk 2]
```diff
@@ -29,11 +29,6 @@ public function getDescription()
         return Piwik::translate('General_Recommended');
     }
 
-    public function getDownloadUrlWithoutScheme($version)
-    {
-        return '://builds.matomo.org/matomo.zip';
```
Comment (mneudert) [inline plugins/CoreUpdater/ReleaseChannel/LatestStable.php:34]: We need an update to our `OneClickUpdate` UI test:

>      Error: Failed to setup fixture Piwik\Tests\Fixtures\LatestStableInstall (error code = 1)

The [fixture](https://github.com/matomo-org/matomo/blob/9a3ef94df61682e7d543f3f8b438c368f6eb71a6/tests/PHPUnit/Fixtures/LatestStableInstall.php#L98) currently passes `null` as the version, and creates a URL that won't be available.

**Review by mneudert — CHANGES_REQUESTED** [review]

**Review by michalkleiner — APPROVED** [review]
Looks good, all tests are green

**Review by mneudert — APPROVED** [review]
