### PR TITLE
Fix incorrect URL parameter in update notification

### LINKED ISSUE #21446: [Bug]: Blank screen crash when showing update notification
### What happened?

An incorrectly formatted URL causes a crash when the VersionInfoHeaderMessage component tries to show that a new version is available.

image

### What should happen?

It shouldn't crash.

### How can this be reproduced?

1) Use 5.0.0-rc5
2) When the 5.0.0-rc6 instance is detected as available for update then a blank screen will be shown and the above message in the browser console.

### Matomo Version

Matomo 5

### Matomo Patch or Minor Version

rc5 / rc6

### PHP Version

8.2

### Server Operating System

Debian 12

### What browsers are you seeing the problem on?

Firefox

### Computer Operating System

Debian 12

### Relevant log output

_No response_

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by bx80**
### Description:

Fixes #21446 

Corrects an invalid URL causing a JS crash when an update is detected.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by michalkleiner** [comment]
Should we perhaps wrap https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/Morpheus/javascripts/piwikHelper.js#L36-L58 in `try {} catch(err) {}` block and return empty string if there's an error thrown? It would prevent the hard fail, but at the same time we would not have caught the incorrect input string 🤷.

**Comment by bx80** [comment]
I think that would be a better outcome than a hard fail, it's possible that future usage of the external link methods, either in core or plugins, could result in invalid URLs causing a similar crash, so minimizing the potential impact makes sense :+1:

File: plugins/Morpheus/javascripts/piwikHelper.js [hunk 1]
```diff
@@ -33,7 +33,17 @@ function _pk_externalRawLink(url, values) {
...
+  var returnURL= null;
+  try {
+      returnURL = new URL(url);
+  } catch(error) {
+      console.log('Error parsing URL: ' + url);
+      return '';
+  }
+  if (!returnURL) {
+    return '';
+  }
```
Comment (michalkleiner) [inline plugins/Morpheus/javascripts/piwikHelper.js]: We already use `let` and `const` so we can stick with `let` here, plus the early return from the catch is not much earlier than the null check right after that.

```suggestion
  let returnURL = null;
  try {
      returnURL = new URL(url);
  } catch(error) {
      console.log('Error parsing URL: ' + url);
  }
  if (!returnURL) {
    return '';
  }
```

**Review by michalkleiner — APPROVED** [review]
