### PR TITLE
Change the messaging when a password reset is initiated and a username/email is incorrect.

### LINKED ISSUE #13654: Possibility to enumerate user
In **Change your password** page, user enumeration is happening and it must change.
Simply replace the message **Error: Invalid username or e-mail address.**  Into something like **an email has been sent to the address on record**.

### PR DESCRIPTION
**Pull request by caddoo**
### Description:

This changes the messaging when a password reset is initiated and a username/email is incorrect.

image

#### Decisions:

- I've intentionally left the path of a pending user trying to reset their password fall into this flow as well, I don't think this will be a big problem, but let me know if it is.
- I added a new exception type rather than just returning `null` in the `PasswordResetter`, feels like the messaging is really something for the presentation/controller to decide. Also keeps the debug log in the same place as before.
- At first I thought having a yellow notice was weird, but later realised it's good because it shows the user has to do something next.
- For the new UI test, i tested against the exact same screenshot as the success flow, confirming there is no difference between each flow.

#### Bonus:

- In a separate commit I refactored the `resetPassword` controller method, making it a little easier to quickly scan / understand.

fixes #13654

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/Login/Controller.php [hunk 1]
```diff
@@ -387,30 +387,32 @@ protected function authenticateAndRedirect($login, $password, $urlToRedirect = f
...
+
+        if (false === empty($nonceError)) {
+            return $this->renderResetPasswordView([$nonceError]);
+        }
+
+        $firstStepFormErrors = $this->resetPasswordFirstStep($form);
+
+        if (false === empty($firstStepFromErrors)) {
+            return $this->renderResetPasswordView([$firstStepFormErrors]);
+        }
```
Comment (michalkleiner) [inline plugins/Login/Controller.php]: I found it harder than necessary to understand the long condition meant something is not empty, perhaps consider the `!empty` notation? Otherwise the refactoring of the method is nice and makes is easier to read.

```suggestion
        if (!empty($nonceError)) {
            return $this->renderResetPasswordView([$nonceError]);
        }

        $firstStepFormErrors = $this->resetPasswordFirstStep($form);

        if (!empty($firstStepFromErrors)) {
            return $this->renderResetPasswordView([$firstStepFormErrors]);
        }
```

File: plugins/Login/Controller.php [hunk 2]
```diff
@@ -387,30 +387,32 @@ protected function authenticateAndRedirect($login, $password, $urlToRedirect = f
...
+
+        return $this->renderResetPasswordView([], Piwik::translate('Login_ConfirmationLinkSent'));
+    }
+
+    private function renderResetPasswordView(array $formErrors = [], string $responseMessage = null): string
```
Comment (michalkleiner) [inline plugins/Login/Controller.php]:
```suggestion
    private function renderResetPasswordView(array $formErrors = [], ?string $responseMessage = null): string
```

File: plugins/Login/PasswordResetter.php [hunk 3]
```diff
@@ -220,7 +220,8 @@ public function initiatePasswordResetProcess($loginOrEmail, $newPassword)
         // get the user's login
         $user = $this->getUserInformation($loginOrEmail);
         if ($user === null) {
-            throw new Exception(Piwik::translate('Login_InvalidUsernameEmail'));
+            // throw a different exception type so can be handled/suppressed
```
Comment (michalkleiner) [inline plugins/Login/PasswordResetter.php]: It may not be clear what "a different exception type" means here based on the comment - different to what? I'd probably just say "custom exception".

```suggestion
            // throw a custom exception type so it can be handled/suppressed
```

File: plugins/Login/lang/en.json [hunk 4]
```diff
@@ -1,7 +1,7 @@
 {
     "Login": {
         "BruteForceLog": "Brute Force Log",
-        "ConfirmationLinkSent": "Open the confirmation link sent to your e-mail inbox to confirm changing your password.",
+        "ConfirmationLinkSent": "If the provided details are associated with an account, you will receive an email to confirm the password reset.",
```
Comment (michalkleiner) [inline plugins/Login/lang/en.json]: I reckon the text change here is significant enough to warrant a new translation key, keeping the old one as it was.

File: plugins/Login/tests/UI/ResetPassword_spec.js [hunk 5]
```diff
@@ -129,6 +137,24 @@ describe('ResetPassword', function () {
...
+          await page.goto('?module=Login&action=logout');
+          await page.waitForNetworkIdle();
+          await page.clearCookies();
+        });
+
+        it('should indicate a confirmation email might be sent even if username invalid', async function () {
+          await goToForgotPasswordPage();
+          await requestPasswordResetWithInvalidLogin();
+
+          expect(await page.screenshot({ fullPage: true })).to.matchImage('password_reset');
```
Comment (michalkleiner) [inline plugins/Login/tests/UI/ResetPassword_spec.js]: I've been burnt several times already by trying to compare UI test screenshots to a previous image used in another test, because the second one would regenerate the processed screenshot again and then you lose the one from the previous comparison, making it harder to debug if there's an issue with the previous run.
Generally I think it's better to duplicate the expected screenshot with a specific name and not reuse them. E.g.

```suggestion
          expect(await page.screenshot({ fullPage: true })).to.matchImage('password_reset_invalid_user');
```

**Review by michalkleiner — CHANGES_REQUESTED** [review]
The change overall looks good, no major concerns there. Left a few comments and marking this is 'request changes' mainly because of the language file where I think we need a new key for the new message.

File: plugins/Login/tests/UI/ResetPassword_spec.js (hunk 5 above)
Comment (caddoo) [reply plugins/Login/tests/UI/ResetPassword_spec.js]: Didn't think of that, updated

File: plugins/Login/Controller.php (hunk 2 above)
Comment (caddoo) [reply plugins/Login/Controller.php]: @michalkleiner I couldn't see why the return type is nullable, can you explain?

File: plugins/Login/lang/en.json (hunk 4 above)
Comment (caddoo) [reply plugins/Login/lang/en.json]: @michalkleiner can you explain a bit why a new key would be required, what impact does it have using the same key?

File: plugins/Login/Controller.php (hunk 2 above)
Comment (michalkleiner) [reply plugins/Login/Controller.php]: @caddoo it's not the return type here, it's the param type and you're assigning null to it as a default value, which is nullable. Otherwise an empty string as a default value would also be possible.

File: plugins/Login/lang/en.json (hunk 4 above)
Comment (michalkleiner) [reply plugins/Login/lang/en.json]: @caddoo the meaning of the message changes and keeping the key will keep existing translations and they would become inaccurate to the English version. Using a new key will add it to Weblate for new translations into other languages.

File: plugins/Login/Controller.php (hunk 2 above)
Comment (caddoo) [reply plugins/Login/Controller.php]: Wow sorry the line wrapping caught me out 😢

File: plugins/Login/lang/en.json (hunk 4 above)
Comment (caddoo) [reply plugins/Login/lang/en.json]: Thanks @michalkleiner I've updated, removed the other translations. And will make sure to translate the string into the top languages in weblate after.

**Review by michalkleiner — APPROVED** [review]
Tested locally and works as expected 👍 

As mentioned in person, I'd leave removing the old translation key from other than English lang files to the automated process via Weblate, but it should be fine to leave as is.
