### PR TITLE
Fix for Http class header parse error

### LINKED ISSUE #20077: Fatal error in tour when detecting consent manager
The recently added tour challenge "detect consent manager" is triggering a fatal error:

> Error: {"message":"explode(): Argument #2 ($string) must be of type string, array given","file":"\/core\/Http.php","line":759,"request_id":"aceb4","backtrace":" on \/core\/Http.php(759)\n#0 \/core\/Http.php(759): explode('\\r\\n', Array)\n#1 \/core\/SiteContentDetector.php(294): Piwik\\Http::sendHttpRequestBy('curl', 'https:\/\/www....', 5, 'Mozilla\/5.0 (Wi...', NULL, NULL, 0, false, true)\n#2 \/core\/SiteContentDetector.php(130): Piwik\\SiteContentDetector->requestSiteData(1, 5)\n#3 \/plugins\/Tour\/API.php(84): Piwik\\SiteContentDetector->detectContent(Array)\n#4 [internal function]: Piwik\\Plugins\\Tour\\API->detectConsentManager('1', 60)\n#5 \/core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#6 \/var

URL: /index.php?date=yesterday&module=API&format=json&method=Tour.detectConsentManager&idSite=1&filter_limit=-1&segment=&period=day

### PR DESCRIPTION
**Pull request by bx80**
### Description:

Fixes #20077

When a non-boolean response is received by the `core/Http::sendHttpRequestBy()` method and no redirect header is found the `explode()` method attempts to execute against a string instead of an array causing a fatal error.

This PR changes the default value for the header variable in this code block from string to array.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/Http.php [hunk 1]
```diff
@@ -742,7 +742,7 @@ public static function sendHttpRequestBy(
                 }
                 $response = '';
             } else {
-                $header = '';
+                $header = [];
```
Comment (sgiehl) [inline core/Http.php]: That's actually not correct. `explode` expects a string, so changing the default value will always create an error if no headers are given. The problem is more likely a few lines below.

```
                    $split = explode("\r\n\r\n", $response, 2);

                    if(count($split) == 2) {
                        [$header, $response] = $split;
                    } else {
                        $response = '';
                        $header = $split;
                    }
```

if the first explode has only one result, `$split` will be an array containing one element. That is than assigned to `$header` in the else. Guess it would be correct to use something like `$header = reset($split);` to ensure it will be the value of the first element and not the full array.

**Review by sgiehl — CHANGES_REQUESTED** [review]

File: core/Http.php (hunk 1 above)
Comment (bx80) [reply core/Http.php]: Good spot @sgiehl, I'd got the types the wrong way around :roll_eyes: I was waiting on recreation data for this before testing which is now available - your suggested change works correctly when tested against the site where this issue was encountered. I've updated the PR :+1:

Comment (justinvelluppillai) [reply core/Http.php]: sorry I set you wrong there!

**Review by sgiehl — APPROVED** [review]
