### PR TITLE
Disallow empty values when tracking content actions

### LINKED ISSUE #11841: Action table for type '14' /  '15' was not found during Actions archiving
Got these errors running archiver:
```
INFO [2017-07-05 05:59:45] Error: Got invalid response from API request: ?module=API&method=API.get&idSite=1&period=day&date=last1000&format=php&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:93:"Action table for type '14' was not found during Actions archiving. - caused by plugin Actions";}'
```

and then
```
ERROR [2017-07-05 07:31:41] Got invalid response from API request: ?module=API&method=API.get&idSite=1&period=day&date=last1000&format=php&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:93:"Action table for type '15' was not found during Actions archiving. - caused by plugin Actions";}'
```

Similar to https://github.com/piwik/piwik/issues/11623

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #11841

### CODE REVIEW

File: plugins/Contents/Columns/ContentName.php [hunk 1]
```diff
@@ -40,18 +42,17 @@ public function getActionId()
...
 
+        $contentName = $request->getParam('c_n');
         $contentName = trim($contentName);
 
         if (strlen($contentName) > 0) {
             return $contentName;
         }
 
-        return false;
+        throw new InvalidRequestParameterException('Param `c_n` must not be empty or filled with whitespaces');
```
Comment (sgiehl) [inline plugins/Contents/Columns/ContentName.php]: content name is required, so discard tracking request if it's not set

**Comment by tsteur** [comment]
👍

**Review by tsteur — APPROVED** [review]
