### PR TITLE
[hotfix]php8.0 key on empty object throw error

### LINKED ISSUE #18609: Uncaught exception: TypeError: key(): Argument #1 ($array) must be of type array, null given in /var/www/html/plugins/ImageGraph/API.php:242
PHP 8.0

> Uncaught exception: TypeError: key(): Argument #1 ($array) must be of type array, null given in /plugins/ImageGraph/API.php:242
Stack trace:
#0 /plugins/ImageGraph/API.php(242): key(NULL)
#1 [internal function]: Piwik\Plugins\ImageGraph\API->get(1, 'day', '2021-12-12,2022...', 'SearchEngineKey...', 'getCrawlingErro...', 'evolution', '2', false, false, true, 700, 200, 9, 11, true, false, false, '222222', 'FFFFFF', 'CCCCCC', false, true, false, false)
#2 /core/API/Proxy.php(244): call_user_func_array(Array, Array)
#3 /core/Context.php(28): Piwik\API\Proxy->Piwik\API\{closure}()
#4 /core/API/Proxy.php(335): Piwik\Context::executeWithQueryParameters(Array, Object(Closure))
#5 /core/API/Request.php(266): Piwik\API\Proxy->call('\\Piwik\\Plugins\\...', 'get', Array)
#6 /core/ReportRenderer.php(270): Piwik\API\Request->process()
#7 /core/ReportRenderer/Html.php(176): Piwik\ReportRenderer::getStaticGraph(Array, 700, 200, false, NULL)
#8 /core/ReportRenderer/Html.php(140): Piwik\ReportRenderer\Html->getAttachment(Array, Array, 'Monday, January...')
#9 /plugins/ScheduledReports/API.php(1021): Piwik\ReportRenderer\Html->getAttachments(Array, Array, 'Monday, January...')
#10 /plugins/ScheduledReports/API.php(551): Piwik\Plugins\ScheduledReports\API->getAttachments(Object(Piwik\ReportRenderer\Html), Array, Array, 'Monday, January...')
#11 /plugins/ScheduledReports/API.php(608): Piwik\Plugins\ScheduledReports\API->generateReport('1', '2022-01-10', 'en', 2, 'day')
#12 /core/Context.php(75): Piwik\Plugins\ScheduledReports\API->Piwik\Plugins\ScheduledReports\{closure}()
#13 /plugins/ScheduledReports/API.php(679): Piwik\Context::changeIdSite('1', Object(Closure))
#14 [internal function]: Piwik\Plugins\ScheduledReports\API->sendReport('1')
#15 /core/Scheduler/Scheduler.php(276): call_user_func(Array, '1')
#16 /core/Scheduler/Scheduler.php(148): Piwik\Scheduler\Scheduler->executeTask(Object(Piwik\Scheduler\Task))
#17 /plugins/CoreAdminHome/API.php(69): Piwik\Scheduler\Scheduler->run()
#18 /core/CronArchive.php(627): Piwik\Plugins\CoreAdminHome\API->runScheduledTasks()
#19 /core/CronArchive.php(264): Piwik\CronArchive->runScheduledTasks()
#20 /core/Access.php(661): Piwik\CronArchive->Piwik\{closure}()
#21 /core/CronArchive.php(269): Piwik\Access::doAsSuperUser(Object(Closure))
#22 /plugins/CoreConsole/Commands/CoreArchiver.php(32): Piwik\CronArchive->main()
#23 /vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\CoreConsole\Commands\CoreArchiver->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\CoreConsole\Commands\CoreArchiver), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /core/Console.php(130): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /core/Access.php(670): Piwik\Console->Piwik\{closure}()
#29 /core/Console.php(131): Piwik\Access::doAsSuperUser(Object(Closure))
#30 /core/Console.php(82): Piwik\Console->doRunImpl(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /console(32): Symfony\Component\Console\Application->run()
#33 {main}

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:
Fixes: #18609 

php8.0 key on empty object throw error

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/ImageGraph/API.php [hunk 1]
```diff
@@ -238,8 +238,11 @@ public function get(
 
             $ordinateColumns = array();
             if (empty($columns)) {
-                $ordinateColumns[] =
-                    empty($reportColumns[self::DEFAULT_ORDINATE_METRIC]) ? key($metadata['metrics']) : self::DEFAULT_ORDINATE_METRIC;
```
Comment (justinvelluppillai) [inline plugins/ImageGraph/API.php:242]: isn't `key($metadata['metrics'])` just `'metrics'` every time? Sorry if I misunderstand this line of code...

Comment (peterhashair) [reply plugins/ImageGraph/API.php:242]: @justinvelluppillai I remember the error was the key 'metrics' does not exist in $metadata, then on PHP 8.0, it throws an error call key on null when `empty($reportColumns[self::DEFAULT_ORDINATE_METRIC])` is empty.

File: plugins/ImageGraph/API.php [hunk 2]
```diff
@@ -238,8 +238,11 @@ public function get(
...
+                if (!empty($metadata['metrics']) && empty($reportColumns[self::DEFAULT_ORDINATE_METRIC])) {
+                    $ordinateColumns[] = key($metadata['metrics']);
+                } else {
+                    $ordinateColumns[] = self::DEFAULT_ORDINATE_METRIC;
+                }
```
Comment (sgiehl) [inline plugins/ImageGraph/API.php]: This might actually cause issues when rendering the graph if the metric `self::DEFAULT_ORDINATE_METRIC` isn't available. We should consider throwing an exception if `$reportColumns[self::DEFAULT_ORDINATE_METRIC]` is empty or at least logging an error

File: plugins/ImageGraph/API.php [hunk 3]
```diff
@@ -238,8 +238,16 @@ public function get(
 
             $ordinateColumns = array();
             if (empty($columns)) {
-                $ordinateColumns[] =
-                    empty($reportColumns[self::DEFAULT_ORDINATE_METRIC]) ? key($metadata['metrics']) : self::DEFAULT_ORDINATE_METRIC;
+                if (!empty($metadata['metrics']) && empty($reportColumns[self::DEFAULT_ORDINATE_METRIC])) {
+                    $ordinateColumns[] = key($metadata['metrics']);
+                } else {
```
Comment (sgiehl) [inline plugins/ImageGraph/API.php]: Now it's not doing the same as before anymore. `self::DEFAULT_ORDINATE_METRIC` should still be used if it is available:
```suggestion
                if (!empty($reportColumns[self::DEFAULT_ORDINATE_METRIC])) {
                    $ordinateColumns[] = self::DEFAULT_ORDINATE_METRIC];
                } else if (!empty($metadata['metrics'])) {
                    $ordinateColumns[] = key($metadata['metrics']);
                } else {
```

**Review by sgiehl — APPROVED** [review]
