### PR TITLE
Fix double escaping bug

### LINKED ISSUE #7531: Special characters in website name not shown correctly
As requested by Matt herewith a bug report:

I have an '& amp ;' and an '& # 039 ;' in my website name.  (written with spaces here because otherwise github shows them correctly)
On the Piwik "All websites dashboard" this look just fine as the & and ' symbols.
all websites dashboard
 
However in the selected website name field on the main dashboard is shows this just as '&amp;' and '&#039;' which looks very strange.
dashboard screenshot
Also in the Piwik Reports email is looks wrong, as well in the description as in the body except for the "Hello,Please find below your weekly report for......" line that one shows correctly
mail screenshot

Don't know if this is a bug or so, I couldn't find anything about this.
I know this issue is there since very early in v2.xx versions.

I run Piwik on my own server.

Hope it will be fix in one of the next versions, or that someone tells me how to fix (.... not by removing those characters).

### PR DESCRIPTION
**Pull request by mnapoli**
Fixes #7531

More explanation in https://github.com/piwik/piwik/issues/7531#issuecomment-86739966

I've also edited the CustomAlerts plugin and made a new release.

### CODE REVIEW

**Comment by mnapoli** [comment]
UI tests show it broke the highlighting of the current searched site…

**Comment by mnapoli** [comment]
It turns out autocompletion highlighting is broken on master. Go on the demo and try to autocomplete `sp` and some HTML code shows up briefly. Same for `la` and other combinations.

I think the problem is that the current autocomplete doesn't clear previous highlighted stuff, so it keeps adding `<span>` tags again and again (nesting them), messing up the HTML.

What I suggest is to disable the autocompletion highlighting for now in this pull request and try to fix it later?

**Comment by diosmosis** [comment]
(quoted from the other issue)
> That being said what do we do? I'm guessing fixing #6714 is not gonna happen. Fixing 1. and 2. to bypass Twig's escaping could make sense but 1. is used by other JS components so making it non-escaped anymore might break something else…

Here's an idea for a simpler hack that doesn't require skipping escaping via twig/angular (I think that's what's going on in this pull request): For 1), maybe we can create a new global var that uses the correct, unescaped site name. And for 2) can we fix users of the `sitename` attribute? Do you think this would be a better solution?

**Comment by mnapoli** [comment]
A slight precision on what this PR is doing: escaping manually the sites returned by the HTTP API so that they are over-escaped like the other variables. Then I can echo those variables in Angular by skipping escaping (because all of them are already escaped).

Your suggestion is nice, except for the new global variable that duplicates the existing one, that's adding clutter and confusion. E.g. how do we name the new variable? `siteRaw` and `siteNameRaw` (I think both of these exist)? Reminds me a bit of `mysql_real_escape_string()` that fixes `mysql_escape_string()` :p But maybe that's still a better way so why not!

> And for 2) can we fix users of the sitename attribute?

Yes it should be easy.

**Comment by mnapoli** [comment]
Answering @diosmosis's comments which for some reason ended up in my comment :)

> Does this mean they are double encoded? Or I guess escaped once so it can be just inserted in HTML? I don't know what over-escaped means.

No basically they are fetched from the HTTP API not escaped, i.e. once in the Javascript variable (in the Angular directive) they are not escaped, which is correct (no reason for a value to be stored escaped). At that point I manually escape them, so they end up "escaped" in the javascript variable, which I call "over-encoded" because at that point there is no reason that they should be escaped.

I do that because all other variables are stored escaped in memory (which they shouldn't ideally, but…): that way everything is consistently escaped in memory.

So when the variable is echo'ed by Angular into the HTML, it is normally escaped first (by Angular) but I disable that (given variables are already all escaped).

> Maybe siteNameUnescaped? I was thinking the old variable could be deprecated (in some manner), and maybe put out of use eventually when angular is used more in the UI. Of course that's quite a long way away, and #6714 could be accomplished well before then, so I guess it doesn't really matter how this is solved right now :)

Yep why not. As you said "I guess it doesn't really matter how this is solved right now" I agree :) I've already spent 2 days of work on this bug (which is kind of depressing) I'd rather leave it be with the currently implemented solution unless we think another solution is much better

**Comment by diosmosis** [comment]
> I'd rather leave it be with the currently implemented solution unless we think another solution is much better

I think it's a good solution that fixes the bug + introduces some consistency, so :+1: from me

**Comment by mattab** [comment]
@tsteur would you mind review this one and +1 if it's valid solution (and xss safe)?

**Comment by tsteur** [comment]
I think it's XSS safe.

For a better understanding: Could the AngularJS part be also solved by using `selectedSiteNameHtml` here? https://github.com/piwik/piwik/pull/7552/files#diff-df586ad4d60f9625a811f797e5547ea6R33  then it should be safe I reckon. 

Not sure how the SitesManager Controller change https://github.com/piwik/piwik/pull/7552/files#diff-d4d6201aa71999510eb45b144a549ef3R129 is related or whether it introduces any XSS. Couldn't find where it is used.

File: plugins/ScheduledReports/API.php [hunk 1]
```diff
@@ -449,7 +449,7 @@ public function generateReport($idReport, $date, $language = false, $outputType
         // render report
         $description = str_replace(array("\r", "\n"), ' ', $report['description']);
 
-        list($reportSubject, $reportTitle) = self::getReportSubjectAndReportTitle(Site::getNameFor($idSite), $report['reports']);
+        list($reportSubject, $reportTitle) = self::getReportSubjectAndReportTitle(html_entity_decode(Site::getNameFor($idSite)), $report['reports']);
```
Comment (diosmosis) [inline plugins/ScheduledReports/API.php]: Should Piwik::unsanitizeInputValue be used instead of html_entity_decode?

Comment (mnapoli) [inline plugins/ScheduledReports/API.php]: :+1: will do

Comment (mnapoli) [inline plugins/ScheduledReports/API.php]: @tsteur This part is to fix the double-escaping issues in scheduled reports (#7531)

File: plugins/CoreHome/angularjs/siteselector/siteselector.directive.html [hunk 2]
```diff
@@ -29,7 +29,8 @@
                     ng-repeat="site in model.sites"
                     ng-hide="!showSelectedSite && activeSiteId==site.idsite">
                     <a piwik-ignore-click href="{{ getUrlForSiteId(site.idsite) }}"
-                       piwik-autocomplete-matched="view.searchTerm">{{ site.name }}</a>
+                       piwik-autocomplete-matched="view.searchTerm"
+                       ng-bind-html="site.name"></a>
```
Comment (mnapoli) [inline plugins/CoreHome/angularjs/siteselector/siteselector.directive.html]: @tsteur here we are in the loop that shows all the sites. `selectedSiteNameHtml` (which has been removed) wouldn't make sense (unless I miss something?) because `site.name` is the name of the current site in the loop, not the selected one.

**Comment by mnapoli** [comment]
@tsteur I have answered your comment in the code parts you mentionned

**Comment by mnapoli** [comment]
I have fixed the `html_entity_decode` and rebased to be able to merge.
