### PR TITLE
[Performance]Cache whether a DB supports transaction level

### LINKED ISSUE #18138: Cache whether a DB supports transaction level or not
We noticed on Cloud that https://github.com/matomo-org/matomo/blob/4.x-dev/core/Db/TransactionLevel.php#L57 might be called very often. Especially when having many funnels but also in general. It can cause a bit of load. It be better to instead cache this information whether uncommitted can be set or not instead of retrying for support every time. We should cache this eg on the `$this->db` as it's DB dependent as if someone configures different DBs for writer and reader for example then we cannot reuse / cache the same result.

I'm meaning something in this direction (not tested): 

```
diff --git a/core/Db/TransactionLevel.php b/core/Db/TransactionLevel.php
index c19699084..fd730ced9 100644
--- a/core/Db/TransactionLevel.php
+++ b/core/Db/TransactionLevel.php
@@ -40,6 +40,10 @@ class TransactionLevel
 
     public function setUncommitted()
     {
+        if ($this->db->supportsUncommitted === false) {
+            return false;
+        }
+
         try {
             $backup = $this->db->fetchOne('SELECT @@TX_ISOLATION');
         } catch (\Exception $e) {
@@ -54,8 +58,13 @@ class TransactionLevel
             $this->db->query('SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED');
             $this->statusBackup = $backup;
 
-            Option::set(self::TEST_OPTION_NAME, '1'); // try setting something w/ the new transaction isolation level
+            if (!isset($this->db->supportsUncommitted)) {
+                Option::set(self::TEST_OPTION_NAME, '1'); // try setting something w/ the new transaction isolation level
+
+                $this->db->supportsUncommitted = true;
+            }
         } catch (\Exception $e) {
+            $this->db->supportsUncommitted = false;
             // catch eg 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED
             $this->restorePreviousStatus();
             return false;
diff --git a/plugins/Cloud b/plugins/Clo
```

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:
Fixes: #18138 
Cache whether a DB supports transaction on all the DB adapter to improve perfomance. 
### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: tests/PHPUnit/Integration/Db/TransactionLevelTest.php [hunk 1]
```diff
@@ -44,16 +44,23 @@ public function test_canLikelySetTransactionLevel()
 
 	public function test_setUncommitted_restorePreviousStatus()
 	{
-		$value = $this->db->fetchOne('SELECT @@TX_ISOLATION');
+        $version = $this->db->fetchOne('SELECT VERSION()');
+        if (preg_match("/8[.].*/", $version)) {
```
Comment (sgiehl) [inline tests/PHPUnit/Integration/Db/TransactionLevelTest.php]: wouldn't that also match `5.8.0` or even something like `5.7.36-0ubuntu0.18.04.1`? 
Maybe it would be easier to run something like `SHOW GLOBAL VARIABLES LIKE 't%_isolation'` to check if a variable is supported?

**Review by sgiehl — CHANGES_REQUESTED** [review]
Code looks fine. Left a comment for improving the tests

**Review by sgiehl — APPROVED** [review]
Looks good to me.
@tsteur do you want to have a last quick view before this is merged?

File: core/Db/TransactionLevel.php [hunk 2]
```diff
@@ -54,8 +60,12 @@ public function setUncommitted()
             $this->db->query('SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED');
             $this->statusBackup = $backup;
 
-            Option::set(self::TEST_OPTION_NAME, '1'); // try setting something w/ the new transaction isolation level
+            if (!isset($this->supportsUncommitted)) {
```
Comment (tsteur) [inline core/Db/TransactionLevel.php]: not sure this `if` is needed?

**Review by tsteur — CHANGES_REQUESTED** [review]
In the original issue in https://github.com/matomo-org/matomo/issues/18138 I mention this:

> We should cache this eg on the $this->db as it's DB dependent as if someone configures different DBs for writer and reader for example then we cannot reuse / cache the same result.

@peterhashair @sgiehl the current solution wouldn't 100% work for us.

We want to cache it per DB (in case writer and reader are somehow different) and also to have better cache when many new instances of this class are created. Otherwise it be only cached in the instance itself. We are creating this class very often so it wouldn't really help.

**Comment by peterhashair** [comment]
@tsteur right, so this `$supportsUncommitted` should be in the `Db.php`.

File: core/Tracker/Db.php [hunk 3]
```diff
@@ -30,6 +30,9 @@ abstract class Db
 
     protected $connection = null;
 
+    // this is used for indicate TransactionLevel Cache
+    public $supportsUncommitted = null;
```
Comment (sgiehl) [inline core/Tracker/Db.php:34]: Is the TransactionLevel only used with Tracker\Db instances. If not we might also add that new variable to `Piwik\Db` maybe?

Comment (tsteur) [reply core/Tracker/Db.php:34]: I would say so it be good to do it for both as the regular DB uses it as well eg when archiving

Comment (tsteur) [reply core/Tracker/Db.php:34]: the test below also uses the regular DB

**Comment by sgiehl** [comment]
@peterhashair most tests are now failing with messages like `Undefined property: Piwik\Db\Adapter\Pdo\Mysql::$supportsUncommitted`. Maybe it needs to be added to the adapters as well...

File: core/Db/Adapter/Pdo/Mysql.php [hunk 4]
```diff
@@ -29,6 +29,10 @@ class Mysql extends Zend_Db_Adapter_Pdo_Mysql implements AdapterInterface
      *
      * @param array|Zend_Config $config database configuration
      */
+    
+    // this is used for indicate TransactionLevel Cache
+    public $supportsUncommitted;
```
Comment (sgiehl) [inline core/Db/Adapter/Pdo/Mysql.php:34]: This needs to be part of the `MySQLi` adapter as well...

**Comment by peterhashair** [comment]
@sgiehl I think that one is good to go?

**Comment by sgiehl** [comment]
From my point of view this looks good to merge.

File: core/Db/TransactionLevel.php [hunk 5]
```diff
@@ -40,6 +40,10 @@ public function canLikelySetTransactionLevel()
 
     public function setUncommitted()
     {
+        if ($this->db->supportsUncommitted === false) {
```
Comment (tsteur) [inline core/Db/TransactionLevel.php:43]: Not sure if I'm seeing this right. Wouldn't this need to be `if ($this->db->supportsUncommitted !== null) {` because otherwise if `supportsUncommitted = true;` then it wouldn't use the cached result? @peterhashair @sgiehl

**Review by tsteur — CHANGES_REQUESTED** [review]
There might be still an issue. Also can we add a test for the cache by setting the property on the `db` object in a test and then we get expected result or something?

File: core/Db/TransactionLevel.php (hunk 5 above)
Comment (peterhashair) [reply core/Db/TransactionLevel.php:43]: @tsteur right, that make sense, just checking should it be return like that.
```php
        if ($this->db->supportsUncommitted !== null) {
            return $this->db->supportsUncommitted;
        }
```

Comment (tsteur) [reply core/Db/TransactionLevel.php:43]: I believe that makes sense. Be good to test it and double check it

File: core/Db/TransactionLevel.php [hunk 6]
```diff
@@ -40,6 +40,10 @@ public function canLikelySetTransactionLevel()
 
     public function setUncommitted()
     {
+        if ($this->db->supportsUncommitted !== null) {
+            return $this->db->supportsUncommitted;
```
Comment (sgiehl) [inline core/Db/TransactionLevel.php]: If we also "cache" and return if `supportsUncommitted` is `true`, that means we won't perform the setting of the transaction level anymore. That might be fine, but don't we need to unset `supportsUncommitted` then in `restorePreviousStatus`, to ensure it's checked and set again if needed?

Comment (sgiehl) [reply core/Db/TransactionLevel.php]: Note: This might also cause issues if the transaction level might be changed due to any other reasons...

Comment (tsteur) [reply core/Db/TransactionLevel.php]: good point, we still want to set the transaction mode, but we don't need to execute the `Option::set` for example to check if it worked.

Comment (peterhashair) [reply core/Db/TransactionLevel.php]: @tsteur @sgiehl did a little adjustment, would that work

File: core/Db/TransactionLevel.php [hunk 7]
```diff
@@ -40,6 +40,10 @@ public function canLikelySetTransactionLevel()
 
     public function setUncommitted()
     {
+        if ($this->db->supportsUncommitted) {
+            return true;
+        }
```
Comment (sgiehl) [inline core/Db/TransactionLevel.php]: That doesn't seem to make sense to me. Doesn't that mean, that if setting the transaction level isn't supported, that it will be retried every time it's requested. And on the other side - if it's supported the transaction level won't be set again once it was detected.

**Comment by peterhashair** [comment]
@sgiehl right, sorry wasn't thinking, update again, if that makes sense.

File: core/Db/TransactionLevel.php [hunk 8]
```diff
@@ -54,7 +59,13 @@ public function setUncommitted()
             $this->db->query('SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED');
             $this->statusBackup = $backup;
 
-            Option::set(self::TEST_OPTION_NAME, '1'); // try setting something w/ the new transaction isolation level
+            if ($this->db->supportsUncommitted === null) {
```
Comment (sgiehl) [inline core/Db/TransactionLevel.php:63]: This will currently always be true, as the method already returns in the beginning

File: core/Db/TransactionLevel.php [hunk 9]
```diff
@@ -40,12 +40,17 @@ public function canLikelySetTransactionLevel()
 
     public function setUncommitted()
     {
+        if ($this->db->supportsUncommitted !== null) {
+            return $this->db->supportsUncommitted;
+        }
```
Comment (sgiehl) [inline core/Db/TransactionLevel.php]: We should only skip the rest if `supportsUncommitted` was set to false.

```suggestion
        if ($this->db->supportsUncommitted === false) {
            return false;
        }
```

File: core/Db/TransactionLevel.php [hunk 10]
```diff
@@ -69,6 +80,7 @@ public function restorePreviousStatus()
         if ($this->statusBackup) {
             $value = strtoupper($this->statusBackup);
             $this->statusBackup = null;
+            $this->db->supportsUncommitted = null;
```
Comment (sgiehl) [inline core/Db/TransactionLevel.php]: We shouldn't reset that one here anymore.

File: core/Db/TransactionLevel.php [hunk 11]
```diff
@@ -54,7 +59,13 @@ public function setUncommitted()
             $this->db->query('SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED');
             $this->statusBackup = $backup;
```
Comment (sgiehl) [inline core/Db/TransactionLevel.php:61]: Shouldn't the `statusBackup` only be set if it wasn't set before? Just wondering what would happen when calling the method twice, without calling `restorePreviousStatus` before. In that case the second call would overwrite the `statusBackup` with `READ UNCOMMITTED` and the previously set level gets lost.

**Review by sgiehl — CHANGES_REQUESTED** [review]

File: core/Db/TransactionLevel.php (hunk 11 above)
Comment (peterhashair) [reply core/Db/TransactionLevel.php:61]: @sgiehl i was wonder the same thing. Otherwise the restore will be always skipped. I am right.

File: core/Db/TransactionLevel.php [hunk 12]
```diff
@@ -54,7 +59,13 @@ public function setUncommitted()
...
 
-            Option::set(self::TEST_OPTION_NAME, '1'); // try setting something w/ the new transaction isolation level
+            if ($this->db->supportsUncommitted === null) {
+                // the first time we need to check if the transaction level actually works by
+                // trying to set something w/ the new transaction isolation level
+                Option::set(self::TEST_OPTION_NAME, '1');
+            }
+            $this->db->supportsUncommitted = true;
+
```
Comment (tsteur) [inline core/Db/TransactionLevel.php]: when it goes in the exception below, then we need to set `$this->db->supportsUncommitted = false;`

File: core/Db/TransactionLevel.php (hunk 9 above)
Comment (tsteur) [reply core/Db/TransactionLevel.php]: 👍  absolutely, otherwise we never set the uncommitted status again when it is supported. @peterhashair I had also sent you this in slack

File: core/Db/TransactionLevel.php (hunk 11 above)
Comment (tsteur) [reply core/Db/TransactionLevel.php:61]: This would be a different issue overall maybe and not as part of this. Generally, because we create each time a separate instance of the transaction level it should work and be fine. Like 

```php
$t = new TransactionLevel();
$t->setUncommitted();
....
$x = new TransactionLevel();
$x->setUncommitted();
$x->restorePrevious();
...
$t->restorePrevious();
```

AFAIK `$t` should then restore the previous one again correctly. `$x` would technically not need to try and set the status if `backup` is already `READ UNCOMMITTED`.

File: core/Db/TransactionLevel.php [hunk 13]
```diff
@@ -40,12 +40,18 @@ public function canLikelySetTransactionLevel()
 
     public function setUncommitted()
     {
+        if ($this->db->supportsUncommitted === false) {
+            // we know "Uncommitted" transaction level is not supported, we don't need to do anything as it won't work to set the status
+            return;
```
Comment (sgiehl) [inline core/Db/TransactionLevel.php]: shouldn't that be to have consistent return types:
```suggestion
            return false;
```

**Review by sgiehl — CHANGES_REQUESTED** [review]
Left a comment. Otherwise guess it looks good now, as the status backup doesn't seem to be an issue.

**Review by sgiehl — APPROVED** [review]
Should be good to merge now. @tsteur do you want to have another look before merging?

File: core/Db/TransactionLevel.php [hunk 14]
```diff
@@ -69,6 +83,7 @@ public function restorePreviousStatus()
         if ($this->statusBackup) {
             $value = strtoupper($this->statusBackup);
             $this->statusBackup = null;
+            $this->db->supportsUncommitted = null;
```
Comment (tsteur) [inline core/Db/TransactionLevel.php]: I'm not understanding why we would reset this one? This would clear the cache every time meaning the cache would effectively never be used?

File: core/Db.php [hunk 15]
```diff
@@ -40,6 +40,8 @@ class Db
 
     private static $logQueries = true;
 
+    // this is used for indicate TransactionLevel Cache
+    public $supportsUncommitted = null;
```
Comment (tsteur) [inline core/Db.php]: not sure this one is actually needed but can leave it there I guess

File: core/Tracker/Db.php (hunk 3 above)
Comment (tsteur) [reply core/Tracker/Db.php:34]: This one still needs to be done. I don't think this is needed in here but rather in `Tracker/Mysqli` and `Tracker/pdo/mysql` DB?

**Review by tsteur — CHANGES_REQUESTED** [review]
@peterhashair @sgiehl I believe there are still few issues. Could we get the these resolved?

File: core/Tracker/Db.php (hunk 3 above)
Comment (sgiehl) [reply core/Tracker/Db.php:34]: @tsteur aren't `Tracker/Mysqli` and `Tracker/PDO/Mysql` inheriting from `Tracker/Db`?

Comment (tsteur) [reply core/Tracker/Db.php:34]: They do indeed 👍

**Review by tsteur — APPROVED** [review]
I haven't tested it but looks all good to me now 👍
