### PR TITLE
convert ignoreClearAllViewDataTableParameters to test vars instead of paramter

### LINKED ISSUE #20822: The ignoreClearAllViewDataTableParameters query parameter doesn't work for UI tests testing evolution graphs
While trying to write some new UI test cases, I noticed that the `ignoreClearAllViewDataTableParameters` query parameter was working for dataTable reports, but not evolution graph reports.

## Context
I'm unable to use an automated test to confirm that the report parameters are being stored and used correctly for visualisation reports. I was able to get it working for table reports, but not visualisation reports. For example, here is [a link to the test cases I added that did work](https://github.com/innocraft/plugin-CustomReports/pull/167/files#diff-bfe33e11d2e988c3fb0fc70edc3c008791ce120e8b5157ee3939bd59cbc3af26R213-R239). When I tried doing something similar for a visualisation report, it didn't work because there was an AJAX call for `?date=2022-11-21&module=Annotations&action=getEvolutionIcons&idSite=1&period=day&filter_limit=-1&lastN=30` which didn't include the `ignoreClearAllViewDataTableParameters` like the `getEvolutionGraph` or `saveViewDataTableParameters` AJAX calls did.

## Expected Behavior
The `ignoreClearAllViewDataTableParameters` query parameter should prevent the parameters from being cleared regardless of the type of report.

## Current Behavior
The `ignoreClearAllViewDataTableParameters` parameter only works for table reports and not visualisations.

## Possible Solution
Update the Annotations.getEvolutionIcons AJAX call to forward the `ignoreClearAllViewDataTableParameters` query parameter so that it doesn't cause stored report parameters to be cleared.

## Steps to Reproduce (for Bugs)
1. Add a new test case around saving the report parameters of a visualisation report. For example, I tried adding one for report 11 in `CustomReports/tests/UI/CustomReportsReport_spec.js`, using the `ignoreClearAllViewDataTableParameters` query parameter.
2. Note that despite including the `ignoreClearAllViewDataTableParameters` query parameter in the URL, the visualisation doesn't persist the report parameters.

## Your Environment
* Matomo Version: 4.14.3-b5
* PHP Version: 8.1.2-1ubuntu2.11
* Additionally installed plugins: CustomReports
* Browser: Brave (Chromium)
* Operating System: Ubuntu 22.04.2 LTS

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #20822

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/Installation/tests/UI/Installation_spec.js [hunk 1]
```diff
@@ -18,6 +18,7 @@ describe("Installation", function () {
         testEnvironment.testUseMockAuth = 0;
         testEnvironment.configFileLocal = path.join(PIWIK_INCLUDE_PATH, "/tmp/test.config.ini.php");
         testEnvironment.dontUseTestConfig = true;
+        testEnvironment.ignoreClearAllViewDataTableParameters = 1;
```
Comment (michalkleiner) [inline plugins/Installation/tests/UI/Installation_spec.js:21]: Should it default to 0?

Comment (sgiehl) [reply plugins/Installation/tests/UI/Installation_spec.js:21]: It defaults to not being set. Various UI tests are reusing the same database (to speed things up), so we need to clean up the changes that might be store to views automatically. Otherwise tests would have different results depending which tests ran before. To prevent that this variable (previously get parameter) can be provided.
In that specific case we can't try to clean up as the database was not yet created in installation tests.

Comment (michalkleiner) [reply plugins/Installation/tests/UI/Installation_spec.js:21]: Ok, thanks for the explanation. I previously thought, based on the list of settings, that this was a general config, hence the question. I now see it's just the installation test, so it makes sense now.

**Review by snake14 — APPROVED** [review]
Looks good and it worked for the test case that I was trying to get working :+1:

**Review by michalkleiner — APPROVED** [review]
