### PR TITLE
Fix goal metric processing for device type / model / brand

### LINKED ISSUE #9777: Process Goal conversions, conversion rate, for each Device Type
Currently we process Goal conversions and Conversion rates for each of the following dimensions:

dimensions goals

Goal of this issue is to add "Device type" at least to these dimensions, so that one can know the conversion rate per device type, for each goal. It would be valuable to know conversion rates of Desktop VS Mobile VS Table!

### PR DESCRIPTION
**Pull request by sgiehl**
Processing goal metrics for device type / model / brand was not working properly.

The visitor column value was not available when processing the goal conversion, which should be fixed with this changes.
I've also added some small tests to prove the goal metrics are processed correctly for device type / brand / model.

fixes #9777

### CODE REVIEW

File: core/Tracker/VisitorRecognizer.php [hunk 1]
```diff
@@ -231,7 +231,7 @@ private function getVisitFieldsPersist()
             $dimensions = VisitDimension::getAllDimensions();
 
             foreach ($dimensions as $dimension) {
-                if ($dimension->hasImplementedEvent('onExistingVisit')) {
+                if ($dimension->hasImplementedEvent('onExistingVisit') || $dimension->hasImplementedEvent('onAnyGoalConversion')) {
```
Comment (sgiehl) [inline core/Tracker/VisitorRecognizer.php]: Not sure it this is the correct solution.
Explanation why I've changed that:

I had following code in a visit dimension
```
    public function onAnyGoalConversion(Request $request, Visitor $visitor, $action)
    {
        return $visitor->getVisitorColumn($this->columnName);
    }
```
That didn't work properly, as the column didn't implement the `onExistingVisit` event (which simply isn't needed) and thus the property wasn't set for an existing visit.

Instead of this change here, I could also add an empty `onExistingVisit` event to the columns. But I think it is more useful this way.

@mattab @tsteur  what do you think?

Comment (tsteur) [inline core/Tracker/VisitorRecognizer.php]: 👍  good solution

**Comment by sgiehl** [comment]
Failing UI tests seem not to be related to this PR.

**Comment by mattab** [comment]
LGTM.  I'll confirm on demo3 in coming days when the reports work
