### PR TITLE
Fix php 8.1 deprecation

### LINKED ISSUE #20356: PHP 8.1: DevicesDetection: urlencode() Passing null to parameter #1 ($string) of type string is deprecated
We tested running PHP 8.1 on Cloud, noticed this warning:

/var/www/html/plugins/DevicesDetection/API.php(129): Deprecated - urlencode(): Passing null to parameter #1 ($string) of type string is deprecated - Matomo 4.13.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) [internal function]: Piwik\ErrorHandler::errorHandler(),#1/plugins/DevicesDetection/API.php(129),[internal function]: Piwik\Plugins\DevicesDetection\API->Piwik\Plugins\DevicesDetection\{closure}(),#3/core/DataTable.php(511),#4/plugins/DevicesDetection/API.php(133),[internal function]: Piwik\Plugins\DevicesDetection\API->getModel(),#6/core/API/Proxy.php(244),#7/core/Context.php(28),#8/core/API/Proxy.php(335),#9/core/Plugin/Visualization.php(341)

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #20356

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/DevicesDetection/API.php [hunk 1]
```diff
@@ -122,7 +122,7 @@ public function getModel($idSite, $period, $date, $segment = false)
                     list($brand, $model) = explode(';', $label, 2);
                     $brand = getDeviceBrandLabel($brand);
                 } else {
-                    $brand = null;
+                    $brand = '';
```
Comment (sgiehl) [inline plugins/DevicesDetection/API.php:125]: This is the only relevant change. Everything else is applying coding styles.

**Review by bx80 — APPROVED** [review]
* [x] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [x] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [x] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [x] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [x] n/a [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [x] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [x] n/a [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [x] none [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [x] n/a [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [x] n/a [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [x] n/a Existing documentation updated if needed
