### PR TITLE
Adjusting recent exception logging changes

### LINKED ISSUE #3620: Prevent path disclosure, automatically hide path from warning messages and backtraces
Path disclosure results to a little piece of information disclosure, the path at which piwik is setup. We better not give out the information even though it is not a problem in itself, it can be used when other attack vectors would be available. Also many users report the bug and it would reduce email traffic and overhead.

The idea would be to automatically remove the path from the error messages, backtraces, in the custom error /exception handler. We could still display the path when the Super User is logged in, just because it would help making things clear.

But for anonymous or view/admin, we should replace the path with empty string.

### PR DESCRIPTION
**Pull request by snake14**
### Description:

The changes in #23372 were causing some erroneous string replacements in error messages during automated tests. This PR adjusts the changes to account for when config values aren't set. For example, in the UI tests of one plugin, all strings containing `0` would have `tokenauth` inserted instead.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
@snake14 could you point me to one of the broken builds? Just wondering why there shouldn't be a token auth at all 🤔

File: core/ExceptionHandler.php [hunk 1]
```diff
@@ -113,11 +113,13 @@ public static function replaceSensitiveValues(string $message): string
         $dbConfig = Db::getDatabaseConfig();
 
         $valuesToReplace = [
-            Piwik::getCurrentUserTokenAuth() => 'tokenauth',
-            SettingsPiwik::getSalt()         => 'generalSalt',
-            $dbConfig['username']            => 'dbuser',
-            $dbConfig['password']            => 'dbpass',
+            Piwik::getCurrentUserTokenAuth() ?: '' => 'tokenauth',
```
Comment (michalkleiner) [inline core/ExceptionHandler.php]: If we were changing this to allow for empty values, it might be best to switch the keys and values around as we can have multiple empty values but not keys, and we always have the replacement value. Having an empty string as an array key might be valid but not super predictable and could cause some debugging headaches later on.
We could then use array_filter to remove empty values before the actual replacement.

**Comment by snake14** [comment]
> @snake14 could you point me to one of the broken builds? Just wondering why there shouldn't be a token auth at all 🤔

Sure @sgiehl . The one that I was trying to fix yesterday was the [AdvertisingConversionExport UI build](https://github.com/innocraft/plugin-AdvertisingConversionExport/actions/runs/15940637701/job/45017956668). In the screenshot, you can see that the `0` was replaced with `tokenauth`.

**Comment by sgiehl** [comment]
@snake14 were you able to find out why there is no token set in that case?

File: core/ExceptionHandler.php (hunk 1 above)
Comment (snake14) [reply core/ExceptionHandler.php]: Thanks for the input @michalkleiner . In another circumstance, I would likely agree with you. However, I don't see any use case where an empty string would be a valid search value for replacement, especially when trying to mask sensitive data. An empty string isn't sensitive data and wouldn't `str_replace` simply ignore an empty string as the search value?

**Comment by snake14** [comment]
> @snake14 were you able to find out why there is no token set in that case?

@sgiehl No. I spent a while trying to adjust the test. The token appeared to be in the JS, but wasn't being used in PHP during API requests. It was at that point that I realised that having a search-and-replace function that replaced all `0` values in an error message when the auth_token wasn't set was buggy.

File: core/ExceptionHandler.php (hunk 1 above)
Comment (michalkleiner) [reply core/ExceptionHandler.php]: @snake14 as mentioned in my comment, we'd first run the list of replacements via array_filter and it would remove it, so it wouldn't be used to search for a value to be replaced. That mechanism would also cover any other replacements that don't actually provide a value, so would be a bit more robust mechanism.

Comment (snake14) [reply core/ExceptionHandler.php]: Thank you for the elaboration; I didn't quite follow all of your first comment. I have applied your feedback. :+1:

File: core/ExceptionHandler.php [hunk 2]
```diff
@@ -113,11 +113,13 @@ public static function replaceSensitiveValues(string $message): string
         $dbConfig = Db::getDatabaseConfig();
 
         $valuesToReplace = [
-            Piwik::getCurrentUserTokenAuth() => 'tokenauth',
-            SettingsPiwik::getSalt()         => 'generalSalt',
-            $dbConfig['username']            => 'dbuser',
-            $dbConfig['password']            => 'dbpass',
+            'tokenauth'   => Piwik::getCurrentUserTokenAuth() ?: '',
```
Comment (michalkleiner) [inline core/ExceptionHandler.php]: We wouldn't need the `?: ''` addition with the array_filter approach as that removes all falsey values, including nulls, zeros, empty strings etc.

Comment (snake14) [reply core/ExceptionHandler.php]: True, but it doesn't hurt anything either. I simply forgot to remove it yesterday. I removed it now.

**Review by michalkleiner — DISMISSED** [review]
This looks good to me, avoiding any edge cases where some of the values may be empty for whatever reason.

I'll leave the final approval to @sgiehl

**Comment by snake14** [comment]
@sgiehl Are you good to merge this PR, please?

**Comment by snake14** [comment]
The failing UI test case appears to be unrelated to this PR as I have another very different PR with the exact same test case failing.

**Review by sgiehl — APPROVED** [review]
