### PR TITLE
When the connection to database fails, the API should return a valid response

### LINKED ISSUE #7903: When the connection to database fails, the API should return a valid response
When Piwik cannot connect to the database, the API should return a valid response. 

Reproduce:
 * Edit config.ini.php and set a wrong username for the database eg. `xyytueyeat`
 * Open `index.php?module=API&method=API.getPiwikVersion&format=xml`
 * Got: HTML error output 
 * Expected: 
   * HTTP error code 500,
   * and the API call returns a valid eg. XML response that returns the API error reponse eg. 
```
<?xml version="1.0" encoding="utf-8" ?>
<result>
	<error message="Cannot connect to the database: SQLSTATE[28000] [1045] Access denied for user 'xyytueyeat'@'localhost' (using password: YES)" />
</result>

```

Steps:
 * Add test case 
 * Fix issue

Refs #7901 #7902

### PR DESCRIPTION
**Pull request by tsteur**
fixes #7903

Whenever the error handler now gets an error, and an API was called, we will still output a valid API message unless an exception contains an HTML message. In this case it will just display the HTML message as it is usually supposed to be in a nice format etc. Not sure re any possible side effects. I tested maintenance mode, and some other errors and they were still displayed correctly.

### CODE REVIEW

File: plugins/Installation/tests/System/APITest.php [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+    }
+
+    public function test_shouldReturnValidApiResponse_IfWrongDbInfo_formatXML()
+    {
+        $http = new HttpResponseText('');
+        $response = $http->getResponse($this->getUrl());
+
+        $response = str_replace("\n", "", $response);
+
+        $this->assertStringStartsWith('<?xml version="1.0" encoding="utf-8" ?><result>	<error message=', $response);
```
Comment (tsteur) [inline plugins/Installation/tests/System/APITest.php]: I don't compare whole output since I'm kinda certain that MySQL will report messages differently depending on the used version

File: plugins/Installation/tests/System/APITest.php [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+    public static $fixture = null; // initialized below class definition
+
+    public static function setUpBeforeClass()
+    {
+        parent::setUpBeforeClass();
+
+        $testingEnvironment = new \Piwik\Tests\Framework\TestingEnvironmentVariables();
+        $testingEnvironment->configFileLocal = PIWIK_INCLUDE_PATH . '/plugins/Installation/tests/resources/config.ini.php';
+        $testingEnvironment->save();
+    }
```
Comment (diosmosis) [inline plugins/Installation/tests/System/APITest.php]: NOTE: It should also be possible to set `configFileLocal` by overriding the `provideContainerConfig()`, eg:

```
public function provideContainerConfig()
{
    return array(
        'test.vars.configFileLocal' => PIWIK_INCLUDE_PATH . '/plugins/...';
    );
}
```

This isn't documented, but is intended to eventually replace direct `TestingEnvironmentVariables()` and `TestingEnvironmentVariables::save()` use. It's not really important, but if you'd like, you can use `provideContainerConfig()` instead here.

**Comment by diosmosis** [comment]
Looks good to me. Not merging directly since I left a comment, but you can merge yourself whenever.

File: plugins/Installation/tests/System/APITest.php (hunk 2 above)
Comment (tsteur) [inline plugins/Installation/tests/System/APITest.php]: I just tried it but didn't work... is it also possible to specify the `$testEnvironment->configOverride` this way?

Comment (diosmosis) [inline plugins/Installation/tests/System/APITest.php]: Should be possible to set configOverride this way. configFileLocal doesn't work because it's created before the DI container (since the INI config is needed before this point)... but there should ideally be only one way to set these properties...

Anyway, it's not important so I will merge this PR.
