### PR TITLE
Apply max execution time limit to goals live query

### LINKED ISSUE #21624: [Bug] Goals/VisitorDetaisl::queryGoalConversionsForVisits() does not apply Live max execution time setting
### What happened?

Seeing in the processlist in the database a query like

```
SELECT
						log_conversion.idvisit,
						'goal' as type,
						goal.name as goalName,
						goal.idgoal as goalId,
						log_link_visit_action.idpageview,
						log_conversion.revenue as revenue,
						log_conversion.idlink_va,
						log_conversion.idlink_va as goalPageId,
						log_conversion.server_time as serverTimePretty,
						log_conversion.url as url,
						log_conversion.referer_type as referrerType,
						log_conversion.referer_name as referrerName,
						log_conversion.referer_keyword as referrerKeyword
				FROM log_conversion AS log_conversion
				LEFT JOIN log_link_visit_action AS log_link_visit_action
				    ON log_link_visit_action.idlink_va = log_conversion.idlink_va
				LEFT JOIN goal AS goal
					ON (goal.idsite = log_conversion.idsite
						AND
						goal.idgoal = log_conversion.idgoal)
					AND goal.deleted = 0
				WHERE log_conversion.idvisit IN ('623238')
					AND log_conversion.idgoal > 0
                ORDER BY log_conversion.idvisit, log_conversion.server_time ASC
```

### What should happen?

The DB select query should have had a `max_execution_query` defined.

### How can this be reproduced?

* Configure `live_query_max_execution_time` in config.ini.php.
* Make sure you have a goal configured
* Make sure you have a visitor who triggered a goal
* Fetch the visits log or profile

The DB query doesn't have the max execution time query applied.

### Matomo major version

Matomo 5

### Matomo minor or patch Version

0

### PHP version

0

### Server operating system

.

### What browsers are you seeing the problem on?

_No response_

### Computer operating system

.

### Relevant log output

_No response_

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes https://github.com/matomo-org/matomo/issues/21624

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/Goals/VisitorDetails.php [hunk 1]
```diff
@@ -90,7 +92,15 @@ protected function queryGoalConversionsForVisits($idVisits)
...
-        $conversions = $this->getDb()->fetchAll($sql);
+
+        $sql = DbHelper::addMaxExecutionTimeHintToQuery($sql, $this->getLiveQueryMaxExecutionTime());
+
+        try {
+            $conversions = $this->getDb()->fetchAll($sql);
+        } catch (\Exception $e) {
+            Model::handleMaxExecutionTimeError($this->getDb(), $e, '', Date::now(), Date::now(), null, 0, ['sql' => $sql]);
+            throw $e;
+        }
```
Comment (michalkleiner) [inline plugins/Goals/VisitorDetails.php]:
```suggestion
        $dateNowStart = Date::now();
        try {
            $conversions = $this->getDb()->fetchAll($sql);
        } catch (\Exception $e) {
            Model::handleMaxExecutionTimeError($this->getDb(), $e, '', $dateNowStart, Date::now(), null, 0, ['sql' => $sql]);
            throw $e;
        }
```

Comment (michalkleiner) [reply plugins/Goals/VisitorDetails.php]: Apologies, I know it's still in draft, I'll be logging off for the week so thought might be still worth mentioning.

**Review by mneudert — APPROVED** [review]

**Review by bx80 — APPROVED** [review]
