### PR TITLE
Fix language detection for UI

### LINKED ISSUE #20374: Language is not correctly detected automatically by Matomo
Say you have a language header `zh-CN,zh;q=0.9` and call `Common::extractLanguageAndRegionCodeFromBrowserLanguage()` then Matomo will say it is an invalid language code when it should detect `zh-CN`. As a result, the Matomo UI may not be shown in the correct language and on the Cloud they are receiving emails and UI in English when it should be `zh-cn`.

Similar eg for `pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6`.

### LINKED ISSUE #20388: @$_SERVER['HTTP_ACCEPT_LANGUAGE'] cause error in php >8
in core/common.php the line: $browserLang = self::sanitizeInputValues(@$_SERVER['HTTP_ACCEPT_LANGUAGE']);   
cause the error <<Undefined array key "HTTP_ACCEPT_LANGUAGE">> with some bots.
The @ (silent-mode) do not work longer as expected in php8.

use: if ( is_null($browserLang) && array_key_exists('HTTP_ACCEPT_LANGUAGE', $_SERVER) ) {  ... insted

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

We had been using `Common::extractLanguageCodeFromBrowserLanguage` in some places for detecting the language. As this never includes the region, this kind of disabled detection for languages like `zh-cn`, `pt-br`,...
Using `Common::extractLanguageAndRegionCodeFromBrowserLanguage` solves that problem.

In addition I've also improved the extracting of language & region from language codes. Before we were not handling codes including the script at all. So if someone only provided the language code `zh_Hans_CN`, it would have falled back to `en`, as `zh` only is not available. The script will now be ignored/removed when detecting languages, so `zh_Hans_CN` results in `zh-cn`

fixes #20374 
fixes #20388

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by tsteur — COMMENTED** [review]
Nice one. Thanks for this 🎉 

I assume https://github.com/matomo-org/matomo/blob/4.13.3/core/Common.php#L945-L950 the `extractLanguageCodeFromBrowserLanguage` method needs to stay and only return 2 letter code? Do we maybe need to check the users of that method if they maybe also need to call a different method or maybe we did already? (I see you already changed it in few places). Is that that in tracking we only log 2 character language code?

Be also good to add various tests.

I've got a few potential cases below. May be able to provide next week more if needed

```
            ['en', 'en-US,en;q=0.8,de-DE;q=0.6,de;q=0.4'],
            ['de', 'de-DE;q=0.6,de;q=0.4'],
            ['zh-cn', 'zh-CN,zh;q=0.9'],
            ['fr', 'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3'],
            ['fr', 'fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7'],
            ['de', 'de,en-US;q=0.7,en;q=0.3'],
            ['pt-br', 'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6'],
            ['hi', 'hi;en-US,en;q=0.8,q=0.6'],
            ['ta', 'ta-IN,ta'],
            ['hi', 'hi-in,hi,en-us,en'],
            ['th', 'th-TH,th;q=0.9,en;q=0.8'],
            ['zh-tw', 'zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7'],
            ['fa', 'fa,en-US;q=0.9,en;q=0.8,fa-IR;q=0.7'],
            ['nl', 'nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7'],
            ['it', 'it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7'],
```

**Comment by tsteur** [comment]
Also not sure if we need to make the browser language string lowercase maybe?

File: core/Common.php [hunk 1]
```diff
@@ -966,7 +966,7 @@ public static function extractLanguageAndRegionCodeFromBrowserLanguage($browserL
     {
         $validLanguages = self::checkValidLanguagesIsSet($validLanguages);
 
-        if (!preg_match_all('/(?:^|,)([a-z]{2,3})([-][a-z]{2})?/', $browserLanguage, $matches, PREG_SET_ORDER)) {
+        if (!preg_match_all('/(?:^|,)([a-z]{2,3})(?:[-][a-z]{4})?([-][a-z]{2})?/', $browserLanguage, $matches, PREG_SET_ORDER)) {
```
Comment (tsteur) [inline core/Common.php:970]: not sure if I'm testing it correctly but below string didn't work for me where it maybe should have detect `zh-cn` but didn't

image

Comment (tsteur) [reply core/Common.php:970]: actually it works with `zh-Hans-CN,zh;q=0.9`. I copied it wrongly from the PR description

Comment (sgiehl) [reply core/Common.php:970]: We are using `Common::getBrowserLanguage()` to get the browser language in most cases. That method already replaces `_` with `-` and lowers the string.

**Comment by sgiehl** [comment]
Yes `extractLanguageCodeFromBrowserLanguage` is still used for archiving. As we only use two letter codes for the language reports.

Where ever the language is detected for UI I changed it to use `extractLanguageAndRegionCodeFromBrowserLanguage` instead. That should fix any issues around language codes containing a region, like `pt-BR` or `zh-TW`

File: core/Common.php [hunk 2]
```diff
@@ -982,10 +982,6 @@ public static function extractLanguageAndRegionCodeFromBrowserLanguage($browserL
                 if (in_array($langIso639 . $regionIso3166, $validLanguages)) {
```
Comment (bx80) [inline core/Common.php]: Some of the `testExtractLanguageAndRegionCodeFromBrowserLanguage` tests are currently failing because the test data doesn't include the language.region in the valid language array, so the method is unable on this line.

For example, data from the first test is:
```
// browser language, valid languages, expected
['fr-ca',            ['fr'],          'fr-ca'],
```
The test should return 'fr-ca' but is unable to because this is not in the valid languages array, so it returns 'fr' instead and the test fails.

The test data could be updated to `['fr-ca', ['fr', 'fr-ca'], 'fr-ca']` to ensure it choose the region version correctly.

**Review by bx80 — CHANGES_REQUESTED** [review]
I noticed the method description for `Common::extractLanguageCodeFromBrowserLanguage()` incorrectly states that it returns the language and region string. Could this method perhaps be deprecated or a note added suggesting that `extractLanguageAndRegionCodeFromBrowserLanguage()` should normally be used instead?

File: core/Common.php (hunk 2 above)
Comment (sgiehl) [reply core/Common.php]: Actually the use cases of the method `extractLanguageAndRegionCodeFromBrowserLanguage` are a bit weird.
It accepts a `validLanguages` parameters, but still might return any of the provided languages with an additional region.
I've now changed that behaviour. If valid languages are provided only a code can be returned that exactly matches one of the entries. Otherwise it returns a code if the language is in the list of all valid languages, possibly extended by the region.

**Review by bx80 — APPROVED** [review]
* [x] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [x] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [x] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [x] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [x] n/a [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [x] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [x] Tests updated [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [x] none [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [x] n/a [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [x] n/a [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [x] n/a Existing documentation updated if needed
