### PR TITLE
Never send a user creation email to anonymous user

### LINKED ISSUE #22068: [Bug] Do not send Notification Email to anonymous user
### What happened?

If users are created from a plugin (e.g. OIDC), the system sends user creation notifications to the anonymous user (anonymous@example.org).

### What should happen?

Do not send Emails to the anonymous user.

### How can this be reproduced?

Use a plugin, that internally creates users, e.g. OIDC or SAML. If you watch the smtp log on the server, you can see, that there is an email send to the anonymous user's email address, which is anonymous@example.org by default.
This seems to be the reason - if not a user, but the system itself creates a user, it falls back to anonymous: 

https://github.com/matomo-org/matomo/blob/1eebd5d3f0f26e392e9c6d084000735ac8800259/core/Piwik.php#L251-L259

### Matomo version

all

### PHP version

_No response_

### Server operating system

_No response_

### What browsers are you seeing the problem on?

_No response_

### Computer operating system

_No response_

### Relevant log output

_No response_

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

When a user is created (not invited), a notification mail is sent to the user, who created the new one.
This currently also happens when users are created by the system (e.g. through plugins or commands).
In this case no user is currently logged in, causing the email being send to the anonymous user.
This PR will avoid this.

fixes #22068

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/UsersManager/Repository/UserRepository.php [hunk 1]
```diff
@@ -126,12 +126,14 @@ public function generateInviteToken(string $userLogin, $expiryInDays = null): st
 
     protected function sendUserCreationNotification(string $createdUserLogin): void
     {
-        $mail = StaticContainer::getContainer()->make(UserCreatedEmail::class, [
-            'login'        => Piwik::getCurrentUserLogin(),
-            'emailAddress' => Piwik::getCurrentUserEmail(),
-            'userLogin'    => $createdUserLogin,
-        ]);
-        $mail->safeSend();
+        if (Piwik::getCurrentUserLogin() !== 'anonymous') {
```
Comment (michalkleiner) [inline plugins/UsersManager/Repository/UserRepository.php:129]: Just a thought — should the responsibility be on this method or on the places where it's called from?

Comment (sgiehl) [reply plugins/UsersManager/Repository/UserRepository.php:129]: As that email should never be sent out to the anonymous user, I think it makes more sense to catch that here. Otherwise it can easily regress when this method is called from somewhere else for some reason.

**Review by michalkleiner — APPROVED** [review]
Is there a test to adjust/add to check this behaviour doesn't regress in future? If not then good to go.
