### PR TITLE
Fix skip-to-content link

### LINKED ISSUE #23060: [Bug] Accessibility: Skip to content broken
### What happened?

The skip to content link, which exists to improve accessibility, is broken, and using that renders empty pages.

The code is part of the CoreHome-plugin

### What should happen?

When using skip to content link, you should be able to jump to reports etc.

### How can this be reproduced?

Go to: https://demo.matomo.cloud
Click in the top banner area. Hit tab. You should now see the "Skip to content"-link. Press enter or click. You will now get an empty reports page.

### Matomo version

5.2.2

### PHP version

_No response_

### Server operating system

_No response_

### What browsers are you seeing the problem on?

_No response_

### Computer operating system

_No response_

### Relevant log output

```shell

```

### Validations

- [x] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [x] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [x] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

The skip to content link is currently broken, as our internal handling of the url hash breaks the link.
This PR replaces the handling to use pure javascript for that link instead.

fixes #23060

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/CoreHome/vue/src/MatomoUrl/MatomoUrl.ts [hunk 1]
```diff
@@ -54,7 +54,23 @@ class MatomoUrl {
...
+      // However, in some cases, like the skip to content link, we want a hash link to act like a
+      // jump-to mark. Therefor we first check if the new hash looks like an anchor/id to jump to
+      // if an element with that id / link with that name exists, we scroll it into view and reset
+      // the changed hash in the url.
+      if (
+        newUrl.hash.match(/^#[a-z0-9_-]+$/i)
+        && $(`${newUrl.hash},a[name=${newUrl.hash.substring(1)}]`).length
+      ) {
+        $(`${newUrl.hash},a[name=${newUrl.hash.substring(1)}]`)[0].scrollIntoView();
+        window.location.href = event.oldURL;
```
Comment (mneudert) [inline plugins/CoreHome/vue/src/MatomoUrl/MatomoUrl.ts]: Can this have some really ugly side effects? :thinking: 

For example the inline link for image tracking in the javascript tracking code generator:

https://github.com/matomo-org/matomo/blob/9a3ef94df61682e7d543f3f8b438c368f6eb71a6/plugins/CoreAdminHome/vue/src/JsTrackingCodeGenerator/JsTrackingCodeGenerator.vue#L213-L219

The actual section links at the top are always going to `#/section`, not just `#section`. That one inline link now goes to the actual anchor, and if you have any other section in your hash, like `#/react`, the change back to the previous hash will also trigger a scroll to the previous section.

Now this is a simple one to fix (just update the inline anchor link), but maybe there are more places that would actually break when cycling hashes?

Comment (sgiehl) [reply plugins/CoreHome/vue/src/MatomoUrl/MatomoUrl.ts]: Would it make sense to check if the previous hash was something containing `=` or `&` and only do it in that case? 🤔

Comment (mneudert) [reply plugins/CoreHome/vue/src/MatomoUrl/MatomoUrl.ts]: Ideally I would say we replace the skip-to-content link with a pure JS implementation: focus the main element, scroll that element into view, don't use any hash manipulation.

If that is sufficient for accessibility we wouldn't need to change any hashes around :thinking:

Comment (michalkleiner) [reply plugins/CoreHome/vue/src/MatomoUrl/MatomoUrl.ts]: I would probably also vote for not updating the hash in the actual URL in browser and just do the scrolling via JS.

**Comment by michalkleiner** [comment]
@sgiehl it might be out of scope for the fix here - creating a `v-skip-link="main"` Vue directive that takes the target anchor as its binding value could be a nice reusable approach, rather than needing to remember that skip links need a custom JS in their href attribute.

**Comment by sgiehl** [comment]
> @sgiehl it might be out of scope for the fix here - creating a v-skip-link="main" Vue directive that takes the target anchor as its binding value could be a nice reusable approach, rather than needing to remember that skip links need a custom JS in their href attribute.

@michalkleiner My previous solution was exactly meant to be able to handle anything without having to think about it. If you don't have in mind that skip links need a custom handling you will also forget about adding a directive. 🤷 
Also the skip to content link is rendered within pure HTML at the moment, so to allow it using a directive we would need to add additional javascript to parse that part. So we will now go with this simple fix you both requested.

**Comment by michalkleiner** [comment]
Fair enough 👍  I don't think either of us thought the reusability of the previous solution was an issue, it was the URL manipulation.

**Review by michalkleiner — APPROVED** [review]
