### PR TITLE
Ensure DNS records are only requested for IP allowlist when needed

### LINKED ISSUE #18244: Ensure DNS records are only requested for IP allowlist when needed
## Expected Behavior

No DNS Request for network entries just for hostnames in login_whitelist_ip/login_allowlist_ip

## Current Behavior

All entries in login_whitelist_ip/login_allowlist_ip for networks that was specified with an "/" are attempted to be resolved using DNS. 
For Example: 
We have "192.168.50.0/24" in our login_whitelist_ip/login_allowlist_ip. Now our DNS Server recivies a ton of request (around 175000 per day) trying to resolve a IP for hostname "192.168.50.0/24" and "192.168.50.0/24.ourdomain.com"

login_whitelist_ip/login_allowlist_ip still is working as expected.
We have this issue since our update to matomo 4.5.0

## Possible Solution

Don't try to resolve a DNS Name for a network.

## Steps to Reproduce (for Bugs)

1. Enter a "/x" Network into login_whitelist_ip or login_allowlist_ip like "192.168.50.0/24"
2. Check all DNS Request send by Matomo

## Your Environment

* Matomo Version: 4.5.0
* PHP Version: 7.4
* Server Operating System: Ubuntu 20.04.3 LTS

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

- only request dns records if it's not an IP range
- cache DNS results for 30 seconds to reduce DNS requests

Note: Tracking requests never go through the allow-list, as that's excluded here: https://github.com/matomo-org/matomo/blob/bc75f9dafc9287a7864f3ecd556a5ae6b699546a/plugins/CoreHome/CoreHome.php#L78-L81

fixes #18244

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: config/global.php [hunk 1]
```diff
@@ -167,19 +167,24 @@
 
         foreach ($ips as $ip) {
             $ip = trim($ip);
-            if (filter_var($ip, FILTER_VALIDATE_IP)) {
+            if (filter_var($ip, FILTER_VALIDATE_IP) || \Matomo\Network\IPUtils::getIPRangeBounds($ip) !== null) {
```
Comment (tsteur) [inline config/global.php:170]: can we add a test for this one @sgiehl ?

File: config/global.php [hunk 2]
```diff
@@ -167,19 +167,24 @@
...
-                    // we don't check using filter_var if it's an IP as "gethostbyname" will return the $ip if it's not a hostname
-                    // and we then assume it is an IP range. Otherwise IP ranges would not be added. Ideally would above check if it is an
-                    // IP range before trying to get host by name.
+                if (!empty($ipFromHost) && $ipFromHost !== $ip) {
                     $ipsResolved[] = $ipFromHost;
                 } 
                 
                 if (function_exists('dns_get_record')) {
-                    $entry = @dns_get_record($ip, DNS_AAAA);
+                    $lazyCache = \Piwik\Cache::getLazyCache();
```
Comment (tsteur) [inline config/global.php]: Can we also cache `gethostbyname` as I would assume it's equally "slow" and can add load for DNS when it resolves IPv4 there?

File: config/global.php [hunk 3]
```diff
@@ -167,19 +167,24 @@
...
+                    $cacheKey = 'DNS.' . md5($ip);
+                    if ( !$lazyCache->contains($cacheKey) ) {
```
Comment (tsteur) [inline config/global.php]: Using the `contains` can maybe cause a bit of a race condition. As when we fetch the entry, the cache might be already outdated. Also `contains` already does a `fetch` I believe (not 100% sure) so we might actually fetch the cache twice in the end. I wonder if we can fetch the cache here using `$entry = $lazyCache->fetch($cacheKey);` and then only get the value if none is there yet?

**Review by tsteur — CHANGES_REQUESTED** [review]
Works overall @sgiehl . Few tweaks be needed though.

**Comment by sgiehl** [comment]
@tsteur Thanks for the suggestions. I've updated the code accordingly.

**Comment by tsteur** [comment]
Works 🚀
