### PR TITLE
Make BulkTracking plugin always activated

### LINKED ISSUE #14553: mark BulkTracking plugin as required, not deactivable
Well this was unexpected. Troubleshooting another problem, I decided to upgrade Matomo to the latest beta. It's not a huge installation, so I used update option inside the dashboard. Everything went smoothly, until I logged back in. Now all sites show "No data has been recorded yet".

At first I thought data was wiped. So I went through the database and it does appear data is in the database, but for some reason Matomo isn't recognizing it anymore. The table prefix is correct in the config file, piwik_

It's only tracking data that's not showing up. Websites are still listed, settings are being saved, etc.

I tried running CLI command to reprocess data, that didn't help.

Few details:
- We only import logs into Matomo. No client-side tracking.
- All system checks are good
- PHP 7.2.14
- MariaDB 10.3.12

This is a list of plugins we've deactivated:
```
Annotations
BulkTracking
Contents
CustomPiwikJs
CustomVariables
DBStats
DevicePlugins
DevicesDetection
Ecommerce
Events
ExampleAPI
ExampleCommand
ExampleLogTables
ExamplePlugin
ExampleReport
ExampleSettingsPlugin
ExampleTracker
ExampleUI
ExampleVisualization
Feedback
GeoIp2
Goals
IntranetMeasurable
Live
MobileAppMeasurable
ProfessionalServices
Provider
Resolution
SegmentEditor
TagManager
UserCountry
UserCountryMap
UserId
Widgetize
```

Here's a screenshot of what I'm seeing in database:
12155597-f373-4bc0-8a81-b75901242552

Any ideas?

### PR DESCRIPTION
**Pull request by katebutler**
Fixes #14553

### CODE REVIEW

File: core/Plugin/Manager.php [hunk 1]
```diff
@@ -70,6 +70,7 @@ public static function getInstance()
 
     // These are always activated and cannot be deactivated
     protected $pluginToAlwaysActivate = array(
+        'BulkTracking',
```
Comment (sgiehl) [inline core/Plugin/Manager.php]: Doesn't the plugin need to be added to the list in `global.ini.php` instead?

Comment (tsteur) [reply core/Plugin/Manager.php]: It's about making sure it is always activated and not be able to be deactivated. AFAIK it is in global.ini.php already. Or not sure if you mean something else?

Comment (sgiehl) [reply core/Plugin/Manager.php]: Ah sure. I misread the title :see_no_evil:
