### PR TITLE
Fix some UI tests, including random failure + allow --piwik-domain use in tests:run-ui

### LINKED ISSUE #13026: Missing translation key on help page
Translation key has be changed/removed, but is still in use.

image

Regression from #12958

### PR DESCRIPTION
**Pull request by diosmosis**
Changes:
* Fix regression in feedback form, translation key was not updated in twig template.
* Pass --piwik-domain in tests:run-ui to phantomjs and in phantomjs to tests:setup-fixture.
* In TestsSetupFixture fix incorrect `unlink()` call that deleted the link target instead of the link.
* Prevent random failure in dashboard w/ realtimemap by applying same query params to normal realtime map UI test.

fixes #13026

### CODE REVIEW

File: tests/PHPUnit/Fixtures/UITestFixture.php [hunk 1]
```diff
@@ -24,6 +24,8 @@
 use Piwik\Plugins\SitesManager\API as SitesManagerAPI;
 use Piwik\Plugins\VisitsSummary\API as VisitsSummaryAPI;
 use Piwik\Config as PiwikConfig;
+use Piwik\SettingsPiwik;
+use Piwik\SettingsServer;
```
Comment (sgiehl) [inline tests/PHPUnit/Fixtures/UITestFixture.php]: Guess those use statements are unneeded
