### PR TITLE
Make PHP tracking client PiwikTracker available through composer

### LINKED ISSUE #9349: Handle submodules via composer and checkout correct submodules when changing branch
Sorry for commenting on the existing issue, I didn't want to open a new one if you planned to work there since it's an identical bug to #6906 just in 2.15.0.

I installed Piwik using `composer`. Originally, all my widgets were erroring (like #6906) and many pages were also erroring. I disabled `CustomVariables` per the other bug, and that fixed my issue.

I just re-enabled it for this bug, and my widgets seem to be working now actually, but all the erroring pages still error.

```
2015/12/07 13:41:28 [error] 11289#11289: *44252 FastCGI sent in stderr: "PHP message: PHP Fatal error:  require_once(): Failed opening required '/home/john/www/analytics.leftforliving.com/libs/PiwikTracker/PiwikTracker.php' (include_path='/home/john/www/analytics.leftforliving.com/vendor/pear/pear_exception:/home/john/www/analytics.leftforliving.com/vendor/pear/console_getopt:/home/john/www/analytics.leftforliving.com/vendor/pear/pear-core-minimal/src:/home/john/www/analytics.leftforliving.com/vendor/pear/archive_tar:/home/john/www/analytics.leftforliving.com/vendor/phpseclib/phpseclib/phpseclib:.:/usr/share/php:/usr/share/pear') in /home/john/www/analytics.leftforliving.com/plugins/CustomVariables/Archiver.php on line 19" while reading response header from upstream, client: 68.62.16.159, server: analytics.leftforliving.com, request: "POST /index.php?date=yesterday&module=VisitsSummary&action=index&idSite=1&period=day HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "analytics.leftforliving.com", referrer: "https://analytics.leftforliving.com/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday"
```

The file it's looking for does not seem to exist:

```
root@dib:/home/john/www/analytics.leftforliving.com# ls libs/PiwikTracker/
root@dib:/home/john/www/analytics.leftforliving.com# 
```

Erroring pages:
 - Visitors > Overview
 - Visitors > Custom Variables
 - Visitors > Engagement
 - Actions > Site search
 
Thank you for the great piece of software!

### PR DESCRIPTION
**Pull request by johnmaguire**
I am closing the pull request at #9353 as this supercedes it.

I wanted to post this pull request now for comments, although piwik/piwik-php-tracker#16 should be taken care of prior to this being merged. Additionally, once the new release is made, `composer update piwik/piwik-php-tracker` should be run again so that the dependency is up-to-date.

This allows PiwikTracker to be installed via the normal composer installation route (see #9349).

While there are still some submodules inside of piwik/piwik, none seem to be creating issues in my installation other than this missing dependency. :+1: 

I was unable to find information on recommended coding style, etc. so I went with my gut. If anything needs to be changed, simply let me know. :)

### CODE REVIEW

**Comment by JohnMaguire** [comment]
Example of the redirection:

```
jmaguire@Styx [09:37:26] [~/repos/piwik] [bugfix/9349-composer-installation-of-piwik-tracker *]
-> % cat test.php
<?php

require_once __DIR__ . '/libs/PiwikTracker/PiwikTracker.php';

var_dump(class_exists('PiwikTracker'));
jmaguire@Styx [09:37:31] [~/repos/piwik] [bugfix/9349-composer-installation-of-piwik-tracker *]
-> % php test.php
bool(true)
```

Also, I chose to use __DIR__ over PIWIK_INCLUDE_PATH, as I wasn't sure every file including `PiwikTracker.php` had that constant defined.

**Comment by JohnMaguire** [comment]
And with this change, I think `composer create-project piwik/piwik` becomes a valid installation route. :)

**Comment by JohnMaguire** [comment]
I will note, there could still be some value in #9353 as far as checking out the remaining (albeit optional) submodules goes. However, the error message should probably give a better explanation if that does ever get merged.

**Comment by JohnMaguire** [comment]
(Integration tests failed due to https://github.com/piwik/piwik-php-tracker/issues/16. Once `composer.lock` is updated with the new release, `doPing()` should exist.)

**Comment by JohnMaguire** [comment]
@tsteur Thanks for the version tag. :) The pull request should be ready to go now.

**Comment by tsteur** [comment]
Thx for this @JohnMaguire That was really fast :) It looks good to merge to me, and tests succeed. @mattab @diosmosis can you maybe think of any downsides by this approach or of any use cases where it wouldn't work? 

Definitely we need to update piwik-package the build script I think

**Comment by mattab** [comment]
Looks good to me @JohnMaguire @tsteur 

The PR needs a rebase (`This branch has conflicts that must be resolved`) and then +1 to merge!

File: libs/PiwikTracker/PiwikTracker.php [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+ * @link http://piwik.org
+ * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
+ *
+ */
+
+// PiwikTracker.php is now managed by composer. To prevent breaking existing
+// code, this file has been left as a redirect to its new location in the
+// vendor directory.
+if (!class_exists('PiwikTracker')) {
+    require_once __DIR__ . '/../../vendor/piwik/piwik-php-tracker/PiwikTracker.php';
```
Comment (mattab) [inline libs/PiwikTracker/PiwikTracker.php]: To play it safe, and prevent issue in case someone changes the constraint in composer.json to later include eg. 2.0 release, could you here add a sanity check eg. 
```php
if(PiwikTracker::VERSION !== 1) { 
    throw new Exception("Expected PiwikTracker in libs/PiwikTracker/PiwikTracker.php to be version 1 for keeping backward compatibility. ");
}

```

**Comment by JohnMaguire** [comment]
Did the rebase, updated piwik/piwik-php-tracker to v1.0.1, and added the exception. :)

**Comment by tsteur** [comment]
Thx for this :+1:
