### PR TITLE
Redirect to a different site if deleting idSite in URL

### LINKED ISSUE #12617: When a user deletes a site that is currently selected in the URL, need to redirect another URL
For example open `index.php?module=SitesManager&action=index&idSite=2&period=day&date=yesterday&showaddsite=false&updated=1`

Now delete site 2, and then move for example to Custom Dimensions manage page (`/index.php?module=CustomDimensions&action=manage&idSite=2&period=day&date=yesterday&showaddsite=false`). A fatal error will occur because the site cannot be found.

> Error: {"message":"Variable \"topMenu\" does not exist.","file":"\/home\/innocraft-cloud-mercury\/www\/*.innocraft.cloud\/plugins\/CoreHome\/templates\/_topBar.twig","line":1}

### PR DESCRIPTION
**Pull request by diosmosis**
Avoids later errors if user clicks on a link w/ the invalid idSite.

Fixes #12617 

@matomo-org/core-team  I wonder if it would also be good not to swallow this exception: https://github.com/matomo-org/matomo/blob/3.x-dev/core/Plugin/Controller.php#L133
The error would have made a lot more sense to me w/ an "invalid idSite" message.

TODO:
* [ ] check if this solves the cloud issue, perhaps by patching staging

### CODE REVIEW

File: plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js [hunk 1]
```diff
@@ -187,6 +187,16 @@
         };
 
         var deleteSite = function() {
+            var redirectParams = $scope.redirectParams;
+
+            // if the current idSite in the URL is the site we're deleting, then we have to make to change it. otherwise,
+            // if a user goes to another page, the invalid idSite may cause a fatal error.
+            if (broadcast.getValueFromUrl('idSite') === $scope.site.idsite) {
+                var site = $scope.adminSites.sites.find(function (site) { return site.idsite !== $scope.site.idsite });
```
Comment (tsteur) [inline plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js]: I think `.find` might not be available eg in IE10

Comment (diosmosis) [reply plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js]: 👍 will fix

Would be great to use something like babel-polyfill in the future :)

**Comment by diosmosis** [comment]
Updated

File: plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js [hunk 2]
```diff
@@ -187,6 +187,25 @@
         };
 
         var deleteSite = function() {
+            var redirectParams = $scope.redirectParams;
+
+            // if the current idSite in the URL is the site we're deleting, then we have to make to change it. otherwise,
+            // if a user goes to another page, the invalid idSite may cause a fatal error.
+            if (broadcast.getValueFromUrl('idSite') === $scope.site.idsite) {
```
Comment (tsteur) [inline plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js]: You need a lose check using `==` instead of `===`. I tested it with Mysqli adapter and didn't work because with Mysqli it is an integer and not a string. Using `==` works.

File: plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js [hunk 3]
```diff
@@ -187,6 +187,25 @@
...
+                var sites = $scope.adminSites.sites;
+
+                var otherSite;
+                for (var i = 0; i !== sites.length; ++i) {
+                    if (sites[i].idsite !== $scope.site.idsite) {
```
Comment (tsteur) [inline plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js]: same here you need to use `!=`

**Comment by tsteur** [comment]
I think it might make still sense to swallow this exception, or not really sense but might cause many other random bugs we cannot foresee so better to maybe just keep it now 👍

File: plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js (hunk 2 above)
Comment (diosmosis) [reply plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js]: Argh, that's annoying. I think I'll convert the idsite to string, since it's considered bad practice to use `==` in JS (which I'm sure you're aware :) ). (Unless you have an objection.)

Comment (tsteur) [reply plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js]: Where would you cast it to string? It's fine by me but would personally just use `==`. Of course it is a bad practice but it doesn't mean it should never be used or something just for the sake of it. In this case, we know idSite is eg never `0` or something and it doesn't really cause any difference to use `==` vs `===`. Might be easier to implement and read in this case. Up to you though.

Comment (diosmosis) [reply plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js]: Yes, but pretty much every linter will complain about that and some transpilers like coffeescript will convert `==` to `===` implicitly. It's really not accepted by the community (not that I'm saying it shouldn't be accepted or anything, it's the opposite in the PHP community), but using it in JS is kind of like adding technical debt, since it will be something that we'd have to change when moving to more modern toolchains. Different languages, different standards.

What I was going to do is just cast `$scope.site.idsite` to string, ie `var currentSite = '' + $scope.site.idsite;` w/ a comment about mysqli.

Comment (tsteur) [reply plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js]: We're not using coffeescript and neither transpile anything etc ;) but totally fine to add the casting as long as it is always updated etc

Comment (diosmosis) [reply plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js]: Not yet, but if matomo ever decides to move to Angular 2, we're going to have to start. But I'll just use `==`. If it inspires this much discussion, then I'd rather be on the same page as my teammates then do something that isn't considered a matomo standard :)

Comment (tsteur) [reply plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js]: As said it's all fine to cast ;) When/if we move to angular we will have to fix things everywhere anyway and already cast the output in the API to work with consistent types independent of DB adapter. If it's only a one liner and doesn't break anything else it should be all good to cast.

**Comment by diosmosis** [comment]
Updated.

**Review by tsteur — APPROVED** [review]
