### PR TITLE
Lock when archiving and avoid invalidating sites that have archiving in progress

### LINKED ISSUE #15170: Wrong data in visitors overview over time
In Matomo 3.12.0 a bug appeared that i have described here:
https://forum.matomo.org/t/visitors-overview-not-updating/34804/7

### PR DESCRIPTION
**Pull request by diosmosis**
When archiving for a site begins, we create a Lock and only release when archiving finishes or fails.

The lock's expire time is updated on each query (the TTL can be configured via DI).

There is also a change to log each archiving query (previously this was just in LogAggregator, but now it will affect all archivers).

I think we should deploy this to demo and see if it works after a day or two (after getting tests to pass of course).

Note: with this implementation it's possible for archiving to start while an invalidation is occurring, which would cause issues. I'm not sure how big of a risk it is since the invalidation queries are fairly simple. There could be a few of them though.

Fixes #15170

### CODE REVIEW

File: core/ArchiveProcessor/Loader.php [hunk 1]
```diff
@@ -73,12 +77,21 @@ private function prepareArchiveImpl($pluginName)
...
-            return $idArchive;
+        try {
+            list($visits, $visitsConverted) = $this->prepareCoreMetricsArchive($visits, $visitsConverted);
+            list($idArchive, $visits) = $this->prepareAllPluginsArchive($visits, $visitsConverted);
+
+            if ($this->isThereSomeVisits($visits) || PluginsArchiver::doesAnyPluginArchiveWithoutVisits()) {
+                return $idArchive;
+            }
+        } finally {
+            $archivingStatus->archiveFinished($lock);
```
Comment (tsteur) [inline core/ArchiveProcessor/Loader.php]: fyi `archiveFinished ` does not take an argument  and above the `archiveStarted ()` does not return a value

File: core/Archive/ArchiveInvalidator.php [hunk 2]
```diff
@@ -206,7 +213,11 @@ public function markArchivesAsInvalidated(array $idSites, array $dates, $period,
             $periodDates = $this->getPeriodDatesByYearMonthAndPeriodType($periods);
         }
 
+        // TODO: it's possible an archiving request could begin during invalidation, though probably unlikely that it would cause true disruption... just note in issue.
+
         $periodDates = $this->getUniqueDates($periodDates);
+
+        $idSites = $this->removeSitesWithInProgressArchiving($idSites);
```
Comment (tsteur) [inline core/Archive/ArchiveInvalidator.php]: @diosmosis not sure I understand why we would filter the idSites here and not just invalidate all of them? Is this because we assume they were already invalidated / will be invalidated? Would there be any harm in still invalidating them or the issue that this would cause the remember flag to be removed?

File: core/Concurrency/Lock.php [hunk 3]
```diff
@@ -21,12 +21,19 @@ class Lock
...
-    public function __construct(LockBackend $backend, $lockKeyStart)
+    public function __construct(LockBackend $backend, $lockKeyStart, $defaultTtl = null)
     {
         $this->backend = $backend;
         $this->lockKeyStart = $lockKeyStart;
         $this->lockKey = $this->lockKeyStart;
+        $this->defaultTtl = $defaultTtl;
+    }
+
+    public function reexpireLock()
```
Comment (tsteur) [inline core/Concurrency/Lock.php]: should it be maybe `reExpireLock`? Not too important though...

File: core/DataAccess/LogAggregator.php [hunk 4]
```diff
@@ -1160,6 +1159,9 @@ public static function makeArrayOneColumn($row, $columnName, $lookForThisPrefix
 
     public function getDb()
     {
-        return Db::getReader();
+        /** @var ArchivingStatus $archivingStatus */
+        $archivingStatus = StaticContainer::get(ArchivingStatus::class);
+        $archivingLock = $archivingStatus->getCurrentArchivingLock();
+        return new ArchivingDbAdapter(Db::getReader(), $archivingLock, $this->logger);
```
Comment (tsteur) [inline core/DataAccess/LogAggregator.php]: @diosmosis is there a chance you forgot to commit this file?

File: core/Archive/ArchiveInvalidator.php (hunk 2 above)
Comment (tsteur) [reply core/Archive/ArchiveInvalidator.php]: I wonder maybe we could still invalidate archives for the other idSites as well just not remove the remember flag?

**Review by tsteur — CHANGES_REQUESTED** [review]
@diosmosis left few comments.  Be good in general to test this on demo for few days.

File: core/Archive/ArchiveInvalidator.php (hunk 2 above)
Comment (diosmosis) [reply core/Archive/ArchiveInvalidator.php]: We remove them because we know they are currently being archived. We also keep the idSites in the remember flags so they will eventually be invalidated when they are not being archiving.

File: core/Concurrency/Lock.php (hunk 3 above)
Comment (diosmosis) [reply core/Concurrency/Lock.php]: Yeah, it looks weird to me too. But so did `reExpireLock` and I couldn't choose :)

File: core/DataAccess/LogAggregator.php (hunk 4 above)
Comment (diosmosis) [reply core/DataAccess/LogAggregator.php]: a chance? no... I definitely forgot to commit it :) added now

File: core/ArchiveProcessor/Loader.php (hunk 1 above)
Comment (diosmosis) [reply core/ArchiveProcessor/Loader.php]: fixed

**Comment by diosmosis** [comment]
I'll add this to demo soon

File: core/Archive/ArchiveInvalidator.php (hunk 2 above)
Comment (tsteur) [reply core/Archive/ArchiveInvalidator.php]: Just wondering if there could be meanwhile some other previously finished archives for those idSites that need to be invalidated?

Comment (diosmosis) [reply core/Archive/ArchiveInvalidator.php]: There could be, but because of the way the function parameters are (idSites + list of dates + period type), it's a bit harder to control exactly what to invalidate. We'd have to loop over idSites & dates and check each individually, and invalidate each archive individually instead of with one query (which is what we do now I think).

Comment (tsteur) [reply core/Archive/ArchiveInvalidator.php]: Not sure I understand... it would be safe to invalidate all the data related to that site/period and all parent periods as long as we keep the remember flag? Or would there be an issue?

Comment (diosmosis) [reply core/Archive/ArchiveInvalidator.php]: The issue is if we invalidate while archiving is ongoing, then it's possible for archives to re-initiate archiving for child periods re-doing archiving unnecessarily.

Eg, if the week period initiates archiving and finishes, then a day in the week is invalidated, and the month period starts archiving, it will re-archive the month and the day. Since we invalidate on new visits, this means for high traffic sites we'll always re-archive these subperiods as soon as an archive request goes through (since invalidation is not just done in core:archive but in Archive.php).

Comment (tsteur) [reply core/Archive/ArchiveInvalidator.php]: Isn't that though what we still want it to behave? Whether it will be rearchived right away depends on `time_before_today_archive_considered_outdated` and `time_before_week_archive_considered_outdated` etc in that case or does it behave differently? I'm not sure how it behaves when data is invalidated... whether it still takes those values into consideration

Comment (diosmosis) [reply core/Archive/ArchiveInvalidator.php]: That's used by `getMinTimeProcessedForTemporaryArchive()` which is no longer used because we got rid of temporary archives... I guess we can re-add that logic?

Comment (diosmosis) [reply core/Archive/ArchiveInvalidator.php]: Incidentally I don't see `time_before_week_archive_considered_outdated` being used anywhere.

Comment (diosmosis) [reply core/Archive/ArchiveInvalidator.php]: @tsteur Ok I found where the period configs are used but they're not used anymore either because of the temporary archive change. This is likely the cause of the bug, and probably a less overarching change.

However, the lock does allow telling if a specific archive is being built (well not quite, but we can modify it if we increase the lock key column length). What do you think should happen? Make sure the time_before_ INI config is used now and keep the locks but don't do anything different in ArchiveInvalidator?

Comment (tsteur) [reply core/Archive/ArchiveInvalidator.php]: @diosmosis it is very important we respect these configured values. We basically need to check if the last archive was done more than the configured time ago even if the archive is invalid (unless the archive is invalid and it is a new day I think then we don't respect these values but not sure? @mattab )

> and keep the locks but don't do anything different in ArchiveInvalidator?
I'm not quite fully understand this part but be good in general to maybe still invalidate an archive in ArchiveInvalidator? Not sure of consequences of not using Locks?

Comment (diosmosis) [reply core/Archive/ArchiveInvalidator.php]: > Not sure of consequences of not using Locks?

It's just an easy way to check if an archive is on-going no matter what machine/process it's on. It's not really necessary, but it might be useful in the future.

Comment (tsteur) [reply core/Archive/ArchiveInvalidator.php]: I reckon be good to keep it 👍

Comment (mattab) [reply core/Archive/ArchiveInvalidator.php]: > It's just an easy way to check if an archive is on-going no matter what machine/process

@diosmosis it would be big value if it would help with this issue: https://github.com/matomo-org/matomo/issues/8444 -> maybe it would be fixed?

> unless the archive is invalid and it is a new day I think then we don't respect these values but not sure? @mattab

correct, these INI settings are only used when the date range includes Today.

Comment (tsteur) [reply core/Archive/ArchiveInvalidator.php]: just wanting to make sure we're not going to work on #8444 as part of this issue :)

**Comment by diosmosis** [comment]
@tsteur added back old functions and added a test for the Loader method that uses them

**Comment by tsteur** [comment]
@diosmosis maybe we can run this code on demo for a while?

**Comment by diosmosis** [comment]
@tsteur it should be running on demo2

**Comment by tsteur** [comment]
@diosmosis do you know of any issue on the demo? Maybe we could merge and release a new beta?

**Comment by diosmosis** [comment]
The metrics for the last two week seem accurate, I'm not aware of any issues (though I don't get emails if demo2 has an issue).

**Comment by mattab** [comment]
There was no error from demo2 in the last few days. @tsteur @diosmosis can you merge this and let me know, i'll release the next beta?
