### PR TITLE
Provide task to find/purge broken archives

### LINKED ISSUE #22450: Provide task to find/purge broken archives
**tldr;:** It can happen that the archive tables contain broken archives (archives without an associated "done" flag). A maintenance task to purge those broken archives should be available.

---

For bigger instances it is not uncommon to run archiving on multiple servers concurrently.

Due to the way intersecting period archiving is detected (see #22394), it can happen that higher periods are being archived before all lower periods are finished. For example a week is being archived before all individuals days are done.

One way to detect if an instance is affected by that behaviour is to check the archiving logs for the following pattern (example requires `--verbose` output):

```
Server 1 - INFO  [2024-07-11 18:00:00] Archived website id 2, period = day, date = 2024-07-10, ... Time elapsed: 21600s
Server 3 - DEBUG [2024-07-11 16:00:00] Starting archiving for ...idSite=2&period=month&date=2024-07-01...
Server 2 - DEBUG [2024-07-11 14:00:00] Starting archiving for ...idSite=2&period=week&date=2024-07-08...
Server 1 - DEBUG [2024-07-11 12:00:00] Starting archiving for ...idSite=2&period=day&date=2024-07-10...
```

This is an example of a setup with 3 archiving servers. By chance both week and month were started before the day archive was completed.

Depending on how the timing of the concurrent archiving processes works out, it can happen that an archive is getting detected as "outdated, not to be used anymore" before the archiving process writing to that archive is actually finished. And then it may happen that more metrics are written to that archive but no "done" flag exists anymore.

To detect if an instance is affected by that problem, the following SQL query/queries can be used (example only checks for day periods):

```
mysql> SELECT date1, COUNT(DISTINCT idarchive) FROM archive_numeric_2024_07 WHERE period = 1 AND idarchive NOT IN (SELECT DISTINCT idarchive FROM archive_numeric_2024_07 WHERE period = 1 AND name LIKE 'done%') GROUP BY date1;

+------------+---------------------------+
| date1      | COUNT(DISTINCT idarchive) |
+------------+---------------------------+
| 2024-07-01 |                         5 |
| 2024-07-02 |                         4 |
| 2024-07-03 |                         6 |
| 2024-07-04 |                        10 |
+------------+---------------------------+

mysql> SELECT DISTINCT idarchive, date1 FROM archive_numeric_2024_07 WHERE period = 1 AND idarchive NOT IN (SELECT DISTINCT idarchive FROM archive_numeric_2024_07 WHERE period = 1 AND name LIKE 'done%');

+-----------+------------+
| idarchive | date1      |
+-----------+------------+
|      1234 | 2024-07-01 |
|      2345 | 2024-07-01 |
|      3456 | 2024-07-01 |
+-----------+------------+
```

As these archives should have no "done" flag associated with them, the rows will probably never be cleaned up during regular operation. And usually there are also several bigger blob rows (each blob row can grow to multiple MB!) linked to those broken archives.

Depending on the instance size, plugins installed, and visit amount, this can lead to a lot of wasted storage.

### PR DESCRIPTION
**Pull request by nathangavin**
### Description:

Relates to #22450

* Adds new functionality for locating and removing broken archives as defined in the related issue. 
* Adds a new scheduled task which is set to purge the latest archiving tables of any broken archives. 
* Adds a new console command which removes all broken archives which occur between any two specified dates.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/Archive/ArchivePurger.php [hunk 1]
```diff
@@ -231,6 +280,34 @@ protected function getOutdatedArchiveIds(Date $date, $purgeArchivesOlderThan)
...
+        $result = $this->model->getArchivesMissingDoneFlag($archiveTable, $dateStart, $dateEnd);
+
+        $idArchivesToDelete = array();
+        if (!empty($result)) {
+            foreach ($result as $row) {
+                $idArchivesToDelete[] = $row['idarchive'];
+            }
+        }
+
+        return $idArchivesToDelete;
```
Comment (michalkleiner) [inline core/Archive/ArchivePurger.php]: Probably can return something like `array_column($result, 'idarchive')`

File: core/Date.php [hunk 2]
```diff
@@ -820,7 +851,7 @@ protected function formatToken($token)
                 return $this->toString('Y');
             case "yy":
                 return $this->toString('y');
-            // month
+                // month
```
Comment (michalkleiner) [inline core/Date.php]: We can probably reset all the indentation changes below.

File: plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+        $this->setName('core:purge-broken-archive-data');
+        $this->setDescription('Purges broken archive data from archive tables.');
+        $this->addOptionalArgument(
+            "dateStart",
+            "The start date to purge data from. Defaults to start of current month",
+            self::getToday()->getStartOfMonth()->toString('Y-m-d')
+        );
+        $this->addOptionalArgument(
+            "dateEnd",
+            "The start date to purge data from. Defaults to end of current month",
```
Comment (michalkleiner) [inline plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php]:
```suggestion
            "The end date to purge data to. Defaults to end of current month",
```

File: plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php [hunk 4]
```diff
@@ -0,0 +1,105 @@
...
+            self::getToday()->getEndOfMonth()->toString('Y-m-d')
+        );
+        $this->setHelp("Broken Archives are removed from all archive tables between supplied dates.\n\n"
```
Comment (michalkleiner) [inline plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php]:
```suggestion
        $this->setHelp("Broken archives are removed from all archive tables between supplied dates.\n\n"
```

File: plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php [hunk 5]
```diff
@@ -0,0 +1,105 @@
...
+        }
+
+        try {
+            $dateEnd = Date::factory($dateEndStr);
+        } catch (\Exception $e) {
+            $output->writeln("Invalid Argument - dateEnd - $dateEndStr");
+            return self::INVALID;
+        }
+
+        $output->writeln("Purging broken archives between $dateStartStr & $dateEndStr");
```
Comment (michalkleiner) [inline plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php]: Just not to confuse the & with a logical operator when looking at the code.
```suggestion
        $output->writeln("Purging broken archives between $dateStartStr and $dateEndStr");
```

File: core/Archive/ArchivePurger.php [hunk 6]
```diff
@@ -147,6 +147,55 @@ public function purgeOutdatedArchives(Date $dateStart)
...
+        // loop through months and delete from relevant tables
+        do {
+            $start = $dateStart->isLater($monthStart) ? $dateStart : $monthStart;
+            $end = $dateEnd->isLater($monthEnd) ? $monthEnd : $dateEnd;
+            $idArchivesToDelete = $this->getBrokenArchiveIds($start, $end);
+            $deletedRowCount = 0;
+            if (!empty($idArchivesToDelete)) {
+                $deletedRowCount = $this->deleteArchiveIds($dateStart, $idArchivesToDelete);
+
+                $this->logger->info("Deleted {count} rows in archive tables (numeric + blob) for {date}.", array(
```
Comment (michalkleiner) [inline core/Archive/ArchivePurger.php]: Are we only deleting from the numeric tables or blobs as well?
```suggestion
                $this->logger->info("Deleted {count} rows in archive numeric tables for {date}.", array(
```

**Review by michalkleiner — COMMENTED** [review]
Did a first round of review and overall it's looking good, so far left a few minor comments.

Can we also use shorthand `[]` array syntax for all the new/updated code? I haven't made code suggestions for that.

File: core/Archive/ArchivePurger.php (hunk 6 above)
Comment (nathangavin) [reply core/Archive/ArchivePurger.php]: `deleteArchiveIds()` deletes from both archive and blob tables, and these broken archives appear in both tables so we need to delete from both.

Comment (michalkleiner) [reply core/Archive/ArchivePurger.php]: Fair enough. Was just wondering as some of the other messages only mention numeric tables, perhaps need to adjust those instead?

Comment (nathangavin) [reply core/Archive/ArchivePurger.php]: well we are only searching the numeric table for broken archives, thats where that comes from in the other logs. we are just expecting any broken archives to also be broken in the blob tables

File: core/Date.php [hunk 7]
```diff
@@ -309,6 +309,37 @@ public function getEndOfDay()
...
+     * the end of the month of the current timestamp.
+     *
+     * For example:
+     * 2025-02-13 -> 2025-02-28
+     * 2025-01-22 -> 2025-01-31
+     * 2025-06-02 -> 2025-06-30
+     *
+     * @return Date
+     */
+    public function getEndOfMonth()
```
Comment (sgiehl) [inline core/Date.php]: Instead of introducing new methods for this you could use the `Month` period object instead. It has a `getDateEnd()` method, which should have the same result.

File: plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php [hunk 8]
```diff
@@ -0,0 +1,105 @@
...
+class PurgeBrokenArchiveData extends ConsoleCommand
+{
+    public const ALL_DATES_STRING = 'all';
+
+    /**
+     * For tests.
+     *
+     * @var Date
+     */
+    public static $todayOverride = null;
```
Comment (sgiehl) [inline plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php]: Is this really needed? Doesn't it work to simply set `Date::$now` in tests and always use ´Date::today()´ here.

File: core/DataAccess/Model.php [hunk 9]
```diff
@@ -410,6 +410,21 @@ public function getTemporaryArchivesOlderThan($archiveTable, $purgeArchivesOlder
         return Db::fetchAll($query, array($purgeArchivesOlderThan));
     }
 
+    public function getArchivesMissingDoneFlag(string $archiveTable, Date $dateStart, Date $dateEnd): array
+    {
+        $query = "SELECT DISTINCT idarchive
+                    FROM $archiveTable
+                    WHERE date1 >= ?
+                        AND date1 <= ?
```
Comment (sgiehl) [inline core/DataAccess/Model.php]: I'm not sure if we actually need to look for certain date here. Target in general is to clean up a month table, so the start or end date actually doesn't matter here.

File: plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php [hunk 10]
```diff
@@ -0,0 +1,105 @@
...
+use Piwik\Plugin\ConsoleCommand;
+use Piwik\Log\NullLogger;
+
+/**
+ * Command that allows users to force purge old or invalid archive data. In the event of a failure
+ * in the archive purging scheduled task, this command can be used to manually delete old/invalid archives.
+ */
+class PurgeBrokenArchiveData extends ConsoleCommand
+{
+    public const ALL_DATES_STRING = 'all';
```
Comment (sgiehl) [inline plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php]: The constant seems unused.
```suggestion
```

**Review by sgiehl — CHANGES_REQUESTED** [review]
Quickly did a high level code review and left a couple of comments for possible improvements.

File: core/DataAccess/Model.php (hunk 9 above)
Comment (nathangavin) [reply core/DataAccess/Model.php]: The inclusion of the dates check is to allow for custom date ranges provided in the cli. If for some reason the user wants to only search up to the middle of a month they can. If we remove the dates then perhaps the cli should also be adjusted to only allow for a range of months to be provided.

File: core/Date.php (hunk 7 above)
Comment (nathangavin) [reply core/Date.php]: I've updated the logic to all use Month period types instead of dates, to simplify the logic a bit.

File: plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php (hunk 8 above)
Comment (nathangavin) [reply plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php]: removed and replaced with overriding `Date::$now` in test.

File: core/DataAccess/Model.php (hunk 9 above)
Comment (nathangavin) [reply core/DataAccess/Model.php]: Updated the code to only go by month, filtering the search by day is no longer supported.

File: plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php (hunk 10 above)
Comment (nathangavin) [reply plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php]: removed

File: core/Archive/ArchivePurger.php (hunk 1 above)
Comment (nathangavin) [reply core/Archive/ArchivePurger.php]: I have done so.

File: core/Archive/ArchivePurger.php [hunk 11]
```diff
@@ -231,6 +279,27 @@ protected function getOutdatedArchiveIds(Date $date, $purgeArchivesOlderThan)
...
+        $archiveTable = ArchiveTableCreator::getNumericTable($month->getDateStart());
+
+        $result = $this->model->getArchivesMissingDoneFlag($archiveTable);
+
+        $idArchivesToDelete = [];
+        if (!empty($result)) {
+            $idArchivesToDelete = array_column($result, 'idarchive');
+        }
+
+        return $idArchivesToDelete;
```
Comment (michalkleiner) [inline core/Archive/ArchivePurger.php]: we may omit the variable and use an early return
```suggestion
        if (!empty($result)) {
            return array_column($result, 'idarchive');
        }

        return [];
```

File: plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php [hunk 12]
```diff
@@ -0,0 +1,94 @@
...
+            $currentMonth->getDateStart()->toString('Y-m-d')
+        );
+        $this->addOptionalArgument(
+            "dateEnd",
+            "The end date to purge data to. Defaults to end of current month",
+            $currentMonth->getDateEnd()->toString('Y-m-d')
+        );
+        $this->setHelp("Broken archives are removed from all archive tables between supplied dates.\n\n"
+                     . "Note: archive purging is done during scheduled task execution, so under normal circumstances, you should not need to "
+                     . "run this command manually.");
```
Comment (michalkleiner) [inline plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php]: Should we mention that the whole month will be purged even if someone passes start ad end date which have just a few days between them? Or accept YYYY-MM format only and always add our own day number?

File: plugins/CoreAdminHome/Tasks.php [hunk 13]
```diff
@@ -312,6 +314,40 @@ public function purgeInvalidatedArchives()
...
+
+            $date = ArchiveTableCreator::getDateFromTableName($archiveTable);
+            [$year, $month] = explode('_', $date);
+
+            try {
+                $monthPeriod = new Month(Date::factory("$year-$month-01"));
+            } catch (\Exception $e) {
+                $this->logger->debug("Date extracted from {table} not valid.", ['table' => $archiveTable]);
+                return false;
+            }
```
Comment (michalkleiner) [inline plugins/CoreAdminHome/Tasks.php]: I guess it's better to be safe here but could it even occur that if not null, the date extracted from a table name would be invalid (unless someone manually tampered with the tables in the database)?

File: plugins/CoreAdminHome/tests/Integration/Commands/PurgeBrokenArchiveDataTest.php [hunk 14]
```diff
@@ -0,0 +1,118 @@
...
+            'command' => 'core:purge-broken-archive-data',
+        ]);
+
+        $this->assertEquals(0, $result, $this->getCommandDisplayOutputErrorMessage());
+
+        self::$fixture->assertBrokenArchivesWithoutDoneFlagPurged(self::$fixture->february);
+        self::$fixture->assertBrokenArchivesNotPurged(self::$fixture->january);
+    }
+
+    public function testExecutingCommandSpecificDatesPurgesOnlyInRange()
```
Comment (michalkleiner) [inline plugins/CoreAdminHome/tests/Integration/Commands/PurgeBrokenArchiveDataTest.php:81]: Since we don't support day ranges anymore but full months, should we change the end date in this test to be in February?

**Review by michalkleiner — COMMENTED** [review]
Good job Nathan, a few more questions, but otherwise looking good.

File: plugins/CoreAdminHome/Tasks.php (hunk 13 above)
Comment (nathangavin) [reply plugins/CoreAdminHome/Tasks.php]: I guess my understanding is that if a function is specified as being able to throw an exception, we should either handle it or allow it to bubble up and document it. Since these task functions are defined as able to throw an exception I'll remove the catch.

File: plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php (hunk 12 above)
Comment (nathangavin) [reply plugins/CoreAdminHome/Commands/PurgeBrokenArchiveData.php]: I've updated the command to work off of using Months as an input (YYYY-MM). If the user provides a full date it will still work, but only the month will be considered.

File: plugins/CoreAdminHome/tests/Integration/Commands/PurgeBrokenArchiveDataTest.php (hunk 14 above)
Comment (nathangavin) [reply plugins/CoreAdminHome/tests/Integration/Commands/PurgeBrokenArchiveDataTest.php:81]: updated the test to properly handle months instead of dates.

File: core/Archive/ArchivePurger.php (hunk 11 above)
Comment (nathangavin) [reply core/Archive/ArchivePurger.php]: done

File: core/Archive/ArchivePurger.php [hunk 15]
```diff
@@ -147,6 +148,53 @@ public function purgeOutdatedArchives(Date $dateStart)
...
+        do {
+            $idArchivesToDelete = $this->getBrokenArchiveIds($currentMonth);
+            $deletedRowCount = 0;
+            if (!empty($idArchivesToDelete)) {
+                $deletedRowCount = $this->deleteArchiveIds($currentMonthStart, $idArchivesToDelete);
+
+                $this->logger->info("Deleted {count} rows in archive tables (numeric + blob) for {date}.", [
+                    'count' => $deletedRowCount,
+                    'date' => $currentMonthStart
+                ]);
```
Comment (michalkleiner) [inline core/Archive/ArchivePurger.php]:
```suggestion
                $this->logger->info("Deleted {count} rows in archive tables (numeric + blob) for month starting {monthStart}.", [
                    'count' => $deletedRowCount,
                    'monthStart' => $currentMonthStart
                ]);
```

File: core/Archive/ArchivePurger.php [hunk 16]
```diff
@@ -147,6 +148,53 @@ public function purgeOutdatedArchives(Date $dateStart)
...
+            } else {
+                $this->logger->debug("No broken archives found in archive numeric table for {date}.", ['date' => $currentMonthStart]);
```
Comment (michalkleiner) [inline core/Archive/ArchivePurger.php]:
```suggestion
                $this->logger->debug("No broken archives found in archive numeric table for month starting {monthStart}.", ['monthStart' => $currentMonthStart]);
```

**Review by michalkleiner — COMMENTED** [review]
Minor two suggestions on the message formatting (to be more accurate).

One question on the input for the console command — when I use 2020 as the param, I don't get an invalid input warning nor it seems to use the value, it defaults to the current month somehow. Is that expected?

I also noticed a strange behaviour for e.g. 2020-09-31 (when going one day beyond the number of days in a shorter month), it turns the date into October, which might be some blackbox magic done by the date handling (probably the same for all dates in Matomo, more an observation than something we should handle here).

File: tests/PHPUnit/Fixtures/RawArchiveDataWithTempAndInvalidated.php [hunk 17]
```diff
@@ -693,4 +751,24 @@ public function assertPartialArchivesPurged(Date $date)
...
+    }
+
+    public function assertPartialBrokenArchivesWithoutDoneFlag(Date $date)
+    {
+        $expectedPurgedArchives = [44];
+        $expectedExistingArchives = [45];
+
+        $this->assertArchivesDoNotExist($expectedPurgedArchives, $date);
+        $this->assertArchivesExist($expectedExistingArchives, $date);
+    }
```
Comment (sgiehl) [inline tests/PHPUnit/Fixtures/RawArchiveDataWithTempAndInvalidated.php]: Looks like this method is actually unused, so guess it can be removed again.

File: core/Archive/ArchivePurger.php [hunk 18]
```diff
@@ -147,6 +148,53 @@ public function purgeOutdatedArchives(Date $dateStart)
...
+     * Removes the broken archives for the given month
+     * (meaning they are not marked with a Done flag correctly)
+     *
+     * @param Month $startMonth a month period where the purge will begin
+     * @param Month|null $endMonth the final month period to purge from,
+     *                  if not provided then will purge to end of the same month as $startMonth.
+     *                  if $endMonth is in the past relative to $startMonth, it is ignored
+     * @return int Returns the total number of rows deleted.
+     */
+    public function purgeBrokenArchives(Month $startMonth, Month $endMonth = null): int
```
Comment (sgiehl) [inline core/Archive/ArchivePurger.php]:
```suggestion
    public function purgeBrokenArchives(Month $startMonth, ?Month $endMonth = null): int
```

File: core/Archive/ArchivePurger.php (hunk 15 above)
Comment (sgiehl) [reply core/Archive/ArchivePurger.php]: Actually I guess it should use `$currentMonthStart->toString('Y-m')` here as well, otherwise it will also print the day.

File: core/Archive/ArchivePurger.php (hunk 16 above)
Comment (sgiehl) [reply core/Archive/ArchivePurger.php]: same as above. Use `$currentMonthStart->toString('Y-m')`

File: core/Date.php [hunk 19]
```diff
@@ -55,7 +55,9 @@ class Date
     public const DATE_FORMAT_YEAR        = DateTimeFormatProvider::DATE_FORMAT_YEAR;
     public const TIME_FORMAT             = DateTimeFormatProvider::TIME_FORMAT;
 
-    // for tests
+    /** for tests
+     * @var int
```
Comment (sgiehl) [inline core/Date.php]:
```suggestion
     * @var null|int
```

**Review by sgiehl — CHANGES_REQUESTED** [review]
Overall the implementation look solid. Left a couple of comments for small code improvements. Otherwise this looks good to merge for me.

**Comment by nathangavin** [comment]
@michalkleiner I have added in an additional check, the cli command will now only accept dates in the format YYYY-MM, and they have to be valid dates, anything below 1970 or above 2999 wont work, and only between 01 and 12 are accepted as months.

File: tests/PHPUnit/Fixtures/RawArchiveDataWithTempAndInvalidated.php (hunk 17 above)
Comment (nathangavin) [reply tests/PHPUnit/Fixtures/RawArchiveDataWithTempAndInvalidated.php]: removed

**Review by michalkleiner — APPROVED** [review]
The inputs are now strongly validated. If we were more descriptive in the error message to the user on the expected format, not just saying that it's invalid, that would be nice, but otherwise 👍 from me.

**Review by sgiehl — APPROVED** [review]
Seems all remaining things were addressed now. Good work :+1:
