### PR TITLE
Make goal title in report clickable

### LINKED ISSUE #10554: On Goals > Overview, the Goal names titles should link to the Goal report
On Goals > Overview page listing all goals, when clicking on a Goal name title, it should open the goal report. 

(regression from 2.x)

### PR DESCRIPTION
**Pull request by tsteur**
fixes #10554 

Please note that the title shows an underline when hovered so the link is more visible. This is default behaviour that can be changed but will be more useable with underline

### CODE REVIEW

File: plugins/Goals/Reports/Get.php [hunk 1]
```diff
@@ -182,6 +184,17 @@ public function configureView(ViewDataTable $view)
                 }
             }
         } else if ($view->isViewDataTableId(Evolution::ID)) {
+            if (!empty($idSite) && Piwik::isUserHasAdminAccess($idSite)) {
+                $view->config->title_edit_entity_url = 'index.php' . Url::getCurrentQueryStringWithParametersModified(array(
+                    'module' => 'Goals',
+                    'action' => 'manage',
```
Comment (mattab) [inline plugins/Goals/Reports/Get.php]: FYI: link should go to the Report page, not the manage page (as users will want to click to view more details goal report)

Comment (tsteur) [inline plugins/Goals/Reports/Get.php]: this is quite tricky currently, it would likely change date etc unless we refactor it quite a bit. Can you check on demo.piwik.org it goes to same page

Comment (mattab) [inline plugins/Goals/Reports/Get.php]: it goes to same page, can you just replace the `action=index` by `action=goalReport`?

Comment (mattab) [inline plugins/Goals/Reports/Get.php]: see http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#?module=Goals&action=index&idSite=7&period=day&date=yesterday

Comment (tsteur) [inline plugins/Goals/Reports/Get.php]: I'm having a look. BTW: The links in Piwik 2 are currently broken when using it widgetized. Need to see what to do there

Comment (tsteur) [inline plugins/Goals/Reports/Get.php]: @mattab it should work now

Comment (mattab) [inline plugins/Goals/Reports/Get.php]: > The links in Piwik 2 are currently broken when exporting it as widgetize. Need to see what to do there

@tsteur could you create an issue for that one?

**Comment by mattab** [comment]
Well done, I know that one wasn't easy at all, and result is perfect!

File: plugins/Goals/Reports/Get.php (hunk 1 above)
Comment (tsteur) [inline plugins/Goals/Reports/Get.php]: In 3.x they are not clickable when exported so shouldn't be a problem and don't think needs fixing in 2.x or even can be easily fixed
