### PR TITLE
Write archive records with writer reconnection attempt

### LINKED ISSUE #21873: [Bug] Database server has gone away exception when inserting archive data
### What happened?

When using both a database reader and writer, in some rare cases a `MySQL error 2006: mysql server has gone away` exception is thrown when `insertArchiveData` is called. This can cause the results of long running queries to be discarded requiring them to be rerun at a later time, slowing down archiving and wasting server resources.

Comment from @tsteur on related issue #21807:

> On Cloud the issue happens very rarely (< 0.001% of the times). When it happens, it's in 85% of the cases during archiving. The other 15% is nothing to worry about. When this issue happens during archiving, it happens 99% of the time to the Writer Database connection when insertArchiveData is called. This means all the select queries on the reader finished and we want to insert data. This could indicate that the writer DB connection has been idle sitting around for a while waiting for the reads to finish.

### What should happen?

Issue #21807 covers adding a generic database connection retry mechanism which would resolve this, but this will be complicated to implement due to temporary table use.

For this specific issue there maybe a quicker and easier fix:

>A fix for "Server gone away" may be a MySQL connection setting change or alternatively restarting the connection for the writer only. This simplifies it because the writer does not use temporary tables when a DB reader is configured. When no DB reader is configured, the issue likely doesn't happen because the same connection is constantly being used and not idle.

>That means if we determine the issue is impactful to fix, we could only implement a reconnect logic while we're archiving, and also only when a DB reader is configured. Then we don't need to think about temporary tables, and I believe archiving also doesn't use transactions. The issue then becomes a lot more trivial to implement maybe.

>Not sure it's clear what I mean. Something like below might be something to think about and since it might be fairly simple to implement it could be worth a try to see if it eliminates the issue (assuming we can't fix the issue with a MySQL config change).

```
...
private $timeLastConnected = ...;
...
if (SettingsServer::isArchivePhpTriggered() 
&& HasDbReaderConfigured && isRegularDbAndNotReaderDb 
&& timeSinceLastConnect > 2 hours) 
{
  reconnectWriterDb
}
```

### How can this be reproduced?

This happens randomly on cloud during long archiving processes, although we have logs of occurrences, the issue is not recreate-able on demand. 

### Matomo version

5.0.1

### PHP version

8.2

### Server operating system

n/a

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Computer operating system

n/a

### Relevant log output

_No response_

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by mneudert**
### Description:

When using a reader/writer database configuration, it can happen that the writer connection times out while the archive data is being collected.

For cron archiving, this can this can lead to lengthy re-archiving times.

This PR should only be seen as an intermediate solution to that problem until #21807 is implemented.

Fixes #21873.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/Db.php [hunk 1]
```diff
@@ -285,12 +286,55 @@ public static function query($sql, $parameters = array())
...
+     *
+     * @internal
+     */
+    public static function executeWithDatabaseWriterReconnectionAttempt(callable $callback)
+    {
+        try {
+            return $callback();
+        } catch (Exception $ex) {
+            // only attempt reconnection in a reader/writer configuration
+            if (!self::hasReaderConfigured()) {
```
Comment (caddoo) [inline core/Db.php:308]: Is this covered by tests?

File: core/Db.php [hunk 2]
```diff
@@ -285,12 +286,55 @@ public static function query($sql, $parameters = array())
...
+                throw $ex;
+            }
+
+            // only attempt reconnection if we encounter a "MySQL server has gone away" error
+            if (
+                !self::get()->isErrNo($ex, Updater\Migration\Db::ERROR_CODE_MYSQL_SERVER_HAS_GONE_AWAY)
```
Comment (caddoo) [inline core/Db.php:314]: Is this covered by tests?

**Comment by caddoo** [comment]
Tested locally and works nicely!

I think another test that might be good is something along the lines of:

`test_withReader_attemptsReconnectOnce`

Just to make sure we don't end up in an infinite loop of trying to connect.

**Review by caddoo — CHANGES_REQUESTED** [review]

File: core/Db.php [hunk 3]
```diff
@@ -285,12 +286,55 @@ public static function query($sql, $parameters = array())
...
+                && false === stripos($ex->getMessage(), 'MySQL server has gone away')
```
Comment (michalkleiner) [inline core/Db.php]: Do MariaDb and Aurora throw the same message/same wording of the message?

**Comment by michalkleiner** [comment]
Just a note on the changes from `\Exception` to `Exception` — I know we are touching the files and that the class is already in `use`s list, but it makes the review cognitively more demanding to get through those changes only to realise they are not functionally important.

File: core/Db.php (hunk 1 above)
Comment (mneudert) [reply core/Db.php:308]: There is a [specific test](https://github.com/matomo-org/matomo/pull/21980/files#diff-93a1f0d6b170456ab57a9cf3699a5e1035bbed43951b142a48e387e54cde7513R139) for that case, yes.

File: core/Db.php (hunk 2 above)
Comment (mneudert) [reply core/Db.php:314]: Added a separate one with a syntax error, so we can verify the connection is not being replaced in that case.

File: core/Db.php (hunk 3 above)
Comment (mneudert) [reply core/Db.php]: The message should be triggered by the client library and not depend on the actual server connected to.

However I changed the actual wording tested to only `server has gone away`, to keep it less MySQL specific. Sometime in the future the underlying client library may change to MariaDB and they apparently [change](https://us02web.zoom.us/j/6827118593) the wording :thinking:

**Review by michalkleiner — APPROVED** [review]
Nice work @mneudert and @caddoo!

**Review by caddoo — APPROVED** [review]
