### PR TITLE
Fix sending secure token in bulk request body & add support for "Authorization: Bearer" header

### LINKED ISSUE #20677: Allow to pass API token using "Authorization" HTTP header as "bearer" token
This is a followup after #19234:

Currently you can only pass the `token_auth` parameter containing the API token with GET or POST. If you do it with GET, the token is visible in logs (on possibly both client and server). After #19234 you can enforce to pass the token in the body of a POST request. But from an REST perspective this is not "correct". GET is to query an API (like statistics/reporting), but POST should only be used to post new content (e.g., to modify it, which is not the case for reporting API). In addition, adding the token authorization to query parameters / form-parameter (in body) is not separating authorization from the API semantics.

Basically the correct way to pass authorization information in HTTP is using the `Authorization` header. The header is defined in HTTP/1.1 and contains 2 informations:
- authentication scheme
- auth parameters (e.g, a token)

For token based auth, the OAuth and REST standard recommend to use "Bearer" as scheme and the token itsself as parameter. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#authentication_schemes about schemes and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization for the general header syntax.

This would allow to call the API of Matomo in a standards conformant way:
- Use GET requests to query information and have all query parameters in URL
- Pass the token as Authorization header like that: `Authorization: Bearer ....token...`

This makes request log files not expose tokens but still allows to log everything relevant to the REST call.

Implementation in Matomo should be easy: Just read header via  `$_SERVER[HTTP_AUTHORIZATION]`,and apply a regex like `^Bearer\s+(\S+)$` and use capture group `\1`. According to OAuth standards the scheme "Bearer" should be written with initial uppercase letter, but most implementations in REST frameworks also accept it case insensitive, so use case insensitive regex matching.

I would also suggest to change the config setting `only_allow_posted_auth_tokens` introduced by #20351 to be renamed to `disallow_auth_tokens_via_urlparams` (or similar). Because a GET request for API is still valid and recommended , only the token_auth parameter should not be posted as URL param.

I'd like you to rethink your decissions in previous issues and for Matomo 5.0 to better propagate "correct" auth and don't force users to use POST as "workaround". Separate auth and API parameters completely!

For backwards compatibility allow to still post tokens in GET/POST parameters, but allow it to be disabled (see above) as URL parameters and disable it in 6.0 by default. In addition, update docs to help users migrate their code to either POST with form-parameters in body or (better) separate auth to Authorization header.

### LINKED ISSUE #21905: [Bug] Bulk tracking does not authenticate
### What happened?

I did some tests with Postman and with debugging enabled. Doing a single tracking request works perfectly. I take the same token and put it into a bulk tracking request and I get the error:
WARNING! token_auth = xxxxx is not valid, Super User / Admin / Write was NOT authenticated 

### What should happen?

It should authenticate and process the tracking requests

### How can this be reproduced?

Send on Postman this tracking request
```
{
   "requests": [
      "?idsite=2&rec=1&cip=23.145.24.180&cdt=1706332501&url=https%3A%2F%2Fwww.rundumgesund.org%2F&urlref=-&ua=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F119.0.0.0+Safari%2F537.36",
      "?idsite=2&rec=1&cip=2.57.122.115&cdt=1706371627&url=https%3A%2F%2Fwww.rundumgesund.org%2F&urlref=http%3A%2F%2Fwww.rundumgesund.org%3A80%2F&ua=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_11_2%29+AppleWebKit%2F601.3.9+%28KHTML%2C+like+Gecko%29+Version%2F9.0.2+Safari%2F601.3.9",
      "?idsite=2&rec=1&cip=2.57.122.115&cdt=1706371627&url=https%3A%2F%2Fwww.rundumgesund.org%2F&urlref=http%3A%2F%2Frundumgesund.org%3A80%2F&ua=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_11_2%29+AppleWebKit%2F601.3.9+%28KHTML%2C+like+Gecko%29+Version%2F9.0.2+Safari%2F601.3.9"
   ],
   "token_auth": "put your token"
}
```

### Matomo version

5.0.2

### PHP version

_No response_

### Server operating system

_No response_

### What browsers are you seeing the problem on?

_No response_

### Computer operating system

_No response_

### Relevant log output

_No response_

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

Currently the auth token is used in various places to authenticate the user. This PR centralizes that handling to it's easier in the future to make certain adjustments.

In addition that PR fixes the authentication problem in bulk tracking requests, when a secure only token is provided in the request body.

Also it adds support to provide the token as `Authorization: Bearer`-Header.

fixes #21905, fixes #20677

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/Access.php [hunk 1]
```diff
@@ -158,15 +159,14 @@ public function reloadAccess(?Auth $auth = null)
...
         $apiMethod = Request::getMethodIfApiRequest(null);
         $isGetApiRequest = !empty($apiMethod) && 1 === substr_count($apiMethod, '.') && strpos($apiMethod, '.get') > 0;
 
-        if (($forceApiSessionPost && $isApiRequest) || ($forceApiSessionGet && $isApiRequest && $isGetApiRequest)) {
-            $request = ($forceApiSessionGet && $isApiRequest && $isGetApiRequest) ? $_GET : $_POST;
-            $tokenAuth = Common::getRequestVar('token_auth', '', 'string', $request);
+        $token = StaticContainer::get(AuthenticationToken::class);
+
+        if ($isApiRequest && ($token->wasTokenAuthProvidedSecurely() || $isGetApiRequest)) {
+            $tokenAuth = $token->getAuthToken();
```
Comment (caddoo) [inline core/Access.php]: This is a lot cleaner than the mess it's replacing 👍 

However I still don't fully understand from reading the if statement why we need to do this.

Doesn't the getAuthToken handle retrieving the token from the right place, does this logic need to exist here as well?

File: core/Request/AuthenticationToken.php [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+        if (!SettingsServer::isTrackerApiRequest()) {
+            return false;
+        }
+
+        $requestBody = file_get_contents('php://input');
+        if (!empty($requestBody) && strpos($requestBody, '{') === 0) {
+            $jsonContent = json_decode($requestBody, true);
+
+            if (!empty($jsonContent['token_auth'])) {
+                $this->authToken = $jsonContent['token_auth'];
```
Comment (caddoo) [inline core/Request/AuthenticationToken.php:85]: What happens if `token_auth` is another type like an array?

File: core/Request/AuthenticationToken.php [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+    private function initTokenFromJsonRequestBody(): bool
+    {
+        // Token in JSON request body is only support for tracking requests
+        if (!SettingsServer::isTrackerApiRequest()) {
+            return false;
+        }
+
+        $requestBody = file_get_contents('php://input');
+        if (!empty($requestBody) && strpos($requestBody, '{') === 0) {
+            $jsonContent = json_decode($requestBody, true);
```
Comment (caddoo) [inline core/Request/AuthenticationToken.php:82]: Can we gracefully handle the json_decode failing?

**Review by caddoo — CHANGES_REQUESTED** [review]

File: core/Access.php (hunk 1 above)
Comment (sgiehl) [reply core/Access.php]: Oh. Actually I missed to add `$token->isSessionToken()` to the condition. The check actually should ensure that we use POST requests for session API requests unless the targeted API methods starts with `get`. That should help to ensure that we do not by accident provide sensitive values as get parameters for API calls.

File: core/Request/AuthenticationToken.php (hunk 3 above)
Comment (sgiehl) [reply core/Request/AuthenticationToken.php:82]: If json_decode fails to parse the JSON string it will simply return `NULL`. That will make the next check to be skipped and `false` to be returned. Not sure what you want to handle more gracefully

File: core/Request/AuthenticationToken.php (hunk 2 above)
Comment (sgiehl) [reply core/Request/AuthenticationToken.php:85]: good catch, guess it makes sense to add a string check

File: core/Request/AuthenticationToken.php (hunk 3 above)
Comment (caddoo) [reply core/Request/AuthenticationToken.php:82]: That's fine then 👍

File: tests/PHPUnit/System/TrackerTest.php [hunk 4]
```diff
@@ -61,17 +62,34 @@ protected static function configureFixture($fixture)
...
+        // one tracking request is supposed to be invalid, as the token doesn't allow tracking custom ip
+        $this->issueBulkTrackingRequest($token_auth, true, 1, 1);
     }
 
     public function testTrackingApiWithBulkRequestsViaCurlWithCorrectTokenAuth()
     {
         $token_auth = Fixture::getTokenAuth();
         \Piwik\Filesystem::deleteAllCacheOnUpdate();
-        $this->issueBulkTrackingRequest($token_auth, $expectTrackingToSucceed = true);
+        // both requests shoulde btracked, as the token doesn't allow tracking custom ip
```
Comment (caddoo) [inline tests/PHPUnit/System/TrackerTest.php]:
```suggestion
        // both requests should be tracked, as the token doesn't allow tracking custom ip
```

**Review by caddoo — DISMISSED** [review]
Looks better, just a small typo in comment

**Review by caddoo — APPROVED** [review]

**Comment by uschindler** [comment]
Many thanks! This is a great step foreward to a more standards-conform API!
