### PR TITLE
copy file instead of renaming it.

### LINKED ISSUE #5050: Windows: rename(C:\misc/GeoIPCity.dat.new,C:\misc/GeoIPCity.dat): The process cannot access the file because it is being used by another process. (code: 32)
Bug reported [in the forum](http://forum.piwik.org/read.php?2,114254):

```
 Warning:&lt;/strong> &lt;em>rename(C:\Webservices\htdocs\piwik/misc/GeoIPCity.dat.new,C:\Webservices\htdocs\piwik/misc/GeoIPCity.dat): The process cannot access the file because it is being used by another process. (code: 32)&lt;/em> in &lt;strong>C:\Webservices\htdocs\piwik\plugins\UserCountry\GeoIPAutoUpdater.php&lt;/strong> on line &lt;strong>268&lt;/strong>
```

This is triggered in the cron, Scheduled tasks.

I'm not sure what should be done with this issue?

### PR DESCRIPTION
**Pull request by RMastop**
As stated in thread; fixes #5050

Please issue pull request against the `3.x-dev` branch only.

Piwik 2 is in LTS mode. This means we do not accept any pull request for 2.x except critical security bugs and major data loss bugs. 

If you need to create a pull request for 2.x, then please also create the pull request against the `3.x-dev` so we can merge both.

Happy hacking!

### CODE REVIEW

File: plugins/UserCountry/GeoIPAutoUpdater.php [hunk 1]
```diff
@@ -268,7 +268,7 @@ public static function unzipDownloadedFile($path, $unlink = false)
             }
 
             $tempFile = GeoIp::getPathForGeoIpDatabase($tempFilename);
-            rename($tempFile, $oldDbFile);
+            copy($tempFile, $oldDbFile);
```
Comment (mattab) [inline plugins/UserCountry/GeoIPAutoUpdater.php]: Hi Richard, should we also delete the `$tempFile` then?
have you had a chance to test this works?
