### PR TITLE
Optimize segment SQL when segment subqueries are used

### LINKED ISSUE #20467: Improve performance of archiving queries when a segment uses "Not contains" or "not equals"
## Context
We're seeing slow DB queries on the cloud that take a very long time to run when a segment uses one of the in the title mentioned comparisons/operators.

Example:
Given a segment `pageUrl=@foo.com;pageUrl!@baz;pageUrl=@test;pageUrl!@hello` Matomo produces below complicated and slow query:

```sql
			SELECT
				distinct log_visit.idvisit as idvisit
			FROM
				log_visit AS log_visit LEFT JOIN log_link_visit_action AS log_link_visit_action ON log_link_visit_action.idvisit = log_visit.idvisit LEFT JOIN log_action AS log_action_segment_log_link_visit_actionidaction_url ON log_link_visit_action.idaction_url = log_action_segment_log_link_visit_actionidaction_url.idaction
			WHERE
				( log_visit.visit_last_action_time >= ?
				AND log_visit.visit_last_action_time <= ?
				AND log_visit.idsite IN (?) )
                AND
                ( (log_action_segment_log_link_visit_actionidaction_url.name LIKE ? AND log_action_segment_log_link_visit_actionidaction_url.type = '1') AND ( log_visit.idvisit NOT IN (
			SELECT
				log_visit.idvisit
			FROM
				log_visit AS log_visit LEFT JOIN log_link_visit_action AS log_link_visit_action ON log_link_visit_action.idvisit = log_visit.idvisit LEFT JOIN log_action AS log_action_segment_log_link_visit_actionidaction_url ON log_link_visit_action.idaction_url = log_action_segment_log_link_visit_actionidaction_url.idaction
			WHERE
				( log_visit.idsite IN (?) AND log_visit.visit_last_action_time >= ? AND log_visit.visit_last_action_time <= ? )
                AND
                ( (log_action_segment_log_link_visit_actionidaction_url.name LIKE ? AND log_action_segment_log_link_visit_actionidaction_url.type = '1') )) ) AND (log_action_segment_log_link_visit_actionidaction_url.name LIKE ? AND log_action_segment_log_link_visit_actionidaction_url.type = '1') AND ( log_visit.idvisit NOT IN (
			SELECT
				log_visit.idvisit
			FROM
				log_visit AS log_visit LEFT JOIN log_link_visit_action AS log_link_visit_action ON log_link_visit_action.idvisit = log_visit.idvisit LEFT JOIN log_action AS log_action_segment_log_link_visit_actionidaction_url ON log_link_visit_action.idaction_url = log_action_segment_log_link_visit_actionidaction_url.idaction
			WHERE
				( log_visit.idsite IN (?) AND log_visit.visit_last_action_time >= ? AND log_visit.visit_last_action_time <= ? )
                AND
                ( (log_action_segment_log_link_visit_actionidaction_url.name LIKE ? AND log_action_segment_log_link_visit_actionidaction_url.type = '1') )) ) )
			ORDER BY
				log_visit.idvisit ASC
```

## Expected Behavior
The query is optimised so it executes a lot faster. 

## Steps to Reproduce (for Bugs)
* Define a segment as described above. 
* Launch the archiving (either via `core:archive` or if browser archiving is enabled by requesting it in the browsers)
* You will see in the logaggregator the query to create the temporary archive table with the complicated query.

## Your Environment
* Matomo Version: 4.13.3
* PHP Version: 8.0
* Server Operating System: Linux

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Fixes #20467 

Changes:
* Refactor segment parsing and related code to use an expression tree (as nested array) for the intermediate data structures. First level in the array represents AND-ed expressions, the second level represents OR-ed expressions. This makes it easier to manipulate the expression before converting it to SQL and simplifies the related code.
* Merge adjacent NOT IN segment subqueries so fewer exist in segment SQL overall. Segment subqueries that are next to each other in a single OR expression chain are merged, and segment subqueries that are not parts of OR expression chains but are part of the overall AND expression chain are merged.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by caddoo** [comment]
Hey @diosmosis , sorry for taking so long to look at this.

To help me out a bit with reviewing are you able to provide some examples of how this has been tested so far, and any reproducible manual tests I could run to verify?

And do you know if this behaviour is covered already by integration/E2E tests.

**Comment by diosmosis** [comment]
@caddoo 

> To help me out a bit with reviewing are you able to provide some examples of how this has been tested so far, and any reproducible manual tests I could run to verify?

You would be testing for regressions only as there is no new behavior in this PR. So, creating segments that have multiple and varied action segments (which would use the `idvisit NOT IN (` subqueries) and checking they select the same visits on develop vs. on this branch.

> And do you know if this behaviour is covered already by integration/E2E tests.

These are covered by `tests/PHPUnit/Integration/SegmentTest.php` (checks the SQL generated is as expected and checks that the segments do not outright fail). And some system test cases but I can't them off the top of my head. You'd need to find ones that use action segments, which I'm sure exist.

Also, note: I think this PR is no longer my responsibility as I'm working on Matomo for Wordpress now. So for bigger changes, someone on the core team would need to take over.

**Comment by caddoo** [comment]
> @caddoo
> 
> > To help me out a bit with reviewing are you able to provide some examples of how this has been tested so far, and any reproducible manual tests I could run to verify?
> 
> You would be testing for regressions only as there is no new behavior in this PR. So, creating segments that have multiple and varied action segments (which would use the `idvisit NOT IN (` subqueries) and checking they select the same visits on develop vs. on this branch.
> 
> > And do you know if this behaviour is covered already by integration/E2E tests.
> 
> These are covered by `tests/PHPUnit/Integration/SegmentTest.php` (checks the SQL generated is as expected and checks that the segments do not outright fail). And some system test cases but I can't them off the top of my head. You'd need to find ones that use action segments, which I'm sure exist.
> 
> Also, note: I think this PR is no longer my responsibility as I'm working on Matomo for Wordpress now. So for bigger changes, someone on the core team would need to take over.

Thanks @diosmosis appreciate the direction here on what to test, I think this is enough for us to go with :D

File: core/Segment/SegmentExpression.php [hunk 1]
```diff
@@ -456,47 +459,25 @@ private function escapeLikeString($str)
...
-            }
-            $isBackslash = ($char == "\\");
-            $i++;
-        }
-        return $tree;
+        // handle backslashes by urlencoding the characters
+        $segmentStr = preg_replace_callback('/\\\\./', function ($matches) {
+            $char = substr($matches[0], 1);
+            return urlencode($char);
+        }, $segmentStr);
```
Comment (sgiehl) [inline core/Segment/SegmentExpression.php]: We might need to revert all changes to this method. We can't simply urlencode all values that follow on a `\`.
There might e.g. be segment values where someone wants to look after `folder\file`. The current solution would simply strip away the `\`. Also we can not start to urlencode various chars, as they might then appear urlencoded in the resulting SQL (which can be seen in the test changes), which could have an effect on the resulting datasets.

Here a small php example what the problem around backslashes are: https://3v4l.org/8kpMn

Comment (bx80) [reply core/Segment/SegmentExpression.php]: @sgiehl Unfortunately I couldn't just revert the `parseTree()` method since as well as changing the handling of backslashes it also changes the grouping of the return array. Instead I've reworked the method to use the original parsing code but tweaked to provide the new grouped array. As part of this I've reverted the test values in `SegmentExpressionTest` back to their original state which includes the use of a backslash as a non-escaping part of the expression (`A\B`).

Both `SegmentExpressionTest` and the recently updated `ComplicatedSegmentTest` are now passing.

Comment (michalkleiner) [reply core/Segment/SegmentExpression.php]: Had a quick play and this may also produce the same nested tree.
It's using a negative lookbehind split, first splits on `;` that is not preceded by `\` and then splits the results on `,` that is not preceded by `\`. Then removes `\` from `\;` and `\,`.

```
function parseTree($segment) {
    $ands = preg_split("/;(?<!\\\;)/", $segment);
    $tree = array_map(function($and) {
        $ors = preg_split("/,(?<!\\\,)/", $and);
        $unescapedOrs = array_map(function($or) { return str_replace(['\,', '\;'], [',', ';'], $or); }, $ors);
        return $unescapedOrs;
    }, $ands);

    return $tree;
}
```
(would need replacing `;` with `self::AND_DELIMITER` and `,` with `self::OR_DELIMITER` in the preg_split expressions).

Comment (michalkleiner) [reply core/Segment/SegmentExpression.php]: Mmmm, would need more tweaks, run the unit test locally and failed on some trailing commas.

Comment (bx80) [reply core/Segment/SegmentExpression.php]: That's a clever solution @michalkleiner and a lot more concise :+1: 

However it fails some of the edge cases in the `SegmentExpression` test where there is a trailing AND or OR operator, eg. `A,B,` should result in `( A OR B, )` whereas this method returns `( A OR B OR )`

Although the original while-character loop parsing isn't very elegant or efficient, it does have the benefit of having had lots of production testing over the last eight years since it was last changed, so I think for this specific issue we should probably try to minimize the risk of introducing regressions so we can get the query optimization merged and then we can look at further improvements after that.

Comment (michalkleiner) [reply core/Segment/SegmentExpression.php]: I got the tests passing locally, have a PR on top of this PR to test it.

Comment (michalkleiner) [reply core/Segment/SegmentExpression.php]: @bx80 check https://github.com/matomo-org/matomo/pull/21669 and see if it works for you.

Comment (bx80) [reply core/Segment/SegmentExpression.php]: That change now passes the tests, but there may be other edge cases not covered by the tests so we're still introducing additional risk.

Comment (michalkleiner) [reply core/Segment/SegmentExpression.php]: Yep, fair. We can leave it open even after this is merged, it will automatically retarget itself to 5.x-dev and we can review/add extra tests then.

**Comment by michalkleiner** [comment]
I've looked through the change and I can't confidently give it an approval on its merits, I could only do it on the fact the tests are passing, but the tests were adjusted as well, so I would need more time or defer to someone else.

File: core/Segment/SegmentExpression.php (hunk 1 above)
Comment (bx80) [reply core/Segment/SegmentExpression.php]: That sounds good :slightly_smiling_face:

**Comment by bx80** [comment]
@sgiehl Now the urlencoding issue is resolved, could you take another look at reviewing this PR when you get a chance?  Thanks! :slightly_smiling_face:

**Review by sgiehl — APPROVED** [review]
In general the code looks fine to me. But as mentioned before it's really hard to ensure if it might introduce any possible regressions regarding the resulting data.
To minimize the risk I did some more local testing by creating a bunch of fake visits for a certain day. Then I created various different segments and added some logging to receive the amount of rows inserted in the temporary segment table. Then I ran archiving once without the config flag and once with it and compared the numbers. For my local tests the numbers were the same. We nevertheless could so some similar testing with bigger data sets or maybe really compare the resulting visit ids to ensure there are no differences.

**Comment by bx80** [comment]
I've reverted the feature flag change and merged in Michal's improved parsing code. If somebody wants to give this a last quick check over then it should be ready to merge into 5.x-dev :checkered_flag:

**Review by michalkleiner — APPROVED** [review]
Ben and Stefan tested this extensively and we have done some more tests in the cloud environment without any obvious issues, so I guess that's as much as we can do at this stage.
