### PR TITLE
Do not use get_results in mysqli as it requires mysqlnd

### LINKED ISSUE #15345: Matomo 3.13.1.b2 : Call to undefined method mysqli_stmt::get_result()
Hello,

This occur since last beta update.

Matomo version: 3.13.1-b2

 PHP Fatal error: Call to undefined method mysqli_stmt::get_result() in (...) piwik/core/Tracker/Db/Mysqli.php

Tracking is completely down : all request are throwing 500 errors.

Thanks,

Eric

### PR DESCRIPTION
**Pull request by tsteur**
fix https://github.com/matomo-org/matomo/issues/15345

### CODE REVIEW

File: core/Tracker/Db/Mysqli.php [hunk 1]
```diff
@@ -148,6 +148,39 @@ public function disconnect()
...
+     * @return array|bool|false
+     */
+    private function fetchResult($stmt, $fields) {
+
+        $values = array_fill(0, count($fields), null);
+
+        $refs = array();
+        foreach ($values as $i => &$f) {
+            $refs[$i] = &$f;
+        }
```
Comment (diosmosis) [inline core/Tracker/Db/Mysqli.php]: Is `$refs` needed? It doesn't seem to be used anywhere.

Comment (tsteur) [reply core/Tracker/Db/Mysqli.php]: It was done like this in Zend I suppose it turns it into a reference.

Comment (diosmosis) [reply core/Tracker/Db/Mysqli.php]: that's weird, but ok zend
