### PR TITLE
Fix possible errors in sparklines when there is no data

### LINKED ISSUE #21087: Fatal error: Sparkline::getComparisonSeries(): Argument #1 ($dataTable) must be of type Piwik\\DataTable\\DataTableInterface, bool given
See below details to reproduce

> Error: {"message":"Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Sparkline::getComparisonSeries(): Argument #1 ($dataTable) must be of type Piwik\\DataTable\\DataTableInterface, bool given, called in plugins\/CoreVisualizations\/Visualizations\/Sparkline.php on line 63","file":"plugins\/CoreVisualizations\/Visualizations\/Sparkline.php","line":185,"request_id":"f91bd","backtrace":" on plugins\/CoreVisualizations\/Visualizations\/Sparkline.php(185)\n#0 plugins\/CoreVisualizations\/Visualizations\/Sparkline.php(63): Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Sparkline->getComparisonSeries(false)\n#1 core\/Plugin\/Report.php(344): Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Sparkline->render()\n#2 plugins\/CoreHome\/Controller.php(60): Piwik\\Plugin\\Report->render()\n#3 [internal function]: Piwik\\Plugins\\CoreHome\\Controller->renderReportWidget(Object(Piwik\\Plugins\\API\\Reports\\Get))\n#4 core\/FrontController.php(637): call_user_func_array(Array, Array)\n#5 core\/FrontController.php(169): Piwik\\FrontController->doDispatch('API', 'get', Array)\n#6 core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 index.php(25): require_once('c...')\n#8 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(100): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(140): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(196): Piwik\\FrontController::(Object(TypeError))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}

> URL: https://demo.matomo.cloud/index.php?date=2023-07-23,2023-07-28&module=API&format=html&forceView=1&viewDataTable=sparkline&action=get&period=day&idSite=1&comparePeriods[]=day&compareDates[]=2023-07-17%2C2023-07-22&segment=&widget=&showtitle=1&random=8189&compareSegments=&colors=%7B%22backgroundColor%22%3A%22%23ffffff%22%2C%22lineColor%22%3A%5B%22%230277bd%22%2C%22%23ff8f00%22%5D%2C%22minPointColor%22%3A%22%23ff7f7f%22%2C%22maxPointColor%22%3A%22%2375bf7c%22%2C%22lastPointColor%22%3A%22%2355aaff%22%2C%22fillColor%22%3A%22%23ffffff%22%7D&columns=$%7b$%7bpinsCt%foo

> GET: {"date":"2023-07-23,2023-07-28","module":"API","format":"html","forceView":"1","viewDataTable":"sparkline","action":"get","period":"day","idSite":"1","comparePeriods":["day"],"compareDates":["2023-07-17,2023-07-22"],"segment":"","widget":"","showtitle":"1","random":"8189","compareSegments":"","colors":"{\"backgroundColor\":\"#ffffff\",\"lineColor\":[\"#0277bd\",\"#ff8f00\"],\"minPointColor\":\"#ff7f7f\",\"maxPointColor\":\"#75bf7c\",\"lastPointColor\":\"#55aaff\",\"fillColor\":\"#ffffff\"}","columns":"${${pinsCt%foo"}

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #21087 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/Visualization/Sparkline.php [hunk 1]
```diff
@@ -215,6 +215,13 @@ private function setSparklineColors($sparkline, $seriesIndex) {
     }
 
     public function render() {
+
```
Comment (michalkleiner) [inline core/Visualization/Sparkline.php]: just a nitpick, disregard if you feel like it

```suggestion
```

**Review by michalkleiner — APPROVED** [review]
