### PR TITLE
POST to login plugin in login form

### LINKED ISSUE #14075: Remember me - not working
Well, let's try this once again (previously in #13327). Old issue now closed is still very much actual in my case.

I haven't investigated this much, but it is totally annoying and unreliable. It doesn't work, really.

Steps to "reproduce" this issue:

1. run Chrome
2. access website/matomo/
3. enter log-in credentials, check 'remember me', submit login form
4. once logged-in, close Chrome
5. repeat from step (1) above - try to access website/matomo/ again, and ... log-in form is presented once again !?

I run Matomo on VPS and cPanel shared hosting plans, and it happens on both of them, and [once-in-a-while Matomo decides to finally remember me](https://github.com/matomo-org/matomo/issues/13327#issuecomment-427692656), so it works for a while until I clear App Storage in Chrome or history + cookies.

What is happening here? I know you switched away from cookies, but sessions in:

> /var/lib/php/sessions

files are all with 0 length.

Ok, so, Piwik/Matomo [maybe] stores sessions locally in its own folder (?):

> website/matomo/tmp/sessions/

Ok, there we go. Now, here's the funny thing - if I delete those temp sessions in matomo's local tmp folder, I am still logged-in. So, they aren't used for that, huh??

Also, how / when are they being created in the first place? When I log-in, I don't see new session file stored in there. Also, php's default sessions files are not related with matomo's log-in, that makes sense already (read above).

So, it is stored in browser (where else could it possible be?)? Then, why this happens? Why Matomo keeps 'forgetting' me?

*How can we fix this once and for all?*

(please do not close this issue too early)

Thanks!

### PR DESCRIPTION
**Pull request by diosmosis**
Fixes #14075

### CODE REVIEW

**Comment by tsteur** [comment]
@diosmosis haven't tested but when doing the redirect, and then logging in, does the feature still work to load the same page as you loaded initially? Say you are logged out and open the users manager, then log in, is the users manager loaded after log in?

**Comment by diosmosis** [comment]
@tsteur It doesn't, but this doesn't work on 3.x-dev for me either. (To be clear that's: login, load users manager, logout, log back in, see dashboard not users manager.)

**Comment by tsteur** [comment]
What happens when you do `load users manager, login`? I think we added some feature to do that... but maybe it isn't merged yet or so

**Comment by diosmosis** [comment]
Would there need to be anonymous access to a site to do that? I'm not sure how I'd get past the login page w/o logging in.

**Comment by tsteur** [comment]
@diosmosis I might be understanding it wrong... it was implemented here: https://github.com/matomo-org/matomo/pull/13441

When you open eg `https://example.com/index.php?module=UsersManager&action=userSettings&idSite=1&period=day&date=yesterday` , then it should show the login form on that page... once you log in, it should show the same page again. Not sure if that URL would now redirect to login page?

**Comment by fdellwing** [comment]
It might be naive, but why is `!$this->shouldHandleRememberMe()` even called? Why not just take a look at `$_POST['form_rememberme']` and if it is there set expires? Wouldn't that instantaniosly solve #14075 and not touch any redirect logic that is present in Matomo?

**Comment by diosmosis** [comment]
@tsteur I see, it should remember the URL, was testing incorrectly.

@fdellwing it's only needed to perform that logic in a single controller action, and w/o that check, the logic could be triggered by a user by simply adding a query parameter. To protect against future bugs/exploits that could arise w/ new features written in completely different places by people who are not aware or have forgotten about this specific code path, we restrict the code's execution to exactly where it needs to be used.

**Comment by diosmosis** [comment]
@tsteur interestingly enough, that feature still works, but remember me doesn't...

**Comment by diosmosis** [comment]
@tsteur updated the code and tweaked the URL retaining feature. Now it posts to `module=Login` and gets the referrer URL from a POST parameter. Can you check if this works for you?

File: plugins/Login/FormLogin.php [hunk 1]
```diff
@@ -19,6 +19,7 @@ class FormLogin extends QuickForm2
 {
     function __construct($id = 'login_form', $method = 'post', $attributes = null, $trackSubmit = false)
     {
+        $attributes = array_merge($attributes ?: [], [ 'action' => '?module=Login' ]);
```
Comment (tsteur) [inline plugins/Login/FormLogin.php]: Would this need to be `getLoginPluginName()` in case a different login plugin is active? instead of hard coded `Login`

**Comment by fdellwing** [comment]
Patch seems to work for me.

File: plugins/Login/FormLogin.php (hunk 1 above)
Comment (diosmosis) [reply plugins/Login/FormLogin.php]: 👍 makes sense

**Comment by tsteur** [comment]
@diosmosis I got redirected to this:

image

What I did was open `https://apache.matomo/index.php?module=UsersManager&action=userSettings&idSite=1&period=day&date=yesterday` and then logged in.

It was supposed to render userSettings but it is rendering users manager because of the wrong URL `&amp;`

**Comment by diosmosis** [comment]
@tsteur should be fixed.

File: plugins/Login/Controller.php [hunk 2]
```diff
@@ -303,14 +303,15 @@ protected function authenticateAndRedirect($login, $password, $urlToRedirect = f
...
         if (empty($urlToRedirect)) {
-            $referrer = Url::getReferrer();
-            $module = Common::getRequestVar('module', '', 'string');
+            $redirect = Common::unsanitizeInputValue(Common::getRequestVar('form_redirect', false));
+            $redirectParams = UrlHelper::getArrayFromQueryString(UrlHelper::getQueryFromUrl($redirect));
+            $module = Common::getRequestVar('module', '', 'string', $redirectParams);
             // when module is login, we redirect to home...
-            if ($module !== 'Login' && $module !== Piwik::getLoginPluginName() && $referrer) {
-                $host = Url::getHostFromUrl($referrer);
+            if ($module !== 'Login' && $module !== Piwik::getLoginPluginName() && $redirect) {
```
Comment (tsteur) [inline plugins/Login/Controller.php]: Be good to check that `$module` is not empty...

Comment (tsteur) [reply plugins/Login/Controller.php]: may actually not be needed though because we do validate a host is set below just seeing

File: plugins/Login/Controller.php [hunk 3]
```diff
@@ -303,14 +303,15 @@ protected function authenticateAndRedirect($login, $password, $urlToRedirect = f
...
+                $host = Url::getHostFromUrl($redirect);
                 // we only redirect to a trusted host
                 if ($host && Url::isValidHost($host)) {
```
Comment (tsteur) [inline plugins/Login/Controller.php]: I just realised I should have maybe adjusted the description for the config setting

```
; Whether to enable trusted host checking. This can be disabled if you're running Matomo
; on several URLs and do not wish to constantly edit the trusted host list.
enable_trusted_host_check = 1
```

When disabled, you can redirect any user to any url... and now that it's even possible by GET parameter and not referrer it may be even more important. Basically, when the setting is disabled, you can link to `https://demo.matomo.org?...&redirect=https://demo.maomo.org` for example and after the succeeded login, the user would be redirected to that page. This could be some security issue if you ask the user on that similar domain to enter the password again. Wonder how we could mention it in the config? In general we should not recommend users to disable the trusted host check.

Comment (diosmosis) [reply plugins/Login/Controller.php]: What if we also check that the host in the URL is the same as the Host header? Then the only way to force a redirect to a different domain, would be to send a curl request w/ the changed Host header.

Comment (tsteur) [reply plugins/Login/Controller.php]: sounds good

File: plugins/Login/Controller.php [hunk 4]
```diff
@@ -307,10 +307,12 @@ protected function authenticateAndRedirect($login, $password, $urlToRedirect = f
             $redirectParams = UrlHelper::getArrayFromQueryString(UrlHelper::getQueryFromUrl($redirect));
             $module = Common::getRequestVar('module', '', 'string', $redirectParams);
             // when module is login, we redirect to home...
-            if ($module !== 'Login' && $module !== Piwik::getLoginPluginName() && $redirect) {
+            if (!empty($module) && $module !== 'Login' && $module !== Piwik::getLoginPluginName() && $redirect) {
                 $host = Url::getHostFromUrl($redirect);
                 // we only redirect to a trusted host
-                if ($host && Url::isValidHost($host)) {
+                if ($host == Url::getHost()
```
Comment (tsteur) [inline plugins/Login/Controller.php]: we probably still need to check `!empty($host)` as `getHost()` may return an empty host when the config setting is disabled for example. It would be able to trick matomo into redirecting maybe when providing some weird URL although I don't really think it's possible and it should be all fine without the !empty but better be safe maybe.

**Review by tsteur — APPROVED** [review]
