### PR TITLE
Automatically remove duplicate invalidations upon reset

### LINKED ISSUE #22972: Automatic Cleanup of Duplicate Invalidation Records Upon Reset
### Background  
In Matomo's current archiving process, when an invalidation request is created, the system checks whether an identical invalidation already exists. If an identical entry is found, a new invalidation is not created, as the existing one will be processed anyway.  

However, if an invalidation is already in progress and a new identical request is made, the system assumes that the currently processed invalidation might result in outdated data and therefore stores the new request.  

A potential issue arises when an in-progress invalidation is interrupted (e.g., due to a crash) but remains marked as "started." While the system is designed to automatically reset such invalidations after 24 hours, it does not currently check for newer identical requests. This can result in duplicate invalidations in the database, leading to unnecessary resource consumption during data aggregation.  

### Proposed Solution  
To optimize resource usage and avoid redundant processing, we propose implementing an automatic cleanup mechanism that performs the following actions when resetting an invalidation after 24 hours:  

**Check for newer identical invalidation records:**  
  - If a newer identical request exists, the older request should be removed instead of being reset and reprocessed.  
  - If no newer identical request exists, the invalidation should be reset as usual.  

### Benefits  
- **Reduced Resource Consumption:** Prevents redundant data aggregation by avoiding duplicate processing.  
- **Improved System Efficiency:** Frees up processing power for other tasks by eliminating unnecessary operations.  
- **Enhanced Data Accuracy:** Ensures that only the most up-to-date invalidation request is processed.  

### Implementation Considerations  
- The cleanup process should be integrated into the existing invalidation reset logic.  
- Logging should be added to track cleanup actions for auditing purposes.  
- The mechanism should ensure it does not inadvertently remove valid pending invalidations.  

---

This request provides a structured and clear outline of the problem, solution, and benefits while ensuring a professional tone suitable for GitHub.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

Currently invalidations might be reset when they are either considered stuck (after 24 hours) or with using the new `core:reset-invalidations` command. 

However, both ways currently simply reset the in progress invalidations, without checking if there might be other identical invalidations not yet been started.

This might cause unneeded archiving work, as a freshly built archive might be directly rebuilt through the other exisiting invalidtion afterwards.

To ensure that won't happen any longer, this PR introduce some additional checks so that duplicate invalidations are being removed instead of reset.

fixes #22972

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/DataAccess/Model.php [hunk 1]
```diff
@@ -1002,11 +1020,84 @@ private function getRemoveInvalidationsIdSitesClause($idSite)
         return "idsite IN ($idSitesStr) AND";
     }
 
-    public function releaseInProgressInvalidation($idinvalidation)
+    /**
+     * Releases in progress invalidations for the given ids
+     *
+     * To avoid duplicate invalidations in the database, the method is also meant to prevent having duplicates after a reset
+     * Therefor below code will check if any of the invalidations to be reset should be removed instead
+     * An invalidation can be savely removed
```
Comment (mneudert) [inline core/DataAccess/Model.php]:
```suggestion
     * An invalidation can be safely removed
```

File: core/DataAccess/Model.php [hunk 2]
```diff
@@ -1002,11 +1020,84 @@ private function getRemoveInvalidationsIdSitesClause($idSite)
...
-        $sql = "UPDATE $table SET status = " . ArchiveInvalidator::INVALIDATION_STATUS_QUEUED . ", ts_started = NULL, processing_host = NULL, process_id = NULL WHERE idinvalidation = ?";
-        Db::query($sql, [$idinvalidation]);
+        $changedCount = 0;
+
+        $sql = "SELECT * FROM $table WHERE idinvalidation IN (" . implode(',', $idinvalidations) . ")";
+        $invalidations = Db::fetchAll($sql);
+
+        // Check invalidations one by one, to ensure we safely remove invalidations in cases where two identical ones are requested to reset
+        foreach ($invalidations as $invalidation) {
+            // Look for other indentical invalidations that are either not started or started after the current one had been invalidated
```
Comment (mneudert) [inline core/DataAccess/Model.php]:
```suggestion
            // Look for other identical invalidations that are either not started or started after the current one had been invalidated
```

File: core/DataAccess/Model.php [hunk 3]
```diff
@@ -1002,11 +1020,84 @@ private function getRemoveInvalidationsIdSitesClause($idSite)
...
+            $query = "SELECT COUNT(*) FROM $table WHERE name = ? AND idsite = ? AND date1 = ? AND date2 = ? AND period = ? AND "
+                   . "(status = ? OR (status = ? AND ts_started > ?)) AND idinvalidation != " . $invalidation['idinvalidation'];
```
Comment (mneudert) [inline core/DataAccess/Model.php]:
```suggestion
                   . "(status = ? OR (status = ? AND ts_started > ?)) AND idinvalidation != ?";
```

Just to be consistent?

File: plugins/CoreAdminHome/tests/Integration/Commands/ResetInvalidationsTest.php [hunk 4]
```diff
@@ -272,6 +272,264 @@ public function getDryRunTestData(): iterable
...
+                'report' => null, 'ts_started' => '2025-01-01 08:00:00', 'processing_host' => 'host4', 'process_id' => 22555
+            ],
+        ];
+
+        $sql = 'INSERT INTO ' . Common::prefixTable('archive_invalidations')
+            . ' (`idarchive`, `name`, `idsite`, `date1`, `date2`, `period`, `ts_invalidated`, `status`, `report`, `ts_started`, `processing_host`, `process_id`)'
+            . ' VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
+
+        foreach ($invalidationsToInsert as $invalidation) {
+            Db::query($sql, $invalidation);
```
Comment (mneudert) [inline plugins/CoreAdminHome/tests/Integration/Commands/ResetInvalidationsTest.php]:
```suggestion
            Db::query($sql, array_values($invalidation));
```

Because we can't have nice things at the moment:

> ArgumentCountError: mysqli_stmt::bind_param() does not accept unknown named parameters

Should we move all those inserts into something like `$this->insertInvalidations($invalidationsToInsert)`? Otherwise there are more occurrences that require the `array_values` workaround (so we can keep "readable" invalidation arrays) for php8-mysqli.

**Review by mneudert — CHANGES_REQUESTED** [review]

**Review by mneudert — APPROVED** [review]
