### PR TITLE
Prevent logging tracking failure for obviously malformed idsite or token auth

### LINKED ISSUE #20525: False alerts "Invalid idSite: '0'" when someone tries to SQLi this parameter
## Context
On a website where Matomo is correctly configured, some attackers try to find vulnerabilities by sending requests like:

`/piwik.php?idsite=1%27%20AND%20EXTRACTVALUE%283565%2CCONCAT%280x5c%2C0x7162706271%2C%28SELECT%20%28ELT%283565%3D3565%2C1%29%29%29%2C0x71766b6b71%29%29%20AND%20%27KCzU%27%3D%27KCzU&rec=1&bots=1`

which is obviously an attempt of SQL injection (SQLi).

## Current Behaviour

Given the parameter idsite is sanitised and converted to an integer (and 0 in case of error), this type of request is interpreted as a tracking error labelled "The site does not exist.".

On one website I am managing (20k visits/day), it is triggered about once a day (since it is de-duplicated, actual access logs show the attackers try sometimes 30 different SQLi requests).

## Expected Behavior

Matomo administrators should not be warned (at least not this way) of these "tracking errors" since it is **out of their control**: it is a 400 Bad Request from the (malicious) user (see #6661).

## Possible Solution

Try to detect these "false alerts", it has to be discussed how to characterise them. It can be for instance:
1. presence of parameter idsite but resulting idsite is 0,
2. non-empty parameter idsite but resulting idsite is 0,
3. non-numeric parameter idsite,
4. the parameter idsite contains "AND" or "SELECT" or "ORDER" (some common SQL words).

I think the 4th solution is the more robust to catch SQLi and at the same time keep the effectiveness of the warning for real misconfigurations.

## Steps to Reproduce (for Bugs)

1. Call the endpoint `/piwik.php?idsite=1%27%20AND%20EXTRACTVALUE%283565%2CCONCAT%280x5c%2C0x7162706271%2C%28SELECT%20%28ELT%283565%3D3565%2C1%29%29%29%2C0x71766b6b71%29%29%20AND%20%27KCzU%27%3D%27KCzU&rec=1&bots=1`
2. It triggers a tracking error `Invalid idSite: '0'` you can see as administrator in Administration > Diagnostic > Tracking failures.

## Your Environment
* Matomo Version: 4.14.1
* PHP Version: not relevant
* Server Operating System: not relevant
* Additionally installed plugins: not relevant
* Browser: not relevant
* Operating System: not relevant

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

This is currently based on #23725, as that one moved some code around that needs adjustments here.

fixes #20525

### Checklist

- [NA] I have understood, reviewed, and tested all AI outputs before use
- [NA] All AI instructions respect security, IP, and privacy rules

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/Tracker/RequestHandlerTrait.php [hunk 1]
```diff
@@ -31,10 +31,12 @@ protected function checkSiteExists(Request $request): void
         try {
             $request->getIdSite();
         } catch (UnexpectedWebsiteFoundException $e) {
-            // we allow 0... the request will fail anyway as the site won't exist... allowing 0 will help us
-            // reporting this tracking problem as it is a common issue. Otherwise we would not be able to report
-            // this problem in tracking failures
-            StaticContainer::get(Failures::class)->logFailure(Failures::FAILURE_ID_INVALID_SITE, $request);
+            $idSite = $this->request->getRawParams()['idsite'] ?? null;
```
Comment (mneudert) [inline core/Tracker/RequestHandlerTrait.php]:
```suggestion
            $idSite = $request->getRawParams()['idsite'] ?? null;
```

The request "should" always be set in the classes using the trait, but as we also get it as a function parameter we don't need to couple it to that.

**Review by mneudert — CHANGES_REQUESTED** [review]

**Review by mneudert — APPROVED** [review]
