### PR TITLE
Hide segments containing expressions from disabled plugins or features

### LINKED ISSUE #21318: When disabling visitor profile feature, then also disable related segment to prevent archiving from failing
## Context
You can currently disable the visitor profile (and visits log) feature. Then certain segments like UserID and visitorId disappear and are no longer valid.

However, segments may already exist that use one of these disabled dimensions..

## Expected Behavior
The segments are deleted so that archiving doesn't fail.

## Current Behavior
Archiving fails. In worst case our scheduled tasks no longer run which could have side effects such as scheduled reports and custom alerts to be no longer sent, billing being inaccurate, etc.

> Uncaught exception in API: Exception: Segment 'visitorId' is not a supported segment. in /core/Segment.php:228 Stack trace: #0 /core/Segment.php(276): Piwik\Segment->getSegmentByName('visitorId') #1 //core/Segment.php(254): Piwik\Segment->getExpressionsWithUnionsResolved(Array) #2 /core/Segment.php(168): Piwik\Segment->initializeSegment('visitorId==0124...', Array) #3 /plugins/CoreAdminHome/API.php(284)

## Possible Solution
Maybe delete those segments? Not sure what we're doing currently when we're deactivating a plugin whose dimensions are used in segments?

## Your Environment
Latest Matomo 4.x

### LINKED ISSUE #21339: Matomo 5 Upgrade issue, userId is not a supported segment, archiving fails
This is likely related to https://github.com/matomo-org/matomo/pull/21218/files

refs https://github.com/matomo-org/matomo/issues/21318

We updated to Matomo 5, now archiving fails for some customers with below error and reports are no longer being processed. The update should probably delete any segment that uses this segment as it's no longer available for the given site?

> [2023-10-02 21:06:08] piwik.ERROR: Uncaught exception in API: Exception: Segment \'userId\' is not a supported segment. in /Segment.php:235 Stack trace: #0 /Segment.php(283): Piwik\\Segment->getSegmentByName(\'userId\') #1 /Segment.php(261): Piwik\\Segment->getExpressionsWithUnionsResolved(Array) #2 /Segment.php(169): Piwik\\Segment->initializeSegment(\'userId!=\', Array) #3 /var/www/html/plugins/CoreAdminHome/API.php(285): Piwik\\Segment->__construct(\'userId%21%3D\', Array, Object(Piwik\\Date), Object(Piwik\\Date)) #4 [internal function]: Piwik\\Plugins\\CoreAdminHome\\API->archiveReports(\'47\', Object(Piwik\\Period\\Month), \'2023-10-01\', \'userId%21%3D\', false, false) #5 /API/Proxy.php(255): call_user_func_array(Array, Array) #6 /Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}() #7 /API/Proxy.php(346): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure)) #8 /API/Request.php(272): Piwik\\API\\Proxy->call(\'\\\\Piwik\\\\Plugins\\\\...\', \'archiveReports\', Array) #9 /var/www/html/plugins/API/Controller.php(45): Piwik\\API\\Request->process() #10 [internal function]: Piwik\\Plugins\\API\\Controller->index() #11 /FrontController.php(637): call_user_func_array(Array, Array) #12 /FrontController.php(169): Piwik\\FrontController->doDispatch(\'API\', false, Array) #13 /dispatch.php(32): Piwik\\FrontController->dispatch() #14 /var/www/html/index.php(25): require_once(\'/var/www/html/c...\') #15 /CliMulti/RequestCommand.php(75): require_once(\'/var/www/html/i...\') #16 /Plugin/ConsoleCommand.php(110): Piwik\\CliMulti\\Req

### PR DESCRIPTION
**Pull request by bx80**
### Description:

refs #21339
Fixes #21318

When an attempt is made to use a segment which contains expressions referencing a disabled dimension then the exception `Segment '$name' is not a supported segment.` is thrown. 

This can happen when a plugin is disabled or if certain features which provide segments are turned off, such as the visitor profile.

For the cron-based archiving process the exception is caught and a non-fatal info message is shown.

In the Matomo dashboard segments containing unavailable expressions can still be chosen in the segment selector and doing so will result in fatal errors as API calls to retrieve segment data will encounter the `Segment '$name' is not a supported segment.` error and return HTTP 500 codes.

### How to recreate

To recreate this issue try the following steps:

- Make sure browser_archiving_disabled_enforce = 1 is not set in `config.ini.php`
- Create a new segment with the definition "visitorId==4b3d9389bae51466"
- Disable visitor profiles in general settings (Live -> "Turn off visitor log and visitor profiles")
- Switch to the new segment in the dashboard
- View the goals overview page (or any other page loading widget data)
- A front end exception will be shown and an error logged `Error: Segment 'visitorId' is not a supported segment.`

### What this PR does

This PR filters the list of segments shown in the segment selector to remove any segments which contain unavailable expressions. If the disabled plugin or feature is re-enabled then the segments will immediately be available again.

Integration tests are included which check availability of test segments for disabled visitor id, disabled user id and a disabled plugin segment.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: tests/PHPUnit/Integration/Segment/SegmentUnavailableTest.php [hunk 1]
```diff
@@ -0,0 +1,186 @@
...
+        FakeAccess::$superUserLogin = 'superusertest';
+        APISitesManager::getInstance()->addSite('test', 'http://example.org');
+
+        Option::set(Rules::OPTION_BROWSER_TRIGGER_ARCHIVING, 0);
+    }
+
+    public function tearDown() : void
+    {
+        parent::tearDown();
+        Option::set(Rules::OPTION_BROWSER_TRIGGER_ARCHIVING, 1);
```
Comment (michalkleiner) [inline tests/PHPUnit/Integration/Segment/SegmentUnavailableTest.php:48]: Should we do `Option::get` in the `setUp` method saving the value into an instance property and then restore it here to what it was? It may not matter much but feels cleaner than explicitly setting it to on for any tests coming after this test. Might cause more flakiness. No strong feelings about it either way, so happy to let it be.

File: plugins/SegmentEditor/API.php [hunk 2]
```diff
@@ -395,11 +395,37 @@ public function getAll($idSite = false)
...
+    private function filterSegmentsWithDisabledElements(array $segments, $idSite = false): array
+    {
+        $sites = [];
+        if (!empty($idSite)) {
+            $sites = [$idSite];
+        }
+
+        foreach ($segments as $k => $segment) {
+            try {
+                new Segment($segment['definition'], $sites);
```
Comment (michalkleiner) [inline plugins/SegmentEditor/API.php:421]: I guess without having any structured way of recording what segment uses what dimensions/metrics and then using that when the providers of those are disabled this might be the best way how to test if a segment can be created.

Or did you consider any other approaches?

File: plugins/SegmentEditor/API.php [hunk 3]
```diff
@@ -395,11 +395,37 @@ public function getAll($idSite = false)
...
+     * @param array $segments
+     * @param       $idSite
+     *
+     * @return array
+     */
+    private function filterSegmentsWithDisabledElements(array $segments, $idSite = false): array
+    {
+        $sites = [];
+        if (!empty($idSite)) {
+            $sites = [$idSite];
```
Comment (michalkleiner) [inline plugins/SegmentEditor/API.php]: Would something like this be needed here or idSite may never be provided as an array?

```suggestion
            $sites = is_array($idSite) ? $idSite : [$idSite];
```

File: tests/PHPUnit/Integration/Segment/SegmentUnavailableTest.php (hunk 1 above)
Comment (bx80) [reply tests/PHPUnit/Integration/Segment/SegmentUnavailableTest.php:48]: I considered doing that, but then checked what other tests were doing and decided consistency is the better part of valour :slightly_smiling_face:

File: plugins/SegmentEditor/API.php (hunk 2 above)
Comment (bx80) [reply plugins/SegmentEditor/API.php:421]: The segment instantiation is where the problem exception is thrown and appears to be quite lightweight as it checks a list of cached segments to see if the segment is available. I could have replicated this logic in a slightly more efficient manner but then these two areas would need to be kept in sync. Without implementing some sort of segment dependency system this seems like the simplest and lowest risk approach.

File: plugins/SegmentEditor/API.php (hunk 3 above)
Comment (bx80) [reply plugins/SegmentEditor/API.php]: The parent parameter documentation for idSite says bool|int, but it's not actually typed so it's possible that an array could be passed, might be good to be defensive here :+1:

**Review by michalkleiner — APPROVED** [review]
Looks good to me, failing tests are unrelated.
Let's see what @sgiehl thinks.

**Comment by sgiehl** [comment]
I had some thoughts around this topic. Did you consider the following scenario when creating/testing this PR:
A segment can be create for a specific website, but also globally. In addition a segment can be valid for one website, while it can be invalid for another. e.g. Disabling the visits log is possible globally, but also in the settings for each website.
How does the UI and archiving behave for segments that are available globally and only invalid for a specific website?

**Comment by bx80** [comment]
> How does the UI and archiving behave for segments that are available globally and only invalid for a specific website?

Archiving will catch the exception thrown when trying to initialize the warning and then skip the segment, nothing has changed there.

For the UI, we're checking each segment against the current site before adding it to the segment selector, so if there is a globally available segment it will be checked for validity against the currently chosen site and only added to the site selector if it is valid. If the user then changes site the globally available segment will be checked again for the new site.

**Comment by sgiehl** [comment]
Ok. So for hiding unavailable segments from the UI the approach works nicely. In terms of archiving we might need to do some more testing. I'll merge this PR already, as we can implement further changes in a new PR if needed.
