### PR TITLE
Fix outlinks and downloads are not tracked if document is already ready when piwik.js is loaded

### LINKED ISSUE #9924: Outlinks and downloads not being tracked in Firefox
From simple test turns out that outlinks are not being tracked in Firefox. Checked on my Mac on newest stable versions of Chrome and FF, Customer tested on Windows versions. Customer that submitted this bug have come up with a suggestion on what might be wrong:

> The function "addEventListener" line 1189 in "Piwik.js" (not minifier version) is not taking into account if the document is loaded or not (readyState === complete ) meaning the functions linked to this one are not executed.
> It could work if piwik.js is altered at the beginning of the "addEventListener" function (ligne 1189):
> if (eventType === "load" && documentAlias.readyState === "complete")
> { eventHandler(); return; }

Please review this and mention me with any further info.

### PR DESCRIPTION
**Pull request by tsteur**
This should fix #9924 

I tested it in Chrome and Firefox so far. If website was already loaded we will now execute the enableLinkTracking logic directly.

### CODE REVIEW

File: js/piwik.js [hunk 1]
```diff
@@ -4689,7 +4619,7 @@ if (typeof window.Piwik !== 'object') {
                 } else if (windowAlias.addEventListener) {
                     windowAlias.addEventListener('load', callback);
                 } else if (windowAlias.attachEvent) {
-                    windowAlias.attachEvent('onLoad', callback);
+                    windowAlias.attachEvent('onload', callback);
```
Comment (tsteur) [inline js/piwik.js]: Should be all lowercase actually. Possibly `onLoad` works as well but lowercase is better

File: js/piwik.js [hunk 2]
```diff
@@ -4708,7 +4638,11 @@ if (typeof window.Piwik !== 'object') {
                 } else if (documentAlias.addEventListener) {
                     documentAlias.addEventListener('DOMContentLoaded', callback);
                 } else if (documentAlias.attachEvent) {
-                    documentAlias.attachEvent('onreadystatechange', callback);
+                    documentAlias.attachEvent('onreadystatechange', function () {
+                        if (documentAlias.readyState === 'complete') {
```
Comment (tsteur) [inline js/piwik.js]: `onreadystatechange` might be actually triggered twice. When it changes to interactive and when it changes to complete. We want to execute it only once.

File: js/piwik.js [hunk 3]
```diff
@@ -6447,7 +6377,6 @@ if (typeof window.Piwik !== 'object') {
 
         // initialize the Piwik singleton
         addEventListener(windowAlias, 'beforeunload', beforeUnloadHandler, false);
-        addReadyListener();
```
Comment (tsteur) [inline js/piwik.js]: All this was not needed / used anymore.

File: js/piwik.js [hunk 4]
```diff
@@ -1068,10 +1068,6 @@ if (typeof window.Piwik !== 'object') {
             /* performance timing */
             performanceAlias = windowAlias.performance || windowAlias.mozPerformance || windowAlias.msPerformance || windowAlias.webkitPerformance,
 
-            /* DOM Ready */
-            hasLoaded = false,
-            registeredOnLoadHandlers = [],
```
Comment (tsteur) [inline js/piwik.js]: registeredOnLoadHandlers + hasLoaded was only used for enableLinkTracking.

enableLinkTracking now uses existing `trackCallbackOnReady` instead

File: js/piwik.js [hunk 5]
```diff
@@ -1247,72 +1243,6 @@ if (typeof window.Piwik !== 'object') {
...
-                                return;
-                            }
-                            loadHandler();
-                        }
-                    }());
-                }
-            }
-
-            // sniff for older WebKit versions
-            if ((new RegExp('WebKit')).test(navigatorAlias.userAgent)) {
```
Comment (tsteur) [inline js/piwik.js]: I totally removed this one as I think it's not needed anymore and it can actually slow down all websites in WebKit for a while for quite a bit. It executed this every 10ms until websites was ready. As it sometimes takes a few seconds until a website is ready it executes this quite often.

**Comment by mattab** [comment]
@tsteur do you mind testing that it still works fine on IE10 / IE11 or so?

Once confirmed +1 to merge this PR :+1: (note: there is currently a conflict, maybe you can remove the merged piwik.js from the commit)

**Comment by tsteur** [comment]
Tested on IE10 and works. Will merge and do afterwards some more tests

**Comment by tsteur** [comment]
I tested with IE8 and the callback works. I had some other problems tracking outlinks on IE8 but that was due to debugging mode likely.
