### PR TITLE
Add return type to satisfy interface implementation and fix deprecation warning

### LINKED ISSUE #20627: [PHP 8.1 compatibility] deprecation warning — Return type of RequiredPhpSetting::jsonSerialize
WARNING: /plugins/Diagnostics/Diagnostic/RequiredPhpSetting.php(104): Deprecated - Return type of Piwik\Plugins\Diagnostics\Diagnostic\RequiredPhpSetting::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice - Matomo 5.0.0-b1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)

### PR DESCRIPTION
**Pull request by michalkleiner**
### Description:

Add return type `mixed` to satisfy the interface the class is implementing. 

fixes #20627

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/Diagnostics/Diagnostic/RequiredPhpSetting.php [hunk 1]
```diff
@@ -101,7 +101,7 @@ public function __toString()
         return $this->setting . ' ' . implode(' OR ', $checks);
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
```
Comment (sgiehl) [inline plugins/Diagnostics/Diagnostic/RequiredPhpSetting.php]: @michalkleiner The typehint `mixed` was introduced with PHP 8.0. See https://www.php.net/manual/en/language.types.declarations.php
So we can't use it as our code needs to be compatible with PHP 7.2+

Comment (michalkleiner) [reply plugins/Diagnostics/Diagnostic/RequiredPhpSetting.php]: In that case we can't be implementing `\JsonSerializable` since that's the cause of the warning.

Comment (sgiehl) [reply plugins/Diagnostics/Diagnostic/RequiredPhpSetting.php]: It can be suppressed using the `#[\ReturnTypeWillChange]` comment

Comment (michalkleiner) [reply plugins/Diagnostics/Diagnostic/RequiredPhpSetting.php]: Yep, that was the alternative solution. Will update the PR to add that instead of the return type.

Comment (michalkleiner) [reply plugins/Diagnostics/Diagnostic/RequiredPhpSetting.php]: PR updated

Comment (sgiehl) [reply plugins/Diagnostics/Diagnostic/RequiredPhpSetting.php]: @michalkleiner I just had another thought on that. Actually we could also simply set `string` as return type hint.
As this is more specific as `mixed`, it should be compatible with that definition, but should be a lot better than the `ReturnTypeWillChange` workaround.

Comment (michalkleiner) [reply plugins/Diagnostics/Diagnostic/RequiredPhpSetting.php]: Yep, that works for me. Updated the PR to that effect. Do we want to add it to the `__toString` method as well since that's the direct source of the output for the method in question?

Comment (sgiehl) [reply plugins/Diagnostics/Diagnostic/RequiredPhpSetting.php]: Yes. why not.
Imho we should try to add return types where ever it is safely possible.

**Review by sgiehl — APPROVED** [review]
