### PR TITLE
Multisite links to reports now pass token_auth

### LINKED ISSUE #17001: When embedding a widget with the "Multisites" report (All websites), the links are not working
I embed the Multisite Widget into an Ifram on my page. The iframe is showing nicely all websites with a view permission. So far so good. The problem begins if I click on a website link. I get redirected and have to login. It  would be much better if the auth_token is added to the dashboard deeplinks. This will make it possible to get on overview of all websites and switch between them.

I added the auth_token directly to the website dashboard deeplink and it worked aout of the box.

### PR DESCRIPTION
**Pull request by justinvelluppillai**
### Description:

Fixes #17001 

Pass token_auth parameter so embedded widget links log user in to their matomo dashboard when they click to view full reports.

### Review

* [ ] Functional review done
* [ ] Potential edge cases thought about (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/MultiSites/angularjs/site/site.controller.js [hunk 1]
```diff
@@ -13,20 +13,24 @@
...
         };
 
-        function sparklineImage(website){
-            var append = '';
+        function tokenParam() {
             var token_auth = piwik.broadcast.getValueFromUrl('token_auth');
-            if (token_auth.length) {
-                append = '&token_auth=' + token_auth;
-            }
+            return token_auth.length ? '&token_auth=' + token_auth : '';
```
Comment (diosmosis) [inline plugins/MultiSites/angularjs/site/site.controller.js:26]: I think here we can just use `piwik.token_auth`. Does that work as well? It should always be set too, since when logged in we have to send it on every HTTP request.

Comment (diosmosis) [reply plugins/MultiSites/angularjs/site/site.controller.js:26]: I just noticed it was like that before... not sure if there was a reason for that.

Comment (diosmosis) [reply plugins/MultiSites/angularjs/site/site.controller.js:26]: I see nevermind, I understand the reasoning now.

**Comment by diosmosis** [comment]
Tested locally, everything works :+1:
