### PR TITLE
Ensure to use unsanitized parameters for API request

### LINKED ISSUE #20030: Performance report not working from pages report when segment is in use
## Expected Behavior
User should be able to use lower/greater than signs (< >) in segment names.
The pages report should show performance reports whether a segment is in use or not.

## Current Behavior
When selecting Performance icon from Pages report when segment is being used, the UI gives an error:
"Error: The segment condition 'actions&gt' is not valid." After this the menu disappears, too.

We found out that if the segment contains a suitable condition such as greater than (>), then the url will contain that character as html-encoded ( & gt; ) and the url of the user interface link will be broken with a semicolon. This only happens from the pages report when clicking the performance icon.

## Steps to Reproduce (for Bugs)
- Rename a segment so it has lower than or greater than sign in the name.
- Select Performance icon from Pages while also using the renamed segment.

## Your Environment
PHP version: 8.0.22
MySQL version: 10.1.36-MariaDB
Matomo version: 4.10.1

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #20030

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/PagePerformance/tests/UI/PagePerformance_spec.js [hunk 1]
```diff
@@ -102,7 +102,7 @@ describe("PagePerformance", function () {
     });
 
     it("performance overlay should work on page titles report", async function () {
-        await page.goto("?" + urlBase + "#?" + generalParams + "&category=General_Actions&subcategory=Actions_SubmenuPageTitles");
+        await page.goto("?" + urlBase + "#?" + generalParams + "&segment=actions>=1&category=General_Actions&subcategory=Actions_SubmenuPageTitles");
```
Comment (sgiehl) [inline plugins/PagePerformance/tests/UI/PagePerformance_spec.js:105]: Note: This change does not result in a changed expected file, as the segment covers all visits. But without the other changes, this test would fail

**Review by peterhashair — APPROVED** [review]
Looks good to me, working as expected. 
* [x] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [x] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [x] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [x] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [x] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [x] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [x] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [x] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [x] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
