### PR TITLE
Throw invalid dimension exception during rendering graph with wrong height/width values

### LINKED ISSUE #17092: fatal error: Modulo by zero: method=imageGraph while widht = 0
I called the API by this:
/index.php?module=API&method=ImageGraph.get&idSite=1&token_auth=xxxxxxxxxxxxx&period=month&date=previous24&apiModule=VisitsSummary&apiAction=get&graphType=evolution&width=0&height=2

and got this fatal error message

grafik

width = 0 AND height != 0

width = 0 and height = 0 => it works fine.

### PR DESCRIPTION
**Pull request by flamisz**
### Description:

fixes #17092 

The package we use for rendering graphs has a bug. To avoid run into that bug, we can check the values we send to the package and if the values would cause the modulo zero error we throw an exception instead. 
Our plugin throws the exceptions as an image by default, but for this error it's not that useful, because usually it happens when the height value is too small, so the user wouldn't be able to read the error message. 
For this specific exception I used the default way.

### Review

* [ ] Functional review done
* [ ] Potential edge cases thought about (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by sgiehl** [comment]
Wondering if it might make more sense to define lower limits for height & weight and automatically set those parameters to the lower limit if they are smaller. That way we could avoid any exception at all.

**Comment by flamisz** [comment]
> Wondering if it might make more sense to define lower limits for height & weight and automatically set those parameters to the lower limit if they are smaller. That way we could avoid any exception at all.

Hey @sgiehl, me and @tsteur were talking about that, and I could calculate that, but if the user wants a lower number, and the graph will be higher, maybe she/he will think it is a bug. Hard to tell which is the better solution, but probably it is something that happens very rarely.

**Comment by tsteur** [comment]
@sgiehl the thought was that if we automatically change a height or width then it will look like a bug and we're getting bug reports and emails about it vs this way it's clear what the problem is and they can change the parameters to a higher number.

**Comment by sgiehl** [comment]
Thought we would have it that way in other places, but wasn't able to find one right now. But it's also fine this way.

File: plugins/ImageGraph/API.php [hunk 1]
```diff
@@ -493,6 +494,8 @@ public function get(
 
             // render graph
             $graph->renderGraph();
+        } catch (InvalidDimensionException $e) {
+            throw new Exception('Error: the graph dimension is not valid. Please try larger width and height values or use 0 for default values.');
```
Comment (sgiehl) [inline plugins/ImageGraph/API.php]: Any reason for not simply re-throwing the caught exception and setting the message where the exception actually occurs?

Comment (flamisz) [reply plugins/ImageGraph/API.php]: You're right, that's better solution 👍 , I'll make it like that.

**Review by sgiehl — APPROVED** [review]
