### PR TITLE
Full refactor of site content detection and no data page logic

### LINKED ISSUE #21200: Error message while accessing tracking code when Tour plugin is disabled
## Context
I disabled the Tour plugin.
When I try to access ⚙️ > Measurables  > Tracking Code
I get following red error message: `The plugin Tour is not enabled. You can activate the plugin on Settings > Plugins page in Matomo.`
In the log viewer, I see:
```
Uncaught exception in API: .../core/Plugin/Manager.php(303): The plugin Tour is not enabled. You can activate the plugin on Settings > Plugins page in Matomo. [Query: ?date=today&module=API&format=json&method=Tour.detectConsentManager&idSite=3&filter_limit=-1&segment=&period=day, CLI mode: 0]
```

## Expected Behavior
No error message when accessing the Tracking code section while Tour is disabled.

## Your Environment
* Matomo Version: 4.14.2
* PHP Version: 7.3.33
* Server Operating System: RedHat 7
* Additionally installed plugins:

## Plugins Activated:
 API, AbTesting 4.2.4, Actions, ActivityLog 4.1.2, AdminNotification 4.0.0, Annotations, AnonymousPiwikUsageMeasurement 4.1.0, BulkTracking, Cohorts 4.0.8, Contents, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, CoreVue, CustomDimensions, CustomJsTracker, CustomReports 4.1.4, CustomTranslations 4.1.1, CustomiseTranslations 1.0.3, DBStats, Dashboard, DevicePlugins, DevicesDetection, Diagnostics, Ecommerce, Events, ForceSSL 4.0.1, FormAnalytics 4.4.1, Funnels 4.1.6, Goals, GroupPermissions 4.0.5, Heartbeat, HeatmapSessionRecording 4.5.9, HidePasswordReset 4.3.3, ImageGraph, Insights, Installation, Intl, IntranetMeasurable, InvalidateReports 4.1.1, JsTrackerForceAsync 4.0.0, KPIWidgets 1.1.6, LanguagesManager, Live, LogViewer 4.1.1, LoginLdap 4.7.3, LoginSaml 4.3.0, MarketingCampaignsReporting 4.1.3, MediaAnalytics 4.2.1, Monolog, Morpheus, MultiSites, Overlay, PagePerformance, PrivacyManager, Proxy, QueuedTracking 4.0.7, Referrers, ReferrersManager 4.0.3, Resolution, RestrictLanguageSelection 4.0.2, RollUpReporting 4.1.3, ScheduledReports, SecurityInfo 4.0.2, SegmentEditor, SitesManager, TagManager, TasksTimetable 4.0.2, Transitions, TreemapVisualization 4.0.2, TwoFactorAuth, UserId, UserLanguage, UsersFlow 4.1.1, UsersManager, VisitFrequency, VisitTime, VisitorInterest, VisitsSummary, WebsiteMeasurable, WhiteLabel 4.0.8, Widgetize

## Plugins Deactivated:
 DiagnosticsExtended 0.1.9, Feedback, GeoIp2, LanguageToogle 0.3.5, Login, Marketplace, MobileAppMeasurable, MobileMessaging, ProfessionalServices, RssWidget, SEO, Tour, UserCountry, UserCountryMap

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

The site detection logic as well as the no data page has grown too rapidly with random new change requests resulting in an unmaintainable, mostly untested code, having direct dependencies to certain plugins with tons of technical dept.

This PR fully refactors all the logic around site content detection as well as the full handling of the no data page.
Everything should now be easier adjustable, reusable, replaceable and extendable by plugins (without having to add changes in core)

The site content detection will the have two major parts:
* class `Piwik\SiteContentDetector`
  this one will handle the overall detection as it was before
* multiple classes extending `Piwik\Plugins\SitesManager\SiteContentDetection\SiteContentDetectionAbstract`
  Those files define the detections we provide. e.g. WordPress, Cloudflare, Osano, ...
  In additional those classes can provide methods to render additional tabs or entries for the others tab on the no data page

The no data page basically still uses the SiteContentDetector to check what was detected or not. But all detection classes might now provide the own tab content. The order of the tabs is defined by a priority each class can provide. That way we can easily define which tab should be displayed if it was detected.

fixes #21200

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+    public function __construct()
+    {
+    }
+
+    /**
+     * Returns the ID of the current detection. Automatically built from the class name (without namespace)
+     *
+     * @return string
+     */
+    public static function getId(): string
```
Comment (caddoo) [inline plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php:32]: I would say simplify this and have the inheritor manually define the ID, the reason is because the ID is now coupled directly to the classname, and I can see this value is used in things like cache.

It could make refactoring class names difficult in future

File: plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+        return false;
+    }
+
+    /**
+     * Returns the content that should be rendered into a new Tab on the no data page
+     *
+     * @param SiteContentDetector|null $detector
+     * @return string|null
+     */
+    public function renderInstructionsTab(SiteContentDetector $detector = null): ?string
```
Comment (caddoo) [inline plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php]: Should the return value of this be nullable? Shouldn't there always be instructions?
Same question for the $detector param

File: plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php [hunk 3]
```diff
@@ -0,0 +1,125 @@
...
+        return null;
+    }
+
+    /**
+     * Returns the content that should be displayed in the Others tab on the no data page
+     *
+     * @param SiteContentDetector|null $detector
+     * @return string|null
+     */
+    public function renderOthersInstruction(SiteContentDetector $detector = null): ?string
```
Comment (caddoo) [inline plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php]: Should the return value of this be nullable? Shouldn't there always be instructions?
Same question for the $detector param

File: plugins/SitesManager/templates/_vueTabInstructions.twig [hunk 4]
```diff
@@ -1,3 +1,12 @@
+<p></p><p></p>
```
Comment (caddoo) [inline plugins/SitesManager/templates/_vueTabInstructions.twig:1]: Seems a bit hacky, is there a better way of doing this?

File: plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php [hunk 5]
```diff
@@ -0,0 +1,125 @@
...
+    }
+
+    /**
+     * Returns if the current detection succeeded for the provided site content or not.
+     *
+     * @param string|null $data
+     * @param array|null  $headers
+     * @return bool
+     */
+    abstract public function detectByContent(?string $data = null, ?array $headers = null): bool;
```
Comment (caddoo) [inline plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php]:
```suggestion
    abstract public function isDetected(string $pageContent, string $responseHeaders): bool;
```

File: core/SiteContentDetector.php [hunk 6]
```diff
@@ -63,56 +56,95 @@ class SiteContentDetector
...
         }
-        $this->siteGuesser = new GtmSiteTypeGuesser();
     }
 
+
     /**
-     * Reset the detection properties
+     * @return array<string, SiteContentDetectionAbstract[]>
+     */
+    public static function getSiteContentDetectionsByType()
```
Comment (caddoo) [inline core/SiteContentDetector.php]: Is there a reason this is static? Also might be good to add a return type while you are here

File: plugins/SitesManager/templates/_vueTabInstructions.twig (hunk 4 above)
Comment (sgiehl) [reply plugins/SitesManager/templates/_vueTabInstructions.twig:1]: Sure. But I only moved that code around, didn't want to apply changes to the html structure, as that would have caused changes in the UI tests as well.

File: plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php (hunk 2 above)
Comment (sgiehl) [reply plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php]: There are many detections that don't have their own tab with instructions. But returning an empty string in that case, might be fine as well. The detector param could also be changed.

File: plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php (hunk 5 above)
Comment (sgiehl) [reply plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php]: makes sense. Guess I simply kept the name when moving stuff around...

File: core/SiteContentDetector.php (hunk 6 above)
Comment (sgiehl) [reply core/SiteContentDetector.php]: Hm. It's a stateless method, that doesn't work with any instance attributes. So there is actually no reason for having it non static. Could change that, but that would also mean changing `getKnownConsentManagers` to non static as it uses that method. What would be your argument for having it non static?

File: plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php (hunk 2 above)
Comment (caddoo) [reply plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php]: Ok fair enough can leave like this for now

File: plugins/SitesManager/templates/_vueTabInstructions.twig (hunk 4 above)
Comment (caddoo) [reply plugins/SitesManager/templates/_vueTabInstructions.twig:1]: Ah sorry my mistake, ignore this one for now

File: core/SiteContentDetector.php (hunk 6 above)
Comment (caddoo) [reply core/SiteContentDetector.php]: My only reason for non-static is in it's current state it can't be mocked making testing difficult, no strong opinion, up to you.

File: plugins/SitesManager/SiteContentDetection/Cloudflare.php [hunk 7]
```diff
@@ -0,0 +1,82 @@
...
+class Cloudflare extends SiteContentDetectionAbstract
+{
+    public static function getName(): string
+    {
+        return 'Cloudflare';
+    }
+
+    public static function getContentType(): string
+    {
+        return self::TYPE_CMS;
```
Comment (michalkleiner) [inline plugins/SitesManager/SiteContentDetection/Cloudflare.php:27]: Should we introduce a CDN/Proxy type? Cloudflare is not really a CMS.

File: core/SiteContentDetector.php (hunk 6 above)
Comment (sgiehl) [reply core/SiteContentDetector.php]: It should still be possible to simply use a full mock class whereever needed. The class is loaded using StaticContainer everywhere, so it could be replaced in testing.

File: plugins/SitesManager/SiteContentDetection/Cloudflare.php [hunk 8]
```diff
@@ -0,0 +1,82 @@
...
+use Piwik\Piwik;
+use Piwik\Request;
+use Piwik\SiteContentDetector;
+use Piwik\View;
+
+class Cloudflare extends SiteContentDetectionAbstract
+{
+    public static function getName(): string
+    {
+        return 'Cloudflare';
```
Comment (michalkleiner) [inline plugins/SitesManager/SiteContentDetection/Cloudflare.php:22]: It might be nice to have the Name, the Type, the Instruction Url and the Priority in protected static variables and then have the methods in the abstract class returning the values, so the actual detection classes don't have to have all the methods, just the config.

See for an example https://3v4l.org/JKtEk#v7.2.0

File: core/SiteContentDetector.php
Comment (michalkleiner) [inline core/SiteContentDetector.php:1]: Since we are cutting into this, I thought to mention the naming side of things as well (though I know we probably don't want to rename the core classes because of BC) — we are not detecting site content. We are detecting tools, libraries, frameworks, content management systems, consent managers etc. Not content.

Would some other naming be better? Just food for thought.

File: plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php (hunk 3 above)
Comment (michalkleiner) [reply plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php]: This is in the 'Others' tab, so a detector can return content for both the tab and the Others tab, but we won't want to display in the Others if it's detected and the tab displayed, so I'd say this is correct as nullable.

File: plugins/SitesManager/SiteContentDetection/VueJs.php [hunk 9]
```diff
@@ -0,0 +1,125 @@
...
+        $view->vue3Code = $this->getVueInitializeCode(3);
+        $view->vue2Code = $this->getVueInitializeCode(2);
+        return $view->render();
+    }
+
+    public function renderOthersInstruction(SiteContentDetector $detector = null): string
+    {
+        if ($detector->wasDetected(self::class)) {
+            return ''; // don't show on others page if tab is being displayed
+        }
```
Comment (michalkleiner) [inline plugins/SitesManager/SiteContentDetection/VueJs.php:65]: This is repeating quite a few times, should the logic be in the Others template rather than in each of the detectors?

File: plugins/SitesManager/SiteContentDetection/VueJs.php [hunk 10]
```diff
@@ -0,0 +1,125 @@
...
+                [
+                    '<a target="_blank" rel="noreferrer noopener" href="https://github.com/AmazingDreams/vue-matomo">vue-matomo</a>',
+                    '<a target="_blank" rel="noreferrer noopener" href="https://matomo.org/faq/new-to-piwik/how-do-i-install-the-matomo-tracking-code-on-websites-that-use-vue-js/">',
+                    '</a>'
+                ]
+            )
+        );
+    }
+
+    private function getVueInitializeCode($vueVersion = '3')
```
Comment (michalkleiner) [inline plugins/SitesManager/SiteContentDetection/VueJs.php:80]: Default param value is string here, then we compare to a number.. Might be good to settle on one type and use consistently. Since versions can be strings (2.1), perhaps strings everywhere would be best?

File: plugins/SitesManager/lang/en.json [hunk 11]
```diff
@@ -112,7 +112,7 @@
         "SiteWithoutDataDetectedSite": "We've detected you're using a %1$s site. Simply follow the instructions from this %2$sguide%3$s.",
         "SiteWithoutDataDetectedSiteWordpress": "We've detected you're using a Wordpress site. Simply %1$sfollow the instructions from this guide%2$s to install the %3$sWP-Matomo plugin%4$s.",
         "SiteWithoutDataDetectedSiteWordpress2": "Set up the WordPress plugin already and not seeing any data? Please check %1$sthis FAQ for help%2$s.",
-        "SiteWithoutDataDetectedGtm": "We've also detected you're using a Google Tag Manager. If you prefer to set up Matomo using GTM please follow this %2$sguide%3$s.",
+        "SiteWithoutDataDetectedGtm": "We've also detected you're using a Google Tag Manager. If you prefer to set up Matomo using GTM please follow this %1$sguide%2$s.",
```
Comment (michalkleiner) [inline plugins/SitesManager/lang/en.json:115]: Should this be a new translation key? The changed placeholders could cause confusion.

File: plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php (hunk 1 above)
Comment (michalkleiner) [reply plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php:32]: Yeah, I'd agree here, the inheriting class could define the id. It can even be a `public static $id` property so that we can directly use it instead of calling a method (probably minor to no performance difference).

File: plugins/SitesManager/SiteContentDetection/Cloudflare.php (hunk 8 above)
Comment (michalkleiner) [reply plugins/SitesManager/SiteContentDetection/Cloudflare.php:22]: I see now that that approach wouldn't support translations for technologies with names that can be/are usually translated like GTM.

Comment (sgiehl) [reply plugins/SitesManager/SiteContentDetection/Cloudflare.php:22]: The problem with protected static variables is, that they can't be defined as abstract. So you can't force a sub class to overwrite the property. Which is why I used abstract methods instead. This makes it at lot easier to create subclasses without forgetting to define something that is required

File: plugins/SitesManager/SiteContentDetection/VueJs.php (hunk 9 above)
Comment (sgiehl) [reply plugins/SitesManager/SiteContentDetection/VueJs.php:65]: Then it wouldn't be possible to show it when it was detected, which would be incorrect.
With the new layout that will be removed anyway I guess. As Vue and other stuff will be displayed always on the front page, there is no benefit in displaying it on the others page anymore.

File: plugins/SitesManager/lang/en.json (hunk 11 above)
Comment (sgiehl) [reply plugins/SitesManager/lang/en.json:115]: I'll update that on weblate, once that is merged, so we don't loose the translations

File: plugins/SitesManager/SiteContentDetection/VueJs.php (hunk 10 above)
Comment (sgiehl) [reply plugins/SitesManager/SiteContentDetection/VueJs.php:80]: Didn't put any effort into improving that method as it was simply moved from one place to the other. Would prefer keeping it as is for now, so we can get this PR merged soon.

File: core/SiteContentDetector.php
Comment (sgiehl) [reply core/SiteContentDetector.php:1]: We are detecting stuff based on the site content. The name might not be that accurate, but don't have a better one in mind actually.

File: plugins/SitesManager/SiteContentDetection/Cloudflare.php (hunk 7 above)
Comment (sgiehl) [reply plugins/SitesManager/SiteContentDetection/Cloudflare.php:27]: We could also use OTHER I guess. I've put it into CMS, as it was detected as CMS before as well. Not sure if changing that would cause problems, as the checks for detected cms wouldn't succeed for Cloudflare anymore.
Might be something we could change after the new layout was implemented...

File: plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php (hunk 1 above)
Comment (sgiehl) [reply plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php:32]: I don't like using static properties for stuff that needs to be defined/overwritten in each subclass. This makes it a lot harder for a developer to understand it, without adding comments. Abstraction is meant to be used for this purpose. So either we leave it the way it is, or we make that method abstract and have it defined in each subclass.
And the purpose of having it automatically defined based on the class name ensures that the id is unique - at least for the stuff defined in core. Non unique IDs would cause a detection to be overwritten and to become unavailable.

Comment (michalkleiner) [reply plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php:32]: Ok for me as it is, we can always iterate on it if we feel strongly about some other approach. I guess I'm just used to it as Silverstripe CMS is all based on static configs, so it's a habit for me.

File: plugins/SitesManager/SiteContentDetection/Cloudflare.php (hunk 8 above)
Comment (michalkleiner) [reply plugins/SitesManager/SiteContentDetection/Cloudflare.php:22]: Hmmm, also an interface wouldn't help here. All good.

File: plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php (hunk 1 above)
Comment (sgiehl) [reply plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php:32]: I used to use that a lot in the past as well. But at some point I tried starting to use abstract methods instead, so others that need to reuse the code have it easier and can't create problems by accident without even knowing it. If there would be something like abstract attributes, that would be what I would prefer most 😆

**Review by caddoo — APPROVED** [review]

**Comment by tsteur** [comment]
Hi @sgiehl , @caddoo @michalkleiner there may be some bug in there. Not sure if I'm seeing it correctly.

image


For a lot of tech it passes the classname to check if it was detected but the actual ID is only the last part of the name.

**Comment by sgiehl** [comment]
Passing the object id is correct. Already came across that problem when working on #21247 and fixed it in that PR.
Will push a fix on 5.x-dev directly.

**Comment by tsteur** [comment]
Thanks @sgiehl . We'll then need a new RC after the fix is applied so we can make our tests work and also test overall

File: core/SiteContentDetector.php [hunk 12]
```diff
@@ -163,97 +191,104 @@ public function detectContent(array $detectContent = [SiteContentDetector::ALL_C
...
-     * @param array $properties
-     * @param array $cache
+     * Returns an array containing ids of all detected detections of the given type
      *
-     * @return bool
+     * @param string $type One of the SiteContentDetectionAbstract::TYPE_* constants
+     * @return array
      */
-    private function checkCacheHasRequiredProperties(array $properties, array $cache): bool
+    public function getDetectsByType(string $type): array
```
Comment (tsteur) [inline core/SiteContentDetector.php:222]: btw just noticed we're actually passing here integers and not string. Maybe not too important though
image
just fyi @sgiehl

Comment (sgiehl) [reply core/SiteContentDetector.php:222]: Good catch. I'll update that in the PR for changing the layout
