### PR TITLE
Fix handling of range invalidations during intersecting period check

### LINKED ISSUE #23135: [Bug] The date is not a correct date range exception when running archive command
### What happened?

Running `matomo/console --matomo-domain=matomo.mydomain.net core:archive` I get the following uncaught exception:

```
In Range.php line 275:
                                                                                                                  
  The date '2025-02-02' is not a correct date range. It should have the following format:  'lastN', 'previousN',  
   'YYYY-MM-DD,YYYY-MM-DD'. 
```

### What should happen?

The exception should not be thrown.

### How can this be reproduced?

Run the archive command.

### Matomo version

5.3.0

### PHP version

8.3.18

### Server operating system

Ubuntu

### What browsers are you seeing the problem on?

_No response_

### Computer operating system

_No response_

### Relevant log output

```shell

```

### Validations

- [x] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [x] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [x] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by mneudert**
### Description:

During the intersection period check, a check that involves range period invalidations can lead to an exception, preventing further archiving until that invalidation is either reset or finished.

```
Exception: General_ExceptionInvalidDateRange

/home/runner/work/matomo/matomo/matomo/core/Period/Range.php:275
/home/runner/work/matomo/matomo/matomo/core/Period.php:132
/home/runner/work/matomo/matomo/matomo/core/Period/Range.php:153
/home/runner/work/matomo/matomo/matomo/core/Period.php:274
/home/runner/work/matomo/matomo/matomo/core/CronArchive/QueueConsumer.php:474
/home/runner/work/matomo/matomo/matomo/core/CronArchive/QueueConsumer.php:447
```

_Should be backported to 5.3.x-dev!_

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/CronArchive/QueueConsumer.php [hunk 1]
```diff
@@ -442,21 +442,29 @@ public function shouldSkipArchiveBecauseLowerPeriodOrSegmentIsInProgress(array $
                 continue;
             }
 
-            $archiveBeingProcessed['periodObj'] = PeriodFactory::build($periods[$archiveBeingProcessed['period']], $archiveBeingProcessed['date1']);
+            $processedPeriodLabel = $periods[$archiveBeingProcessed['period']];
+            $processedPeriodDate = 'range' === $periods[$archiveBeingProcessed['period']]
```
Comment (michalkleiner) [inline core/CronArchive/QueueConsumer.php]:
```suggestion
            $processedPeriodDate = 'range' === $processedPeriodLabel
```

**Review by michalkleiner — DISMISSED** [review]
Nice catch, good addition to the tests as well. Approving with a minor suggestion where I had to read the condition twice to only find out it's the same thing as the variable.

File: tests/PHPUnit/Integration/CronArchive/QueueConsumerTest.php [hunk 2]
```diff
@@ -1461,6 +1472,38 @@ public function getTestDataForShouldSkipArchiveBecauseLowerPeriodOrSegmentIsInPr
...
+
+        yield 'range period should be detected as intersecting when day is processed' => [
+            'existingInvalidations' => [
+                ['name' => 'done', 'idsite' => 5, 'date1' => '2020-03-04', 'date2' => '2020-03-04', 'period' => Day::PERIOD_ID, 'status' => 1, 'ts_started' => date('Y-m-d H:i:s')],
+            ],
+            'archiveToProcess' => ['name' => 'done', 'idsite' => 5, 'date1' => '2020-03-03', 'date2' => '2020-03-05', 'period' => Range::PERIOD_ID],
+            'expected' => 'lower or same period in progress (period = day, date = 2020-03-04)',
+        ];
+
+        yield 'range period should be detected as intersecting when overlapping range is processed' => [
```
Comment (sgiehl) [inline tests/PHPUnit/Integration/CronArchive/QueueConsumerTest.php:1492]: I'm wondering if that behavior is actually needed. Processing ranges should not use other ranges, so there might be no need to wait for an intersecting range period though. Doesn't need to be changed in this PR, but we could maybe create a follow up issue if we want to change that.

Comment (michalkleiner) [reply tests/PHPUnit/Integration/CronArchive/QueueConsumerTest.php:1492]: I would probably keep it, it's a good reminder that even ranges can overlap, either fully or partially, but yeah, they wouldn't use nested ranges (if they existed) to get the data. Hmmm... In a worst case scenario it can delay data if it's waiting for one range to finish before starting the other one if e.g. all days are already available.

**Review by michalkleiner — APPROVED** [review]

File: tests/PHPUnit/Integration/CronArchive/QueueConsumerTest.php (hunk 2 above)
Comment (sgiehl) [reply tests/PHPUnit/Integration/CronArchive/QueueConsumerTest.php:1492]: We should keep that test in any case. It was purely around challenging the fact that the current code behavior might delay data processing unnecessarily for such cases.
