### PR TITLE
PHP 8.2 deprecation warning fixes

### LINKED ISSUE #20402: PHP 8.2 deprecation warnings
From https://github.com/matomo-org/matomo/issues/20236#issuecomment-1436067158
 - [ ] `WARNING: /plugins/DBStats/Reports/Base.php(43): Deprecated - Creation of dynamic property Piwik\Plugins\CoreVisualizationsWisualizations\HtmlTable \Config::Skeep_summary_row is deprecated - Matomo 4.13.3
WARNING: /plugins/CoreVisualizationsficiplotDataGenerator/Evolution.php(89): Deprecated - Creation of dynamic property Piwik\Plugins\CoreVisualizationsVqplotDataGenerator\Chart::SdataTable is deprecated - Matomo 4.13.3 (Module: DBStats, Action: index, In CLI mode: false)`

From https://forum.matomo.org/t/php-8-2-depreciated-features-on-ver-4-13-1/49221/5
- [ ] `WARNING: /plugins/Live/VisitorProfile.php(24): Deprecated - Creation of dynamic property Piwik\Plugins\Live\VisitorProfile::$idSite is deprecated - Matomo 4.13.1 (Module: API, Action: getVisitorProfilePopup, Method: Live.getVisitorProfile, In CLI mode: false)`
- [ ] `WARNING: /core/Tracker/TableLogAction/Cache.php(41): Deprecated - Creation of dynamic property Piwik\Tracker\TableLogAction\Cache::$limitActionIds is deprecated - Matomo 4.13.3
(Module: API, Action: getEvolutionGraph, Method: VisitsSummary.get, In CLI mode: false)`

From https://forum.matomo.org/t/logs-filled-with-deprecated-warnings-in-matomo-4-13-3-with-php-8-2-2/49799:
 - [ ] `Message: plugins/LogViewer/Log/Query.php(15): Deprecated - Creation of dynamic property Piwik\Plugins\LogViewer\Log\Query::$query is deprecated - Matomo 4.13.3`

### PR DESCRIPTION
**Pull request by bx80**
### Description:

Fixes #20402 

Various small fixes for PHP 8 dynamic property creation deprecation warnings

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/ViewDataTable/Config.php [hunk 1]
```diff
@@ -552,6 +552,40 @@ class   Config
...
+    public $highlight_summary_row = false;
+
+    /**
+     * Controls whether the Series Picker is shown or not. The Series Picker allows users to
+     * choose between displaying data of different columns.
+     *
+     * Default value: true
+     * @var bool
+     */
+    public $show_series_picker = true;
```
Comment (sgiehl) [inline core/ViewDataTable/Config.php]: We should not set those in the base configuration. Those should be properties that exists in classes that inherit from this one.
So if a report / plugin tries to set this property they should either first check for the correct view table type or if the property exist or similar.

File: plugins/CoreVisualizations/JqplotDataGenerator/Chart.php [hunk 2]
```diff
@@ -27,6 +27,8 @@ class Chart
     // temporary
     public $properties;
 
+    public $dataTable;
```
Comment (sgiehl) [inline plugins/CoreVisualizations/JqplotDataGenerator/Chart.php]: I think this property should not be needed. Instead I think we should remove any usage of that property in other files. If I remember correctly it was only set in some other files but actually used anywhere else... Didn't I remove the usages in a previous PR?

**Review by sgiehl — CHANGES_REQUESTED** [review]

File: plugins/CoreVisualizations/JqplotDataGenerator/Chart.php (hunk 2 above)
Comment (bx80) [reply plugins/CoreVisualizations/JqplotDataGenerator/Chart.php]: Yes, this was fixed by your previous PR, reverted. :+1:

File: core/ViewDataTable/Config.php (hunk 1 above)
Comment (bx80) [reply core/ViewDataTable/Config.php]: Agreed, I've reverted this, it seems `HtmlTable/Config` was missing the `keep_summary_row` property so I've added that instead. :+1:

**Review by sgiehl — APPROVED** [review]
