### PR TITLE
Fix first visit in visitor profile

### LINKED ISSUE #12373: Visitor Profile "First visit" does not always show the very first visit
As reported in https://github.com/piwik/piwik/issues/11996#issuecomment-352869747 by @blynch11p 

>  I've been tinkering with v3.2 and I have many users that top 100 visits. The Visit count is starting at #100 (not a big deal, really) but the secondary issue is that the "First Visit" date is (in my case) whatever the date for Visit #91 is in the Visitor Profile window (ie: the date for the oldest of the 10 visits that load initially. This does not update when I click 'Load more visits'). So if the user visits a site every day, visit #91 / First Visit is only 10 days back, rather than >100 days or > 3 years or whatever. I believe in prior Piwik versions (I'm coming from 3.0.4) "First Visit" only ever showed the text Visit #100 for these use cases, but now "First Visit" is less accurate.

## Current behavior 

Currently "First visit" will only be the 10th oldest visit, but there could have been 50 visits or more. 

## Expected behavior

* The `First visit` panel in the Visitor Profile should refer the very first visit of the user. 
  * ideally it's possible to query this very first visit very quickly in Mysql,
   * but if not we can always use the first visit in the `live_visitor_profile_max_visits_to_aggregate` limit (100 by default) which would restore the previous behavior before we recently regressed

### PR DESCRIPTION
**Pull request by sgiehl**
Visitor profile will now show the first visit the use made (within the profile limit)

fixes #12373

### CODE REVIEW

File: plugins/Live/API.php [hunk 1]
```diff
@@ -207,12 +207,10 @@ public function getVisitorProfile($idSite, $visitorId = false, $segment = false,
...
         }
 
-        $newSegment = ($segment === false ? '' : $segment . ';') . 'visitorId==' . $visitorId;
-
         $limit = Config::getInstance()->General['live_visitor_profile_max_visits_to_aggregate'];
 
-        $visits = $this->loadLastVisitorDetailsFromDatabase($idSite, $period = false, $date = false, $newSegment,
-            $offset = 0, $limit);
+        $visits = $this->loadLastVisitorDetailsFromDatabase($idSite, $period = false, $date = false, $segment,
+            $offset = 0, $limit, false, false, $visitorId);
```
Comment (sgiehl) [inline plugins/Live/API.php]: Not sure why we added the visitorid to the segment instead of setting the parameter, as the used method directly supports it. The resulting query for fetching the visits changes only slightly:

with segment:
```sql
SELECT sub.*
FROM (
SELECT log_visit.*
FROM piwik_log_visit AS log_visit
WHERE (log_visit.idsite IN (?)) AND (log_visit.idvisitor = ?)
ORDER BY idsite DESC, visit_last_action_time DESC
LIMIT 0, 1000) AS sub
GROUP BY sub.idvisit
ORDER BY sub.visit_last_action_time DESC
LIMIT 100;
```

with param:
```sql
SELECT sub.*
FROM (
SELECT log_visit.*
FROM piwik_log_visit AS log_visit
WHERE log_visit.idsite IN (?) AND log_visit.idvisitor = ?
ORDER BY idsite DESC, visit_last_action_time DESC
LIMIT 0, 100) AS sub
GROUP BY sub.idvisit
ORDER BY sub.visit_last_action_time DESC
LIMIT 100;
```

Not sure if that has any impact on performance...

File: plugins/Live/VisitorDetails.php [hunk 2]
```diff
@@ -181,12 +183,42 @@ public function finalizeProfile($visits, &$profile)
...
+        ]);
+
+        $row                                 = $response->getFirstRow();
+        $visitorData                         = $row->getColumns();
+        $visitorData['firstActionTimestamp'] = strtotime($visitorData['visit_first_action_time']);
+
+        // process referrer details
+        $referrersDetails = new \Piwik\Plugins\Referrers\VisitorDetails();
+        $referrersDetails->setDetails($visitorData);
+        $referrersDetails->extendVisitorDetails($visitorData);
```
Comment (sgiehl) [inline plugins/Live/VisitorDetails.php]: this might be a bit hackish, but the referrer information is displayed for that "last visit". As it is fetched afterwards it does not go through the visitordetails process and such leaks the processed information.
If we later decide to display some other information processed by another plugin we might need to do that with additional or even all `VisitorDetails` classes

**Comment by sgiehl** [comment]
@mattab I've now adjusted the PR to show the very first visit in the visitor profile. Feel free to review ;-)

File: plugins/Live/API.php [hunk 3]
```diff
@@ -289,6 +287,28 @@ public function getMostRecentVisitorId($idSite, $segment = false)
         return $visitor->getVisitorId();
     }
 
+    /**
+     * Returns the very first visit for the given visitorId
+     *
+     * @internal
```
Comment (sgiehl) [inline plugins/Live/API.php]: marked the new method as internal for now. Or should we make it public API? Any opinions?

File: plugins/Live/API.php (hunk 1 above)
Comment (tsteur) [reply plugins/Live/API.php]: There should be no difference in performance as MySQL will parse this the same way IMO 👍

Comment (sgiehl) [reply plugins/Live/API.php]: There is a slightly difference as the inner query now only has a limit of `100` instead of `1000`, so maybe it might be even faster, as it has lower amount of rows to sort in outer query ;-)

**Comment by diosmosis** [comment]
LGTM, re making the API public, unless it's useful to display in a report on it's own, seems better not to introduce new API. Plugin devs can always call it themselves, though maybe there's a use case out there for finding a user's first visit via the API...

File: plugins/Live/API.php (hunk 3 above)
Comment (mattab) [reply plugins/Live/API.php]: Sounds good to leave it internal as fetching first visit can be done with the existing API methods :+1:

File: plugins/Live/API.php [hunk 4]
```diff
@@ -289,6 +295,28 @@ public function getMostRecentVisitorId($idSite, $segment = false)
...
+     * @param $visitorId
+     *
+     * @return DataTable
+     */
+    public function getFirstVisitForVisitorId($idSite, $visitorId)
+    {
+        Piwik::checkUserHasViewAccess($idSite);
+
+        $model = new Model();
+        $data = $model->queryLogVisits($idSite, false, false, false, 0, 1, $visitorId, false, 'ASC');
```
Comment (mattab) [inline plugins/Live/API.php]: Here we should it seems check that `$visitorId` is set, and if not fail? as otherwise we may return possibly some other visits in `queryLogVisits`?

**Review by mattab — CHANGES_REQUESTED** [review]

File: plugins/Live/API.php (hunk 4 above)
Comment (sgiehl) [reply plugins/Live/API.php]: It now returns an empty datatable if the visitorid is empty
