### PR TITLE
Log archiving query timeouts

### LINKED ISSUE #18025: Max execution timeout exceptions for archiving are not handled
The maximum database query execution timeout for archiving queries defaults to two hours and may also be overridden with a custom timeout value in config.ini.php

When an archiving query exceeds this timeout a  'maximum statement execution time exceeded' exception is returned.

## Expected Behavior
The max execution time exception for archiving queries should be caught and used to trigger an event in the same way that the live query Model::handleMaxExecutionTimeError() method works. This event can then be used to provide notifications that the archiving operation has failed due to query timeout.

We need to make sure the user will be aware if queries run into timeouts. 

The goal of this issue is that when you run the archiving using core:archive command, then the archiving will fail and an exception message is shown and it's clear what happened. Ideally also which query caused the issue (if any possible).

## Current Behavior
The max execution time exception is currently not caught for archiving queries and the archiving operation will silently fail. If an archiving query is slow enough to consistently exceed the timeout then archiving may never complete for some reports and without notification it could be difficult to determine why.

### PR DESCRIPTION
**Pull request by bx80**
### Description:

Fixes #18025 

Added an exception handler to the archiving db adapter which will catch any exceptions thrown because of the max_execution_time hint and log the exception and query details.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/DataAccess/ArchivingDbAdapter.php [hunk 1]
```diff
@@ -98,4 +111,25 @@ private function logSql($sql)
...
+        unset($args[0]);
+
+        try {
+            return call_user_func_array([$this->wrapped, $function], $args);
+        } catch (\Exception $e) {
+            if ($this->isErrNo($e, \Piwik\Updater\Migration\Db::ERROR_CODE_MAX_EXECUTION_TIME_EXCEEDED_QUERY_INTERRUPTED) ||
+                $this->isErrNo($e, \Piwik\Updater\Migration\Db::ERROR_CODE_MAX_EXECUTION_TIME_EXCEEDED_SORT_ABORTED)
+            )
+            {
+                $this->logger->info('Archiver query exceeded maximum execution time: {details}',
```
Comment (sgiehl) [inline core/DataAccess/ArchivingDbAdapter.php]: I doubt that many people would actually log a `info` on an instance. As the exception is rethrown, and the archiving will fail with an error in any case, wouldn't it be more helpful to log that as a warning, so it appears with normal log configuration?

Comment (bx80) [reply core/DataAccess/ArchivingDbAdapter.php]: Yes, makes sense :+1:

**Review by sgiehl — APPROVED** [review]
