### PR TITLE
Reactivate previously active plugins after core upgrade

### LINKED ISSUE #22998: [Bug] Warning about Incompatible Plugins When Updating Matomo to Version 5.2.2
### What happened?

When attempting to update Matomo to version 5.2.2, some users are receiving a warning about incompatible plugins. The warning indicates that the plugins will be deactivated, and users are concerned about losing data. The affected plugins until now include: Custom Reports, White Label and WooCommerce Analytics.

### What should happen?

Matomo should either automatically update the plugins or provide clear instructions on whether plugins need to be updated manually before upgrading Matomo.

### How can this be reproduced?

- Attempt to update Matomo to version 5.2.2.
- Receive a warning about incompatible plugins.

### Matomo version

5.2.1

### PHP version

_No response_

### Server operating system

_No response_

### What browsers are you seeing the problem on?

_No response_

### Computer operating system

_No response_

### Relevant log output

```shell

```

### Validations

- [x] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [x] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [x] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by michalkleiner**
### Description

This change allows to store a list of active plugins before core is upgraded and then read it and reactivate previously active plugins after core upgrade, if they don't have any missing requirements.

fixes #22998

### Checklist

* [NA] I have understood, reviewed, and tested all AI outputs before use
* [NA] All AI instructions respect security, IP, and privacy rules

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/CoreUpdater/Updater.php [hunk 1]
```diff
@@ -196,6 +200,36 @@ public function oneClickUpdatePartTwo($newVersion = null)
...
+            }
+
+            $reactivatedPlugins = [];
+            if (!empty($previouslyActivePlugins)) {
+                $pluginManager = PluginManager::getInstance();
+                foreach ($previouslyActivePlugins as $previouslyActivePluginName) {
+                    if (!$pluginManager->isPluginActivated($previouslyActivePluginName)) {
+                        $plugin = $pluginManager->loadPlugin($previouslyActivePluginName);
+                        if (empty($plugin->getMissingDependencies($newVersion))) {
+                            $plugin->activate();
```
Comment (mneudert) [inline plugins/CoreUpdater/Updater.php]:
```suggestion
                            $pluginManager->activatePlugin($plugin);
```

When I tried the updated process locally, the plugin was updated, announced as "reactivated", but missing in the `[Plugins]` config. It was kept in `[PluginsInstalled]`.

Just having the plugin manager take care of updating the config should prevent that, unless it should have never been removed in the first place and something else was wrong (and is not reproducible).

Comment (michalkleiner) [reply plugins/CoreUpdater/Updater.php]: Thanks for finding that quirk, I've updated it to use plugins manager as suggested, with a tweak that it takes the plugin name as a param, not the param object.

File: plugins/CoreUpdater/Updater.php [hunk 2]
```diff
@@ -196,6 +200,37 @@ public function oneClickUpdatePartTwo($newVersion = null)
...
+                $previouslyActivePlugins = [];
+            }
+            Option::delete('OneClickUpdate_ActivatedPlugins');
+
+            $reactivatedPlugins = [];
+            if (!empty($previouslyActivePlugins)) {
+                $pluginManager = PluginManager::getInstance();
+                foreach ($previouslyActivePlugins as $previouslyActivePluginName) {
+                    if (!$pluginManager->isPluginActivated($previouslyActivePluginName)) {
+                        $plugin = $pluginManager->loadPlugin($previouslyActivePluginName);
```
Comment (sgiehl) [inline plugins/CoreUpdater/Updater.php:218]: We could maybe change the try catch handling. I would maybe add one around loading/activating the plugin. If a plugin e.g. fails to load or activate for any reason it would currently cause the updater to fail and all following plugins not to reactivate.
It might be fine to just skip/ignore plugins that can't be loaded or activated. Or we add another info message around plugins that couldn't be reactivated.

File: tests/PHPUnit/Fixtures/LastForcedInstall.php [hunk 3]
```diff
@@ -9,10 +9,49 @@
...
+        parent::setUp();
+
+        $this->installAndActivateTreemapPlugin();
+    }
+
     protected function getDownloadUrl()
     {
-        return 'http://builds.matomo.org/matomo-4.15.0.zip';
+        return 'https://builds.ctd.nz/matomo-' . self::FORCED_VERSION . '.zip';
+//        return 'http://builds.matomo.org/matomo-' . self::FORCED_VERSION . '.zip';
```
Comment (sgiehl) [inline tests/PHPUnit/Fixtures/LastForcedInstall.php]: Needs to be reverted before merge. Only adding a comment so we don't forget it.

**Review by sgiehl — CHANGES_REQUESTED** [review]
I just had a look at the code changes. Overall they look fine. I've nevertheless left a small suggestion that could be applied.

File: plugins/CoreUpdater/Updater.php (hunk 2 above)
Comment (michalkleiner) [reply plugins/CoreUpdater/Updater.php:218]: I can tweak that to move it closer to the activation.

We had a discussion with Marc on the topic of not reactivated plugins and they are already mentioned by the following code that tries to disable plugins with missing requirements. I previously had a list of not reactivated plugins, but it was exactly the same as the list created there. Even though they might be already disabled from the core update, the message lists them all based on their actual missing requirement after the core update, so there's no need for another message with the same list of incompatible plugins.

File: plugins/CoreUpdater/Updater.php [hunk 4]
```diff
@@ -196,6 +200,37 @@ public function oneClickUpdatePartTwo($newVersion = null)
...
+            foreach ($previouslyActivePlugins as $previouslyActivePluginName) {
+                if (!$pluginManager->isPluginActivated($previouslyActivePluginName)) {
+                    try {
+                        $plugin = $pluginManager->loadPlugin($previouslyActivePluginName);
+                        if (empty($plugin->getMissingDependencies($newVersion))) {
+                            $pluginManager->activatePlugin($previouslyActivePluginName);
+                            $reactivatedPlugins[] = $previouslyActivePluginName;
+                        }
+                    } catch (\Throwable $e) {
+                        throw new UpdaterException($e, $messages);
```
Comment (sgiehl) [inline plugins/CoreUpdater/Updater.php]: I'm actually not sure if we should throw an exception here at all. If a plugin fails to reactivate for any reason, than it might be fine to just keep it disabled but proceed with reactivating the other plugins.

Comment (michalkleiner) [reply plugins/CoreUpdater/Updater.php]: Ok, removed rethrow, replaced with noop. The list of plugins that were not reactivated will still be output to the user, so it should be fine.

File: tests/PHPUnit/Fixtures/LastForcedInstall.php (hunk 3 above)
Comment (michalkleiner) [reply tests/PHPUnit/Fixtures/LastForcedInstall.php]: Reverted now. The UI test for forced update will fail until 4.16.2 is released.

**Review by sgiehl — COMMENTED** [review]
The code looks good to me now. Not adding an approval for now, as we first need to merge the 4.x PR and release 4.16.2.

**Review by sgiehl — APPROVED** [review]
