### PR TITLE
Fixes js memory leak in dashboard directive

### LINKED ISSUE #12058: JavaScript Memory Leak: #columnPreview click handlers
`renderDashboard` adds click handlers to `#columnPreview` divs every time the user visits the dashboard, and never removes them:

https://github.com/piwik/piwik/blob/defc5469a5d4634d64023477a447a31c58812a12/plugins/Dashboard/angularjs/dashboard/dashboard.directive.js#L49

The result is a small memory leak.

## Solution

A quick fix is to add the following just before you add the new listeners:

```javascript
$('#columnPreview').find('>div').off('click');
```

If you are concerned about the possibility of there being other `click` handlers installed on the divs, you can namespace your handlers:

```javascript
$('#columnPreview').find('>div').off('click.renderDashboard');
$('#columnPreview').find('>div').on('click.renderDashboard', ...);
```

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #12058

### CODE REVIEW

File: plugins/Dashboard/angularjs/dashboard/dashboard.directive.js [hunk 1]
```diff
@@ -38,15 +38,18 @@
...
                 $('div', this).each(function () {
                     width.push(this.className.replace(/width-/, ''));
                 });
                 $(this).attr('layout', width.join('-'));
             });
 
-            $('#columnPreview').find('>div').on('click', function () {
+            divElements.off('click.renderDashboard');
+            divElements.on('click.renderDashboard', function () {
                 $('#columnPreview').find('>div').removeClass('choosen');
```
Comment (mneudert) [inline plugins/Dashboard/angularjs/dashboard/dashboard.directive.js]: Could this also be replaced with `divElements`?

As long as the events are always rebound when a new element is added there should be no reason not to.

Comment (sgiehl) [reply plugins/Dashboard/angularjs/dashboard/dashboard.directive.js]: yes. correct. changed it

**Review by tsteur — APPROVED** [review]
