### PR TITLE
Fix some "Passing null to parameter" warnings (PHP8.1)

### LINKED ISSUE #19127: PHP8.1 compatibility fixes in referrers plugin
With Matomo 4.9.0, I see lots of these warnings:

**1.**
```
WARNING Referrers
plugins/Referrers/Columns/Base.php(525): 
Deprecated - mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated
```

**2.**
```
WARNING Referrers
plugins/Referrers/Columns/Base.php(478): 
Deprecated - urldecode(): Passing null to parameter #1 ($string) of type string is deprecated
```

Problem 1 I solved temporarily by replacing
`$this->keywordReferrerAnalyzed = mb_strtolower($this->keywordReferrerAnalyzed);`
with
`$this->keywordReferrerAnalyzed = mb_strtolower($this->keywordReferrerAnalyzed ?? '');`

But I am not sure this is the best fix.

### PR DESCRIPTION
**Pull request by MichaelRoosz**
This fixes:
```
WARNING Referrers
plugins/Referrers/Columns/Base.php(525): 
Deprecated - mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated

WARNING Referrers
plugins/Referrers/Columns/Base.php(478): 
Deprecated - urldecode(): Passing null to parameter #1 ($string) of type string is deprecated

WARNING Events
core/Twig.php(363): Deprecated - str_replace(): 
Passing null to parameter #3 ($subject) of type array|string is deprecated

WARNING UsersManager
plugins/UsersManager/Model.php(662): Deprecated - explode():
Passing null to parameter #2 ($string) of type string is deprecated

WARNING UsersManager
plugins/UsersManager/Model.php(210):
Deprecated - explode(): Passing null to parameter #2 ($string) of type string is deprecated

WARNING Login
libs/HTML/QuickForm2/Rule/Nonempty.php(96): 
Deprecated - strlen(): Passing null to parameter #1 ($string) of type string is deprecated
```
First priority was to keep the existing behavior to avoid creating any bugs.

### CODE REVIEW

File: core/Twig.php [hunk 1]
```diff
@@ -360,6 +360,11 @@ protected function addFilter_notification()
     protected function addFilter_safeDecodeRaw()
     {
         $rawSafeDecoded = new TwigFilter('rawSafeDecoded', function ($string) {
+
+            if (!$string) {
```
Comment (sgiehl) [inline core/Twig.php]: This one actually changes the result. The string `0` will no be returned as empty string. That can be seen in the UI test results. Maybe we need to check if it is a string

Comment (MichaelRoosz) [reply core/Twig.php]: Good point, or maybe we could just directly do `$string === null`

Comment (MichaelRoosz) [reply core/Twig.php]: @sgiehl PR has been updated

**Review by sgiehl — APPROVED** [review]

**Comment by sgiehl** [comment]
Thanks for the contribution @MichaelRoosz
