### PR TITLE
Fix total time of visit is not the sum of times of page visits if heartbeat feature is used

### LINKED ISSUE #9610: total time of visit is not the sum of times of page visits
Total time of a visit
shown for a visit e.g. in visitor log
is not always the sum of times of all page visits

an example is shown in attachments

if this total time of a visit is not only shown but also used to calculate other things like avarage duration of a visit, it may have a big imapct

2016-01-21_11h48_02

2016-01-21_11h49_23

2016-01-21_11h49_04

2016-01-21_11h48_52

2016-01-21_11h48_39

2016-01-21_11h48_16

### PR DESCRIPTION
**Pull request by tsteur**
We can fix the incorrect action time by not updating `visit_last_action_time` see problem explained in https://github.com/piwik/piwik/issues/9610#issuecomment-173689254 . A ping is not really an action so it should not update `visit_last_action_time`.

This changes behaviour of heart beat in a way that the "time spent on last action" can be max 30 minutes (or custom value specified in `visit_standard_length` config setting). Why? So far we updated `visit_last_action_time` on each ping request and set it to now. This kept the visitors session active and the `VisitorRecognizer` would find an existing visit even if the user did not click within 30 minutes but if there were ping request.

Now the `visit_last_action_time` is no longer updated. This means after 30 minutes of sending ping requests the `VisitorRecognizer` will no longer find an existing visit and therefore all further ping requests will be aborted by this line https://github.com/piwik/piwik/blob/2.16.0-b6/plugins/Heartbeat/Tracker/PingRequestProcessor.php#L33-L35

fixes  #9610

### CODE REVIEW

File: core/Tracker/Request.php [hunk 1]
```diff
@@ -407,6 +407,10 @@ public function setParam($name, $value)
     {
         $this->params[$name] = $value;
         unset($this->paramsCache[$name]);
+
```
Comment (tsteur) [inline core/Tracker/Request.php]: this change is kinda unrelated but noticed it while fixing this issue

**Comment by tsteur** [comment]
Ideally, we would fix this in Piwik 3.0 the proper way.

For example we could have a `visit_last_ping_time` and let users decide whether a ping should extend the current session or not. Ideally we would directly update the value for the time spent on the last action see https://github.com/piwik/piwik/issues/9539 . To do this we would need to fetch the last action during tracking time. To make this fast we would need something like https://github.com/piwik/piwik/issues/8476 to store active, ongoing visits and actions in a separate table to make it blazing fast to fetch and update them.

**Comment by mattab** [comment]
LGTM. updated tests files, when build is green we can merge!
