### PR TITLE
Development mode notifications when Matomo not installed through git

### LINKED ISSUE #16922: replace generate:plugin warning with pointer to guide
When someone wants to create a plugin and is using the Matomo version from matomo.zip, they probably get an error like this one:

>Uncaught exception: Error: Class 'Piwik\Plugins\ExamplePlugin\ExamplePlugin' not found

This is expected as Matomo doesn't ship with the Example* plugins anymore, but doesn't help the person struggling with this.

Instead, the `generate:plugin` should detect if those plugins are missing and if not point people towards https://developer.matomo.org/guides/getting-started-part-1

### PR DESCRIPTION
**Pull request by flamisz**
### Description:

fixes #16922 

### Review

* [ ] Functional review done
* [x] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [x] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [x] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/CoreConsole/Commands/GeneratePluginBase.php [hunk 1]
```diff
@@ -397,4 +399,10 @@ private function replaceContent($replace, $contentToReplace)
         return $contentToReplace;
     }
 
+    protected function throwErrorIfNotGitInstalled()
```
Comment (sgiehl) [inline plugins/CoreConsole/Commands/GeneratePluginBase.php:407]: instead of calling this method in every class' execute, you could extend the `initialize` method in this base class to check that. It should be called automatically before `execute`

Comment (flamisz) [reply plugins/CoreConsole/Commands/GeneratePluginBase.php:407]: I wanted to do that, but there are commands (or at least one, the `development:enable`) where we don't want to throw it. So either I create exception or call one-by-one. But TBH I haven't tried the `initalize`, I used `__construct`. I can give it a go.

Comment (flamisz) [reply plugins/CoreConsole/Commands/GeneratePluginBase.php:407]: Thanks for the tip @sgiehl, I couldn't see that `initialize` method. It works, I updated the PR

File: plugins/CoreConsole/Commands/GeneratePluginBase.php [hunk 2]
```diff
@@ -397,4 +404,10 @@ private function replaceContent($replace, $contentToReplace)
...
+    {
+        if (!SettingsPiwik::isGitDeployment()) {
+            throw new NotGitInstalledException('Using this feature Matomo has to be installed through git!');
```
Comment (sgiehl) [inline plugins/CoreConsole/Commands/GeneratePluginBase.php]: Maybe we could improve this message a bit and also mention the url `https://developer.matomo.org/guides/getting-started-part-1``, which should give more details how to set up for development.

File: lang/en.json [hunk 3]
```diff
@@ -487,6 +487,7 @@
         "WarningFileIntegrityNoMd5file": "File integrity check could not be completed due to missing md5_file() function.",
         "WarningPasswordStored": "%1$sWarning:%2$s This password will be stored in the config file visible to everybody who can access it.",
         "WarningDebugOnDemandEnabled": "Tracker %1$s mode is enabled. For security reasons this should be enabled only for a short time frame. To disable it set %2$s to %3$s in %4$s",
+        "WarningDevelopmentModeOnButNotGitInstalled": "You are currently using Matomo in development mode, but it was not installed through git. It's not recommended to use Matomo in development mode in production environment.",
```
Comment (sgiehl) [inline lang/en.json:490]: Not sure if we need this one translatable. Should be a very uncommon case when this is displayed and might be fine to always show the english text.  @tsteur what do you think about that?
If we decide to keep it translatable, we should also add the exception message and the command comment.

Comment (flamisz) [reply lang/en.json:490]: I just added this into the language file, because it shows on the UI. 
I checked other exceptions and messages in the commands and they are mostly English (at least what I've seen). Kind of tried to follow the actual convention.
But easy to modify to each way, happy to do that.

File: plugins/CoreConsole/Commands/GeneratePluginBase.php (hunk 2 above)
Comment (flamisz) [reply plugins/CoreConsole/Commands/GeneratePluginBase.php]: Good point, I'll do it.

File: lang/en.json (hunk 3 above)
Comment (flamisz) [reply lang/en.json:490]: @tsteur what your thoughts on this?

File: plugins/CoreConsole/Commands/GeneratePluginBase.php (hunk 2 above)
Comment (flamisz) [reply plugins/CoreConsole/Commands/GeneratePluginBase.php]: @sgiehl I added the url to the message, but not sure about how it could be improved. any recommendation?

Currently it is:
`Using this feature Matomo has to be installed through git. For more information please visit https://developer.matomo.org/guides/getting-started-part-1.`

File: lang/en.json (hunk 3 above)
Comment (tsteur) [reply lang/en.json:490]: Have no thoughts on this. Both is fine. :) And as both is fine I'd just leave it there with a translation as it's less work to simply keep it compared to removing it but really no preference

File: plugins/CoreConsole/Commands/GeneratePluginBase.php (hunk 2 above)
Comment (sgiehl) [reply plugins/CoreConsole/Commands/GeneratePluginBase.php]: I'm not sure if the `installed through git` is that helpful. Downloading the package from GitHub might actually include the require plugin files, but there won't be a `.git/HEAD`, so the command would still raise an error. So actually it would be required to do a full git checkout. Guess it doesn't hurt if the message is a bit more technical, as it actually should be used by developers only.

So maybe something like `This development feature requires Matomo to be checked out from git. For more information please visit https://developer.matomo.org/guides/getting-started-part-1.`

**Review by sgiehl — APPROVED** [review]
LGTM now

File: core/Plugin/ControllerAdmin.php [hunk 4]
```diff
@@ -170,6 +171,25 @@ private static function notifyIfURLIsNotSecure()
...
 
+    private static function notifyIfDevelopmentModeOnButNotInstalledThroughGit()
+    {
+        if (!Piwik::hasUserSuperUserAccess()) {
+            return;
+        }
+
+        if (SettingsPiwik::isGitDeployment()) {
+            return;
+        }
```
Comment (diosmosis) [inline core/Plugin/ControllerAdmin.php:186]: I haven't tested locally, so I might be missing something, but shouldn't this also check `if (Development::isEnabled())`?

**Review by diosmosis — CHANGES_REQUESTED** [review]
Saw a possible issue but haven't tested locally

File: core/Plugin/ControllerAdmin.php (hunk 4 above)
Comment (flamisz) [reply core/Plugin/ControllerAdmin.php:186]: you were right @diosmosis, I added the extra validation

**Comment by sgiehl** [comment]
guess should be good to merge now.
