### PR TITLE
Refactor new action insertion code so duplicate actions will not exist + provide means to fix duplicates

### LINKED ISSUE #6436: duplicate entries in piwik_log_action leading to pages not visible in segments
Hi,

currently we encountered a strange issue with pages listed in *actions->pages*, but not if using a segment (which should include this page). Investigating the issue I found duplicate entries in piwik_log_action.

idaction | name | hash | type | url_prefix
---------- | -------- | --------- | -------- | --------
4114714 | example.com/somepage | 652463546 | 1 | 1
4114715 | example.com/somepage | 652463546 | 1 | 1

In piwik_log_link_visit_action only *idaction 4114715* is referenced, and displayed with views in *actions->pages*; creating a segment matching *example.com/somepage* gets 0 views for this page.

Something to consider is that, we use 2 balanced Piwik installations for tracking, a setup which should be working fine, but also has the potential to create this kind of issue as *type, hash* is not unique.

### PR DESCRIPTION
**Pull request by diosmosis**
This pull request modifies the tracking logic so duplicate actions will not exist in the log_action table and so even if duplicate actions exist in the log_action table, only one action ID will be used at any time.

Fixes #6436

Changes include:
- new code when inserting an action, instead of just executing an INSERT and returning the last insert ID, the tracker will now:
  - perform an insert
  - select the smallest idaction that matches the name (another query)
  - check if the last insert ID != selected ID, and if true, delete the inserted action
- changes to SQL that selects idactions from the log_action table so they will always select the lowest idaction. Sometimes involves group bys.
- there's an update + console command for fixing duplicates. Neither one invalidates existing archives, since I couldn't find a good way to do this in the Update w/o running possibly big queries when creating the Update SQL.
  - I'm not sure if having an update is the best idea. It will automatically remove duplicates for all users, but the SQL it uses to do so is dependent on the data in the tables. So users that want to run the SQL statements themselves might be a bit confused/put-off. Also, w/o the update, I can add archive invalidation to the command.

@mnapoli @tsteur @mattab What are your thoughts?

### CODE REVIEW

**Comment by mnapoli** [comment]
I remember a discussion about a UNIQUE index, the reason it wasn't implemented that way was because of the potential index size right?

Regarding the patch I don't have a lot of feedback, I'm not familiar at all with the tracker. Is the additional query a problem? I guess it's searching against the whole table, so I wonder how it performs.

**Comment by diosmosis** [comment]
Do you mean the query after an INSERT? There's an index on hash + type, so it should be fast. I'm not positive about the group by's but I think the index will be used there too, since it should group by type + hash then name.

**Comment by tsteur** [comment]
Do you mind writing tests for the `Tracker/Model` part?

> I'm not positive about the group by's but I think the index will be used there too, since it should group by type + hash then name.

Maybe we can ask PRO to run such a query on a big instance with `EXPLAINS` to be sure an index is used? 

Also not sure re the Update. I would probably just remove it and if someone wants to run it, they can use the command. Should be announced in the release blog post and mentioned in FAQ

**Comment by tsteur** [comment]
Looking for duplicated action ids this way looks like a pretty good solution to me :+1: It shouldn't cause much overhead as it is only done once on each action creation anyway.

The `DuplicateActionRemover` class contains many private methods which sometimes indicate that the class could be split into multiple classes but I'm not so deep in it as you are. Maybe It's worth it, maybe not. Might make more methods separately/easier testable when they are public afterwards. Maybe the SQL parts of that class can be also moved into the `Tracker\Model` part so it can be reused and easier tested when needed? 

Otherwise :+1:

**Comment by diosmosis** [comment]
Note: I removed some private methods, but I don't think the SQL is actually useful enough to move to another class (in a plugin or in core). The queries could only be used for detecting and fixing duplicate actions.

**Comment by tsteur** [comment]
It's not only whether it can be reused by core or plugins. It is also that the SQL statements just rather belong to a "model"  and it makes them better testable. Also you never know whether it can be maybe reused in the future. If anyone has a use case he/she would probably not find it in that class but maybe in the model... Eg those methods could be maybe useful for other cases in the future one never knows: https://github.com/piwik/piwik/pull/7112/files#diff-23c6df91cba3becc700f91001c4e39bbR203 or https://github.com/piwik/piwik/pull/7112/files#diff-23c6df91cba3becc700f91001c4e39bbR172 . At least the SQL could be extracted in another class in that plugin. Doesn't have to be core `Tracker\Model` I agree. This will also make the code more readable since the queries are only a detail and there would be maybe less private methods ;) There is still a lot of code in private methods which indicates that a lot of that code actually belongs somewhere else (it "indicates" it only, it doesn't mean this is always actually the case. it's up to you). It's maybe not so important here.

Can you maybe use bind params here? https://github.com/piwik/piwik/pull/7112/files#diff-23c6df91cba3becc700f91001c4e39bbR179 and here https://github.com/piwik/piwik/pull/7112/files#diff-23c6df91cba3becc700f91001c4e39bbR268 or maybe convert Ids to integer? I know we only get numbers from the database but it will prevent any possible injections in the future in case someone wants to reuse it somewhere else or so and it doesn't hurt.

**Comment by diosmosis** [comment]
@tsteur @mnapoli  I've performed a pretty big refactor on this branch, I think it merits another review. Let me know your thoughts.

File: plugins/CoreAdminHome/Model/DuplicateActionRemover.php [hunk 1]
```diff
@@ -0,0 +1,193 @@
...
+
+            $this->logger->debug("Found following idactions in {table}: {columns}", array(
+                'table' => $table,
+                'columns' => implode(',', $columns)
+            ));
+
+            $result[$table] = $columns;
+        }
+        return $result;
+    }
```
Comment (mnapoli) [inline plugins/CoreAdminHome/Model/DuplicateActionRemover.php]: since the `$tablesWithIdActionColumns` is hardcoded, couldn't it be the same for the columns? Or can they be dynamically added by plugins maybe?

File: core/DataAccess/TableMetadata.php [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+     * Returns the list of column names for a table.
+     *
+     * @param string $table Prefixed table name.
+     * @return string[] List of column names..
+     */
+    public function getColumns($table)
+    {
+        $table = str_replace("`", "", $table);
+
+        $columns = Db::fetchAll("SHOW COLUMNS FROM `" . $table . "`");
```
Comment (mnapoli) [inline core/DataAccess/TableMetadata.php]: Why un-quote then re-quote?

File: plugins/CoreAdminHome/Model/DuplicateActionRemover.php (hunk 1 above)
Comment (diosmosis) [inline plugins/CoreAdminHome/Model/DuplicateActionRemover.php]: They can be added via dimension classes (eg, ContentName). I don't know if there are any non-core ones that add idaction columns, but many core ones do so I guess it's conceivable that they exist. Also, I guess it's possible for some plugins to be disabled in which case the columns wouldn't exist.

File: core/DataAccess/TableMetadata.php (hunk 2 above)
Comment (diosmosis) [inline core/DataAccess/TableMetadata.php]: I'm attempting to avoid SQL injections here (since getColumns is a public method, I am assuming its possible for plugin developers to do stupid things w/ it).

File: core/DataAccess/TableMetadata.php [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+ */
+namespace Piwik\DataAccess;
+
+use Piwik\Db;
+
+/**
+ * Data Access Object that can be used to get metadata information about
+ * the MySQL tables Piwik uses.
+ */
+class TableMetadata
```
Comment (mnapoli) [inline core/DataAccess/TableMetadata.php]: I'm probably picking but I believe this kind of code would be better in `Piwik\Db`, i.e.

- `Piwik\Db` for code related to database, unrelated to domain stuff
- `Piwik\DataAccess` for code related to linking domain stuff to the db

To me getting the columns of a table is really DBAL stuff. This class could still be separated from the `Db` class (I see you deprecated the method), maybe in a `Piwik\Db\Schema` class (like the [`Schema`](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Schema/Schema.php) class in Doctrine)? I imagine later we could have a full abstraction of schema manipulation in there (again, like in Doctrine) to get/create tables, columns, etc…

Thoughts?

File: core/Tracker/Model.php [hunk 4]
```diff
@@ -375,9 +411,21 @@ private function visitFieldsToQuery($valuesToUpdate)
         return array($updateParts, $sqlBind);
     }
 
+    private function deleteDuplicateAction($newActionId)
```
Comment (mnapoli) [inline core/Tracker/Model.php]: `deleteDuplicateActions`?

Comment (diosmosis) [inline core/Tracker/Model.php]: Only deletes one action, but I think this is a redundancy w/ Actions::deleteDuplicateActions. Anyone see a problem w/ using that class from within Tracker/Model?

File: core/DataAccess/TableMetadata.php (hunk 3 above)
Comment (diosmosis) [inline core/DataAccess/TableMetadata.php]: Yeah, my thoughts are that getColumns is pretty generic, but getIdActionColumnNames is specific to certain use-cases/functionality. Ideally, I think all relational stuff would be in its own plugin (ie, plugins/MySQL or plugins/Relational, etc.). This way it wouldn't need to be in core, but Piwik is pretty far away from the possibility of defining a data access layer in a plugin.

FYI, I only moved it in response to @tsteur last comment about making as much re-usable as possible.

File: plugins/CoreAdminHome/Commands/FixDuplicateLogActions.php [hunk 5]
```diff
@@ -0,0 +1,215 @@
...
+
+        if ($actionsAccess === null) {
+            $actionsAccess = new Actions();
+        }
+        $this->actionsAccess = $actionsAccess;
+
+        if ($logger === null) {
+            $logger = StaticContainer::get('Psr\Log\LoggerInterface');
+        }
+        $this->logger = $logger;
```
Comment (mnapoli) [inline plugins/CoreAdminHome/Commands/FixDuplicateLogActions.php]: if you prefer those if statements could be eg:

```php
$this->archiveInvalidator = $invalidator ?: new ArchiveInvalidator();
```

Comment (diosmosis) [inline plugins/CoreAdminHome/Commands/FixDuplicateLogActions.php]: > You could also get all those dependencies from the container so that you can use dependency injection without having null in constructors

Would I have to access StaticContainer directly? Maybe it's possible to do it once for the console command? That would be nice.

Comment (mnapoli) [inline plugins/CoreAdminHome/Commands/FixDuplicateLogActions.php]: Yes that would definitely be nice!

The problem lies with how Symfony's Console work: we need to register command objects, so that means creating every single command just to init the console (see https://github.com/symfony/symfony/issues/12063).

So if we start doing dependency injection in commands, that means every dependency will be created and injected, with dependencies of dependencies, etc... So 1 or 2 command isn't a big deal but we risk running into a case where a huge load of objects are created by the container just to end up using a few of them…

PHP-DI offers to do lazy injection but:

1. we can't use that in Piwik since it requires a lib that requires PHP > 5.3.20 or something
2. it would mean marking most services as lazy, which doesn't make any sense
3. this is not a clean solution anyway…

So in the meantime we are stuck with doing service location instead of dependency injection in commands…

Comment (mnapoli) [inline plugins/CoreAdminHome/Commands/FixDuplicateLogActions.php]: By the way we could do something a tiny bit cleaner by introducing a `get()` method on commands that would proxy that to the container, e.g.:

```php
$logger = $this->get('Psr\Log\LoggerInterface');
```

(like in Symfony's controllers)

That's still service location, it's just a few characters shorter (and no static calls to `StaticContainer`)… I don't have a strong opinion on this.

File: core/DataAccess/TableMetadata.php (hunk 2 above)
Comment (mattab) [inline core/DataAccess/TableMetadata.php]: In Db::getColumnNamesFromTable() we have already such logic, could it be reused?

File: core/Tracker/Model.php (hunk 4 above)
Comment (mattab) [inline core/Tracker/Model.php]: Which class do you mean? (couldn't see a method called `deleteDuplicateActions`)

File: core/DataAccess/TableMetadata.php (hunk 2 above)
Comment (mnapoli) [inline core/DataAccess/TableMetadata.php]: @mattab the code was moved from that method (see [here](https://github.com/piwik/piwik/pull/7112/files#diff-4410ab928da865a7fe6bbb3dea2e48c2L391))

Comment (mattab) [inline core/DataAccess/TableMetadata.php]: Ok nice!

**Comment by mattab** [comment]
Looks good to me, ready to merge?

**Comment by mattab** [comment]
Well done @diosmosis 

It's a real relief that this bug will be fixed! :+1:

File: plugins/CoreAdminHome/Commands/FixDuplicateLogActions.php (hunk 5 above)
Comment (diosmosis) [inline plugins/CoreAdminHome/Commands/FixDuplicateLogActions.php]: @mnapoli Is it possible to inject dependencies in-place? Ie, after an object has been created? We could maybe create commands w/o setting dependencies and then before executing a command, we resolve the dependencies and call Command::execute. The dependencies would have to be specified via the `@Inject` annotation I think.

Comment (mnapoli) [inline plugins/CoreAdminHome/Commands/FixDuplicateLogActions.php]: Yes it's possible (`$container->injectOn($obj)`) but we decided not to use annotations last time it was discussed.

Another option would be to keep commands as simple as possible and move everything into classes, though that's very far from the current reality in the codebase.

Comment (diosmosis) [inline plugins/CoreAdminHome/Commands/FixDuplicateLogActions.php]: Maybe a proxy command class can be used in core\Console.php and the actual command instance wouldn't be created until the proxy's execute() method is called?

Comment (mnapoli) [inline plugins/CoreAdminHome/Commands/FixDuplicateLogActions.php]: Commands are instantiated because Symfony's Console needs to read the options/configuration. Even if we had a proxy commands would still be instantiated, unless we change the way commands are configured (i.e. we diverge from Symfony's official way) which would be fine by me (given this problem is pretty important)…

Comment (mnapoli) [inline plugins/CoreAdminHome/Commands/FixDuplicateLogActions.php]: After thinking about it that sounds a good idea, I think I'll have a look at it (having DI only in controllers is really limiting…)

Comment (diosmosis) [inline plugins/CoreAdminHome/Commands/FixDuplicateLogActions.php]: It would be awesome if it works :)
