### PR TITLE
GeoIP first will update the next day, then weekly/monthly after that

### LINKED ISSUE #11006: some broken/non good things before/during setting up geoip
some broken things before/during setting up geoip in latest stable Piwik (2.17.1):
1. [fixed with P3.0 see https://github.com/piwik/piwik/issues/11006#issuecomment-267133495]
broken design (too large font, FF 50.1)
please see attachment 
2. url shown of free  DB without only http instead of https (which works perfect for download)
please see attachment
3. url has to be copied which is uncomfortable: would be better to have a button "use this"
4. after setting up, one get a date at least one week in the future when it's downloaded first time - should be immediately (otherwise there is no geoip function for at least a week)
please see attachment

2016-12-14_14h33_50
2016-12-14_14h57_28

### PR DESCRIPTION
**Pull request by diegobanos**
This should fix the last part of #11006

### CODE REVIEW

**Comment by mattab** [comment]
Thanks Diego for the nice PR including the tests!

We will review for inclusion in 3.0.5 release. We hope you will keep submitting such quality Pull requests :sunglasses:

**Comment by diegobanos** [comment]
@mattab It's a fun project to contribute to! Thanks for the feedback!

File: tests/PHPUnit/Unit/Scheduler/TimetableTest.php [hunk 1]
```diff
@@ -61,6 +63,19 @@ public function testGetTimetableFromOptionValue($expectedTimetable, $option)
         self::resetPiwikOption();
     }
 
+    public function testRescheduleTaskAndRunTomorrow()
+    {
+        $timetable = new Timetable();
```
Comment (sgiehl) [inline tests/PHPUnit/Unit/Scheduler/TimetableTest.php]: This test [fails](https://travis-ci.org/piwik/piwik/jobs/227048006#L857), as no database is set up, but `Timetable` constructor performs an `Option:get`, which requires a database.

Comment (diegobanos) [inline tests/PHPUnit/Unit/Scheduler/TimetableTest.php]: @sgiehl Wouldn't that test run on the test database?

Comment (sgiehl) [inline tests/PHPUnit/Unit/Scheduler/TimetableTest.php]: No. The test class extends `\PHPUnit_Framework_TestCase`. It would need to be an Integration or System test to have a database setup.
Nevertheless the test might work if another test using database ran before, but that's not always the case.

Comment (diegobanos) [inline tests/PHPUnit/Unit/Scheduler/TimetableTest.php]: @sgiehl I could review this if needed. What would you recommend me to do? Should I change this test for an Integration test or something similar?

Comment (sgiehl) [inline tests/PHPUnit/Unit/Scheduler/TimetableTest.php]: Maybe creating a Mock of TimeTable with empty constructor and `save` method could work as well.
It's only those methods requiring the database.

Comment (diegobanos) [inline tests/PHPUnit/Unit/Scheduler/TimetableTest.php]: @sgiehl I will get on that then. Thanks for the feedback.

**Comment by diosmosis** [comment]
Hi @diegobanos, do you think you'll have time to finish this PR?

**Comment by tsteur** [comment]
@diegobanos are you still working on this PR? It looks like not much is missing.  Be good to let us know 👍

**Comment by diosmosis** [comment]
Thanks @diegobanos for the contribution! Glad we can finally get it merged.
