### PR TITLE
[JS]update beforeunload to visibilitychange

### LINKED ISSUE #18810: Ensure JS tracker unload event is triggered in edge cases to make sure tracking requests are sent
While testing https://github.com/matomo-org/matomo/pull/18135 I noticed that the beforeunload event isn't triggered when forcing a page reload. Was then reading https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon . 

> Web sites often want to send analytics or diagnostics to the server when the user has finished with the page. The most reliable way to do this is to send the data on the [visibilitychange](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) event

It also explains why you should use this event instead of unload. It basically may not be triggered in various cases (not sure if it's also the case for `beforeunload`, to be investigated).

This could result in few queued requests not being sent and therefore some data may not be tracked. Especially premium features leverage the unload event and queued tracking to send a tracking request (eg for Media Analytics to track how much of a media has been viewed when leaving).

Something like:

```js
        addEventListener(windowAlias, 'visibilitychange', function () {
  if (document.visibilityState === 'hidden') {
          executePluginMethod('unload');
}
        }, false);
```

Seems this is supported on most browsers: https://caniuse.com/?search=visibilitychange Maybe as a fallback we would still also listen to beforeunload in case this event isn't triggered so it still works on older browsers too maybe? Might not be needed depending on browser compatibility.

We would also need to make sure that this won't cause any regressions by listening to this new event. Also if someone switches a lot between tabs and the page becomes visible and hidden a lot, then we wouldn't want to start sending heaps of tracking requests.

Be good if someone could look into this. The goal of the issue would be to make sending tracking requests more reliable when a user leaves a site.

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:

Fixes: #18810 

update `beforeunload` to `visibilitychange`

Please include a description of this change and which issue it fixes. If no issue exists yet please include context and what problem it solves.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by peterhashair** [comment]
build js

**Comment by peterhashair** [comment]
build js

File: js/piwik.js [hunk 1]
```diff
@@ -499,11 +499,13 @@ if (typeof window.Matomo !== 'object') {
          */
         function beforeUnloadHandler() {
             var now;
-            isPageUnloading = true;
 
-            executePluginMethod('unload');
+            if (documentAlias.visibilityState === 'hidden') {
```
Comment (sgiehl) [inline js/piwik.js]: Shouldn't that be more something like
```js
if (documentAlias.visibilityState !== 'hidden') {
    return;
}
isPageUnloading = true;
executePluginMethod('unload');
```

Otherwise blocking the UI below will always be done...

**Comment by peterhashair** [comment]
build js

**Comment by peterhashair** [comment]
build js

**Comment by peterhashair** [comment]
@sgiehl it seems like the `documentAlias.visibilityState === 'hidden'` can only apply to `executePluginMethod('unload')`. Otherwise it won't update the time, I am not too sure if that's better than origin method `beforeUnload`

**Comment by peterhashair** [comment]
build js

File: js/piwik.js [hunk 2]
```diff
@@ -7166,7 +7169,8 @@ if (typeof window.Matomo !== 'object') {
          ************************************************************/
 
         // initialize the Matomo singleton
-        addEventListener(windowAlias, 'beforeunload', beforeUnloadHandler, false);
+        addEventListener(windowAlias, 'beforeunload', beforeUnloadHandler,false);
```
Comment (justinvelluppillai) [inline js/piwik.js]:
```suggestion
        addEventListener(windowAlias, 'beforeunload', beforeUnloadHandler, false);
```

**Comment by peterhashair** [comment]
build js

**Review by justinvelluppillai — CHANGES_REQUESTED** [review]
This looks like the right approach to me @peterhashair, but there is one failing test  because the unload handler takes longer now:

> Test failed in module request: 'Internal timers and setLinkTrackingTimer()' 
> 
> Error: beforeUnloadHandler(): 522 was greater than 520

Also can any test be added eg  `beforeUnloadHandler({ type: 'visibilitychange' })` ?

**Comment by peterhashair** [comment]
@justinvelluppillai will fix that one, you are 100% correct, test changed to `visibilitychange `

**Comment by justinvelluppillai** [comment]
I don't see the changes yet so will remove the `needs review` label until they're done @peterhashair 👍

**Review by bx80 — CHANGES_REQUESTED** [review]
It looks like the most recent merge of 4.x into this branch has overwritten the commit that updated the test time from 520 to 530.

File: tests/javascript/index.php [hunk 3]
```diff
@@ -5205,16 +5205,18 @@ function testWithWrappedConsole(callback) {
         equal( typeof tracker.hook.test._beforeUnloadHandler, 'function', 'beforeUnloadHandler' );
 
         startTime = new Date();
-        tracker.hook.test._beforeUnloadHandler();
+        tracker.hook.test._beforeUnloadHandler({ type: 'beforeunload' });
         stopTime = new Date();
         var msSinceStarted = (stopTime.getTime() - startTime.getTime());
-        ok( msSinceStarted < 525, 'beforeUnloadHandler(): ' + msSinceStarted + ' was greater than 520 ' );
+        ok( msSinceStarted < 520, 'beforeUnloadHandler(): ' + msSinceStarted + ' was greater than 520 ' );
```
Comment (justinvelluppillai) [inline tests/javascript/index.php]:
```suggestion
        ok( msSinceStarted < 530, 'beforeUnloadHandler(): ' + msSinceStarted + ' was greater than 530 ' );
```

**Comment by bx80** [comment]
@peterhashair I'm seeing `beforeUnloadHandler` calling `executePluginMethod('unload')` once when initially switching tabs on a tracked page. Is this intentional? 

My test was to add a `console.log(event);` statement to the first line of `beforeUnloadHandler` and `console.log('executePluginMethod');` after the `isPageUnloading` check. Then load a tracked page and switch tabs. The first time the tab is switched `executePluginMethod` is called, subsequent tab switches do not result in additional calls.

**Comment by peterhashair** [comment]
@bx80 yes, I found the same problem, mention on the issue itself as well,`visibilitychange` event is a kind of design for mobile, triggers on changing tab, etc, but I guess that's expected.

**Comment by bx80** [comment]
@peterhashair I suppose existing plugin code would need to be aware that `executePluginMethod('unload')` could now be called on a tab switch and not just on page unload. This might be a breaking change if code is relying on a single unload event being fired only when a page is closed. 

For example, it looks like HSR will stop sending data the first time that the plugin unload event is called, so in a scenario where the user loaded the page, quickly switched to another tab to check mail and then switched back, then I suspect none of the subsequent user interactions would be recorded.

**Comment by peterhashair** [comment]
@bx80 makes sense, let me see if I can filter out the tab switch event.

**Comment by peterhashair** [comment]
@bx80 I am trying to do some research seems like that even can't escape tab change. Maybe that event shouldn't be added, any thought?

**Comment by bx80** [comment]
@peterhashair I took a look too and it doesn't look like the visibility API offers any way to differentiate between a tab switch and leaving the page, so we probably don't want to have this event trigger the plugin unload event and potentially break existing plugins.

**Comment by peterhashair** [comment]
@bx80 agree, but I notice, the visibiltyChange actually useful when is mobile.` beforeunload` won't trigger for those.

- A mobile user visits your page.
- The user then switches to a different app.
- Later, the user closes the browser from the app manager.

**Comment by peterhashair** [comment]
@bx80 just revert some changes, am I on the right track?

**Review by bx80 — APPROVED** [review]
Looks good to me, both events are being handled and the plugin `load` event is only being called once on leaving the page. The first tab switch is still triggering the unload event, but as discussed this should be ok :+1:
