### PR TITLE
fix row actions for action table with goal metrics

### LINKED ISSUE #21117: Page evolution chart URLs incorrect when choosing "Display a table with Goal metrics"
When an evolution chart is viewed after selecting the chart option "Display a table with Goal metrics", the chart displays a URL without including subdirectories. The chart also appears to display results for these non-existent URLs (no data)...
image

Reproduced with on-premise and Cloud, v 4.15

### Steps to reproduce:

1. Go to Behaviour -> Pages
2. Choose the table option "Display a table with Goal metrics"
Screenshot from 2023-08-04 11-46-20

3. View an evolution chart for a page that is located in a subdirectory of the site
 image

If the Pages table is set to 'Make it flat' this does not occur.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #21117 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/CoreHome/javascripts/dataTable_rowactions.js [hunk 1]
```diff
@@ -178,7 +178,7 @@ DataTable_RowAction.prototype.trigger = function (tr, e, subTableLabel, original
     }
 
     // ascend in action reports
-    if (subtable.closest('div.dataTableActions').length) {
```
Comment (michalkleiner) [inline plugins/CoreHome/javascripts/dataTable_rowactions.js:181]: Were we just missing the `dataTableActions` class (e.g. it being removed in past) and it would work with it or we still have the class but need to be more specific with the selector?

Comment (sgiehl) [reply plugins/CoreHome/javascripts/dataTable_rowactions.js:181]: I actually wasn't pretty sure about it. Maybe a bit of both. It's not the normal actions datatable, but a goal visualization with actions, so it doesn't have the `dataTableActions`, but the goal viz related classes. Goal metrics for actions have been added somewhen end of last year, so guess this was kind of missed and the row evolution didn't ever work there.

**Review by michalkleiner — APPROVED** [review]
