### PR TITLE
Only invalidate in past for segments that belong to the site …

### LINKED ISSUE #16892: Check only invalidations created for correct sites
We have a customer that reports this:

> Piwik\Segment->__construct(dimension17==DE, Array ([0] => 1)) - that looks like Matomo is trying to load a segment from another idSite for Site 1, which will fail because idSite1 does not have a dimension17.

image

Here is the backtrace:

```
[32mINFO [2020-12-05 15:30:25] 8485 [39m Start processing archives for site 1.
#0  Piwik\Segment->getSegmentByName(dimension17) called at [core/Segment.php:258]
#1  Piwik\Segment->getExpressionsWithUnionsResolved(Array ([0] => Array ([0] => ,[1] => Array ([0] => dimension17,[1] => ==,[2] => DE)))) called at [core/Segment.php:236]
#2  Piwik\Segment->initializeSegment(dimension17==DE, Array ([0] => 1)) called at [/var/app/current/core/Segment.php:145]
#3  Piwik\Segment->__construct(dimension17==DE, Array ([0] => 1)) called at [core/CronArchive/SegmentArchiving.php:128]
#4  Piwik\CronArchive\SegmentArchiving->findSegmentForHash(90a5a511e1974bca37613b6daec137ba, 1) called at [core/CronArchive/QueueConsumer.php:472]
#5  Piwik\CronArchive\QueueConsumer->findSegmentForArchive(Array ([idinvalidation] => 210,[idarchive] => ,[idsite] => 1,[date1] => 2020-12-04,[date2] =>
```

@diosmosis can you check if it's possible that we invalidate entries for a segment for a wrong site somehow?

That's using 4.0.4

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

… and only process an invalidation if it is for a site + we can load the segment

Fixes #16892
FYI @tsteur 

### Review

* [ ] Functional review done
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/CronArchive/SegmentArchiving.php [hunk 1]
```diff
@@ -20,6 +20,7 @@
 use Piwik\Segment;
 use Piwik\Site;
 use Psr\Log\LoggerInterface;
+use function DI\object;
```
Comment (sgiehl) [inline core/CronArchive/SegmentArchiving.php]: guess that use statement isn't needed

File: core/CronArchive/SegmentArchiving.php [hunk 2]
```diff
@@ -294,7 +305,7 @@ public function getAllSegmentsToArchive($idSite)
         return $segments;
     }
 
-    private function isSegmentForSite($segment, $idSite)
+    public function isSegmentForSite($segment, $idSite)
```
Comment (sgiehl) [inline core/CronArchive/SegmentArchiving.php]: Any reason for having that on public now? Seems it isn't used outside the class. Not even in tests...

File: core/CronArchive/SegmentArchiving.php [hunk 3]
```diff
@@ -121,11 +124,19 @@ public function getSegmentArchivesToInvalidate($idSite, $checkOnlyForNewSegments
...
+            if (!$this->isAutoArchivingEnabledFor($segment)
+                || !$this->isSegmentForSite($segment, $idSite)
+            ) {
+                continue;
+            }
+
+            try {
+                $segmentObj = new Segment($segment['definition'], [$idSite]);
+            } catch (\Exception $ex) {
+                $this->logger->debug("Could not process segment {$segment['definition']} for site {$idSite}. Segment should not exist for the site, but does.");
```
Comment (sgiehl) [inline core/CronArchive/SegmentArchiving.php:135]: The debug message confuses me. Isn't an exception thrown when the segment does not exist?
Also this case shouldn't occur at all if the `isSegmentForSite` works correctly, right?

**Review by sgiehl — CHANGES_REQUESTED** [review]

File: core/CronArchive/SegmentArchiving.php (hunk 3 above)
Comment (diosmosis) [reply core/CronArchive/SegmentArchiving.php:135]: It shouldn't occur, but if it does it would break archiving, and I didn't think that needed to happen. This is a sanity check.

**Comment by diosmosis** [comment]
@tsteur @sgiehl merging this, any other changes I can make in a new PR
