### PR TITLE
[UI]update invalid archive notification

### LINKED ISSUE #19011: When a segment is shown, and no data is there, then show accurate error message when segment won't be archived
To reproduce, set below config settings:

```
[General]
rearchive_reports_in_past_last_n_months = "last1"
rearchive_reports_in_past_exclude_segments = 1
process_new_segments_from = "editLast30"
enable_general_settings_admin = 0
enable_browser_archiving_triggering = 0
browser_archiving_disabled_enforce = 1
enable_create_realtime_segments = 0
```

* Then create a segment
* Then request a date range from 1 year ago.
* You will see an error message like below:

image

It suggests the data may become available and it may be a problem if the message doesn't go away.

However, in reality, the data will never appear because the requested data will never be archived. That's because the segment was last edited on say `2022-01-13 08:25:22` meaning we never archive any data from before say `2021-12-13` because of the `process_new_segments_from = "editLast30"` setting. 

Expected:
The message should make it clear why the data won't become available.

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:
Fixes: #19011 
update invade archive notification caused by config `rearchive_reports_in_past_last_n_months` limitation

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/Archive/ArchiveInvalidator.php [hunk 1]
```diff
@@ -795,7 +795,7 @@ private function getAllSitesId()
         return $this->allIdSitesCache;
     }
 
-    private function getEarliestDateToRearchive()
+    public static function getEarliestDateToRearchive()
```
Comment (sgiehl) [inline core/Archive/ArchiveInvalidator.php]: When changing a method to `static`, I would expect that some method calls in that class needs to be changed to a static calls. Otherwise this might throw deprecations on newer PHP versions.

File: plugins/SegmentEditor/lang/en.json [hunk 2]
```diff
@@ -39,6 +39,7 @@
         "SegmentOperatorIsNotNullNorEmpty": "is not null nor empty",
         "UnprocessedSegmentNoData1": "These reports have no data, because the Segment you requested %1$s has not yet been processed by the system.",
         "UnprocessedSegmentNoData2": "Data for this Segment should become available in a few hours when processing completes. (If it does not, there may be a problem.)",
+        "UnprocessedSegmentNoData3": "Data is not showing because the re archive date setting in config (rearchive_reports_in_past_last_n_months) is later than the select period, please update config or select a new period, then rerun archive process.",
```
Comment (sgiehl) [inline plugins/SegmentEditor/lang/en.json]: This message sounds very technical. Is it only displayed to super users? It might be more useful to have a message that everyone can understand. Maybe something like `Matomo is unable to display data for this period, as the configuration prevents a rearchiving. Please contact your administrator or check this FAQ how to solve this problem.`

File: plugins/SegmentEditor/SegmentEditor.php [hunk 3]
```diff
@@ -283,7 +285,20 @@ private function getSegmentIfIsUnprocessed()
             $storedSegment = null;
         }
 
-        return [$segment, $storedSegment, $isSegmentToPreprocess];
+
+        $lastArchiveData =  ArchiveInvalidator::getEarliestDateToRearchive();
+
+        $endDate = $period->getDateEnd();
+        $archived = true;
```
Comment (sgiehl) [inline plugins/SegmentEditor/SegmentEditor.php]: Wouldn't a variable name like `$canBeArchived` make the code easier to understand?

File: plugins/SegmentEditor/SegmentEditor.php [hunk 4]
```diff
@@ -283,7 +285,20 @@ private function getSegmentIfIsUnprocessed()
             $storedSegment = null;
         }
 
-        return [$segment, $storedSegment, $isSegmentToPreprocess];
+
+        $lastArchiveData =  ArchiveInvalidator::getEarliestDateToRearchive();
```
Comment (sgiehl) [inline plugins/SegmentEditor/SegmentEditor.php]: `$lastArchiveData` seems to be an improper variable name. Would be good to use names that make the code easier to understand.

File: plugins/SegmentEditor/templates/_unprocessedSegmentMessage.twig [hunk 5]
```diff
@@ -1,17 +1,22 @@
...
-<p>
-    {{ 'SegmentEditor_UnprocessedSegmentInVisitorLog1'|translate(visitorLogLinkHtml, '</a>')|raw }}
-    {{ 'SegmentEditor_UnprocessedSegmentInVisitorLog2'|translate }}
-    {{ 'SegmentEditor_UnprocessedSegmentInVisitorLog3'|translate }}
-</p>
\ No newline at end of file
+    {% if isSegmentToPreprocess %}
+        {% if not archived %}
+            <p>
+                {{ 'SegmentEditor_UnprocessedSegmentNoData3'|translate }}
```
Comment (sgiehl) [inline plugins/SegmentEditor/templates/_unprocessedSegmentMessage.twig]: Does it make sense to show this message and also the others below? First it says the data is unavailable and the second part then says it will become available in a couple of hours maybe. That might irritate people...

**Review by sgiehl — CHANGES_REQUESTED** [review]
Had a look through the code and left some comments. Did not yet do any functional testing

File: plugins/SegmentEditor/lang/en.json [hunk 6]
```diff
@@ -39,6 +39,7 @@
         "SegmentOperatorIsNotNullNorEmpty": "is not null nor empty",
         "UnprocessedSegmentNoData1": "These reports have no data, because the Segment you requested %1$s has not yet been processed by the system.",
         "UnprocessedSegmentNoData2": "Data for this Segment should become available in a few hours when processing completes. (If it does not, there may be a problem.)",
+        "UnprocessedSegmentNoData3": "Matomo is unable to display data for this period, as the configuration prevents a rearchiving. Please contact your administrator or check this FAQ how to solve this problem.",
```
Comment (sgiehl) [inline plugins/SegmentEditor/lang/en.json]: Not sure if we already have a FAQ that matches for this case. If not we may need to create one and link the FAQ in the text above.

**Comment by peterhashair** [comment]
I believe the doc is here, https://matomo.org/wp-admin/post.php?post=775&action=edit&lang=en.
 
 Adding when PR merged
> This could be caused by configuration in `config.ini.php`, the limitation of the archive date setting, under [General] `rearchive_reports_in_past_last_n_months`, make sure the request period is in the range of the earliest archive date, then rerun the archive process.

File: plugins/SegmentEditor/lang/en.json (hunk 6 above)
Comment (sgiehl) [reply plugins/SegmentEditor/lang/en.json]: The link is missing and we should still avoid displaying both messages. Maybe we could unify that to:
```suggestion
        "UnprocessedSegmentNoData3": "Matomo is unable to display data for the segment %1$s, as the configuration prevents a rearchiving for this period. Please contact your administrator or check %2$sthis FAQ%3$s how to solve this problem.",
```

File: plugins/SegmentEditor/templates/_unprocessedSegmentMessage.twig [hunk 7]
```diff
@@ -1,17 +1,24 @@
...
-    {{ 'SegmentEditor_UnprocessedSegmentInVisitorLog1'|translate(visitorLogLinkHtml, '</a>')|raw }}
-    {{ 'SegmentEditor_UnprocessedSegmentInVisitorLog2'|translate }}
-    {{ 'SegmentEditor_UnprocessedSegmentInVisitorLog3'|translate }}
-</p>
\ No newline at end of file
+    {% if isSegmentToPreprocess %}
+        {% if not canBeArchived %}
+            <p>
+                {{ 'SegmentEditor_UnprocessedSegmentNoData3'|translate }}
+                {{ 'SegmentEditor_UnprocessedSegmentNoData1'|translate('<strong>(' ~ segmentName ~ ')</strong>')|raw }}
```
Comment (sgiehl) [inline plugins/SegmentEditor/templates/_unprocessedSegmentMessage.twig]:
```suggestion
                {{ 'SegmentEditor_UnprocessedSegmentNoData3'|translate('<strong>(' ~ segmentName ~ ')</strong>', '<a href="https://matomo.org/faq/troubleshooting/faq_141/" rel="noreferrer noopener">', '</a>')|raw }}
```

**Review by sgiehl — CHANGES_REQUESTED** [review]
The message shown can still be improved. Also the linked FAQ is missing. I've added a couple suggestions to improve it. The UI test will need an update as well. And I was wondering if we can't add another UI test that covers the other case.

**Review by bx80 — CHANGES_REQUESTED** [review]
I've done some functional testing, looks good :+1:

There are two failing UI tests related to the segment editor, since this PR makes changes to the segment editor I've pushed an empty commit to rerun the tests in case it's a random failure, if not then we should find out why these tests are failing.

**Comment by peterhashair** [comment]
@bx80 that's wired one, will investigate

**Comment by peterhashair** [comment]
@bx80 I believe the UI test's failure is random.

**Review by bx80 — APPROVED** [review]
The UI test fails are unrelated, so this should be good to merge :+1:

(Don't forget to update the FAQ :slightly_smiling_face:)
