### PR TITLE
Fix type hints for nullable parameters

### LINKED ISSUE #23904: [Bug] Deprecation warnings for nullables
### What happened?

The parameter types should be marked optional (?).

app/core/FrontController.php(588)
`private function makeAuthenticator(SessionAuth $auth = null)`

app/plugins/CoreAdminHome/Commands/RunScheduledTasks.php(26)
`    public function __construct(LoggerInterface $logger = null)`

app/vendor/wikimedia/less.php/lib/Less/Functions.php(12)
`        function __construct($env, array $currentFileInfo = null)`

app/core/Settings/Interfaces/Traits/PolicyComparisonTrait.php(37)
`    public static function getPolicyValuesAgainstProvided($settingValue, int $idSite = null)`

app/core/Settings/Interfaces/PolicyComparisonInterface.php(25)
`    public static function getPolicyValuesAgainstProvided($settingValue, int $idSite = null);`

app/plugins/PrivacyManager/API.php(388)
`    public function setComplianceStatus(string $idSite, string $complianceType, bool $enforce, string $passwordConfirmation = null) : bool`

I was directed here from the WordPress [plugin support page](https://wordpress.org/support/topic/deprecation-warnings-for-nullables/#post-18758793).

### What should happen?

No warnings.

### How can this be reproduced?

Set up Matomo and click through the admin pages.

(Otherwise see the code, it's trivial.)

### Matomo version

5.6.0

### PHP version

8.4

### Server operating system

Debian

### What browsers are you seeing the problem on?

_No response_

### Computer operating system

Windows

### Relevant log output

```shell

```

### Validations

- [x] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [x] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [x] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description

This PR also enables a PHPCS rule to ensure this is correctly type hinted in the future.

fixes #23904 

### Checklist

- [NA] I have understood, reviewed, and tested all AI outputs before use
- [NA] All AI instructions respect security, IP, and privacy rules

### Review

- [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
- [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behaviour of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
- [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
- [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
- [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
- [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
- [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
- [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
- [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
- [ ] [New documentation added or existing documentation updated](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)

### CODE REVIEW

File: plugins/CorePluginsAdmin/API.php [hunk 1]
```diff
@@ -46,8 +46,11 @@ public function __construct(SettingsProvider $settingsProvider, SettingsMetadata
      * @param array $settingValues Format: array('PluginName' => array(array('name' => 'SettingName1', 'value' => 'SettingValue1), ..))
      * @throws Exception
      */
-    public function setSystemSettings($settingValues, $passwordConfirmation = false)
-    {
+    public function setSystemSettings(
+        $settingValues,
+        #[\SensitiveParameter]
+        $passwordConfirmation = false
```
Comment (tzi) [inline plugins/CorePluginsAdmin/API.php:52]: Could this be on the same line?

```suggestion
        #[\SensitiveParameter] $passwordConfirmation = false
```

Comment (sgiehl) [reply plugins/CorePluginsAdmin/API.php:52]: no, that would break on PHP 7, as it doesn't support those attributes and would then interpret the whole line as a comment.

Comment (tzi) [reply plugins/CorePluginsAdmin/API.php:52]: Clear! Thanks

**Review by tzi — APPROVED** [review]
