### PR TITLE
With multi_server_environment enable maintain won't send 503 as response

### LINKED ISSUE #18054: Multi server environment in maintenance mode shouldn't result in 503 response
In the FAQ https://matomo.org/faq/new-to-piwik/faq_134/ it is written
"When Matomo is used behind a load balancer, here are the steps to follow:
..... in your config.ini.php, below the section [General], add the following line: multi_server_environment=1. This setting lets Matomo know you’re using multiple servers....."

When publishing a web-service via loadbalancers, you use a health-monitor that checks that the web-application answers as expected. As described in https://matomo.org/faq/how-to/faq_20278/

When activating maintenance_mode, the Reporting API and Core platform changes status-code from 200 to 503.
This will cause the loadbalancers to stop sending traffic to the web-server. And the maintenance page is not reachable for the visitors/clients.

## Expected Behavior

When multi_server_environment = 1  (or new property indicating that there is a loadbalancers in front of matomo) is set.
And maintenance_mode = 1 is set,  the status code from Reporting API and Core platform should still be http 200.
So clients are displayed with the maintenance page.

## Current Behavior

Reporting API and Core platform returns 503 when maintenance_mode is set to 1.

## Possible Solution

When using multi_server_environment ( or new property),  and maintenance_mode is set to 1. Keep the response code 200.

## Steps to Reproduce (for Bugs)

1. maintenance_mode = 0 
2. `curl -ik 'https://matomo.example.com/index.php?module=API&method=API.getMatomoVersion&token_auth=<token>`
Results in a 200 OK
3. maintenance_mode = 1
4. same command as in step 2 results in a 503  Service Unavailable.

## Your Environment

* Matomo Version: 4.4.1
* PHP Version: PHP 7.4.3
* Server Operating System: Ubuntu 20.04.3

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:
Fixes: #18054 

With multi_server_environment enable maintain won't send 503 as a response. Missing tests

Docs update
https://matomo.org/faq/how-to/faq_20278/
 ```
+ When Matomo is maintenance_mode, the API will return `503`, unless Matomo is configured behind a load balancer, with `General` config `multi_server_environment=1`, should return http status code `200` 
```

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/FrontController.php [hunk 1]
```diff
@@ -493,7 +493,8 @@ protected function prepareDispatch($module, $action, $parameters)
 
     protected function handleMaintenanceMode()
     {
-        if ((Config::getInstance()->General['maintenance_mode'] != 1) || Common::isPhpCliMode()) {
+        // as request matomo behind load balancer should not return 503. https://github.com/matomo-org/matomo/issues/18054
+        if ((Config::getInstance()->General['maintenance_mode'] != 1) || Common::isPhpCliMode() || Config::getInstance()->General['multi_server_environment']) {
```
Comment (sgiehl) [inline core/FrontController.php]: I don't think it's on purpose to disable the maintenance mode on multi server environments, is it?
I actually understood the issue in a way, that only the response code should be changed to `200` in that case...

File: core/FrontController.php [hunk 2]
```diff
@@ -493,10 +493,14 @@ protected function prepareDispatch($module, $action, $parameters)
...
     protected function handleMaintenanceMode()
     {
-        if ((Config::getInstance()->General['maintenance_mode'] != 1) || Common::isPhpCliMode()) {
+        if ((Config::getInstance()->General['maintenance_mode'] != 1) || Common::isPhpCliMode() ) {
             return;
         }
-        Common::sendResponseCode(503);
+
+        // as request matomo behind load balancer should not return 503. https://github.com/matomo-org/matomo/issues/18054
+        if (Config::getInstance()->General['multi_server_environment'] != 1) {
```
Comment (sgiehl) [inline core/FrontController.php]: I was wondering if we maybe should replace the usage of Config with the `GeneralConfig::getConfigValue`, when adjusting such code.
It's not really needed, but might be good at some point to only use `GeneralConfig`

**Review by sgiehl — COMMENTED** [review]
The code looks fine now. We should maybe mention this behavior in the description of the config flag here:
https://github.com/matomo-org/matomo/blob/2ba0f7a67cb4aa336ef312e2850de1f325adcb69/config/global.ini.php#L637-L642

And not sure if this should also be mentioned in the changelog, as this is something that might be relevant there. @tsteur what do you think?

**Comment by tsteur** [comment]
@sgiehl it doesn't hurt to mention it if it can be explained easily 👍  

* We also need to update https://matomo.org/faq/how-to/faq_111/
* and https://matomo.org/faq/new-to-piwik/faq_134/

File: config/global.ini.php [hunk 3]
```diff
@@ -639,6 +639,7 @@
 ; By enabling this flag we will for example not allow the installation of a plugin via the UI as a plugin would be only
 ; installed on one server or a config one change would be only made on one server instead of all servers.
 ; This flag doesn't need to be enabled when the config file is on a shared filesystem such as NFS or EFS.
+; During maintenance mode, multiple environment will continue return 200 as response on API request.
```
Comment (sgiehl) [inline config/global.ini.php]: Not sure if that makes it clear enough. Actually this is not limited on API requests. I would suggest something like `When enabled, Matomo will return the response code 200 instead of 503 in maintenance mode.`
Or maybe @justinvelluppillai has a better idea here.

**Review by sgiehl — APPROVED** [review]
Should be good to merge if all FAQs were updated accordingly.

**Comment by sgiehl** [comment]
@peterhashair did you already update the FAQs on this one?

**Comment by peterhashair** [comment]
@sgiehl yes, but haven't reviewed yet. They are here.

- https://matomo.org/wp-admin/revision.php?revision=50566
- https://matomo.org/wp-admin/revision.php?revision=50753
- https://matomo.org/wp-admin/revision.php?revision=50754
