### PR TITLE
Fix percentage calculation on world map

### LINKED ISSUE #14849: Wrong percentage on Visitors Location page
Hi, there is a diff in unique visitors percent stat on the Visitors Location page (`/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&category=General_Visitors&subcategory=UserCountry_SubmenuLocations`) between the Country map widget and the Country table widget.

See the pictures below (19,7% for France on the map, 23,9% for France on the table, both for the same unique visitors number).

Capture d’écran 2019-09-03 à 11 01 30
Capture d’écran 2019-09-03 à 11 01 05

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #14849

### CODE REVIEW

File: plugins/UserCountryMap/Controller.php [hunk 1]
```diff
@@ -286,10 +287,7 @@ private function getMetrics($idSite, $period, $date, $token_auth)
         $metrics = array();
         if (!empty($metaData[0]['metrics']) && is_array($metaData[0]['metrics'])) {
             foreach ($metaData[0]['metrics'] as $id => $val) {
-                // todo: should use SettingsPiwik::isUniqueVisitorsEnabled ?
-                if (Common::getRequestVar('period') == 'day' || $id != 'nb_uniq_visitors') {
-                    $metrics[] = array($id, $val);
-                }
+                $metrics[] = array($id, $val);
```
Comment (sgiehl) [inline plugins/UserCountryMap/Controller.php]: That check should not be needed, as the `API.getMetadata` should only return metrics that are available for the given period.

File: plugins/UserCountryMap/javascripts/visitor-map.js [hunk 2]
```diff
@@ -197,7 +197,7 @@
                 if (metric.substr(0, 3) == 'nb_' && metric != 'nb_actions_per_visit') {
                     var total;
                     if (id.length == 3) total = UserCountryMap.countriesByIso[id][metric];
-                    else if (id == 'world') total = _worldTotal;
+                    else if (id == 'world') total = self.config.visitsSummary[metric];
```
Comment (diosmosis) [inline plugins/UserCountryMap/javascripts/visitor-map.js]: I think we can get rid of the `_worldTotal` variable in the whole file, it doesn't appear to be used anywhere else.

Comment (sgiehl) [reply plugins/UserCountryMap/javascripts/visitor-map.js]: removed the unused vars
