### PR TITLE
[Graphic]reload table if the default date changes

### LINKED ISSUE #18781: Show correct "Rows to display" on Evolution graph
_This issue is related to one I reported before, just can't find it right now. In older issue I complained that "Rows to display" drop-down selector is missing if we use default "Last 30 days" configuration in **Admin Dashboard > Personal > Settings** to be shown in widgets (etc.) when we open **/matomo/index.php** URL (default dashboard), while on Behavior > Pages > Open Row Evolution (for particular page) reports. Now, there is another problem, different than the old one._

The affected function: (screenshot from Behavior > Pages > Open Row Evolution on single row/page > drop-down button under Chart area)

matomo-row-evolution-range-bug

### How to reproduce:

1. Configure Matomo to display "Last 30 days" by default in widgets reports when you open basic **/matomo/index.php** URL (setting is located in **Admin Dashboard > Personal > Settings**, as you prob already know).

2. Open basic Matomo URL, then go to Behavior > Pages > **then switch to single day in the calendar/data range selector [see * note]** e.g. select yesterday (if you don't have enough today's hits) or today's date (if you have enough pages visits / data).

_[note *] This is a very important step, because, as I already wrote about it before, the drop-down button in above screenshot **will not** appear otherwise! This is yet another bug/issue with ORE charts that should be resolved, but it is now not related to this bug report_

3. Now hover over each page and click on **Open Row Evolution** icon/button

4. Chart will open, with drop-down range value at **30** by default. Change it to, say, **90**. Wait until data loads, then close the page (hit anywhere outside the popup window or hit "X" at the top right corner of the popup window).

5. Open another Open Row Evolution window for a different page. Chart still loads "30" but the drop-down selector remembers "90" from before! In order to actually load last 90 (days) report in the chart now you have to select another value, and then select again "90" to actually load last 90 days in the chart.

This was working fine before.

### Is this reproducible on Matomo Online Demo (demo.matomo.cloud)?
No, funny thing is that it works OK there, but the explanation might be that you use "yesterday" as a default reporting date/range in the settings, so that your default URL looks like this:

```https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&segment=&category=Dashboard_Dashboard&subcategory=1```

So, when you switch to Pages, you don't really have to change anything in the date range selector, in order to make Range drop-down button appear when you click on Open Row Evolution. Update: even if we manually select today's date, it still works OK in the demo site.

### Conclusion
This bug is consistent on 3 different installations, all installed at different time points, and running on different systems. I tried logging-out and signing back, but that didn't help.

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:
Fixes: #18781 
reload table if the default date changes. that may cause performance issue

Please include a description of this change and which issue it fixes. If no issue exists yet please include context and what problem it solves.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by bx80** [comment]
@peterhashair I think the desired behavior should be to use the configured defaultLastN period unless there is a remembered lastN from a previous selection. 

It seems this is almost happening except that the lastN dropdown value is initialized as 90 days but the data table is loading data for 30 days. I think the initial data table load should match the value of the lastN dropdown (90 days in this case).

Forcing a reload of the data table when it already exists is going probably to be bad for performance as this will apply to every visualization in every circumstance so big data tables may be reloaded multiple times when they don't need to be.

It might be worth checking where both the evolution lastN dropdown and data table load are getting their initial values. Whatever logic is setting the lastN dropdown to 90days should also be instructing the data table initial load to be 90days too. It would be better to get the data table to load the correct lastN first time rather than having it load the wrong values and then do a second load for the correct values. Hope that makes some sense! :slightly_smiling_face:

**Comment by peterhashair** [comment]
@bx80 yes, I add a flag in to the evolution, when the lastN is remember force the reload, otherwise, it won't reload.

**Comment by peterhashair** [comment]
@sgiehl sorry try to understand this a little bit more, I believe we init load the data from this point
https://github.com/matomo-org/matomo/blob/0d8d469dd88c6aa3009182202e5bea20d31742ac/plugins/CoreHome/DataTableRowAction/RowEvolution.php#L153 

At this point the customer params are not loaded.  it's the possible we load evolution config before  this line`$url = Url::getQueryStringFromParameters($parameters);`.

**Comment by peterhashair** [comment]
@bx80 fixed it, found how to load the data, and put it onto the first API loads. but it seems like the PHPCS started to fail on all my PRs.

File: plugins/CoreHome/DataTableRowAction/RowEvolution.php [hunk 1]
```diff
@@ -111,8 +112,12 @@ public function __construct($idSite, $date, $graphType = 'graphEvolution')
 
         if ($this->period != 'range') {
             // handle day, week, month and year: display last X periods
+            //handle cache if exist
+            $cache = ViewDataTableManager::getViewDataTableParameters(Piwik::getCurrentUserLogin(),
+              'CoreHome.getRowEvolutionGraph');
+            $lastDay = !empty($cache) ? $cache['evolution_' . $this->period . '_last_n'] : null;
```
Comment (bx80) [inline plugins/CoreHome/DataTableRowAction/RowEvolution.php]:
```suggestion
            $lastDay = (isset($cache['evolution_' . $this->period . '_last_n']) ? $cache['evolution_' . $this->period . '_last_n'] : null);
```
The cache object might be non-empty but still not contain `evolution_xxx_last_n` key

**Comment by bx80** [comment]
This is works well for me, nice to catch the cached parameters and get the table loading the correct data first time :+1:

Other than the array key validation tweak, it should be good to go :slightly_smiling_face:

**Review by bx80 — CHANGES_REQUESTED** [review]

**Review by bx80 — APPROVED** [review]

File: plugins/CoreHome/DataTableRowAction/RowEvolution.php [hunk 2]
```diff
@@ -111,8 +112,12 @@ public function __construct($idSite, $date, $graphType = 'graphEvolution')
 
         if ($this->period != 'range') {
             // handle day, week, month and year: display last X periods
+            //handle cache if exist
+            $cache = ViewDataTableManager::getViewDataTableParameters(Piwik::getCurrentUserLogin(),
+              'CoreHome.getRowEvolutionGraph');
+            $lastDay = (isset($cache['evolution_' . $this->period . '_last_n']) ? $cache['evolution_' . $this->period . '_last_n'] : null);
```
Comment (sgiehl) [inline plugins/CoreHome/DataTableRowAction/RowEvolution.php:118]: Just a small note: This could have been simplified to:
```php
$lastDay = $cache['evolution_' . $this->period . '_last_n']) ?? null;
```
