### PR TITLE
Ensure system settings of plugins are displayed correctly in config overview

### LINKED ISSUE #22993: [Bug] Configured plugin settings show as default value in config file page
### What happened?

When configuring plugin settings they seem to override default values in config file page. The configured value is displayed as default and the default value is not visible at all.

In some cases this may expose sensitive information in the UI. For example, if Redis password is configured in QueuedTracking plugin it is displayed as default value in plaintext even if it is a password field. 

### What should happen?

The configured value should be displayed appropriately in it's own column and the default should display the actual default.

### How can this be reproduced?

1. Install a plugin.
2. Configure plugin setting via UI (or config.ini.php).
3. Go to "Config file" page and look for the corresponding setting.

### Matomo version

5.2.0

### PHP version

8.3.15

### Server operating system

AlmaLinux 9, Matomo in docker container

### What browsers are you seeing the problem on?

Chrome

### Computer operating system

Windows 10

### Relevant log output

```shell

```

### Validations

- [x] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [x] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [x] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

Settings for a plugin were incorrectly shown as the default in some cases.

fixes #22993 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/Diagnostics/ConfigReader.php [hunk 1]
```diff
@@ -179,19 +179,21 @@ public function addConfigValuesFromSystemSettings($configValues, $systemSettings
...
-                        'isCustomValue' => false,
-                        'defaultValue' => $defaultValue
+                        'isCustomValue' => $setting->getValue() != $setting->getDefaultValue(),
+                        'defaultValue' => $setting->getDefaultValue()
                     );
                 }
+
+                if (
+                    !empty($configValues[$configSection][$name]['value'])
+                    && $config->uiControl === PiwikSettings\FieldConfig::UI_CONTROL_PASSWORD
```
Comment (michalkleiner) [inline plugins/Diagnostics/ConfigReader.php:193]: Haven't done any benchmarking and don't know PHP internals good enough to be able to say from top of my head, but would the comparison for uiControl type be better as the first condition compared to 3 levels down array value lookup? Perhaps no difference there, but just crossed my mind that in general it's best to put the conditions that can cause skipping the execution most likely at the beginning so that the rest doesn't need to be evaluated at all.

Comment (sgiehl) [reply plugins/Diagnostics/ConfigReader.php:193]: In general it makes sense to put comparisons before function calls if that can avoid additional processing time. But I doubt that has any notable difference in this case. A construct like empty and an array access (even with three levels) should be nothing to worry about.

**Review by mneudert — APPROVED** [review]
