### PR TITLE
Transitions should work as expected even when used along with a Goal segment 

### LINKED ISSUE #9822: SQLSTATE[23000]: Integrity constraint vilation when trying to open transition
Hello,

One of our customers wants to view transition for a certain page, using also segment based on events.

As we know, there is a limitation that when segment is based on events, there are no reports for other kinds of actions. To bypass it, customer defined a goal by "send an event", after that he created a segment on "Visit converted for specific Goal ID".

Problem is that if he wants to open the transition for a certain page (using segment as above), he got the following error message: _SQLSTATE[23000]: Integrity constraint vilation: 1052 Column 'idaction_url' in field list is ambigous_.

clipboard01

Seems that wrong SELECT was generated, using segments and transitions as described above. Customer is using Piwik 2.15.0.

### PR DESCRIPTION
**Pull request by mattab**
- We add a system reproducing the issue
- we fix the issue by prefixing the DB field by the table alias, to prevent error when a segment joins another table that has some field names in common

fixes #9822

### CODE REVIEW

File: plugins/Transitions/API.php [hunk 1]
```diff
@@ -222,7 +222,8 @@ protected function queryFollowingActions($idaction, $actionType, LogAggregator $
         if ($actionType != 'title') {
             // specific setup for page urls
             $types[Action::TYPE_PAGE_URL] = 'followingPages';
-            $dimension = 'if ( idaction_url IS NULL, idaction_name, idaction_url )';
+            $dimension = 'if ( %s.idaction_url IS NULL, %s.idaction_name, %s.idaction_url )';
+            $dimension = str_replace('%s', 'log_link_visit_action', $dimension );
```
Comment (sgiehl) [inline plugins/Transitions/API.php]: any reason for not using `sprintf` here and below?

Comment (tsteur) [inline plugins/Transitions/API.php]: :+1: for sprintf

Comment (mattab) [inline plugins/Transitions/API.php]: it's possible to use sprintf but we need to replace `%s` by `%1$s` in all 3 occurrences. Otherwise we get `sprintf(): Too few arguments`. Shall I do it?

Comment (sgiehl) [inline plugins/Transitions/API.php]: Sure, use `%1$s`

Comment (mattab) [inline plugins/Transitions/API.php]: Ok, done
