### PR TITLE
Fix/improve behaviour of update check visualization

### LINKED ISSUE #21259: Matomo update check times out at times
I tried to upgrade to the latest Matomo 5RC a few times by running the update check and Matomo wouldn't suggest the latest Matomo 5 RC update is available.

I started debugging why that is and noticed we have a 2 second HTTP timeout in https://github.com/matomo-org/matomo/blob/5.0.0-rc2/core/UpdateCheck.php#L71

However, https://api.matomo.org/1.0/getLatestVersion/?piwik_version=5.0.0-rc1&php_version=8.1.14&mysql_version=8.0.26&release_channel=latest_5x_beta&url=http%3A%2F%2Fmyest.com%2F.%2Fconsole&trigger=&timezone=Europe%2FLondon took 4 seconds to execute.

5-10 minutes later the request took less than 2 seconds and only few hundred ms. 

I'm not sure why the request took so long at times and if there has been a regression in performance and/or if it makes sense to increase the timeout so that when people do want to upgrade, it won't falsely say there's no update available

### PR DESCRIPTION
**Pull request by mneudert**
### Description:

Additional work was done to get the manual check working. The parsing of the result was not yet updated for the new vue component structure and flagged every response as "no update available".

Fixes #21259.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/UpdateCheck.php [hunk 1]
```diff
@@ -51,6 +52,12 @@ public static function check($force = false, $interval = null)
                 $latestVersion = '';
             }
 
+            if ('' === $latestVersion) {
+                // retry check on next request if previous attempt failed
+                Option::set(self::LAST_TIME_CHECKED, $lastTimeChecked, $autoLoad = 1);
+            }
+
+            Option::set(self::LAST_CHECK_FAILED, '' === $latestVersion, $autoLoad = 1);
```
Comment (michalkleiner) [inline core/UpdateCheck.php]:
```suggestion
            $hasLastCheckFailed = '' === $latestVersion;
            if ($hasLastCheckFailed) {
                // retry check on next request if previous attempt failed
                Option::set(self::LAST_TIME_CHECKED, $lastTimeChecked, $autoLoad = 1);
            }

            Option::set(self::LAST_CHECK_FAILED, $hasLastCheckFailed, $autoLoad = 1);
```

**Comment by michalkleiner** [comment]
Yet to run it locally but code changes look good from my perspective.

File: plugins/CoreHome/javascripts/corehome.js [hunk 2]
```diff
@@ -6,76 +6,73 @@
...
-                    else {
-                        headerMessage.find('.title').html(_pk_translate('CoreHome_YouAreUsingTheLatestVersion'));
-                        headerMessage.show();
-                        setTimeout(function () {
-                            headerMessage.fadeOut('slow', function () {
-                                headerMessage.replaceWith(response);
-                            });
-                        }, 4000);
-                    }
+        var initUpdateCheck = function() {
```
Comment (michalkleiner) [inline plugins/CoreHome/javascripts/corehome.js:13]: Also since none of this code is part of the tracker JS where we do care about using legacy JS techniques, could we use `const` and `let` here?

Comment (mneudert) [reply plugins/CoreHome/javascripts/corehome.js:13]: We could definitely.

I only skipped that to keep the style of the file sort of as is. And I think the next step should be to integrate it fully into the vue component, there should be no reason to keep this block around longer than necessary.

File: core/UpdateCheck.php [hunk 3]
```diff
@@ -51,6 +52,13 @@ public static function check($force = false, $interval = null)
...
             }
 
+            $hasLastCheckFailed = '' === $latestVersion;
+            if ($hasLastCheckFailed) {
+                // retry check on next request if previous attempt failed
+                Option::set(self::LAST_TIME_CHECKED, $lastTimeChecked, $autoLoad = 1);
+            }
+
+            Option::set(self::LAST_CHECK_FAILED, $hasLastCheckFailed, $autoLoad = 1);
             Option::set(self::LATEST_VERSION, $latestVersion);
```
Comment (sgiehl) [inline core/UpdateCheck.php]: Does it make sense to update the version if the last check failed? Shouldn't we maybe keep the previous record in that case?

File: plugins/CoreHome/templates/_headerMessage.twig [hunk 4]
```diff
@@ -1,18 +1,28 @@
 {# testing, remove test_ from var names #}
-{% set test_latest_version_available="4.0.0" %}
-{% set test_piwikUrl='https://demo.matomo.org/' %}
+{% set test_lastUpdateCheckFailed = false %}
+{% set test_latest_version_available = '6.0.0' %}
+{% set test_piwikUrl = 'https://demo.matomo.org/' %}
```
Comment (sgiehl) [inline plugins/CoreHome/templates/_headerMessage.twig]: I guess those variables are only for testing purpose and in order to use them the `test_` prefix needs to be removed? Not sure if we actually want to keep such things. If we want to provide an easy way to allow to overwrite those variables for testing purpose we should rather use an event or DI to allow that.

**Review by sgiehl — CHANGES_REQUESTED** [review]
Left some minor comments. Otherwise tests are looking good and locally it worked without problems.

File: core/UpdateCheck.php (hunk 3 above)
Comment (mneudert) [reply core/UpdateCheck.php]: Good point, it should not be worth setting the version if the check failed.

While it would prevent having "not the most up-to-date version" displayed it would also hide a previously available update if the request failed.

_I also removed the `autoLoad` flag from the new option. After some previous code changes it is only ever read in the manual update action, no need to have it available for reading otherwise._

File: plugins/CoreHome/templates/_headerMessage.twig (hunk 4 above)
Comment (mneudert) [reply plugins/CoreHome/templates/_headerMessage.twig]: I removed them. They were existing for 10 years, but with the new UI tests, that are setting the options to specific values, there should be no benefit to keeping them :+1:

**Review by sgiehl — APPROVED** [review]
Looks good now
