### PR TITLE
Fix possible PHP deprecation notice

### LINKED ISSUE #22248: Missing delimiter for preg_match pattern in UrlHelper::inArrayMatchesRegex
I got this errors in my log
preg_match(): Delimiter must not be alphanumeric or backslash in /core/UrlHelper.php:41
preg_match(): Delimiter must not be alphanumeric or backslash in /core/UrlHelper.php:46

Matomo version: 5.0.3
PHP version: 8.1.28

As I see the solution could be this lines insted
Line 41: if(@preg_match("/$val/", null) === false) {
Line 46: if( preg_match("/$val/", $test) === 1 ) {

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #22248

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/UrlHelper.php [hunk 1]
```diff
@@ -39,7 +39,7 @@ class UrlHelper
     protected static function inArrayMatchesRegex($test, $patterns): bool
     {
         foreach ($patterns as $val) {
-            if (@preg_match($val, null) === false) {
+            if (@preg_match($val, '') === false) {
```
Comment (mneudert) [inline core/UrlHelper.php:42]: Can we add that change to [`VisitsExcluded`](https://github.com/matomo-org/matomo/blob/80b20d8dd69079524738f403ddc37daf2fca26fb/core/Tracker/VisitExcluded.php#L374) as well?

Comment (sgiehl) [reply core/UrlHelper.php:42]: sure. hadn't seen that.

**Review by mneudert — APPROVED** [review]
