### PR TITLE
Lower case the string in a way that works with any language

### LINKED ISSUE #11130: Garbled text of translation
There's a garbled text at segment editor when using language zh-TW and even zh-CN.

zh-TW (Should be 指標)
qq 20170103001523

zh-CN (Should be 指标)
qq 20170103001701

But I've checked the translated strings, there was nothing wrong with them, so I think it's a bug.

### PR DESCRIPTION
**Pull request by mattab**
Fixes #11130

### CODE REVIEW

File: plugins/SegmentEditor/SegmentSelectorControl.php [hunk 1]
```diff
@@ -54,8 +54,7 @@ public function __construct($idSite = false)
             if ($segment['category'] == $visitTitle
                 && ($segment['type'] == 'metric' && $segment['segment'] != 'visitIp')
             ) {
-                $metricsLabel = Piwik::translate('General_Metrics');
-                $metricsLabel[0] = Common::mb_strtolower($metricsLabel[0]);
+                $metricsLabel = Common::mb_strtolower(Piwik::translate('General_Metrics'));
```
Comment (tsteur) [inline plugins/SegmentEditor/SegmentSelectorControl.php]: Is it on purpose to remove the metricsLabel[0] completely?

Comment (mattab) [inline plugins/SegmentEditor/SegmentSelectorControl.php]: Yes, this is the fix actually: it does not work to use [0] to replace first character  in a multibyte chinese string since the first character might be 2 or 3 bytes.

Comment (tsteur) [inline plugins/SegmentEditor/SegmentSelectorControl.php]: Sweet. You can call this a fix as well then to completely remove it :) 👍  Thought you meant to really fix it

Comment (mattab) [inline plugins/SegmentEditor/SegmentSelectorControl.php]: It's the real fix actually, we're now lowercasing the whole string which has the same effect of just lower casing the first letter (in most languages anyway)
