### PR TITLE
Fix adding a site is not possible when coming from All Websites Dashboard

### LINKED ISSUE #7802: Can't add new site after update to 2.13.0
Clicking "+Add a new website" from the "All Websites Dashboard" does not allow me to add a new website. This started after upgrading to 2.13.0. 

The text inputs to add a new site briefly appear on the screen before disappearing. By briefly I mean less than 1 second. 

This happens on Chrome 42 and Firefox 37 on Ubuntu 14. This also happens on Chrome 42, Firefox 33 and IE9 on Windows 7
piwik-add-site-bug
.

There are no console errors shown when this occurs.

### PR DESCRIPTION
**Pull request by tsteur**
fixes #7802

### CODE REVIEW

File: plugins/SitesManager/angularjs/sites-manager/sites-manager-admin-sites-model.js [hunk 1]
```diff
@@ -70,7 +70,7 @@
             fetchLimitedSitesWithAdminAccess();
         }
 
-        function fetchLimitedSitesWithAdminAccess(searchTerm)
```
Comment (tsteur) [inline plugins/SitesManager/angularjs/sites-manager/sites-manager-admin-sites-model.js]: FYI `searchTerm` was not used before
