### PR TITLE
[Bug]fix prefilght cors OPTIONS request record in the action visits

### LINKED ISSUE #18812: options request will also be recorded
## Expected Behavior

`options request` should not recorded!

## Current Behavior

`options request` will also be recorded

## Possible Solution

The server should filter out the `options request` and not participate in the record.

## Steps to Reproduce (for Bugs)

image

image

## Your Environment

* Matomo Version: 4.7.1
* MySQL version: 10.6.5-MariaDB-1:10.6.5+maria~focal
* PHP Version: 8.0.15
* Server Operating System: centos7
* Additionally installed plugins:

* Browser: chrome98
* Operating System: macos 12.1

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:

Fixes: #18812 

Extend requests with `headers` and `method` do not record preflight cors in the database. 

To reproduce the issue one needs to trigger prefight cors, eg add a request header more details can be found [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) 
```js
       headers:{'X-PINGOTHER':'pingpong'}
```

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/Tracker/Request.php [hunk 1]
```diff
@@ -60,8 +63,9 @@ class Request
     /**
      * @param $params
      * @param bool|string $tokenAuth
+     * @param null $server
```
Comment (justinvelluppillai) [inline core/Tracker/Request.php]: Should this be array|null ?

File: core/Tracker/Request.php [hunk 2]
```diff
@@ -921,4 +928,12 @@ private function getVisitorIdAsBinary($idVisitor)
         }
         return false;
     }
+
+    /**
+     * @return bool
+     */
+    public function isPreFightCorsRequest()
+    {
+        return !empty($this->server['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']) || !empty($this->server['HTTP_ACCESS_CONTROL_REQUEST_METHOD']);
```
Comment (sgiehl) [inline core/Tracker/Request.php]: I guess it should be fine to directly use `$_SERVER` here. There is no need to pass the server variables in constructor.

**Review by sgiehl — CHANGES_REQUESTED** [review]

File: core/Tracker/Request.php [hunk 3]
```diff
@@ -921,4 +924,12 @@ private function getVisitorIdAsBinary($idVisitor)
         }
         return false;
     }
+
+    /**
+     * @return bool
+     */
+    public function isPreFightCorsRequest()
+    {
+        return !empty($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']) || !empty($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD']);
```
Comment (sgiehl) [inline core/Tracker/Request.php]: Was it intended that this no longer checks for the request method?

File: core/Tracker/Action.php [hunk 4]
```diff
@@ -381,6 +381,10 @@ public function loadIdsFromLogActionTable()
      */
     public function record(Visitor $visitor, $idReferrerActionUrl, $idReferrerActionName)
     {
+        if ($this->request->isPreFightCorsRequest()) {
+            return;
```
Comment (sgiehl) [inline core/Tracker/Action.php]: Actually I'm not sure if this is the correct place. It will only prevent a new action from being inserted. A visit would still be created. I would actually expect that the whole request should be dropped in that case.
Maybe we could also have a test, that proves no data was recorded for such a request.

**Comment by sgiehl** [comment]
I'm not really deep into such CORS stuff, but I was wondering if we shouldn't send a proper answer to a CORS request.
According to https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request it seems the correct answer would a `204` with some additional headers containing the allowed methods.
@peterhashair did you test what happens if we send a normal answer to the preflight request? Is the tracking request still sent in that case?

**Comment by peterhashair** [comment]
@sgiehl right that makes sense, will update that.

**Comment by peterhashair** [comment]
@sgiehl I am trying to figure out how to do a response as 204, but I notice there is a set of requests, not just one, if I respond 204 in the foreach, will that affect another request?

**Comment by peterhashair** [comment]
@sgiehl I am trying to figure out how to do a response as 204, but I notice there is a set of requests, not just one, if I respond 204 in the foreach, will that affect another request?

**Comment by sgiehl** [comment]
@peterhashair You may need to handle that at an earlier stage. As it's not relevant if the preflight request might contain one or more tracking requests, you should do that before the request is actually parsed. Guess here it might suite:
https://github.com/matomo-org/matomo/blob/078909ef807910a1f2a4d93d738306d0bf6a9e04/core/Tracker.php#L130-L136

**Comment by peterhashair** [comment]
@sgiehl it seems like the prefight works, just wondering should I use the site url store in the data for the `Access-Control-Allow-Origin`, otherwise there will be security issue I guess.
```php 
             header('Access-Control-Allow-Methods: GET, POST');
               header('Access-Control-Allow-Headers: *');
               header('Access-Control-Allow-Origin: *');
               Common::sendResponseCode(204);
```

File: core/Tracker.php [hunk 5]
```diff
@@ -355,4 +363,13 @@ private static function isDebugEnabled()
 
         return false;
     }
+
+    public function isPreFightCorsRequest()
```
Comment (sgiehl) [inline core/Tracker.php]: for new methods we should already try to add typehints where possible
```suggestion
    public function isPreFightCorsRequest(): bool
```

**Review by sgiehl — CHANGES_REQUESTED** [review]
> @sgiehl it seems like the prefight works, just wondering should I use the site url store in the data for the Access-Control-Allow-Origin, otherwise there will be security issue I guess.

Actually I guess the `*` might be fine. We can't really know where a tracking request might come from. Using all configured sites might also not be correct, as people could also track unconfigured site urls.

File: core/Tracker/RequestSet.php [hunk 6]
```diff
@@ -45,8 +45,8 @@ public function setRequests($requests)
             if (!$request instanceof Request) {
                 $request = new Request($request, $this->getTokenAuth());
             }
-
             $this->requests[] = $request;
+            Common::sendResponseCode(204);
```
Comment (sgiehl) [inline core/Tracker/RequestSet.php]:
```suggestion
```

**Comment by sgiehl** [comment]
I've now applied a couple of fixes and added a simple test to get this ready to merge...
