### PR TITLE
setting save success, scroll to notification

### LINKED ISSUE #18637: Saving general settings successfully no longer scrolls to the success notification
I checked with Matomo 4.6 and this seems to have worked there so it looks like this is a regression.

When saving settings, you now never really know whether it worked and it's confusing.

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:

Fixes: #18637 
after setting save success, should scroll to notification

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/CorePluginsAdmin/vue/src/PluginSettings/PluginSettings.vue [hunk 1]
```diff
@@ -227,7 +227,7 @@ export default defineComponent({
           context: 'success',
           type: 'transient',
         });
-        NotificationsStore.scrollToNotification('generalSettings');
```
Comment (diosmosis) [inline plugins/CorePluginsAdmin/vue/src/PluginSettings/PluginSettings.vue:225]: w/ the new code the way to do this is:

```
const notificationInstanceId = NotificationsStore.show({
  message: translate('CoreAdminHome_PluginSettingsSaveSuccess'),
  id: 'generalSettings',
  context: 'success',
  type: 'transient',
});
NotificationsStore.scrollToNotification(notificationInstanceId);
```

The reason for this change is because Notification.vue makes an AJAX request in markNotificationAsRead() if an ID is specified, but that isn't needed for notifications added client side only. So if you want to avoid making that request, you don't have to specify the `id:` property.

Comment (diosmosis) [reply plugins/CorePluginsAdmin/vue/src/PluginSettings/PluginSettings.vue:225]: I'll add documentation for this later unless it's desired to revert this to the old behavior.

cc @sgiehl

Comment (peterhashair) [reply plugins/CorePluginsAdmin/vue/src/PluginSettings/PluginSettings.vue:225]: @diosmosis that makes more sense. updating it now

**Review by diosmosis — APPROVED** [review]
looks good if tests pass

**Comment by peterhashair** [comment]
@diosmosis sorry to bother got a question. when I run `./console vue:build` it returns random errors on 4.x-dev. 
image

Also here, should that be a catch method instead of finally? https://github.com/matomo-org/matomo/blob/165be4f4ea40cbca50ae71821e517e6edb6054ba/plugins/CoreAdminHome/vue/src/ArchivingSettings/ArchivingSettings.vue#L178

**Comment by diosmosis** [comment]
> when I run ./console vue:build it returns random errors on 4.x-dev.

I've noticed this, seems to be a tsc issue/bug, but I don't know how to fix it. Currently just rebuilding when it happens. It doesn't happen very often for me (once a day at most).

> Also here, should that be a catch method instead of finally? 

It should be finally, unless you want to show the loading gif if there's an error. (EDIT: "no error" not an error.)

**Comment by peterhashair** [comment]
@diosmosis I saw someone solved it by add  this https://www.npmjs.com/package/eslint-import-resolver-typescript

**Comment by diosmosis** [comment]
Thanks, @peterhashair! Do you have info on how they used it, specifically w/ vue CLI?

**Comment by peterhashair** [comment]
@diosmosis haven't try myself, but they claim work like this https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1059
