### PR TITLE
fix processing of Actions>Events> metric "Minimum event value"

### LINKED ISSUE #9418: Minimum event value" metric is not displayed in the Actions>Events report
eg 
image

### PR DESCRIPTION
**Pull request by mattab**
fixes #9418

### CODE REVIEW

**Comment by tsteur** [comment]
LGTM. Maybe squash them before? But not necessarily needed.

File: core/DataArray.php [hunk 1]
```diff
@@ -265,7 +265,7 @@ protected static function makeEmptyEventRow()
             Metrics::INDEX_EVENT_NB_HITS            => 0,
             Metrics::INDEX_EVENT_NB_HITS_WITH_VALUE => 0,
             Metrics::INDEX_EVENT_SUM_EVENT_VALUE    => 0,
-            Metrics::INDEX_EVENT_MIN_EVENT_VALUE    => 0,
+            Metrics::INDEX_EVENT_MIN_EVENT_VALUE    => false,
```
Comment (tsteur) [inline core/DataArray.php]: Funny things. Just out of interest: How does it come that this fixes it?

Comment (mattab) [inline core/DataArray.php]: see https://github.com/piwik/piwik/blob/2.15.0/core/DataArray.php#L257-L264
