### PR TITLE
Correctly normalize diacritics in segment search

### LINKED ISSUE #24185: [Bug] Search segments of visits in Cyrillic stop working since version 5.8
### What happened?

I named my segments combining Latin and Cyrillic words. I have two keyboard layouts in my Windows OS: English and Ukrainian.
So I want to find segment without switching keyboard layout. 
If segment  is named, for example "Click Phone Телефон", I could search this segment by both "Phone" and "Телефон" words. it worked before version 5.8

### What should happen?

But I can't search a proper segment of visits by Cyrillic words after version 5.8 upgrade

### How can this be reproduced?

Goto Matomo main dashboard -> Top buttons -> Button "Choose a segment". Rename any existing segment (or create new one) to have both Latin and Cyrillic word(s) in a name.
Then try to type  in the field "Search" Cyrillic words of such a segment.

### Matomo version

5.8

### PHP version

8.2.30 

### Server operating system

_No response_

### What browsers are you seeing the problem on?

Firefox

### Computer operating system

_No response_

### Relevant log output

```shell

```

### Validations

- [x] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [x] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [x] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

It has been reported that diacritics are causing problems when using the segment search.

If a segment names e.g. contains letter like `Çàêč` or similar, those segment would not be found when searching for `caec`.
This makes it hard in some languages to search for segments.

This PR changes the segment search, so it compares the search term with the original segment name, but also with the normalized segment name. This way you can search for `a`, but would find `a` and `à`, while searching for `à`, would only find `à`

fixes https://github.com/matomo-org/matomo/issues/24185

### Checklist

- [✔] I have understood, reviewed, and tested all AI outputs before use
- [✔] All AI instructions respect security, IP, and privacy rules

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/SegmentEditor/javascripts/Segmentation.js [hunk 1]
```diff
@@ -723,22 +717,6 @@ Segmentation = (function($) {
...
-            // remove accents, swap ñ for n, etc
-            var from = "àáäâèéëêìíïîòóöôùúüûñç·/_,:;";
-            var to   = "aaaaeeeeiiiioooouuuunc------";
-            for (var i=0, l=from.length ; i<l ; i++) {
-                search = search.replace(new RegExp(from.charAt(i), 'g'), to.charAt(i));
-            }
-
-            search = search.replace(/[^a-z0-9 -]/g, '') // remove invalid chars
-                .replace(/\s+/g, '_') // collapse whitespace and replace by underscore
-                .replace(/-+/g, '-'); // collapse dashes
```
Comment (chippison) [inline plugins/SegmentEditor/javascripts/Segmentation.js:832]: Should we also add this into the new `normalize` function to preserve old behaviour?

File: plugins/Morpheus/javascripts/piwikHelper.js [hunk 2]
```diff
@@ -164,6 +164,11 @@ window.piwikHelper = {
         return window.vueSanitize(value);
     },
 
+    normalize: function(value)
+    {
+        return value.normalize('NFD').replace(/\p{Diacritic}/gu, '').toLowerCase();
```
Comment (chippison) [inline plugins/Morpheus/javascripts/piwikHelper.js:169]: If we want to really follow old behaviour:
```suggestion
        return value.normalize('NFD').replace(/\p{Diacritic}/gu, '')
            .trim()
            .toLowerCase()
            .replace(/[^a-z0-9 -]/g, '')  // only allow: [a-z,0-9,' ','-']
            .replace(/\s+/g, '_')     // replace spaces with '_'
            .replace(/-+/g, '-');     // collapse '-'
```

**Review by chippison — COMMENTED** [review]
Aside from the comment above,
functional tests are all good on my end

File: plugins/Morpheus/javascripts/piwikHelper.js (hunk 2 above)
Comment (sgiehl) [reply plugins/Morpheus/javascripts/piwikHelper.js:169]: I actually left those parts away on purpose. The first replace broke the search in the first place. And replacing punctuation chars or spaces is imho also bit strange behavior. If I search for a `!` or even a white space, I might want to look exactly for that, so why should we remove and ignore those chars completely?

File: plugins/CorePluginsAdmin/vue/src/FormField/FieldExpandableSelect.vue [hunk 3]
```diff
@@ -174,6 +178,14 @@ export default defineComponent({
...
   },
   methods: {
+    normalize(value: string) {
+      return Matomo.helper.normalize(value);
+    },
+    isSearchMatch(value: unknown) {
+      const stringValue = `${value ?? ''}`;
+      return this.normalize(stringValue).indexOf(this.searchTermNormalized) !== -1
+        || stringValue.toLowerCase().indexOf(this.searchTermLowercase) !== -1;
+    },
```
Comment (tzi) [inline plugins/CorePluginsAdmin/vue/src/FormField/FieldExpandableSelect.vue:188]: This function is also used in the SegmentPanel, would it be great to have it in the Matomo.helper as well?

Comment (sgiehl) [reply plugins/CorePluginsAdmin/vue/src/FormField/FieldExpandableSelect.vue:188]: Hm. I don't have a too strong opinion on that. We could extract that, but it then would loose the micro optimizations currently in place. The search term is currently only normalized and lowercased once and reused for every match. If we move that to a helper method we would need to reapply that for every match.

Comment (tzi) [reply plugins/CorePluginsAdmin/vue/src/FormField/FieldExpandableSelect.vue:188]: Good point 👍 
Perhaps it's too complex for an helper, but we could also create an helper that returns a closure that we use to do the comparison.

Comment (sgiehl) [reply plugins/CorePluginsAdmin/vue/src/FormField/FieldExpandableSelect.vue:188]: I don't want to bring more complexity into this relatively simple comparison. It might be used twice, yes. But not sure if that already makes it worth to put more effort into this PR to abstract that into a helper...

**Review by chippison — DISMISSED** [review]

**Review by nathangavin — APPROVED** [review]
