### PR TITLE
Cache additional site urls in live visitor details

### LINKED ISSUE #21971: Visits log executes thousands of DB queries in a single request in getAliasSiteUrlsFromId()
### What happened?

See screenshot 
image

image

It translates to DB calls
image

### What should happen?

Only 1 or very few queries.

### How can this be reproduced?

* Issue a visits log request.
* I assume that for each action it executes one DB query

### Matomo version

5

### PHP version

_No response_

### Server operating system

_No response_

### What browsers are you seeing the problem on?

_No response_

### Computer operating system

_No response_

### Relevant log output

_No response_

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by mneudert**
### Description:

Rendering the details for a visitor (common) action makes use of the site alias URLs to render the action URL.

Every action fetches these URLs from the database without any caching, issuing lots of db queries while always receiving the same data.

Adding a transient cache to the URL lookup should reduce the amount of database queries to one per site.

Fixes #21971.

_Note_: I decided to skip a test for this. Only checking the cache usage seems extremely narrow for the setup/maintenance overhead. Will happily add a small test that checks for cache calls (and more?), if there is benefit in having one.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/Live/VisitorDetails.php [hunk 1]
```diff
@@ -309,4 +308,24 @@ public static function getReferrerSummaryForVisit($visit)
...
+        $cache = Cache::getTransientCache();
+        $cacheKey = 'Live.additionalSiteUrls.' . $this->getIdSite();
+
+        if (!$cache->contains($cacheKey)) {
+            $sitesModel = new \Piwik\Plugins\SitesManager\Model();
+
+            $cache->save(
+                $cacheKey,
+                $sitesModel->getAliasSiteUrlsFromId($this->getIdSite())
+            );
```
Comment (michalkleiner) [inline plugins/Live/VisitorDetails.php]: Saves the extra fetch when not needed.

```suggestion
            $sitesModel = new \Piwik\Plugins\SitesManager\Model();
            $aliasSiteUrls = $sitesModel->getAliasSiteUrlsFromId($this->getIdSite());

            $cache->save(
                $cacheKey,
                $aliasSiteUrls
            );
            
            return $aliasSiteUrls;
```

Comment (mneudert) [reply plugins/Live/VisitorDetails.php]: The block was actually designed to look like most of `if (!$cache->contains())` constructs I found, with an explicit `$cache->fetch()` after it.

The other choice I found was `if ($cache->contains())` with an early return at the beginning, and having the `$cache->save(); return` without nesting.

Or a simple `if {} else {}; return $var`.

Happy with every option here.

Comment (michalkleiner) [reply plugins/Live/VisitorDetails.php]: Right. I always forget there could pre-existing patterns we duplicate/tweak, and then I'm on the fence with whether we should keep doing that or do it better/differently in the areas we're touching.

Perhaps if there's a pattern with cache contains and an early return,  we can do that. I'm not sure the explicit fetch has any meaning here apart from possibly having some logic outside in the cache layer that would, I don't know, amend the value somehow 🤷.

Plus, if the write fails, it would then fetch nothing, so returning the currently processed value anyway makes it a bit more robust?

Comment (mneudert) [reply plugins/Live/VisitorDetails.php]: Doing it differently could be a nice `$cache->get($key, function () { /* generate value */ });` :sweat_smile: 

And here I'll opt for the early return as a "cache short-circuits execution" pattern.

File: plugins/Live/VisitorDetails.php [hunk 2]
```diff
@@ -309,4 +308,24 @@ public static function getReferrerSummaryForVisit($visit)
 
         return $visit->getColumn('referrerName');
     }
+
+    /**
+     * @return array
+    */
+    private function getAdditionalUrlsForSite(): array
+    {
+        $cache = Cache::getTransientCache();
```
Comment (tsteur) [inline plugins/Live/VisitorDetails.php]: @mneudert fyi the transient cache is still a bit slow and this might be called a lot. Because the system is already caching all visitorDetails instances, we may be able to simplify this and could maybe use a private property like `$this->siteUrlsCached[$idSite] = ...`.

It would make caching of these things faster and simpler. 

The instances should be created only once and cached here: https://github.com/matomo-org/matomo/blob/5.0.2/plugins/Live/Visitor.php#L50-L103 
Might be good to double check though

Comment (mneudert) [reply plugins/Live/VisitorDetails.php]: Will check and adjust :eyes:

**Review by caddoo — APPROVED** [review]

File: plugins/Live/VisitorDetails.php (hunk 2 above)
Comment (mneudert) [reply plugins/Live/VisitorDetails.php]: Also only found that one place for instantiation, so skipping the cache in favor of a private variable :+1:

File: plugins/Live/VisitorDetails.php [hunk 3]
```diff
@@ -11,6 +11,7 @@
 namespace Piwik\Plugins\Live;
 
 use Piwik\API\Request;
+use Piwik\Cache;
```
Comment (michalkleiner) [inline plugins/Live/VisitorDetails.php]:
```suggestion
```

File: plugins/Live/VisitorDetails.php [hunk 4]
```diff
@@ -309,4 +315,21 @@ public static function getReferrerSummaryForVisit($visit)
 
         return $visit->getColumn('referrerName');
     }
+
+    /**
+     * @return array<int, array<string>>
+    */
```
Comment (michalkleiner) [inline plugins/Live/VisitorDetails.php]:
```suggestion
     */
```

**Review by michalkleiner — APPROVED** [review]
Looks good, just pushed a CS fix.
