### PR TITLE
Fix transition popover for page titles with percent signs

### LINKED ISSUE #21657: [Bug] Transition popover does not work for rows with "%"
### What happened?

Opening the transition popover for a row containing a percent sign (`%`) will throw an exception:

```
jquery.min.js?cb=5690:2 Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at DataTable_RowActions_Transitions.doOpenPopover (transitions.js?cb=5690:82:25)
    at Array.RowAction (dataTable_rowactions.js?cb=5690:260:47)
    at e.value (PopoverHandler.ts:77:40)
    at e.value (PopoverHandler.ts:49:12)
    at HTMLDocument.<anonymous> (PopoverHandler.ts:39:12)
    at e (jquery.min.js?cb=5690:2:30158)
    at t (jquery.min.js?cb=5690:2:30460)
```

### What should happen?

The transition overlay should work similar to other data table row actions for all entries.

### How can this be reproduced?

Track a page with `%` in the title, go to "Behaviour > Page titles", try to open the transitions popover.

### Matomo major version

Matomo 5

### Matomo minor or patch Version

rc9

### PHP version

n/a

### Server operating system

n/a

### What browsers are you seeing the problem on?

Firefox, Chrome

### Computer operating system

n/a

### Relevant log output

_No response_

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by mneudert**
### Description:

Fixes #21657.

Should this be the time we add some of those edge cases (at least a `%` and a `:` in the title) to the general UITestFixture, so we have them readily available for problems like this?

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/Transitions/javascripts/transitions.js [hunk 1]
```diff
@@ -79,7 +79,14 @@ DataTable_RowActions_Transitions.prototype.doOpenPopover = function (link) {
 
     var i = 0;
     while (i < parts.length) {
-        var paramName = decodeURIComponent(parts[i]);
+        var paramName = '';
+
+        try {
+            paramName = decodeURIComponent(parts[i]);
+        } catch (e) {
+            // invalid parameter
```
Comment (sgiehl) [inline plugins/Transitions/javascripts/transitions.js:87]: Shouldn't we add a `continue` here? Wouldn't otherwise `overrideParams` end up having an array element with an empty string key? 🤔 
```suggestion
            // invalid parameter
            i += 1;
            continue;
```

Comment (mneudert) [reply plugins/Transitions/javascripts/transitions.js:87]: The continue is already handed by the following check for `ALLOWED_OVERRIDE_PARAMS.indexOf(paramName)`, that one will never succeed with an empty string.

We could add an additional one here for clarity, but it should not change the behaviour.

Comment (sgiehl) [reply plugins/Transitions/javascripts/transitions.js:87]: Ah true. Somehow thought `ALLOWED_OVERRIDE_PARAMS` would be a string and an `indexOf` on a string looking for an empty string is always `0` 🙈  All good then.

**Review by sgiehl — APPROVED** [review]
Looks good to me. At some point it would really be useful to have more edge case tests. Guess we should update our ui test fixture accordingly at some point...
