### PR TITLE
Improve / fix handling of best converting page on goal overview

### LINKED ISSUE #19512: Improve / fix handling of best converting page on goal overview
Reproduced in demo2 here

## Current Behavior

image

## Expected Behavior

Instead we expect 3 things to work differently:

* The URL says `t` but instead should give the actual URL (`t` is only a "directory" or a partial path, but not a URL...). So in this case we expect instead for example `https://forum.matomo.org/t/matomo-integration-in-react-app/41044` since that's the top URL for this goal
* The tooltip should give the conversion rate but it's currently empty
* The link doesn't work. It seems to just link to the current page in Matomo instead of linking to the actual URL of the website 

## Possible Solution

Fix all 3 issues above

## Context

4.11 RC tested on demo2

### LINKED ISSUE #20003: Entry page link on Goals page in Conversions Overview widget has a different color
see screenshot:
image
It doesn't have the regular link color

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #19512
fixes #20003

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by peterhashair — APPROVED** [review]
Working as expected, sorry pushed some UI screenshots that need an update, I believe one is from my PR that already merged.

* [x] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [x] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [x] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [x] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [x] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [x] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [x] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [x] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)

**Review by bx80 — CHANGES_REQUESTED** [review]
I've done some functional testing, the tooltip works and broken URL is removed. :+1:

The original issue mentions that a directory shouldn't be shown as the top entry URL. When testing locally my top entry page is shown as 'blog' which is a directory. The top dimensions request might need to be filtered to exclude directories?

**Comment by sgiehl** [comment]
@bx80 That should be fixed now. I've changed the request for entry pages and added `flat=1`, that way only full page urls are returned.

File: plugins/Goals/Controller.php [hunk 1]
```diff
@@ -335,24 +334,36 @@ protected function getTopDimensions($idGoal)
...
                 "&filter_limit=" . (self::COUNT_TOP_ROWS_TO_DISPLAY + 2));
-            $datatable = $request->process();
-            $topDimension = array();
-            $count = 0;
 
             if ($apiMethod == 'Actions.getEntryPageUrls') {
-                $columnConversionRate = 'goal_' . $idGoal . '_nb_conversions_entry_rate';
-            } else {
-                $columnConversionRate = 'goal_' . $idGoal . '_conversion_rate';
+                $request .= '&flat=1';
```
Comment (peterhashair) [inline plugins/Goals/Controller.php]: it seems like the `$request` is an object, maybe need to update the whole thing like below.

```php
       $requestString = "method=$apiMethod
                                   &format=original
                                   &format_metrics=0
                                   &filter_update_columns_when_show_all_goals=1
                                   &idGoal=$idGoalToProcess
                                   &filter_sort_order=desc
                                   &filter_sort_column=$columnNbConversions
                                   &showColumns=label,$columnNbConversions,$columnConversionRate" .
                // select a couple more in case some are not valid (ie. conversions==0 or they are "Keyword not defined")
                "&filter_limit=" . (self::COUNT_TOP_ROWS_TO_DISPLAY + 2);

            if ($apiMethod == 'Actions.getEntryPageUrls') {
                $requestString .= '&flat=1';
            }

            $request = new Request($requestString);

```

Comment (sgiehl) [reply plugins/Goals/Controller.php]: Ah sure. Should be fixed.

**Review by peterhashair — APPROVED** [review]
Update some failed screenshots, looks good to me.
