### PR TITLE
CronArchive: Catch UnexpectedWebsiteFoundException

### LINKED ISSUE #14393: Add option to core:archive that allows you to continue even if the site is not in matomo anymore
Hi, could a option be added that allows you to continue even if you get a error like:

  [Piwik\Exception\UnexpectedWebsiteFoundException]                               
  An unexpected website was found in the request: website id was set to '2897' .  

please?

This would be super useful.

Or is there a way to clear the deleted websites so they are not run?

### PR DESCRIPTION
**Pull request by paladox**
This is to allow the archive to continue if the site was deleted from matomo.

Fixes #14393

### CODE REVIEW

File: core/CronArchive.php [hunk 1]
```diff
@@ -716,7 +722,13 @@ private function archiveSingleSite($idSite, $requestsBefore)
         /**
          * Trigger archiving for non-day periods
          */
-        $success = $this->processArchiveForPeriods($idSite, $lastTimestampWebsiteProcessedPeriods);
+        try {
+            $success = $this->processArchiveForPeriods($idSite, $lastTimestampWebsiteProcessedPeriods);
+        } catch (UnexpectedWebsiteFoundException $e) {
+            // this website was deleted in the meantime
```
Comment (tsteur) [inline core/CronArchive.php]: do we need a `$this->skipped++;` here too?

**Review by tsteur — CHANGES_REQUESTED** [review]
left a minor comment but otherwise looked and worked 👍

File: core/CronArchive.php (hunk 1 above)
Comment (paladox) [reply core/CronArchive.php]: I doin't think so (after looking through), this is only used for the logger to tell how many sites were skipped.

Comment (tsteur) [reply core/CronArchive.php]: yeah just thought because we kind of skip the website here... at least the "log info" says "skipped" so assumed it might be needed but indeed may not be needed

**Comment by paladox** [comment]
Thank you! (would this make it into matomo 3.10?):)

**Comment by tsteur** [comment]
Yes 👍  Cheers for the PR

**Comment by paladox** [comment]
Thanks!!!
