### PR TITLE
Fix aggregation of additional action metrics

### LINKED ISSUE #22350: [Bug] Calculation of min/max performance metrics incorrect in aggregated reports
### What happened?

For all page performance reports we additionally provide metrics for the highest and lowest value occurred.
Those metrics are calculated correctly when generated for non-aggregated reports - like normal day reports.
As soon as data is aggregated - like for month reports, the metrics are summed up instead of calculated with the correct method.

### What should happen?

Metrics should be correctly calculated

### How can this be reproduced?

As the metrics are only available through API, this can't be easily reproduced in the UI. It's though visible in certain tests, where the metrics simply don't match.

### Matomo version

5.2.0-alpha

### PHP version

_No response_

### Server operating system

_No response_

### What browsers are you seeing the problem on?

_No response_

### Computer operating system

_No response_

### Relevant log output

_No response_

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

Some plugins like PagePerformance or Bandwidth are adding additional metrics to the action reports. Some of those metrics need to be aggregated using min, max or avg aggregation.

As those column aggregation where not correctly set for the datatables, they were by default aggregated by summing the values up. This resulted in incorrect values.

fixes #22350 

(Ref DEV-18236)

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/DataTable/Row.php [hunk 1]
```diff
@@ -521,7 +521,13 @@ private function getColumnValuesMerged($operation, $thisColumnValue, $columnToSu
...
                 break;
             case 'max':
-                $newValue = max($thisColumnValue, $columnToSumValue);
+                if (!$thisColumnValue) {
+                    $newValue = $columnToSumValue;
+                } elseif (!$columnToSumValue) {
+                    $newValue = $thisColumnValue;
+                } else {
+                    $newValue = max($thisColumnValue, $columnToSumValue);
+                }
```
Comment (sgiehl) [inline core/DataTable/Row.php:530]: This was added to handle min and max values the same. Without that all max values would always be `0`, even if there was not a single value tracked.

Comment (rr-it) [reply core/DataTable/Row.php:530]: Is the actual logic behind the code as follows?

```php
            case 'max':
                if (!is_numeric($thisColumnValue) && !is_numeric($columnToSumValue)) {
                    $newValue = null;
                } else {
                    $newValue = max(
                        (is_numeric($thisColumnValue) ? +($thisColumnValue) : -INF),
                        (is_numeric($columnToSumValue) ? +($columnToSumValue) : -INF)
                    );
                }
```

File: core/DataTable/Row.php [hunk 2]
```diff
@@ -521,7 +521,13 @@ private function getColumnValuesMerged($operation, $thisColumnValue, $columnToSu
...
                 break;
             case 'min':
```
Comment (rr-it) [inline core/DataTable/Row.php:532]: The implementation of `min` looks like it is not providing the expected result for:

- `$thisColumnValue = 0`
- `$columnToSumValue = null`

Current result: `$newValue = null`

Expected result: `$newValue = 0`

----

This might work as expected:

```php
            case 'min':
                if (!is_numeric($thisColumnValue) && !is_numeric($columnToSumValue)) {
                    $newValue = null;
                } else {
                    $newValue = min(
                        (is_numeric($thisColumnValue) ? +($thisColumnValue) : INF),
                        (is_numeric($columnToSumValue) ? +($columnToSumValue) : INF)
                    );
                }
```

**Review by rr-it — COMMENTED** [review]
Please also check implementation of `min`.

File: core/DataTable/Row.php (hunk 1 above)
Comment (sgiehl) [reply core/DataTable/Row.php:530]: Thanks for pointing to that. I actually didn't think too much about that. I will try to improve the code

File: tests/PHPUnit/System/expected/test_CustomEvents_eventCategoryOrNameMatch__Events.getName_day.xml [hunk 3]
```diff
@@ -7,7 +7,7 @@
 		<nb_events>16</nb_events>
 		<nb_events_with_value>2</nb_events_with_value>
 		<sum_event_value>19.32</sum_event_value>
-		<min_event_value>9.66</min_event_value>
+		<min_event_value>0</min_event_value>
```
Comment (rr-it) [inline tests/PHPUnit/System/expected/test_CustomEvents_eventCategoryOrNameMatch__Events.getName_day.xml]: This one somehow still does not look correct:

nb_events_with_value: 2
sum_event_value: 19.32
min_event_value: 0
max_event_value: 9.66
avg_event_value: 9.66

_This should either be:_
nb_events_with_value: 2
sum_event_value: 19.32
min_event_value: 0
max_event_value: **> 19.32 <**
avg_event_value: 9.66

_Or:_
nb_events_with_value: 2
sum_event_value: 19.32
min_event_value: **> 9.66 <**
max_event_value: 9.66
avg_event_value: 9.66

Comment (rr-it) [reply tests/PHPUnit/System/expected/test_CustomEvents_eventCategoryOrNameMatch__Events.getName_day.xml]: `plugins/Events/RecordBuilders/EventReports.php` needs a change:

https://github.com/matomo-org/matomo/blob/bebbd31bf7253293e71b493e88fb859939bca34e/plugins/Events/RecordBuilders/EventReports.php#L195-L203

- `php -r "echo round(null ?? 0, 2);"` returns `0`
- `php -r "echo round(null ?? false, 2);"` returns `0`

To return `false` this should become:

```php
Metrics::INDEX_EVENT_MIN_EVENT_VALUE    => is_numeric($row[Metrics::INDEX_EVENT_MIN_EVENT_VALUE]) ? round($row[Metrics::INDEX_EVENT_MIN_EVENT_VALUE], 2) : false,
```

----

We could also return `null` - which results in empty entries for the test-case or API:

```php
Metrics::INDEX_EVENT_MIN_EVENT_VALUE    => is_numeric($row[Metrics::INDEX_EVENT_MIN_EVENT_VALUE]) ? round($row[Metrics::INDEX_EVENT_MIN_EVENT_VALUE], 2) : null,
Metrics::INDEX_EVENT_MAX_EVENT_VALUE    => is_numeric($row[Metrics::INDEX_EVENT_MAX_EVENT_VALUE]) ? round($row[Metrics::INDEX_EVENT_MAX_EVENT_VALUE], 2) : null,
```

```xml
       <row>
         <nb_events>2</nb_events>
         <nb_events_with_value>0</nb_events_with_value>
         <sum_event_value>0</sum_event_value>
-        <min_event_value>0</min_event_value>
-        <max_event_value>0</max_event_value>
+        <min_event_value/>
+        <max_event_value/>
         <avg_event_value>0</avg_event_value>
       </row>
```

File: tests/PHPUnit/System/expected/test_DataComparisonTest_flat__Actions.getPageUrls_month.xml [hunk 4]
```diff
@@ -140,10 +140,10 @@
 				<sum_bandwidth_change_from>+800%</sum_bandwidth_change_from>
 				<nb_hits_with_bandwidth_change>-88.9%</nb_hits_with_bandwidth_change>
 				<nb_hits_with_bandwidth_change_from>+800%</nb_hits_with_bandwidth_change_from>
-				<min_bandwidth_change>-75%</min_bandwidth_change>
-				<min_bandwidth_change_from>+300%</min_bandwidth_change_from>
-				<max_bandwidth_change>-75%</max_bandwidth_change>
-				<max_bandwidth_change_from>+300%</max_bandwidth_change_from>
+				<min_bandwidth_change>+0%</min_bandwidth_change>
```
Comment (rr-it) [inline tests/PHPUnit/System/expected/test_DataComparisonTest_flat__Actions.getPageUrls_month.xml:143]: Percentage does not work anymore:
`'75%'` is not numeric.

- `php -r "echo (is_numeric('75%') ? 'TRUE' : 'FALSE');"` returns `FALSE`
- `php -r "echo (is_numeric('75foo') ? 'TRUE' : 'FALSE');"` returns `FALSE`

Whereas `min()`/`max()` does the comparison somehow and then returns the original type and value:

- `php -r "echo min('75%', '-20%');"` returns `'-20%'`
- `php -r "echo min('75foo', '-20bar');"` returns `'-20bar'`

See https://www.php.net/manual/en/function.min.php
> Values of different types will be compared using the standard comparison rules. For instance, a non-numeric string will be compared to an int as though it were 0, but multiple non-numeric string values will be compared alphanumerically. **The actual value returned will be of the original type with no conversion applied.**

File: tests/PHPUnit/System/expected/test_CustomEvents_eventCategoryOrNameMatch__Events.getName_day.xml (hunk 3 above)
Comment (sgiehl) [reply tests/PHPUnit/System/expected/test_CustomEvents_eventCategoryOrNameMatch__Events.getName_day.xml]: good catch, will update that

File: tests/PHPUnit/System/expected/test_DataComparisonTest_flat__Actions.getPageUrls_month.xml (hunk 4 above)
Comment (sgiehl) [reply tests/PHPUnit/System/expected/test_DataComparisonTest_flat__Actions.getPageUrls_month.xml:143]: I'll check if using `null === $thisColumnValue || false === $thisColumnValue || '' === $thisColumnValue` instead of `!is_numeric($thisColumnValue)` works in that case

Comment (rr-it) [reply tests/PHPUnit/System/expected/test_DataComparisonTest_flat__Actions.getPageUrls_month.xml:143]: Percentage min/max calculation is bugged anyway.
This is caused by ''multiple non-numeric string values will be compared alphanumerically".
Thereby min/max does compare the values of percentage-strings not as we might expect.

- `php -r "echo min('+99%','-20%');"` returns `'+99%'` instead of `'-20%'`
- `php -r "echo min('10%','+20%');"` returns `'+20%'` instead of `'10%'`

Comment (sgiehl) [reply tests/PHPUnit/System/expected/test_DataComparisonTest_flat__Actions.getPageUrls_month.xml:143]: actually I think that the `change` values should not be aggregated, but should be calculated by a filter. So there might be another issue

Comment (sgiehl) [reply tests/PHPUnit/System/expected/test_DataComparisonTest_flat__Actions.getPageUrls_month.xml:143]: Looking a bit deeper into the test fixture it seems that there are only visits tracked with a bandwidth of `3574`. So that means that the min and max values are always `3574`. So comparing different datasets indeed has a change of `0%`. So the values were incorrect before, as it was comparing the incorrectly summed up min/max values.

File: tests/PHPUnit/System/expected/test_CustomEvents_Events.getCategory_lastN__API.getProcessedReport_day.xml [hunk 5]
```diff
@@ -181,7 +181,7 @@
 		<nb_events>69</nb_events>
 		<nb_events_with_value>14</nb_events_with_value>
 		<sum_event_value>137.96</sum_event_value>
-		<min_event_value>9.66</min_event_value>
+		<min_event_value>28.32</min_event_value>
```
Comment (rr-it) [inline tests/PHPUnit/System/expected/test_CustomEvents_Events.getCategory_lastN__API.getProcessedReport_day.xml]: There must be something wrong here:

`nb_events_with_value`: 14
`min_event_value`: 28.32
`sum_event_value`: 137.96

Check: 
`nb_events_with_value` * `min_event_value` <= `sum_event_value`

- Fails: 14 * 28.32 = 396.48 is bigger than 137.96

Either `nb_events_with_value`, `sum_event_value` or `min_event_value` is wrong here.

File: tests/PHPUnit/System/expected/test_CustomEvents_Events.getName_flat__API.getProcessedReport_day.xml [hunk 6]
```diff
@@ -617,6 +617,6 @@
 		<nb_events_with_value>14</nb_events_with_value>
 		<sum_event_value>137.96</sum_event_value>
 		<min_event_value>9.66</min_event_value>
-		<max_event_value>52.32</max_event_value>
+		<max_event_value>9.66</max_event_value>
```
Comment (rr-it) [inline tests/PHPUnit/System/expected/test_CustomEvents_Events.getName_flat__API.getProcessedReport_day.xml]: There must be something wrong here:

`nb_events_with_value`: 14
`min_event_value`: 9.66
`max_event_value`: 9.66
`sum_event_value`: 137.96

Check in case of `min_event_value` = `max_event_value`:
`nb_events_with_value` * `min_event_value` === `sum_event_value`
`nb_events_with_value` * `max_event_value` === `sum_event_value`

- Fails: 14 * 9.66 = 135.24 is smaller than 137.96

Is this some kind of rounding error?

**Review by rr-it — COMMENTED** [review]
There are still some values that do not look correct.

File: tests/PHPUnit/System/expected/test_DataComparisonTest_flat__Actions.getPageUrls_month.xml (hunk 4 above)
Comment (rr-it) [reply tests/PHPUnit/System/expected/test_DataComparisonTest_flat__Actions.getPageUrls_month.xml:143]: If this feature does not calculate with percentage string-values we might use:
`!is_numeric($thisColumnValue)`
instead of
`null === $thisColumnValue || false === $thisColumnValue || '' === $thisColumnValue`

A string that contains some num format is numeric:
- `php -r "echo (is_numeric('-0.5') ? 'TRUE' : 'FALSE');"` returns `TRUE`

A string that contains other characters is not numeric but also does not work correctly with min/max anyway:
- `php -r "echo (is_numeric('10bar') ? 'TRUE' : 'FALSE');"` returns `FALSE`
- `php -r "echo min('+99foo','-20foo');"` returns `'+99foo'` instead of `'-20foo'`
- `php -r "echo min('10bar','+20bar');"` returns `'+20bar'` instead of `'10bar'`

File: tests/PHPUnit/System/expected/test_CustomEvents_Events.getName_flat__API.getProcessedReport_day.xml (hunk 6 above)
Comment (sgiehl) [reply tests/PHPUnit/System/expected/test_CustomEvents_Events.getName_flat__API.getProcessedReport_day.xml]: Those are actually caused by another problem. The event metrics seem to be summed up as well. Need to set the correct metadata for that to work...

File: core/DataTable/Row.php [hunk 7]
```diff
@@ -521,12 +521,18 @@ private function getColumnValuesMerged($operation, $thisColumnValue, $columnToSu
                 $newValue = null;
                 break;
             case 'max':
-                $newValue = max($thisColumnValue, $columnToSumValue);
+                if (null === $thisColumnValue || false === $thisColumnValue || '' === $thisColumnValue) {
```
Comment (michalkleiner) [inline core/DataTable/Row.php]: This might be a bit cryptic
```suggestion
                if (0 == $thisColumnValue && 0 !== $thisColumnValue) {
```
but this might be easier to read
```suggestion
                if (in_array($thisColumnValue, [null, false, ''], true)) {
```

**Comment by rr-it** [comment]
@sgiehl ~~Looks like this branch https://github.com/matomo-org/matomo/tree/actiontotals was accidentally overridden with some other changes:~~

Edit: This was just a rebase - everything looks good.

**Comment by caddoo** [comment]
@sgiehl to help me review this, can you explain steps to reproduce.

I know in the issue you mentioned it's hard to reproduce in the UI, but can you help me with steps in the API.

Also the issue mentions the expected behavior is:
`Metrics should be correctly calculated` 
Can you explain exactly what that means.

**Review by caddoo — APPROVED** [review]
