### PR TITLE
Fix segment invalidation for custom dimensions

### LINKED ISSUE #21678: [Bug] Segment invalidation not working for custom dimensions
### What happened?

Trying to invalidate a segment using a custom dimension fails when both the segment name or definition are used.

### What should happen?

Report invalidation should work as expected for custom segment if a custom dimension is used.

### How can this be reproduced?

1. Create a custom dimension
2. Create a segment for that custom dimension
3. Invalidate reports for the new segment

### Matomo version

5.0.0-rc8

### PHP version

_No response_

### Server operating system

_No response_

### What browsers are you seeing the problem on?

_No response_

### Computer operating system

_No response_

### Relevant log output

```shell
> ./console core:invalidate-report-data --sites=1 --segment='test' --dates=2023-12-01,2023-12-31
> ERROR     [15:22:14] 8252  Uncaught exception: /srv/matomo/core/Segment.php(238): Segment 'dimension2' is not a supported segment. [Query: , CLI mode: 1]

> ./console core:invalidate-report-data --sites=1 --segment='dimension2==test' --dates=2023-12-01,2023-12-31
> ERROR     [15:22:14] 8252  Uncaught exception: /srv/matomo/core/Segment.php(238): Segment 'dimension2' is not a supported segment. [Query: , CLI mode: 1]
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by mneudert**
### Description

The segment filtering introduced in #21521 filters out segments that use custom dimensions if no `$idSite` parameter is given. This happens during the instantiation try that does not find custom dimensions when eventually [fetching the segment metadata](https://github.com/matomo-org/matomo/blob/b4207ef8dce0a3651956fae697e342b5c5e7b7ec/core/Segment.php#L190).

This patch restores segment invalidation by fetching segments for all to be invalidated sites individually. The behaviour to throw when multiple sites are given but a custom dimension is used was restored ([see test](https://github.com/matomo-org/matomo/blob/c4f903b6031d92dbb850b8a87165fb854bd2270d/plugins/CoreAdminHome/tests/Integration/Commands/InvalidateReportDataTest.php#L151)). We could, at a later date, change that behaviour to not break but only run the invalidation for sites where the custom dimension exists.

Tests should pass when running them on 5.0.0-rc7 or earlier, 5.0.0-rc8 and later require the fix.

Refs L3-616
Fixes #21678

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by bx80 — APPROVED** [review]
This looks good to me, tested before and after :+1:

File: plugins/SegmentEditor/API.php [hunk 1]
```diff
@@ -405,20 +405,17 @@ public function getAll($idSite = false)
      * Filter out any segments which cannot be initialized due to disable plugins or features
      *
      * @param array $segments
-     * @param       $idSite
+     * @param bool|int $idSite
      *
      * @return array
      */
     private function filterSegmentsWithDisabledElements(array $segments, $idSite = false): array
```
Comment (sgiehl) [inline plugins/SegmentEditor/API.php:412]: We could maybe try to get rid of such idSite parameters, that can either be a number or false. A better handling would imho be either a number or `null`. That would at some point even allow to type hint that parameter.
No need to change that now, but we should imho consider this for future improvements if we are already working on certain places of the code...

**Review by sgiehl — APPROVED** [review]
Code changes a looking fine. Did some local testing. Without this PR invalidating a custom dimension segment didn't work, with the changes it works again. so 👍
