### PR TITLE
Fix user path was not working as it should (allow placing config file outside webroot)

### LINKED ISSUE #13037: global(.ini).php in local PIWIK_USER_PATH not updated (composer)
Hi,

We update matomo with composer and host a central piwik/matomo, with local config files for each directadmin account. 

The constant 'PIWIK_USER_PATH' is set to the right config-dir inside an user-account. That works fine!

Matomo also needs 'global.php' and 'global.ini.php' to be in this local dir. In the above configuration these file are not updated, when composer updates the central matomo. 
Since it is adviced NOT to change these global files, what is the purpose of keeping them in a local user-path? 

This issue could be fixed if these file would be (also) loaded from the central matomo. Or that you could change the absolute paths in bootstrap.php.
Same for common.ini.php > here an option to set the path would be best, so you can have a own central common.ini.php somewhere else on your server.

When looking into the code of matomo, I see that the config files are chained. 
Why not have a chain like, load:
- from matomo vendor dir: /config/config.ini.php (holds the global (updated) settings)
- if exists /your/global/path/to/global/config/config.ini.php  > instead of common.ini.php
- PIWIK_USER_PATH/config/config.ini.php

Can this be changed in matomo? 
Or what can we do to have the global files inside the central matomo-dir?

Thanks in advance, flexjoly

### PR DESCRIPTION
**Pull request by tsteur**
fix https://github.com/matomo-org/matomo/issues/13037

As user described in the issue the user path behaviour didn't quite make sense. For example in an update we copied over `config/global.php` and `config/global.ini.php` to the user path. This may fail though due to write permission and is generally not needed cause the only files it should load from there is `config/config.php` and `config/config.ini.php` and `config/common.config.ini.php`. 

This makes things a lot simpler and now there is an easy way to put the config file outside Matomo webroot.

Should probably also create an FAQ for this afterwards.

### CODE REVIEW

File: core/Filechecks.php [hunk 1]
```diff
@@ -40,7 +40,9 @@ public static function checkDirectoriesWritable($directoriesToCheck)
     {
         $resultCheck = array();
         foreach ($directoriesToCheck as $directoryToCheck) {
-            if (!preg_match('/^' . preg_quote(PIWIK_USER_PATH, '/') . '/', $directoryToCheck)) {
+	        if (!preg_match('/^' . preg_quote(PIWIK_USER_PATH, '/') . '/', $directoryToCheck)
```
Comment (tsteur) [inline core/Filechecks.php]: those 3 constant might point to different directories so we need to only add another directory if none of these are set

File: js/tracker.php [hunk 2]
```diff
@@ -22,9 +22,19 @@
...
  */
-define('PIWIK_INCLUDE_PATH', '..');
 define('PIWIK_DOCUMENT_ROOT', '..');
-define('PIWIK_USER_PATH', '..');
+
+if (file_exists(PIWIK_DOCUMENT_ROOT . '/bootstrap.php')) {
+    require_once PIWIK_DOCUMENT_ROOT . '/bootstrap.php';
+}
+
+if (!defined('PIWIK_INCLUDE_PATH')) {
```
Comment (tsteur) [inline js/tracker.php]: same behaviour now as in `index.php` as `bootstrap.php` could change the user path

File: misc/cron/updatetoken.php [hunk 3]
```diff
@@ -15,12 +15,8 @@
 use Piwik\Tests\Framework\TestingEnvironmentManipulator;
 use Piwik\Tests\Framework\TestingEnvironmentVariables;
 
-if (!defined('PIWIK_INCLUDE_PATH')) {
```
Comment (tsteur) [inline misc/cron/updatetoken.php]: these constants are now removed as they are detected and set by `index.php`

File: plugins/CoreUpdater/Updater.php [hunk 4]
```diff
@@ -298,11 +298,6 @@ private function installNewFiles($extractedArchiveDirectory)
             $model->removeGoneFiles($extractedArchiveDirectory, PIWIK_DOCUMENT_ROOT);
         }
 
-        // Config files may be user (account) specific
-        if (PIWIK_INCLUDE_PATH !== PIWIK_USER_PATH) {
```
Comment (tsteur) [inline plugins/CoreUpdater/Updater.php]: no longer needed to copy the global config files over as there might not be write permission anyway and it's not needed. They should be always in document root.

**Comment by mattab** [comment]
> Should probably also create an FAQ for this afterwards.

@tsteur if you have a FAQ draft let me know, happy to publish it :+1:

**Comment by tsteur** [comment]
It was already there kind of

**Comment by florianjacob** [comment]
This made it impossible to use `PIWIK_USER_PATH` as an instance-specific writable location, separated from a shared, read-only `PIWIK_DOCUMENT_ROOT`: https://github.com/matomo-org/matomo/issues/15087
