### PR TITLE
Replace some characters in Email subject and Email attachments filename

### LINKED ISSUE #9631: PDF in Scheduled reports' attachments may include  " â€“ characters
As reported on the forum: http://forum.piwik.org/t/weekly-mail-report-is-empty-it-has-different-wrong-mime-format-since-version-2-15-0/17643

Sometimes, email attachments names can show up as: `December 21 â€“ 27, 2015.pdf` - for example the long hyphen (called `em-dash`) can cause this issue in email attachments, in at least some email client.

Goal of this issue would be to sanitise the Subject and attachment name to prevent these weird characters display issues.

### PR DESCRIPTION
**Pull request by mattab**
Fixes #9631  #9580

### CODE REVIEW

File: core/Mail.php [hunk 1]
```diff
@@ -154,4 +166,18 @@ protected function isHostDefinedAndNotLocal($url)
...
         return isset($url['host']) && !Url::isLocalHost($url['host']);
     }
+
+    /**
+     * Replaces characters known to appear incorrectly in some email clients
+     *
+     * @param $string
+     * @return mixed
+     */
+    static public function sanitiseString($string)
```
Comment (tsteur) [inline core/Mail.php]: Is it needed to have this method static?

Comment (mattab) [inline core/Mail.php]: Removed the useless `static`
