### PR TITLE
do not update token usage in tracking requests

### LINKED ISSUE #16924: Tons of "General error: 1205" in php error log while importing via the python log importer
It seems that there is a problem with the user_token_auth while importing log via the python logimporter. 
While looking at the SQL processlist I see several UPDATE queries for the matomo_user_token_auth table, they run the entire time until the timeout:

`[09-Dec-2020 09:28:08 UTC] Error in Matomo (tracker): Error query: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction In query: UPDATE 'matomo_user_token_auth' SET 'last_used' = ? WHERE 'idusertokenauth' = ? Parameters: array (   0 => '2020-12-09 09:27:17',   1 => '207', )`

Manually executing one of these queries works like a charm in some milliseconds. But not while the python script runs.

After the timeout the python script echoes this:

2020-12-09 09:28:08,641: [INFO] Error when connecting to Matomo: HTTP Error 500: Internal Server Error
2020-12-09 09:28:08,642: [INFO] Retrying request, attempt number 2

That's since the latest 4.0.4 update (I updated from v3) and I use Python 3.7 to execute the script.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

Seems updating the usage timestamp of a token might cause issues when using log import.
Not sure if we need to update the usage at all in this case. If so we maybe could also update it every 10 minutes only or so, but that would at least require an additional read request to check that.

fixes #16924

### Review

* [ ] Functional review done
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by tsteur** [comment]
Seems this doesn't fix the issue? Also it shouldn't really be a problem I think as when using the API concurrently we would see these issues as well maybe? Generally could change the where though like 

```sql
UPDATE 'matomo_user_token_auth' SET 'last_used' = ? WHERE 'idusertokenauth' = ? and last_used < ?
```
It likely wouldn't make a difference though . We basically only want to update it when `time()` is higher. When value doesn't change then mysql should be smart enough though.

**Comment by sgiehl** [comment]
Maybe that's only one part of the issue. But firing thousands of updates on the same row isn't good in any case.
Will have a closer look at the code again later. Maybe there's any easy way to update it like only every 10 minutes or so

**Comment by tsteur** [comment]
Be great to indeed only update it like every 10 min (in tracker and in general). Probably can't use general tracker cache as it would invalidate the cache every 10min when we use a much longer cache time on cloud.(1hr+)

**Comment by sgiehl** [comment]
@tsteur updated the PR. There will now always be an select to check if the last date for the token is older than 10 minutes. Not sure if that might make problems if multiple requests are executed at the same time

File: plugins/UsersManager/Model.php [hunk 1]
```diff
@@ -388,6 +389,15 @@ public function setTokenAuthWasUsed($tokenAuth, $dateLastUsed)
     {
         $token = $this->getTokenByTokenAuth($tokenAuth);
         if (!empty($token)) {
+
+            $lastUsage = strtotime($token['last_used']);
```
Comment (tsteur) [inline plugins/UsersManager/Model.php]: @sgiehl can last_used key be empty?

File: plugins/UsersManager/Model.php [hunk 2]
```diff
@@ -388,6 +389,15 @@ public function setTokenAuthWasUsed($tokenAuth, $dateLastUsed)
...
+            $newUsage = strtotime($dateLastUsed);
+
+            // update token usage only every 10 minutes
```
Comment (tsteur) [inline plugins/UsersManager/Model.php]: might be good to add a comment why this is eg link to https://github.com/matomo-org/matomo/issues/16924 ?

File: plugins/UsersManager/Model.php (hunk 1 above)
Comment (sgiehl) [reply plugins/UsersManager/Model.php]: guess it can be. will add a check

File: plugins/UsersManager/Model.php (hunk 2 above)
Comment (sgiehl) [reply plugins/UsersManager/Model.php]: done.
