### PR TITLE
Fix giving a user access to a site is not possible when login is numeric

### LINKED ISSUE #11680: Manage User Access Bug
I am having an issue setting access permission with version 3.0.3. Whenever I click to grant view permissions to a user, who is not the anonymous or stats user, nothing happens. I checked the console to see if an error was being thrown and the following is what is displayed. Thank you for any help.

TypeError: value.replace is not a function
at Object.htmlEntities (index.php?module=Proxy&action=getCoreJs&cb=a62b7d8…:934)
at ManageUserAccessController.setAccess (index.php?module=Proxy&action=getCoreJs&cb=a62b7d8…:3324)
at fn (eval at compile (index.php?module=Proxy&action=getCoreJs&cb=a62b7d8…:337), :4:325)
at b (index.php?module=Proxy&action=getCoreJs&cb=a62b7d8…:235)
at e (index.php?module=Proxy&action=getCoreJs&cb=a62b7d8…:378)
at b.$eval (index.php?module=Proxy&action=getCoreJs&cb=a62b7d8…:254)
at b.$apply (index.php?module=Proxy&action=getCoreJs&cb=a62b7d8…:254)
at HTMLImageElement. (index.php?module=Proxy&action=getCoreJs&cb=a62b7d8…:378)
at HTMLImageElement.dispatch (index.php?module=Proxy&action=getCoreJs&cb=a62b7d8…:5)
at HTMLImageElement.r.handle (index.php?module=Proxy&action=getCoreJs&cb=a62b7d8…:5)

### PR DESCRIPTION
**Pull request by tsteur**
Eg when login is 1234, the `login` var may actually be a number and then `.replace` won't work.

fixes #11680

I had a rough look for the other JS files there and should work for all other cases.

### CODE REVIEW

File: plugins/UsersManager/angularjs/manage-user-access/manage-user-access.controller.js [hunk 1]
```diff
@@ -42,7 +42,8 @@
             }
         };
 
-        this.setAccess = function (login, access) {
+        this.setAccess = function (login, access)
```
Comment (sgiehl) [inline plugins/UsersManager/angularjs/manage-user-access/manage-user-access.controller.js]: guess you accidentally removed the `{`

**Review by sgiehl — CHANGES_REQUESTED** [review]
Left a comment. After fixing that it should be good to merge.

File: plugins/UsersManager/angularjs/manage-user-access/manage-user-access.controller.js (hunk 1 above)
Comment (tsteur) [inline plugins/UsersManager/angularjs/manage-user-access/manage-user-access.controller.js]: good find 👍
