### PR TITLE
Do not update report title for secondary dimension reports

### LINKED ISSUE #23650: Secondary dimension in event report takes over the header
### What happened?

We've noticed that when you change secondary dimension in the event report you also change the header.

Image
Image

### What should happen?

The header should always be event categories.

### How can this be reproduced?

Go to behaviour -> event report. Change secondary dimension to event name. You will see the header change to Event Name.

### Matomo version

5.4.0

### PHP version

_No response_

### Server operating system

_No response_

### What browsers are you seeing the problem on?

_No response_

### Computer operating system

_No response_

### Relevant log output

```shell

```

### Validations

- [x] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [x] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [x] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #23650

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: plugins/Events/tests/UI/Events_spec.js [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+    it('should load the Events > index page correctly', async function () {
+        await page.goto("?" + urlBase + "#?" + generalParams + "&category=General_Actions&subcategory=Events_Events");
+        await page.mouse.move(-10, -10);
+
+        expect(await page.screenshotSelector('.pageWrap,.dataTable')).to.matchImage('overview');
+    });
+
+    it("should show report flattened", async function() {
+        await page.click('.dropdownConfigureIcon');
+        await page.mouse.move(-10, -10);
```
Comment (michalkleiner) [inline plugins/Events/tests/UI/Events_spec.js:17]: Likely not needed here, but also no big harm in keeping it.

**Review by michalkleiner — APPROVED** [review]
