### PR TITLE
[Hotfix]add date, period params into common function 

### LINKED ISSUE #18639: strtolower(): Argument #1 ($string) must be of type string, array given in Date.php
## First problem:

> Error: {"message":"strtolower(): Argument #1 ($string) must be of type string, array given","file":"\/core\/Date.php","line":1079,"request_id":"ba369","backtrace":" on \/core\/Date.php(1079)\n#0 \/core\/Date.php(1079): strtolower(Array)\n#1 \/core\/Period\/Range.php(255): Piwik\\Date->addPeriod(-29, Array)\n#2 \/core\/Period.php(131): Piwik\\Period\\Range->generate()\n#3 \/core\/Period\/Range.php(152): Piwik\\Period->getDateStart()\n#4 \/core\/Period\/Range.php(533): Piwik\\Period\\Range->getDateStart()\n#5 \/core\/Plugin\/Controller.php(502): Piwik\\Period\\Range::getRelativeToEndDate(Array, 'last30', Object(Piwik\\Date), Object(Piwik\\Site))\n#6 \/plugins\/MultiSites\/Controller.php(97): Piwik\\Plugin\\Controller->getGraphParamsModified()\n#7 \/plugins\/MultiSites\/Controller.php(37): Piwik\\Plugins\\MultiSites\\Controller->getSitesInfo(false)\n#8 [internal function]: Piwik\\Plugins\\MultiSites\\Controller->index()\n#9 \/core\/FrontController.php(619): call_user_func_array(Array, Array)\n#10 \/core\/FrontController.php(168): Piwik\\FrontController->doDispatch('MultiSites', 'index', Array)\n#11 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#12

Happens on
* `/index.php?action=index&date=yesterday&idSite=1&module=MultiSites&period[]=day`

## Second problem

> Error: {"message":"urldecode(): Argument #1 ($string) must be of type string, array given","file":"\/core\/Date.php","line":138,"request_id":"83d50","backtrace":" on \/core\/Date.php(138)\n#0 \/core\/Date.php(138): urldecode(Array)\n#1 \/core\/Period.php(121): Piwik\\Date::factory(Array)\n#2 \/core\/Plugin\/Controller.php(644): Piwik\\Period::checkDateFormat(Array)\n#3 \/core\/Plugin\/Controller.php(616): Piwik\\Plugin\\Controller->setGeneralVariablesViewAs(Object(Piwik\\View), 'basic')\n#4 \/plugins\/MultiSites\/Controller.php(100): Piwik\\Plugin\\Controller->setGeneralVariablesView(Object(Piwik\\View))\n#5 \/plugins\/MultiSites\/Controller.php(37): Piwik\\Plugins\\MultiSites\\Controller->getSitesInfo(false)\n#6 [internal function]: Piwik\\Plugins\\MultiSites\\Controller->index()\n#7 \/core\/FrontController.php(619):

Happens on 
* `index.php?action=index&date[]=yesterday&idSite=1&module=MultiSites&period=day`

## Expected outcome

No fatal error

### PR DESCRIPTION
**Pull request by peterhashair**
### Description:

Fixes: #18639
Accidently click merge on original PR https://github.com/matomo-org/matomo/pull/18653, revert it.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: core/Piwik.php [hunk 1]
```diff
@@ -889,4 +889,14 @@ public static function translate($translationId, $args = array(), $language = nu
 
         return $translator->translate($translationId, $args, $language);
     }
+
+    public static function getPeriod($default = null)
```
Comment (sgiehl) [inline core/Piwik.php:902]: We should add useful code comments for new methods. Guess something like 
```suggestion
    /**
     * Returns the period provided in the current request.
     * If no $default is provided, this method will throw an Exception if `period` can't be found in the request
     * 
     * @param string|null $default  default value to use
     * @throws Exception
     * @return string
     * @api
     */
    public static function getPeriod($default = null)
```

File: core/Piwik.php [hunk 2]
```diff
@@ -889,4 +889,14 @@ public static function translate($translationId, $args = array(), $language = nu
...
+    {
+        return Common::getRequestVar('period', $default, 'string');
+    }
+
+    public static function getDate($default = null)
```
Comment (sgiehl) [inline core/Piwik.php:916]: Same as above

File: core/Plugin/Controller.php [hunk 3]
```diff
@@ -476,25 +476,18 @@ protected function getLastUnitGraphAcrossPlugins($currentModuleName, $currentCon
      */
     protected function getGraphParamsModified($paramsToSet = array())
     {
-        if (!isset($paramsToSet['period'])) {
-            $period = Common::getRequestVar('period');
-        } else {
-            $period = $paramsToSet['period'];
+        try {
+            $period = isset($paramsToSet['period']) ?? Piwik::getPeriod();
```
Comment (sgiehl) [inline core/Plugin/Controller.php]: That can't work, as period will be `true` if `$paramsToSet['period']` has a value.
```suggestion
            $period = $paramsToSet['period'] ?? Piwik::getPeriod();
```

File: core/Plugin/Controller.php [hunk 4]
```diff
@@ -476,25 +476,18 @@ protected function getLastUnitGraphAcrossPlugins($currentModuleName, $currentCon
...
+        } catch (\Exception $e) {
+            $period = null;
         }
```
Comment (sgiehl) [inline core/Plugin/Controller.php]: I don't think this try catch is useful here. If no period was provided, the graph can't be displayed. So throwing an exception, like it was before, should be fine.

File: core/Plugin/Controller.php [hunk 5]
```diff
@@ -476,25 +476,18 @@ protected function getLastUnitGraphAcrossPlugins($currentModuleName, $currentCon
...
-        } else {
-            $range = $paramsToSet['range'];
-        }
 
-        if (!isset($paramsToSet['date'])) {
-            $endDate = $this->strDate;
-        } else {
-            $endDate = $paramsToSet['date'];
-        }
+        $range = isset($paramsToSet['range']) ?? 'last30';
```
Comment (sgiehl) [inline core/Plugin/Controller.php]: This won't have the result it should have. Same below.
It's either `isset($x) ? $x : 'default'` or `$x ?? 'default'`

**Review by sgiehl — CHANGES_REQUESTED** [review]

File: core/Visualization/Sparkline.php [hunk 6]
```diff
@@ -181,7 +181,8 @@ private function setSparklineColors($sparkline, $seriesIndex) {
             $colors = $defaultColors;
         }
 
-        if (strtolower($colors['backgroundColor']) !== '#ffffff') {
+        if (strtolower($colors['bcore/Plugin/Controller.php
+ackgroundColor']) !== '#ffffff') {
```
Comment (sgiehl) [inline core/Visualization/Sparkline.php]: Guess that happened by accident. Nevertheless it might be useful not to simply add and commit all changes without checking them. Personally I'm always using `git add -p`, which iterates through all changes and allows to decide which one to add or not. That helps reducing such "accidents" a lot....

```suggestion
        if (strtolower($colors['backgroundColor']) !== '#ffffff') {
```

**Comment by sgiehl** [comment]
Overall the code looks fine, but the errors described in the original issue are actually still showing up as warnings in the log:
```
WARNING MultiSites[2022-02-01 14:30:24 UTC] [09f2b] /srv/matomo/core/Date.php(1079): Deprecated - strtolower(): Passing null to parameter #1 ($string) of type string is deprecated - Matomo 4.7.0-rc1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) [internal function]: Piwik\ErrorHandler::errorHandler(),#1/core/Date.php(1079),#2/core/Period/Range.php(255),#3/core/Period.php(131),#4/core/Period/Range.php(152),#5/core/Period/Range.php(543),#6/core/Plugin/Controller.php(491),#7/plugins/MultiSites/Controller.php(97),#8/plugins/MultiSites/Controller.php(37),[internal function]: Piwik\Plugins\MultiSites\Controller->index()
```

I guess to solve that you may need to change this:
https://github.com/matomo-org/matomo/blob/83ed55c06e96a9423f0d1101cec05c233ec403a3/plugins/MultiSites/Controller.php#L97
and supply `['period' => $period]` as parameter for the method call.

File: core/Plugin/Controller.php [hunk 7]
```diff
@@ -476,25 +476,14 @@ protected function getLastUnitGraphAcrossPlugins($currentModuleName, $currentCon
      */
     protected function getGraphParamsModified($paramsToSet = array())
     {
-        if (!isset($paramsToSet['period'])) {
-            $period = Common::getRequestVar('period');
-        } else {
-            $period = $paramsToSet['period'];
-        }
+        $period = isset($paramsToSet['period']) ? $paramsToSet['period'] : null;
```
Comment (sgiehl) [inline core/Plugin/Controller.php]: That one now misses the default:

```suggestion
        $period = $paramsToSet['period'] ?? Piwik::getPeriod();
```

**Review by sgiehl — CHANGES_REQUESTED** [review]
left a comment, which I guess causes the UI test failures.

**Review by sgiehl — APPROVED** [review]
Seems tests are passing now
