### PR TITLE
Better error handling for custom logo upload

### LINKED ISSUE #7264: Warning - imagecopyresampled() expects parameter 2 to be resource
I received this message after upgrading to 2.11.0 and adding a custom logo.  The image failed to validate with `pngcheck`.  It must have gotten corrupted during conversion.  Uploading random files with non-`.png` suffixes did not produce the error.  I labeled a `.jpg` with `.png` and produced the error.

Verifying the image was a valid PNG fixed any issue.

>WARNING CoreAdminHome[2015-02-19 04:42:12] [fcf03] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(223): Warning - imagecopyresampled() expects parameter 2 to be resource, boolean given - Piwik 2.11.0 - Please report this message in the Piwik forums: [forum.piwik.org] (please do a search first as it might have been reported already)
>WARNING CoreAdminHome[2015-02-19 05:03:38] [01db7] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(202): Warning - imagecreatefrompng(): '/tmp/phpEfv0yj' is not a valid PNG file - Piwik 2.11.0 - Please report this message in the Piwik forums: [forum.piwik.org] (please do a search first as it might have been reported already)

Putting the `.png` suffix on a text file generated other errors.

>WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(221): Warning - imagecolortransparent() expects parameter 1 to be resource, boolean given - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(223): Warning - imagecopyresampled() expects parameter 1 to be resource, boolean given - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(224): Warning - imagepng() expects parameter 1 to be resource, boolean given - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(220): Warning - imagecolorallocate() expects parameter 1 to be resource, boolean given - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(217): Warning - imagesavealpha() expects parameter 1 to be resource, boolean given - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(211): Warning - Division by zero - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(213): Warning - imagecreatetruecolor(): Invalid image dimensions - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(216): Warning - imagealphablending() expects parameter 1 to be resource, boolean given - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING CoreAdminHome[2015-02-21 18:15:22] [5a2f3] /www/piwik/plugins/CoreAdminHome/CustomLogo.php(202): Warning - imagecreatefrompng(): '/tmp/phpB7EnAK' is not a valid PNG file - Piwik 2.11.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

http://forum.piwik.org/read.php?2,124339,124384

### PR DESCRIPTION
**Pull request by sgiehl**
As described in #7264 some errors while uploading a custom logo might occur.
Those errors weren't shown directly. Instead noting happened and the error is displayed after the next page reload.

To improve that behavior, I've suppressed those errors that might occur while opening an invalid file and implemented a simple error message that is displayed when the upload failed.

image

fixes #7264

### CODE REVIEW

File: plugins/CoreAdminHome/CustomLogo.php [hunk 1]
```diff
@@ -196,18 +196,22 @@ private function uploadImage($uploadFieldName, $targetHeight, $userPath)
         list($width, $height) = getimagesize($file);
         switch ($_FILES[$uploadFieldName]['type']) {
             case 'image/jpeg':
-                $image = imagecreatefromjpeg($file);
+                $image = @imagecreatefromjpeg($file);
```
Comment (tsteur) [inline plugins/CoreAdminHome/CustomLogo.php]: I wonder if the `@` actually needed as it would return `false` on any failure or not?

Comment (tsteur) [inline plugins/CoreAdminHome/CustomLogo.php]: Just asking as we kinda try to get rid of using `@` :)

File: plugins/CoreAdminHome/javascripts/generalSettings.js [hunk 2]
```diff
@@ -123,6 +123,13 @@ $(document).ready(function () {
                 var frameContent = $(uploadFrame.contents()).find('body').html();
                 frameContent = $.trim(frameContent);
 
+                if ('0' === frameContent) {
+                    $('.uploaderror').show();
+                    setTimeout(function(){
+                        $('.uploaderror').fadeOut();
```
Comment (tsteur) [inline plugins/CoreAdminHome/javascripts/generalSettings.js]: Can we maybe keep the error message visible and instead when uploading another image remove a possible displayed notification? Might be hard to read within 5 seconds but not sure how we handle this in other places

File: plugins/CoreAdminHome/CustomLogo.php (hunk 1 above)
Comment (sgiehl) [inline plugins/CoreAdminHome/CustomLogo.php]: It throws a warning if the file is invalid, which might be shown as notification.

Comment (tsteur) [inline plugins/CoreAdminHome/CustomLogo.php]: Cool, thx. Can you have a look at the other comment? Not sure if something is do on the other comment. If not, feel free to merge

File: plugins/CoreAdminHome/javascripts/generalSettings.js (hunk 2 above)
Comment (sgiehl) [inline plugins/CoreAdminHome/javascripts/generalSettings.js]: Ok. I'll keep the error message visible. Until a need upload is triggered
