### PR TITLE
Real-time report under Visitors does not refresh

### LINKED ISSUE #14374: Real-time report under Visitors does not refresh
The Visitors > Real-time report does not automatically refresh every few seconds (as we'd expect). When the page loads the following JS error is triggered early on:

> Error: cannot call methods on liveWidget prior to initialization; attempted to call method 'started'

The Real-time report is displayed correctly once but does not refresh then.
Also, when clicking on the Pause/Play button at the bottom of the page, it triggers slightly different JS errors:

> Error: cannot call methods on liveWidget prior to initialization; attempted to call method 'stop' index.php:4:1813
> Error: cannot call methods on liveWidget prior to initialization; attempted to call method 'start' index.php:4:1813

### PR DESCRIPTION
**Pull request by tsteur**
fixes #14374

### CODE REVIEW

File: plugins/Live/angularjs/live-widget-refresh/live-widget-refresh.directive.js [hunk 1]
```diff
@@ -0,0 +1,64 @@
+/*!
+ * Piwik - free/libre analytics platform
```
Comment (katebutler) [inline plugins/Live/angularjs/live-widget-refresh/live-widget-refresh.directive.js]: Should this be updated to Matomo branding?

Comment (tsteur) [reply plugins/Live/angularjs/live-widget-refresh/live-widget-refresh.directive.js]: we'll change this at some stage on all files in a new PR. so far we kept it for existing files.
