### PR TITLE
When you are logged out, the URL gets lost when you log in

### LINKED ISSUE #13328: When you are logged out, the URL gets lost when you log in
**Steps to reproduce:**

1. I am unauthenticated.
2. I load `/index.php?module=MultiSites&action=index&idSite=1&period=range&date=last30`.
3. Matomo appropriately complains of the permissions error and presents me with a login form.
4. I log in.

**Expected result:** I am at the page I requested, `/index.php?module=MultiSites&action=index&idSite=1&period=range&date=last30`.

**Actual result:** I am at the site’s default URL, which for me is `/index.php?module=CoreHome&action=index&idSite=1&period=range&date=last30`.

**Remarks:** this is more common than you might imagine for me: if I have a browser tab open persistently, #13327 means that I will be logged out fairly regularly, and then when I go to the open tab my place is lost.

### PR DESCRIPTION
**Pull request by tsteur**
It won't remember any hash as the hash won't be visible in the referrer etc but it would work for most other pages.

To make it work for hash it would get likely way more complicated like we would need to persist it through JS, temporarily store it somewhere and redirect accordingly. It fixes the case mentioned in the issue.

fix https://github.com/matomo-org/matomo/issues/13328

### CODE REVIEW

File: plugins/Login/Controller.php [hunk 1]
```diff
@@ -220,6 +220,19 @@ protected function authenticateAndRedirect($login, $password, $urlToRedirect = f
...
         $this->passwordResetter->removePasswordResetInfo($login);
 
+        if (empty($urlToRedirect)) {
+            $referrer = Url::getReferrer();
+            $module = Common::getRequestVar('module', '', 'string');
+            // when module is login, we redirect to home...
+            if ($module !== 'Login' && $module !== Piwik::getLoginPluginName() && $referrer) {
+                $host = Url::getHostFromUrl($referrer);
+                // we only redirect to a trusted host
+                if ($host && Url::isValidHost($host)) {
```
Comment (tsteur) [inline plugins/Login/Controller.php]: To increase security we could maybe do even `if ($host && Url::isValidHost($host) && $host === Url::getCurrentHost()) {` but this could be maybe tricky with proxies etc.

Comment (diosmosis) [reply plugins/Login/Controller.php]: isValidHost does `$host === Url::getCurrentHost()` basically, so should be ok IMO

**Comment by diosmosis** [comment]
Works for me, though I think a simple solution to support the hash would be to store in the session when redirecting to login. Think it's doable @tsteur ?

**Comment by tsteur** [comment]
You'd just need to send the hash through JS which may be a problem or bit difficult...

**Comment by diosmosis** [comment]
Of course, wasn't thinking...

I guess it could be sent through a custom query param when logging in, but that might be too much work, and maybe a security risk.

**Comment by chris-morgan** [comment]
I shall be blunt: not handling the hash makes this a non-fix. The pages that I believe people spend almost all their time on depend fundamentally on the hash, and you’re effectively not on the same page at all if the hash is lost.

The correct fix is to stop using the hash, and put everything in the query string (using history.pushState to manage it all from the client).

**Comment by tsteur** [comment]
@chris-morgan we will maybe in Matomo 4 or at some point stop using the hash but we can't easily do it as it requires changing quite a bit of code through our big codebase and couple plugins.
